### ISSUE TITLE
can not add url 

### ISSUE THREAD

**Issue by hrutie** [gpodder/gpodder#1004]
As url tried to add

https://www.peoplespharmacy.com/podcasts

and get 
 
Some podcasts could not be added to your list:
https://www.peoplespharmacy.com/podcas ts: Could not parse 
feed <unknown>:1:21:Unsupported feed type:html

When I am at that website can click on a podcast and hear it.
What is problem?

**Comment by auouymous** [comment]
The URL **must** be an RSS feed, and that URL is a web page. That site doesn't have an RSS because they make money showing you ads on the page, or selling you an ad-free page subscription.
