### ISSUE TITLE
[podcastparser] ERROR: Cannot parse date:

### ISSUE THREAD

**Issue by clort81** [gpodder/gpodder#1010]
Getting a bunch of  [podcastparser] ERROR: Cannot parse date: 'Wed, 09/09/2009 - 17:58'

Looks like this is handled in podcastparser.py time.striptime or line 587:
```
    try:
        parsed = time.strptime(text[:19], '%Y-%m-%dT%H:%M:%S')
        if parsed is not None:
            m = re.match(r'^(?:Z|([+-])([0-9]{2})[:]([0-9]{2}))$', text[19:])
            if m:
                parsed = list(iter(parsed))
                if m.group(1):
                    offset = 3600 * int(m.group(2)) + 60 * int(m.group(3))
                    if m.group(1) == '-':
                        offset = 0 - offset
                else:
                    offset = 0
                parsed.append(offset)
                return int(mktime_tz(tuple(parsed)))
            else:
                return int(time.mktime(parsed))
    except Exception:
        pass

    logger.error('Cannot parse date: %s', repr(text))
```
What would be best way to add support for this format?
Cheers!

**Comment by auouymous** [comment]
Can you provide the feed URL?

**Comment by clort81** [comment]
I don't know which podcast causes it.   I am seeing it using the gpo cli client.

I'll do some experiments with time.strptime and that re.match.

**Comment by auouymous** [comment]
Well, the feed causing the error is not valid (it doesn't comply with RFC822) and it is unlikely podcastparser will be changed to fix it. You could patch it locally or contact the feed author so they can fix it on their end.

**Comment by clort81** [comment]
Thank you for that information.  Closing then.
