### ISSUE TITLE
gPodder 3.10.19 youtube-dl from European countries error

### ISSUE THREAD

**Issue by elelay** [gpodder/gpodder#1011]
This commit https://github.com/ytdl-org/youtube-dl/commit/14f29f087e6097feb46bdb84878924bc410a57eb is needed.
It has been released in youtube-dl 2021.04.01 but we have 2021.3.25.

**Comment by elelay** [comment]
Error is `youtube_dl.utils.RegexNotFoundError: Unable to extract yt initial data`

**Comment by auouymous** [comment]
A working `pip` in mac and windows builds, and a menu item for users to upgrade youtube-dl would be nice right about now.

**Comment by computerfreak105** [comment]
Yes, please, updating youtube-dl is a big wish of mine. Please also include a command for this in the CLI.

Thanks.

**Comment by elelay** [comment]
See https://github.com/gpodder/gpodder-osx-bundle/pull/20 for a wip.
It also need pip-running code (invoke pip in a subprocess). I'm inclined to install packages to `${GPODDER_HOME}/pip`, so even if the user doesn't have write access to the gPodder.app they can update youtube-dl.

**Comment by auouymous** [comment]
Fixed in gPodder 3.10.20.
