### ISSUE TITLE
"No network connection" when checking for new episodes on 3.10.19

### ISSUE THREAD

**Issue by LeifW** [gpodder/gpodder#1014]
Also doesn't download episodes. This was working up until about a week ago.

I tried running the `linux_get_active_interfaces()` method in `util.py`, and it returns an empty generator. If I run the command it execs myself, `ip addr show scope global up`, I get:
```
4: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 58:96:1d:5b:47:08 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.5/24 scope global noprefixroute wlan0
       valid_lft forever preferred_lft forever
```
My `ip` command is from iproute2 5.11.0

**Comment by elelay** [comment]
It's looking for broadcast information (eg `inet 192.168.1.20/24 brd 192.168.1.255  scope global dynamic eth0`), which you have not.
@tpikonen do you remember why it looks for **brd**?
Thanks,

**Comment by auouymous** [comment]
The broadcast address (`brd`) is not required for a working interface, and was probably chosen as a known phrase that came after `inet`. `scope global` should always be there since the command requests it.

I propose it be changed to `r'^([^:]*):.*inet.*scope'`.

**Comment by auouymous** [comment]
I also propose a checkbox in preferences to override the interface checking because issues like this break gpodder until an update is available.

**Comment by elelay** [comment]
agree on both proposals

**Comment by LeifW** [comment]
I changed the `brd` to `scope` in that regex, and it's working again - thanks!
