### ISSUE TITLE
error getting new epesodes from the folowing url, going to the rss feed's page displayes that another epesode has been added.

### ISSUE THREAD

**Issue by mhussaincov93** [gpodder/gpodder#1024]
hi there,
for some reason, I am not getting updates for this podcast or for podcasts like this url.
https://rss.hosting.thisisdax.com/a88d2e26-3a60-43f3-a7c8-7a35a72590af/
checking for updates does not bring up the latest epesodes,
however going to the url in question,
shows that there was another epesode added.
onother url.
that displayes the saim simptoms:
https://rss.hosting.thisisdax.com/384ca9f6-a25a-414c-8bdb-d9bebc98738d/
Gpodder version
3.10.17
running debian sid.
assistive tech is in play
orca screen reader.

thanks for your help!
Majid

**Comment by auouymous** [comment]
The feed only has 4 episodes from 27-30 of April. You'll need to contact the site about a broken feed if the website shows additional episodes.

**Comment by mhussaincov93** [comment]
arr,
that may be a little tricky:
the way I got these feeds was by using chrome's developer tools to sniff out the catchup urls for the audio files of the epesode in question, changeing the url from
catchup.hosting.thisisdax.com to
rss.hosting.thisisdax.com
with the id string of the channel.
I feer if I go to glowble with my complaintes, they may ask how I got these urls?
and block this.
but then they may be aware of this...
hence me asking you lovly fokes
if something on gpodder's end could be done?
thanks,
Majid

**Comment by auouymous** [comment]
Gpodder can only process what is shared by the author in the feed. If the feed is broken, you will probably never see anything new from it again, and asking them to fix it could be the only option. They might also remove it entirely instead of wasting time fixing it, but it was already broken to begin with...
