### ISSUE TITLE
[Feature idea] Option to automatically or manually (re)download/refresh podcast pictures; globally and per podcast

### ISSUE THREAD

**Issue by Marrib** [gpodder/gpodder#1033]
**Current state**
When adding a podcast, gPodder downloads the podcast's cover picture. This is great.

**Problem**
However, podcast pictures/covers are changed from time to time by the podcast providers, especially with YouTube channel's pictures this happens quite often. But gPodder does not refresh/re-download those cover pictures periodically. So those podcast pictures/covers must be refreshed manually _per podcast_ which is quite time consuming and tedious.

**Feature idea**
- Please add an on/off toggle option in gPodder preferences that makes gPodder automatically re-download/refresh the podcast pictures/covers when searching for new episodes.
- In addition to that, there should also be an entry in the menu "Podcasts" in the menu bar called "Download cover pictures" so that users can manually initiate the cover refresh of _all podcasts globally_.

**Comment by auouymous** [comment]
Opening and closing the channel dialog requests a cover image, but it seems to abort when the image has already been downloaded. I changed the cover image on my test feed and updating the feed stores the changed URL, but it doesn't fetch the image. I assume that means it won't fetch a modified image when the URL hasn't changed. And subscribing to the feed again without removing it also doesn't fetch the cover image.

You can also drag an image from a file:// or http:// URL to the cover image in channel dialog and override the default channel image. #1034 is needed to make it work, and 8b4a4e381acc68fe0e9a121d379fb3605cfe4c7a is needed for https:// URLs.

I'll look at it some more in a couple days.

**Comment by auouymous** [comment]
Try right-clicking on the cover image in channel dialog... :)

It would still be nice to have a menu item or preferences button that refreshed all channels.

**Comment by Marrib** [comment]
Cool, thanks for the hint! I didn't know that a manual refresh was possible by right-clicking on the cover image in channel dialog (even if it's only per individual podcast).

**Comment by Marrib** [comment]
Am I missing something again or does the manual re-download not work for YouTube feeds?

**Comment by auouymous** [comment]
I didn't know about it either until reading the code, it could be more discoverable. An entry in the channel's context menu would not only make it more discoverable but also easier to manually update many feeds.

I just refreshed a couple youtube feeds and the image changed for one of them.
