### ISSUE TITLE
Youtube videos won't download or stream

### ISSUE THREAD

**Issue by mads5408** [gpodder/gpodder#1045]
All YouTube downloads seem to fail with error "ERROR: Download failed: No formats found for video ID "the videos id""

When checking for new episodes, new episodes are found but will fail downloading with above error.
I am using the latest version of gPodder 3.10.19 on Ubuntu 20.04

**Comment by mads5408** [comment]
Well it started working, sorry

**Comment by auouymous** [comment]
It was because the endpoint gpodder uses went away in the global youtube outage Tuesday. #1043 uses the same endpoint as youtube-dl.

**Comment by mads5408** [comment]
I just updated youtube-dl and it started working. again sorry for the bug report even though i had not trouble shot enough

**Comment by auouymous** [comment]
Oh, I was under the impression the endpoint came back and gpodder was working again, which is not the case. For anyone else with this issue, install #1043 if you want to use gpodder to download, or update youtube-dl, enable the extension and enable `manage_downloads`. The youtube-dl included with the Windows and Mac builds should work fine.

**Comment by stillpointx** [comment]
I can also verify this issue occurs on Ubuntu 20.04.2 LTS

**Comment by ZikZakFR** [comment]
Same issue under Archlinux.
I can use Youtube-DL but I do not like doing that, downloading hundreds of megabytes for something I may not watch.
I usually use Youtube-DL only to keep a file that I'll watch again (tutorials, documentary etc.).

**Comment by auouymous** [comment]
I'm waiting for verification of #1043 working in Europe and then I'll merge it and try to quickly get a new release out.

**Comment by auouymous** [comment]
Fixed in gPodder 3.10.20.
