### ISSUE TITLE
gpodder.youtube.YouTubeError: No formats found for video ID

### ISSUE THREAD

**Issue by ZikZakFR** [gpodder/gpodder#1046]
I can't open a stream, downloading it with youtube-dl from right-click works fine and the playing the downloaded file is ok.
Direct stream play will result in:
  File "/usr/lib/python3.9/site-packages/gpodder/youtube.py", line 184, in youtube_real_download_url
    res, duration = get_real_download_url(episode.url, allow_partial, fmt_ids)
  File "/usr/lib/python3.9/site-packages/gpodder/youtube.py", line 279, in get_real_download_url
    raise YouTubeError('No formats found for video ID "%s"' % vid)
gpodder.youtube.YouTubeError: No formats found for video ID

**Comment by auouymous** [comment]
See pinned issue #1045.

**Comment by ZikZakFR** [comment]
> See pinned issue #1045.

I'll do, the subject wasn't clear enough and no log provided so I wasn't sure if it was the same I'm experiencing.
