### ISSUE TITLE
adaptive: Too much text in "Cancel download" Button

### ISSUE THREAD

**Issue by fossdd** [gpodder/gpodder#1067]
I recently installed the gpodder adaptive application. By starting downloading a episode, there are three buttons `Stream`, `Can... load` and `New`.

My guess is that Can.. load means "Cancel download" but libhandy adjusted it. It happens on phosh and Gnome 40.

Is it possible to only show `Cancel`?

**Comment by tpikonen** [comment]
Indeed this string is too long for the button size. I've made the change you suggested to the adaptive branch.
