### ISSUE TITLE
All Youtube downloads failing (in Europe): Error: No ytInitialPlayerRespose found

### ISSUE THREAD

**Issue by TinoJ** [gpodder/gpodder#1074]
Hallo,
today I got for all Youtube subscriptions the download "Error: No ytInitialPlayerRespose found". The download remains in the list.

I have gPodder portable 3.10.20 (2021-06-06) on Windows.

Best, Tino

**Comment by auouymous** [comment]
You are probably in Europe and #1073 is a potential fix to the issue. This should only happen for new videos and they should become available within 24 hours. You can also enable the youtube-dl extension, enable `manage_downloads` in edit config and then download the episodes again.

**Comment by TinoJ** [comment]
Hi, I have enabled the extension, restarted. Currently gP is checking for new eposides. But it takes very long. Hanging for 30 min now and it is at 1/3 of the subscription list. Usually it takes 30 seconds for all feeds to check. Let's see, what happens. :)
Best, Tino

**Comment by TinoJ** [comment]
Oups, enabling the extension seems not to work for me. I get a lot of errors when checking the subscription list for new episodes:
[gpodder.gtkui.main] ERROR: Error: HTTPSConnectionPool(host='www.blablalaaa.de', port=443): Max retries exceeded with url: 

or

see attachment.

Should I try the fix?

**Comment by TinoJ** [comment]
(Regarding the failed downloads from yesterday: They work now. But the checktime and the mentioned errors with enabled extension rather not.)

**Comment by auouymous** [comment]
Did you enable `manage_channels` too? Using youtube-dl to manage channels can fetch more than the newest 15 episodes but takes forever to update channels.

The errors appear to be an issue with your connection or DNS.

**Comment by TinoJ** [comment]
Yes, manage_channels is enabled. The next update on the next day and today had a different behaviour. It run through more or less like always. So it where only the first two or three runs with problems. The DNS problem is gone. Manual refresh is also okay now. 

So I would say, I close the issue. Thanks for your hints!
