### ISSUE TITLE
[Feature Request] Add Strawberry to list of Mediaplayers

### ISSUE THREAD

**Issue by fbride** [gpodder/gpodder#1078]
Strawberry is a media player forked from Clementine and which is currently heavily supported : https://github.com/strawberrymusicplayer/strawberry

I think it would be nice to add it to the list of external mediaplayers you can use.

It's possible by adding the following lines in the `share/gpodder/extensions/enqueue_in_mediaplayer.py` file in the Players block, currently starting at line 193 :

```bash
    # Strawberry, https://www.strawberrymusicplayer.org/
    FreeDesktopPlayer('strawberry', 'Strawberry', ['strawberry', '--append']),
```

On my systems, Strawberry doesn't seem to be affected by the Zombie behavior described for the Clementine.

**Comment by auouymous** [comment]
Thanks for the suggestion, added.
