### ISSUE TITLE
Sudden issues with BBC podcasts

### ISSUE THREAD

**Issue by cliffsloane555** [gpodder/gpodder#1082]
Hi, I am completely new to GitHub, and neither a developer nor a programmer, so forgive the lapses in knowledge.

I have been using gpodder on my Linux Mint machine for years. A couple of days ago, I have a new issue with BBC podcasts (and ONLY BBC, all others working normally). Gpodder only downloads 700 B headers, while streaming and direct downloads from the website work as normal.
When I open the header file in a text editor, there is a link to the audio. When I copy and paste to go, the file downloads.

Here is a typical header file:

`<html><head><noscript><meta http-equiv=Refresh Content="0; URL=http://192.168.1.1/ui/dynamic/internet-blocked.html"></noscript><script language='javascript' type='text/javascript'>function init(_frm) { if (_frm.sent.value == 0) { _frm.sent.value=1; _frm.submit(); } }</script></head><body onload=init(auth)><form name=auth action='http://192.168.1.1/ui/dynamic/internet-blocked.html' METHOD=GET><input type=hidden name='mac_addr' value='XX:XX:XX:XX:XX:XX'>
<input type=hidden name='url' value='http://open.live.bbc.co.uk/mediaselector/6/redir/version/2.0/mediaset/audio-nondrm-download-low/proto/http/vpid/p09n58lr.mp3'>
<input type=hidden name='reason' value='1'>
<input type=hidden id=sent value='0'></form></body></html>`

The audio is in 
`value=`

When I copy and paste the audio link in the browser, it downloads.
How can I fix this?

**Comment by thp** [comment]
This looks like something that your WIFI is doing? (192.168.1.1 is a [Private Network IP](https://en.wikipedia.org/wiki/Private_network#Private_IPv4_addresses), meaning it's only valid in your local home network)

```
http://192.168.1.1/ui/dynamic/internet-blocked.html
```

A quick Google search reveals that it might be something about a Linksys router... could it be that "Parental Controls" are enabled on your router? Check out this Linksys support article article:

https://www.linksys.com/sa/support-article?articleNum=135864

If you don't have a Linksys router, open http://192.168.1.1/ in your browser (while it's on the local home network, it won't work from somewhere else) and see what it shows (probably the web interface of your router).

Disabling the "Parental Controls" or "Web Filtering" or something on your router will most likely fix the issue.

**Comment by cliffsloane555** [comment]
Well, I DID install a Linksys router, but that was a month ago. There is no option for Parental Controls, and I did not find anything that seems similar to Web Filtering. I could also change my login to Guest and see if that bypasses the difficulty. I could always run a VPN, I suppose, or search their knowledge base for answers. But I could just as easily (maybe more so) return to my Netgear router.
So, this question is "Still Open" for now.

**Comment by cliffsloane555** [comment]
Found It!
Each device on the Network Map has a separate pulldown menu, and the Desktop reported that it was on. Man, that is really helpful. Will close if that does the job.
