### ISSUE TITLE
Unable to play youtube videos

### ISSUE THREAD

**Issue by jEsuSdA** [gpodder/gpodder#1090]
Hi!
I just updated  gpodder. I expected to be able to play youtube again, but it still not working.

The log say this:

1626190868.260287 [gpodder.youtube] WARNING: Youtube get_video_info: 404 Not Found

And the message error is:

ERROR: no ytInitialPlayerResponse found, 08:13

Trying to activate the youtube-dl plugin but does not work at all too.

Changing the video player does not change the behavior.

Any ideas about ? thanks a lot for this great piece of software. ;)

**Comment by elelay** [comment]
Thanks for reporting!
This will be fixed in upcoming release.
See #1074

**Comment by jEsuSdA** [comment]
Thanks a lot. While waiting to next release, I put the new youtube.py into my gpodder installation and it works fine!
Thanks!!!
