### ISSUE TITLE
Can't access gpodder -- getting 'password does not exist' after registering

### ISSUE THREAD

**Issue by kajodowe** [gpodder/gpodder#1091]
Can't access gpodder -- getting 'wrong username or password' after trying to log in. I have it succesfully installed on one computer but cannot log in to gpodder.net to synchronize to another computer. Then I try the 'forget password" option and enter my email -- I get "user does not exist' -- THEN if i try to re-register i get "this email address is already in use."

Can you help -- I really enjoy GPodder -- thanks for developing it!

**Comment by elelay** [comment]
Hi, does login to the website work? If it does but login from gpodder client doesn't work then it's an issue with the client, otherwise it's with the website.

**Comment by kajodowe** [comment]
Hi -- I have the app on Linux Mint 19.3 where I first installed GPodder and it works fine. So it's logging in to the web site to synchronize to my other computer running Linux Mint 20.2 that is the problem. So the client is fine on the Mint 19.3 computer. I never made an account on the website till I needed to synchronize to my newer computer. I seem to have been able to create an account a month or so ago but nowI can't log in to it as noted above. I can just manually add podcasts to GPodder on the newer computer but I have about 30-40 podcasts that I follow. 

It's no problem to do it manually but I would enjoy using the web app if we can figure this out. Thanks again!

-Allen

**Comment by elelay** [comment]
okay, so definitely an issue with the webapp then...
You know you can just grab the `~/gPodder` folder from the old one and copy it to the new one?
Also if you have another way to synchronize files (syncthings, ...) you can keep them in sync that way. Just be sure not to open gPodder at the same time on both computers...

**Comment by kajodowe** [comment]
I should know that but I didn't think of it -- thanks! It worked great and I'm happy now! Thank you for taking the time to respond. Much appreciated!

-Allen

**Comment by elelay** [comment]
Cool that it works for you :-)
