### ISSUE TITLE
[Enhancement Idea] Automatically replace unsupported characters in podcast name with custom character and keep the original name inside of gPodder

### ISSUE THREAD

**Issue by Marrib** [gpodder/gpodder#1099]
**Current state**
I was trying to add a YouTube channel to gPodder which has a colon ":" in its name like "Super:Duper:Channel". I am on Windows so colons (and some other special characters) are not allowed in file or folder names in the file system (which is NTFS). Because of this gPodder does not accept the name "Super:Duper:Channel" so I had to rename it to something without the colon. This is not optimal because it forces users to alter the way of writing the original name.

**Idea**
It would be cool if the original name with the special characters could be preserved _inside_ gPodder in the podcast list. As for the folder and file names on the hard drive, gPodder could automatically replace unsupported characters with "_" or "-" or some other character that the user can specify somewhere in the preferences. This way the original podcast name would be preserved, at least in the podcast list.

**Comment by elelay** [comment]
Hi,
colon should be removed from the podcast folder, exactly as you describe. I can't try right now on Windows.
What version are you running? Have you tried with latest version 3.10.21?
Thanks,

**Comment by Marrib** [comment]
I am using gPodder 3.10.21 on Windows 10 21H1 x64.

When I am adding the YouTube channel "Computer:Club2" (https://www.youtube.com/channel/UCPiFOcskeiOj0jHz3YCWDBQ) to gPodder, it looks like screenshot 1 in the podcast list. Note that the colon has been removed from the name automatically by gPodder.
The folder in the download directory looks like in screenshot 2: the colon is missing there, because the Windows file System NTFS does not allow a colon in the name of a file or folder.

The colon in the podcast list inside gPodder should be preserved, the colon in the download folder is something I don't really care about. But to indicate that there a character replacement took place, gPodde could add a custom character like "_" or "-"


Screenshot 1
![01](https://user-images.githubusercontent.com/40357209/126825972-63c95b3a-1fec-47f9-93e8-3e071fa1b19c.png)

Screenshot 2
![02](https://user-images.githubusercontent.com/40357209/126826379-483d1577-00a4-4a5f-917e-3995a6de161c.png)

**Comment by elelay** [comment]
Thanks for the details.
Unfortunately I can't reproduce: 

on a fresh install of gpodder 3.10.21 portable, without youtube-dl extension:
![image](https://user-images.githubusercontent.com/222469/127048062-10269679-ae30-4d03-a504-9af1e420b9e8.png)

on a fresh install of gpodder 3.10.21 portable, with youtube-dl extension enabled (make sure to change episodes to keep to 10 or it takes forever to download hundred of video descriptions):
![image](https://user-images.githubusercontent.com/222469/127047667-38e19d33-184a-48df-a77c-f0614cf1c6f0.png)

Either way I don't get the show icon and the download folder is Computer_Club2
![image](https://user-images.githubusercontent.com/222469/127048392-53ae93f3-1a1d-47d1-a86b-d9ede4fb959b.png)

Is it an old subscription or have you subscribed recently? The podcast name and folder are chosen when it is first added to gPodder. Then it stays the same forever. Special character handling has been added some time ago, maybe you subscribed before?

**Comment by Marrib** [comment]
I have deleted and re-added the podcast with the youtube-dl extension enabled and disabled and this time it worked as you have described. However, I can rename the podcast to remove the colon. But it's not possible to add the colon again (for example when fixing a typo).

**Comment by elelay** [comment]
Indeed, that's a bug: when editing the name it's not escaped before converting it...
