### ISSUE TITLE
GPodder 3.10.21 Throws 'NoneType' Object Has No Attribute 'write' Error

### ISSUE THREAD

**Issue by ChrisMTheMan** [gpodder/gpodder#1101]
After updating to GPodder 3.10.21 I am getting an error on all video channels when using youtube-dl to manage subscriptions.  The error reads 'NoneType' object has no attribute 'write'.  Please see attached screenshot.  I also attached the error log.   System is Windows 7.
![ScreenHunter_522 2021-07-20 11 35](https://user-images.githubusercontent.com/64171309/126378368-4b0383be-c983-4bd0-8d60-ee3550985e0d.jpg)
[2021-07-20.log](https://github.com/gpodder/gpodder/files/6850543/2021-07-20.log)

**Comment by ChrisMTheMan** [comment]
Unchecking 'Manage Channel' in the config makes this error go away but the same error remains upon trying to download each video.
![ScreenHunter_523 2021-07-20 15 08](https://user-images.githubusercontent.com/64171309/126401686-82411537-6106-4214-a748-04d17bce6585.jpg)

**Comment by auouymous** [comment]
Does it work if you uncheck both?

**Comment by ChrisMTheMan** [comment]
It does work if I uncheck both.

**Comment by auouymous** [comment]
Does it break again if you re-check both?

Both 3.10.20 and 3.10.21 have the same 2021.06.06 version of youtube-dl. I turned on both settings and added one of your channels that failed, and it worked fine.

> ERROR: Cannot save <gpodder.gtkui.model.GEpisode object at 0x08240f08>: UNIQUE constraint failed: episode.podcast_id, episode.guid

This error was thrown (for you) for each channel that had updates. You might have a corrupt database or youtube-dl might be adding new episodes with the same guid. I'm not sure why, but gpodder hides these errors unless you have a console open. It should probably display them in the UI.

The errors you saw came from inside youtube-dl, and were most likely a result of the invalid guid during update.

If re-checking doesn't fix it, you could try a fresh install:
- export subscriptions to an OPML file
- stop gpodder
- rename the `gPodder` directory to `gPodder-backup`
- create `gPodder` directory and copy the `Settings.json` file to it
- start gpodder and import the OPML file
- turn off automatic downloads to avoid downloading episodes you've seen
- perform an update and download one episode

If this works, you can copy over the `Downloads` directory from `gPodder-backup`.

**Comment by ChrisMTheMan** [comment]
I rechecked both and found I also had to recheck Youtube-dl under Extensions.  I'll start the rest of the procedure you outlined.

**Comment by ChrisMTheMan** [comment]
Big errors after following this procedure.  Upon trying to import the OPML every video channel failed to import with the same error message as before.  See screenshot.  All audio channels imported fine.
![ScreenHunter_524 2021-07-20 19 00](https://user-images.githubusercontent.com/64171309/126418859-53d1c0c7-59f9-4b4d-a92c-c9064c5b5cef.jpg)

**Comment by auouymous** [comment]
So there is an issue with youtube-dl, and not the database. Did you use the installer or portable exe?

**Comment by ChrisMTheMan** [comment]
I used the installer.

**Comment by auouymous** [comment]
It works on Linux and Windows 10 (installer). The build system was upgraded from VS2015 to VS2019 to fix an msys2 issue and it is possible this is causing an issue with Windows 7. I'll try to get it working with VS2015 or VS2017 so you can test if that is the cause.

**Comment by ChrisMTheMan** [comment]
Would it be helpful for me to try the portable version and see if it works?

**Comment by auouymous** [comment]
https://ci.appveyor.com/project/elelay/gpodder/builds/40074705/artifacts

Could you try the installer for that build? It is 3.10.21 built using VS2015, which is what 3.10.20 was built with.

**Comment by ChrisMTheMan** [comment]
Just after I sent the above comment I put the portable version on.  It imported my OPML ok and has been getting video data for about the last 5 hours.  Once it completes I'll try the .21 build you mentioned.

**Comment by ChrisMTheMan** [comment]
Portable version is working with no errors and downloading ok with all the 'use youtube-dl' functions checked.  However, it is not getting the best video versions of videos.  One example is the video at https://www.youtube.com/watch?v=iil0mdr9GYo

There is a 4k version and it's only getting a 1920x1080 version of the video.

Video options are set like this:
![ScreenHunter_525 2021-07-21 11 57](https://user-images.githubusercontent.com/64171309/126544688-8f8e3e39-e3ec-494f-bea2-e1faed78a048.jpg)

**Comment by auouymous** [comment]
Don't bother trying the VS2015 build if portable version is working. It is possible the installer you downloaded was corrupt, and downloading it again and re-installing might fix it.

As for 4K video, you have selected MP4 which excludes WEBM, and that video only has 4K in a WEBM format. It has 1080 in both formats so that is what you got. The WEBM options fallback to MP4, but MP4 doesn't fallback to WEBM.

Have you tried streaming with that HLS setting? It should fail because HLS is not handled by youtube-dl and gpodder needs numeric format values. #963 has a WIP patch to stream with youtube-dl capable video players, but I think it uses the non-HLS formats setting.

**Comment by ChrisMTheMan** [comment]
Good to know on the fallback path.  I have not tried streaming yet...I don't usually stream, I just download.

I don't see youtube-dl as part of the portable version so am I right in suspecting it's using youtube-dl from my Python install?

**Comment by auouymous** [comment]
I don't know what the portable version is or if it bundles youtube-dl. Did re-downloading the installer and re-installing it work?

**Comment by ChrisMTheMan** [comment]
The fallback option doesn't seem to be happening.  On this video: https://www.youtube.com/watch?v=1FaUPvcK2a0 it downloaded a 1080p webm file when there is a 4 webm available.  I have the video options set like this.  Am I missing something?

![ScreenHunter_526 2021-07-22 10 32](https://user-images.githubusercontent.com/64171309/126683372-f8fb2bce-4638-481a-9120-05457c42a285.jpg)

**Comment by auouymous** [comment]
That video is 60fps and doesn't have a 30fps version. There is no support for 60fps formats yet, but you could create a custom format with `bestvideo[height<=2160]+bestaudio` to download any 4K content and exclude 8K content.

**Comment by ChrisMTheMan** [comment]
Weird...when I use youtube-dl from the commandline with bestvideo+bestaudio I get a 4k version.

youtube-dl.exe -f bestvideo+bestaudio -o "%(upload_date)s - %(title)s.%(ext)s" https://www.youtube.com/watch?v=1FaUPvcK2a0

Are you saying that Gpodder has no support for 60fps formats yet or youtube-dl?

If I used the <= option which box in config would I put that in?

**Comment by ChrisMTheMan** [comment]
This is what I see after downloading the video above and playing it in VLC.  It's 2160p and 60fps.

![ScreenHunter_527 2021-07-22 14 40](https://user-images.githubusercontent.com/64171309/126713037-028911a0-4f1c-4d71-8f11-bec9306bb58a.jpg)

**Comment by auouymous** [comment]
`bestvideo+bestaudio` will download 8K if available, that is why I suggested `bestvideo[height<=2160]+bestaudio`. The 60fps formats use different numeric IDs than 30fps formats and the gpodder format menu does not have those IDs. Adding those to the menu will likely never happen because there are already too many options, but we are slowly working to replace the menu with separate resolution, fps and file type menus.

The best format is entered the same way you did it for HLS, search for `fmt` in `edit config`.

**Comment by ChrisMTheMan** [comment]
I know that just as a simple user all the ID's are overwhelming.  Can't imagine how to deal with it as a developer.

I'm configured like this now, does this look right?

![ScreenHunter_528 2021-07-22 16 39](https://user-images.githubusercontent.com/64171309/126722005-be976f37-f8de-4f8d-b6a4-e5b25d2079c9.jpg)

**Comment by auouymous** [comment]
Select custom in the menu or change that 313 to a 0. And then select the highest format in the HLS menu because best doesn't work for streaming unless you have the #963 patch.

**Comment by ChrisMTheMan** [comment]
Got it!  Thank you.  Once all this is sorted I'll try downloading and installing the new version again.  Something came to memory.  Occasionally when downloading software it will install fine and run strange.  On a .exe download there is a property of the file to 'unblock' it.  I'll look for that before installing to test.

**Comment by ChrisMTheMan** [comment]
I am happy to report that Gpodder portable has been downloading highest resolution videos well.  It still has an older problem of not renaming files with a dollar sign in the name though.  I'll start testing a new download of the most current Windows build.

**Comment by ChrisMTheMan** [comment]
As to the installer for GPodder, I just downloaded it and, after making sure none of the old GPodder folders remained, installed it.  I had it import only about 15 entries from my OPML.  It imported them fine.  After config it began downloading 4k versions of videos.  It is working fine.

The only thing I can figure is perhaps the installed version of Youtube-dl in the GPodder folder was bad, my settings JSON file was bad, or, well, I don't know after that.  At any rate even though the installer version is working I'm going to stick with the portable version from here on out.

**Comment by elelay** [comment]
ok, thanks for the followup.
