### ISSUE TITLE
Include a method for packagers to disable update check

### ISSUE THREAD

**Issue by limburgher** [gpodder/gpodder#1103]
See: https://bugzilla.redhat.com/show_bug.cgi?id=1984726

**Comment by tpikonen** [comment]
There's the config variable software_update.check_on_startup, which could be set to False by default in src/gpodder/config.py with a one line patch. Would this be enough?

**Comment by limburgher** [comment]
That would be good, but they're looking for the menu option to be disabled/removed as well.

**Comment by auouymous** [comment]
There is no UI that can easily be disabled, only an "advanced" UI that shows all config options. The best solution would be to have gpodder check if a file exists, such as `/etc/gpodder-no-update-check`, and not perform the check even if the setting is enabled. The distro can then touch that file during install without needing to patch each release. Are there any conventions for such files?

**Comment by limburgher** [comment]
Not that I'm aware of. gpodder as currently packaged has nothing in /etc since everything is configured per-user. What about a build-time options to set that flag? That seems the most portable.

**Comment by tpikonen** [comment]
There is the 'Software updates' menu item in the app menu. But, I don't see the original bug report complaining about that, rather than about the automatic update, which happens every 5 days by default, and pops up a dialog if (and only if) a new version is found.

**Comment by limburgher** [comment]
/me needs to schedule an appointment with her optometrist.

I'll just patch software_update.check_on_startup. Thanks!

**Comment by auouymous** [comment]
Patching the default setting to False only works for new users, existing users will still have it set to True in their Settings.json file. The patch must remove the six lines in `gtkui/main.py` at `self.config.software_update.check_on_startup`.

**Comment by limburgher** [comment]
I'll patch that as well for now, thanks!

**Comment by oturpe** [comment]
Original reporter here.
Thank you everybody for working on this!
Fedora patch looks good (though it is diffucult to test properly)
and #1132 looks even better.
