### ISSUE TITLE
Unable to download an episode that has failed, without first cancelling it

### ISSUE THREAD

**Issue by auouymous** [gpodder/gpodder#1117]
Subscribe to https://www.youtube.com/channel/UCX4Vp6cm35OcPTQVN5_zeHQ and attempt to download the age-restricted video. It will fail because gpodder doesn't support age-gated content and youtube-dl is currently broken. Now try to download it again, the error icon disappears but nothing happens. You have to open progress and cancel the failed download before attempting to try the download again.

@blushingpenguin Prior to #1054, failed episodes could be re-downloaded without manually cancelling them.

**Comment by auouymous** [comment]
The issue is worse when downloading many episodes because cancelling a failed episode doesn't take effect until all episodes finish. You have to wait until everything finishes before queuing up the failed episodes.

**Comment by blushingpenguin** [comment]
@auouymous I have had another go at fixing this -- sorry for the long delay. Would you be able to retest and let me know?

**Comment by auouymous** [comment]
Fixed by #1149.
