### ISSUE TITLE
Font regression on Windows

### ISSUE THREAD

**Issue by neodyne** [gpodder/gpodder#1118]
In the latest portable version of gPodder (3.10.21), new install, on Windows 10 x64, the font across the program UI looks worse than in 3.10.20, as if not evenly spaced and smooth.  The contents of `data\etc\gtk-3.0\settings.ini` are  identical ( `gtk-font-name = Segoe UI 10`  ).

Screenshots ('Getting started' dialog, both have `gtk-application-prefer-dark-theme = true` added to settings.ini for better contrast, note for example 'de' in gpodder.net or 'st' in list):

v3.10.20 (normal):
![obrázok](https://user-images.githubusercontent.com/45676605/127778963-74216526-d20f-4493-8031-b9576df0914b.png)

v3.10.21 (worse):
![obrázok](https://user-images.githubusercontent.com/45676605/127778953-261099da-2c0a-4dfb-b401-dd4df4fd619a.png)

It probably doesn't show well because of compression but is immediately apparent when run and compared, and is even more obvious with diacritics.

**Comment by auouymous** [comment]
![cancel-diff](https://user-images.githubusercontent.com/5005204/127807573-054ade73-cfb2-47d0-9e2f-e179a9dc6ba5.png)

The kerning between the 'e' and 'l' has increased, other than that, the letters are identical. Some letters in otheer words have more kerning and others have less kerning. I don't see how kerning would change diacritics, unless they are using combining characters and the rendering engine is misplacing them.

The following is the difference between the two images. The cancel button centers the word, so the extra kerning changes the entire button. The others are left aligned and have no changes until the first kerned pair increases or decreases the width.

![diff](https://user-images.githubusercontent.com/5005204/127806960-d3a7c5bf-05ba-41d5-9f9f-6f048f121984.png)

Does the problem go away if you launch 3.10.20?

**Comment by neodyne** [comment]
> Does the problem go away if you launch 3.10.20?

Yes, as seen in the screenshots, when both portable versions are run side by side, the font in 3.10.20 looks normal, only the font in the latest version has the extra 'kerning' described.

The reason why it's immediately visually apparent is the mismatch to native windows font in explorer, or other applications, even other gtk-based ones set to Segoe UI, for example uGet. Diacritics like ť or ľ look depending on the position in a word often look 'smushed' and are less readable.

**Comment by neodyne** [comment]
I understand that this is an older issue, regardless, just wanted to point out that the regression is gone in current [git builds](https://ci.appveyor.com/project/elelay/gpodder/build/artifacts) from appveyor. This might have been an issue with the particular version/build of the msys2 gtk3 package gpodder 3.10.21 was built against.

What might also be an upstream regression, the above mentioned `gtk-font-name` preference in `settings.ini`  is completely ignored (both in release and git versions). Changing the font name, font size or even ommiting the line altogether has no effect, the application always follows system font/size.
