### ISSUE TITLE
Release flatpak packages on flathub

### ISSUE THREAD

**Issue by tpikonen** [gpodder/gpodder#1153]
I finally got a response from flathub maintainers and can now hopefully update the gPodder package at https://github.com/flathub/org.gpodder.gpodder (@elelay was also invited).

The flatpak build manifest will be in good shape once I get my changes merged, so adding new releases there should be easy. New releases should be also made to flathub along with other platforms.

I can have a look if that can be automated somehow.

**Comment by elelay** [comment]
Cool,
thanks for pushing this!
Pending automation you can update https://github.com/gpodder/gpodder.github.io/docs/release-process.md with instructions and we will apply them when releasing ;-)

**Comment by tpikonen** [comment]
I just updated the flathub package to the latest version and made a PR to update the release-process docs. Let's see how this works out on the next release.

**Comment by elelay** [comment]
Great, thanks!
