### ISSUE TITLE
gpo download fails for all feeds, gui works

### ISSUE THREAD

**Issue by dieterdeyke** [gpodder/gpodder#1157]
gpo download fails for all feeds, gui works

errors:
```
Wissen vor 8 - Natur
1631458085.569472 [__main__] WARNING: Action could not be completed
Traceback (most recent call last):
  File "/usr/local/gpodder/bin/gpo", line 222, in _action
    yield
  File "/usr/local/gpodder/bin/gpo", line 622, in _download_episode
    task = download.DownloadTask(episode, self._config)
  File "/usr/local/gpodder/src/gpodder/download.py", line 622, in __init__
    assert episode.download_task is None
AssertionError
Downloading Die Übersäuerung der Meere                                   [FAIL]
```

**Comment by auouymous** [comment]
Which version and commands are you using?

I tried `download [URL] [GUID]` in 3.10.21 and master. In 3.10.21 it shows progress and then completes the download as expected. In master it immediately shows `[DONE]` and doesn't download the episode, and opening gui shows a paused download.

@blushingpenguin This was introduced by 68195acc004b1a8f5e22c7dd46d63e7cc8bcca23.

**Comment by dieterdeyke** [comment]
auouymous ***@***.***> writes:

> Which version and commands are you using?
>
> I tried download [URL] [GUID] in 3.10.21 and master. In 3.10.21 it shows progress and then
> completes the download as expected. In master it immediately shows [DONE] and doesn't download the
> episode, and opening gui shows a paused download.
>
> @blushingpenguin This was introduced by 68195ac.

The version I use is from git:

commit 2ded35705eba54d3f41004a798db679327012809 (HEAD -> master, origin/master, origin/HEAD)
Author: Teemu Ikonen ***@***.***>
Date:   Sat Sep 11 03:14:12 2021 +0300

The commands are (from a python script):

    os.system("/usr/local/gpodder/bin/gpo update 2>&1 | grep -v -F 'WARNING: Using download URL as GUID' | grep -v -F '[DONE]'")
    os.system("/usr/local/gpodder/bin/gpo download")

When I use the gui after those commands I see that it updated the feeds
correctly, but all new episodes are in a pause state. To download them I
have to select them in the gui and use the download menu button.

-- 
Dieter Deyke
***@***.***
Get my Gnupg key:
gpg --keyserver keys.gnupg.net --recv-keys B116EA20

**Comment by blushingpenguin** [comment]
@auouymous @dieterdeyke this is fixed by https://github.com/gpodder/gpodder/pull/1155

**Comment by auouymous** [comment]
@dieterdeyke Current master branch fixes the issue I had above, does it fix the issue for you?

**Comment by dieterdeyke** [comment]
auouymous ***@***.***> writes:

> @dieterdeyke Current master branch fixes the issue I had above, does it fix the issue for you?

Yes, a quick test was successful. Thank you.

-- 
Dieter Deyke
***@***.***
Get my Gnupg key:
gpg --keyserver keys.gnupg.net --recv-keys B116EA20

**Comment by dieterdeyke** [comment]
Fix worked. Thank you.
