### ISSUE TITLE
gpodder fails for all youtube feeds (at least here in Germany)

### ISSUE THREAD

**Issue by dieterdeyke** [gpodder/gpodder#1165]
gpodder fails for all youtube feeds (at least here in Germany) 

error message:
```
1631813675.095769 [__main__] WARNING: Action could not be completed
Traceback (most recent call last):
  File "/usr/local/gpodder/bin/gpo", line 222, in _action
    yield
  File "/usr/local/gpodder/bin/gpo", line 547, in _update_podcast
    podcast.update()
  File "/usr/local/gpodder/src/gpodder/model.py", line 1175, in update
    result = self.feed_fetcher.fetch_channel(self, max_episodes)
  File "/usr/local/gpodder/src/gpodder/model.py", line 211, in fetch_channel
    return self.fetch(url, channel.http_etag, channel.http_last_modified, max_episodes=max_episodes)
  File "/usr/local/gpodder/src/gpodder/feedcore.py", line 190, in fetch
    res = self._check_statuscode(stream.status_code, stream.url)
  File "/usr/local/gpodder/src/gpodder/feedcore.py", line 143, in _check_statuscode
    raise Unsubscribe('forbidden')
gpodder.feedcore.Unsubscribe: forbidden
 WeeScottishLass                                                         [FAIL]
```

I get the same error message for all youtube feeds.

gpodder version is from github:

commit ed5d18e1b04f5e32b18d90b3da151a57ae507571 (HEAD -> master, origin/master, origin/HEAD)
Author: Mark Weaver <mark@blushingpenguin.com>
Date:   Tue Sep 14 08:53:15 2021 +0100

**Comment by auouymous** [comment]
Is this persistent or just a temporary youtube outage? And what commands did you use?

**Comment by dieterdeyke** [comment]
auouymous ***@***.***> writes:

> Is this persistent or just a temporary youtube outage? And what commands did you use?

gpo update.

The failure lasted for a whole day, but today everything is back to
normal, looks like a youtube glitch of some sort. Sorry for wasting your
time, I will be more patient the next time.

Thanks,
-- 
Dieter Deyke
***@***.***
Get my Gnupg key:
gpg --keyserver keys.gnupg.net --recv-keys B116EA20
