### ISSUE TITLE
[Question (and maybe feature improvement idea)] Better formatting of episode description / show notes possible?

### ISSUE THREAD

**Issue by Marrib** [gpodder/gpodder#1166]
Screenshot 1 shows the episode description of a video on the YouTube website, screenshot 2 shows what the same description looks like in gPodder. Paragraphs and line breaks, for example, are lost (clickable URLs, too, but I don't care about them not being clickable anymore).
Is this because gPodder ignores paragraphs and like breaks? Or is it because this unformatted text occurs like this in the YouTube feed added to gPodder? Any chance to keep the text formatted with paragraphs and line breaks like the original? (Probably not, I suppose, huh?)

![Screenshot (54)](https://user-images.githubusercontent.com/40357209/136123744-3b1c0f7a-3e7b-4e66-b0dc-e7784a27d008.png)

![Screenshot (55)](https://user-images.githubusercontent.com/40357209/136123749-9b0eba7a-0131-4a19-a5c7-f5963ecbcb8b.png)

**Comment by auouymous** [comment]
This feature was added by #1094, but you will need to wait for the next release or apply the patch.

**Comment by Marrib** [comment]
But does this https://github.com/gpodder/gpodder/pull/1094 also work for non-YouTube feeds?

**Comment by Marrib** [comment]
Thanks for fixing and providing the information. Very ture, clickable links for the timestamps like the YouTube website are of no importance in the description.
