### ISSUE TITLE
Switch from youtube-dl to yt-dlp?

### ISSUE THREAD

**Issue by auouymous** [gpodder/gpodder#1176]
Youtube-dl hasn't merged any PRs since 1jul2021 and last release was 6jun2021. Age-restricted content hasn't worked for a while, but no one has complained. Both youtube-dl and gpodder's native youtube support are throttled to ~50kbps. It is questionable how long the throttling "fix" will continue working in yt-dlp, so I may or may not try to fix the throttling in gpodder because of that.

The following patch uses yt-dlp if available, and it appears to work with no other changes. So we do have something to fallback to if the youtube API changes and youtube-dl still doesn't update.

```patch
--- a/share/gpodder/extensions/youtube-dl.py
+++ b/share/gpodder/extensions/youtube-dl.py
@@ -10,7 +10,10 @@ import re
 import sys
 import time
 
-import youtube_dl
+try:
+    import yt_dlp as youtube_dl
+except:
+    import youtube_dl
 from youtube_dl.utils import DownloadError, ExtractorError, sanitize_url
 
 import gpodder
```

yt-dlp required half a dozen or so dependencies that would need to be included in the windows and mac builds. Although, one of them was jeepney which may or may not cause issues with the fake dbus.

**Comment by tpikonen** [comment]
I agree that youtube-dl starts to be useless, at least with youtube.

When installed from pypi in linux, yt-dlp only adds two additional dependencies: websockets and pycryptodomex. This is not too bad IMO.

**Comment by mhussaincov93** [comment]
agreed with the switch to yt-dlp,

it will get things moveing again.

Majid
