### ISSUE TITLE
Can't delete from filesystem and unmark as delete

### ISSUE THREAD

**Issue by moorepants** [gpodder/gpodder#1178]
After I listen to a podcast episode (stream or from download) I press "delete" so that the file is deleted from my file system (to free space) *and* to mark the episode so I know I've listened to it. In some cases I download some episodes and don't get around to listening to them. At some piont I want to free up disk space they are occupying but not mark the episode as "listened to". I can't figure out a way to free disk space without marking it as deleted. I guess I shouldn't be using the "delete" functionality to label the episodes as "listened to", but there doesn't seem to be a way to do that otherwise. Is there a way to manage this? If I simply delete the episode's file from the filesystem (not from gpodder), is that the way to achieve this deletion without marking as deleted? Or is there a way to mark the episode in gpodder as "not deleted" after clicking "delete"?

**Comment by auouymous** [comment]
You need to delete the episode, show all episodes for the channel, and then click the mark as new twice (once to undelete and mark new, second to mark as old). There is an old PR #868 to do this with a single click that I will one day rebase and try to push forward again.

**Comment by moorepants** [comment]
I'm not getting this suggestion to work. I already always use the view setting that "shows all". When I right click and select new twice (or even more times) it still has the red delete symbol to the left of the episode.

**Comment by moorepants** [comment]
I got it to work. Seems like the right click setting for "new" does not work but if I use the menu bar setting for new it does. That solves my issue. Thanks.

**Comment by auouymous** [comment]
3.10.21 works fine, are you using an older version?

**Comment by moorepants** [comment]
I'm on 3.10.17 which just shipped with Ubuntu 21.10 this week.

**Comment by auouymous** [comment]
The "new" menu item was fixed by #991 in 3.10.20.

Also, keep in mind that episodes without files will not be held by gpodder if removed from the feed. For example, youtube feeds only contain the newest 15 episodes (unless managed with youtube-dl), and "undownloading" an older episode will result in it vanishing on the next update. Non-youtube feeds may or may not contain all episodes forever.

**Comment by moorepants** [comment]
Thanks!
