### ISSUE TITLE
Add an option for the dark theme

### ISSUE THREAD

**Issue by xmha97** [gpodder/gpodder#1194]
Hi, now gPodder supports the dark theme.
![image](https://user-images.githubusercontent.com/23485114/141367845-dec0606b-0e65-4821-86a6-ffe69aa1604e.png)
```
gtk-application-prefer-dark-theme = true
```
Please add an option for the dark theme on settings.
![image](https://user-images.githubusercontent.com/23485114/141368174-74899b39-f07d-43b0-a12e-a8de77e4297e.png)

**Comment by elelay** [comment]
I don't see a way for the gPodder app to do it easily

**Comment by auouymous** [comment]
Adding the following to `bin/gpodder` changes the theme from inside gpodder. We could have a config to choose between system theme, `Adwaita`, `Adwaita-dark`, or an option to enter a custom theme name. It might also be possible to scan known theme directories to provide more options.

```patch
                 logger.info('Cannot connect to remote object.', exc_info=True)
 
     if gpodder.ui.gtk:
+        if "GTK_THEME" not in os.environ:
+            os.environ["GTK_THEME"] = "Adwaita-dark"
+
         from gpodder.gtkui import app
         gpodder.ui_folders.insert(0, os.path.join(ui_folder, 'gtk'))
         app.main(options)
```

But I don't think `Settings.json` is loaded before the `from gpodder.gtkui import app` line, and setting GTK_THEME in `do_activate` in `gtkui/app.py`, where Core is initialized, is too late to work.
