### ISSUE TITLE
Website gpodder.net does not allow to register an account

### ISSUE THREAD

**Issue by Linkinsoldier** [gpodder/gpodder#1202]
Hi,

when I try to register an account i get the result:

_500 - Internal server error.
The service is currently overloaded. Please try again later or contact us._

Is this a known issue? I have tried it for some time now and was not able to register an account.
https://gpodder.net/register/

Thank you,
Linkin

![grafik](https://user-images.githubusercontent.com/24806068/147653111-b9728135-bd09-4b35-9876-0f674f896cd1.png)

**Comment by adamawoolley** [comment]
I have the same problem.

**Comment by auouymous** [comment]
See https://github.com/gpodder/mygpo/issues/673.
