### ISSUE TITLE
[Feature request] History of latest downloads

### ISSUE THREAD

**Issue by Jojo144** [gpodder/gpodder#1207]
It would be very nice to have an history of the latest downloaded files.

I often wonder what are the files that I have to listen among my many subscriptions...

Have anybody already tried something in this direction?

**Comment by auouymous** [comment]
I'm not exactly sure what you are asking for, but you can use the view menu to show only downloaded files, and then ctrl-click the columns to sort by release date. Unless you are using the command line `gpo`, you will need to use a file manager to browse the `~/gPodder/Downloads` folder.

If you are looking for a complete history of all downloads, you can write an extension or external tool to scrape the databases. The `gpodder.net` database tracks every action ever made, but I think it clears the database each time you sync to gpodder.net. But for those who don't sync:

```
# most recent downloads at bottom
sqlite3 ~/gPodder/gpodder.net 'select * from EpisodeAction where action = "download" order by timestamp;'

# most recent downloads at top
sqlite3 ~/gPodder/gpodder.net 'select * from EpisodeAction where action = "download" order by timestamp desc;'

# columns: action, device_id, episode_url, podcast_url, position, started, timestamp, total
```

You can replace `download` with `play` to see when you played episodes. You could join the query with `~/gPodder/Database` to map `episode_url` to an episode title and filename, and convert the unix timestamps to human readable dates.

**Comment by Jojo144** [comment]
Thanks for the pointers I will have a look.

I don't use gpodder.net indeed. But your sqlite query seems to do the job.
