### ISSUE TITLE
How we can orgenize our podcasts?

### ISSUE THREAD

**Issue by mohammadmohammadiarchangel** [gpodder/gpodder#1215]
Is it possible to create folders in the sidebar? or set some tags to organize our podcasts?

**Comment by auouymous** [comment]
In general preferences there is a `Use sections for podcast list` checkbox. Then open `podcast settings` by right-clicking on a podcast and in the `Settings` tab you can add the podcast to a new or existing section.

**Comment by mohammadmohammadiarchangel** [comment]
Thx.
