### ISSUE TITLE
bug! podcast files are not deleted after device sync completes via GPO if the delete podcast epesodes from gpodder is selected

### ISSUE THREAD

**Issue by mhussaincov93** [gpodder/gpodder#1216]
hi,
not really sure if this is a bugg,
but after epesode sync has completed to device, the epesodes are not purged from gpodder when ran via gpo, when ran via the gtk interface, the epesodes are deleted.
here's the relevent snip of settings.json.
"device_sync": {
    "after_sync": {
      "delete_episodes": true,
      "mark_episodes_played": false,
      "sync_disks": true
    },
    "custom_sync_name": "{episode.sortdate}_{episode.title}",
    "custom_sync_name_enabled": true,
   
being blind, the gpo cli interface is far more accessible and does not take too much load compared to the gtk interface does with orca my screen reader on linux.
hence my request for this to be fixed/added.
thank you for gpodder.
Majid Hussain

**Comment by auouymous** [comment]
The `after_sync.mark_episodes_played` and `after_sync.delete_episodes` options are only used by the gtk code. I'll see if the code can easily be ported to gpo.

**Comment by mhussaincov93** [comment]
hi,

my thanks!

Majid
