### ISSUE TITLE
Download error for a podcast

### ISSUE THREAD

**Issue by xmha97** [gpodder/gpodder#1229]
Hi, I'm using gPodder on Windows 10.
Download working fine,
but I can't download episodes from this podcast:
https://www.spreaker.com/show/4451544/episodes/feed
Please help me.

**Comment by auouymous** [comment]
I am able to subscribe, download and listen to episodes for that podcast. Which version of gpodder are you using? Can you try installing https://ci.appveyor.com/project/elelay/gpodder/builds/42488873/artifacts if you have 3.10.21 or older version? Please provide the error shown in UI or in logs if it still doesn't work.

**Comment by xmha97** [comment]
I tried again and I have no problem now.
