### ISSUE TITLE
Question: downloading more then 1000 items of a feed

### ISSUE THREAD

**Issue by tanja84dk** [gpodder/gpodder#1236]
I have the question of which file I should change the limit in for letting the gui go above the download max 1000 items per feed. The reason is that I have found a podcast where I would like to start from the beginning but unfortunally the RSS feed has almost 2500 entry's.

**Comment by auouymous** [comment]
Open preferences, click the edit config button at bottom and start typing `limit.episodes` until it appears in the list. You can then click the value and change it to anything.

**Comment by tanja84dk** [comment]
Thank you very very much that worked like a charm and sorry I didn't think of that.
#I were worried I had to change it in source Python files and then compile it again with the makefile wich I also were completely okay with, I just couldn't find the right file.

So again thank you very very much
