### ISSUE TITLE
not an issue really but a question when running gpodder from git, does the git version of gpodder use the settings file from /home/username/gpodder folder?

### ISSUE THREAD

**Issue by mhussaincov93** [gpodder/gpodder#1239]

**Comment by mhussaincov93** [comment]
woops pressed enter when I did not mean to.
so is the settings file from /home/username/gpodder used when gpodder is ran from  git?
curious you see,
running debian 11.
Majid

**Comment by elelay** [comment]
Hi,
yes it uses the same mechanism to [find gPodder home](https://gpodder.github.io/docs/user-manual.html#gpodder-home-folder-and-download-location) (${GPODDER_HOME}, default path, ...)

**Comment by mhussaincov93** [comment]
hi,

thanks for your answer!

Majid
