### ISSUE TITLE
Incorrectly displayed accents in Spanish

### ISSUE THREAD

**Issue by joteror** [gpodder/gpodder#1241]
Incorrectly displayed podcast summary text (accents) in spanish in a Linux laptop with Language->English (US), Formats->España, Input Sources->Spanish
Ubuntu 20.04, GNOME Shell 3.36.9
Sample:
Iniciamos el mes de marzo en Atm&oacute;sfera con propuestas muy experimentales, de gran peso y densidad. Abriremos los nuevos trabajos de Carlos Casas con su proyecto multiformato &ldquo;Kamana&rdquo;, el &ldquo;Ptriarchs&rdquo; de Christopher Chaplin, la uni&oacute;n de Sao Paulo Underground con los tinerfe&ntilde;os Tupperwear, el debut de Naaljos Ljom, Ka Baird &amp; Pekka Airaksinen, Kaspar, Megan Alice Clune, Geir Sundst&oslash;l, Peter Zirbs y Landikhan Feat. Dat Garc&iacute;a

**Comment by auouymous** [comment]
What is the feed URL?

**Comment by joteror** [comment]
Hi, thanks, sorry
http://api.rtve.es/api/programas/1891/audios.rss

**Comment by auouymous** [comment]
https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fapi.rtve.es%2Fapi%2Fprogramas%2F1891%2Faudios.rss

```
line 27, column 0: Invalid HTML: Named entity expected. Got none. (16 occurrences)
      <description>&lt;p&gt;Iniciamos el mes de marzo en Atm&amp;oacute;sfer ...
```

The feed is using HTML entities in the text description. The good news is that the git version and next version of gpodder will convert text descriptions to html in the shownotes, allowing for HTML entities and clickable links.

**Comment by joteror** [comment]
Thanks!

**Comment by joteror** [comment]
Sorry again, I have found another podcast with issues that seems to be OK for the validator.
feed URL:
https://www.ivoox.com/carnecruda-es-programas_fg_f157350_filtro_1.xml
validation:
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.ivoox.com%2Fcarnecruda-es-programas_fg_f157350_filtro_1.xml
Sample summary:
M&aacute;s Samantha de Hostias con Samantha Hudson &ldquo;Georgina&rdquo;, la serie de Netflix sobre la pareja de Cristiano Ronaldo, se ha convertido en un fen&oacute;meno de audiencia que nos lleva a hacernos muchas preguntas: &iquest;Por qu&eacute; fascinan las vidas de los ricos? &iquest;Por qu&eacute; conquistan sus historias de dinero, opulencia, gloria, fama? En Nuevo Mundo con Anna Pacheco traemos un programa de lujo para hablar de los ricos y de la vida de los pijos a trav&eacute;s del documental de Georgina. M&aacute;s informaci&oacute;n del programa aqu&iacute;: https://bit.ly/NuevoMundoGeorgina1015 Sigue haciendo posible nuestros monogr&aacute;ficos: http://bit.ly/ProduceCC

**Comment by auouymous** [comment]
That description also contains HTML entities, it does however wrap them in CDATA to make it a valid feed. The problem is that the old text shownotes only support plain text, and can't render HTML entities. The new shownotes will render it fine.

Another issue with this second feed, and the validator points it out, is that it uses HTML entities in the titles.

```
title should not contain HTML: &eacute; (108 occurrences)
    ... nan (NUEVO MUNDO - CARNE CRUDA #1015)]]></title>
```

So the title of that episode shows as `Ricos y famosos: por qu&eacute; fascinan (NUEVO MUNDO - CARNE CRUDA #1015)` in the episode list and in the shownotes for it.

**Comment by joteror** [comment]
Thanks again. Regards
