### ISSUE TITLE
Raspi3b gPodder 3.10.7 not receiving new episodes since march 5 2022

### ISSUE THREAD

**Issue by blokdk** [gpodder/gpodder#1247]
Dear members,
As described in the title of this post my gPodder installation on a raspberry 3b, working since 2019, suddenly stopped receiving new episodes from my subscriptions. 

When I run ps -aux | grep gpodder, the gpodder process shows up with a status Sl.

When I run a tcpdump and perform a Ctrl+R and Ctrl+N in gPodder, the dump with a filter on user agent gpodder is not empty, but shows very little = old news.

Please let your lights shine on this.

Thanks in advance,
peter blok

**Comment by auouymous** [comment]
Do you have a wide variety of feed hosts that aren't updating? Is the time correct on the gpodder device? Does a newer version of gpodder work?

**Comment by blokdk** [comment]
My OPML export showed 32 items. 
Time and date are correct.
sudo apt-get install gpodder informs me it is the latest version...

**Comment by auouymous** [comment]
Are those 32 feeds from the same domain, or are they from many different sites? And there are 14 newer releases, 3.10.21 is the latest.
