### ISSUE TITLE
Episode title with '%' causes gpo hang

### ISSUE THREAD

**Issue by davedeaven** [gpodder/gpodder#1254]
An unprotected use of episode.title string causes issues if the episode title contains a '%' character.

This fixes the issue in gpo:
```
--- a/bin/gpo
+++ b/bin/gpo
@@ -865,7 +865,7 @@ class gPodderCli(object):
             for idx, episode in enumerate(episodes):
                 if not episode.archive:
                     self._start_action(_('Deleting episode: %(episode)s') % {
-                            'episode': episode.title})
+                            'episode': episode.title.replace('%', '%%')})
                     episode.delete_from_disk()
                     self._finish_action(success=True)
                     episode_urls.add(episode.url)

```

**Comment by auouymous** [comment]
Would it not also hang for other calls to `_start_action()` such as downloading? Could you provide a feed and episode in which it hangs? And what OS are you running gpo on?

**Comment by davedeaven** [comment]
Yes, it also fails on download; the episode I ran into this has a title "0.25% Increase? No Problem!" accessible at https://www.fool.com/podcasts/motley-fool-money/2022-03-18-0-25-increase-no-problem

I am running on OpenSUSE linux tumbleweed, and reproduced in version 3.10.21, as well as a git clone from the same day I filed the issue.

The behavior in "gpo sync" is to raise an exception and then hang because (I assume) the background job queue never finishes.  I intercepted this and killed (kill -HUP), then tried the isolated fix when the same issue occurred on episode deletion as well.

I'm not sure how extensive the issue is across the code, or what the author's preferred pattern is to protect string expansion content from embedded format strings, so don't take this diff as a proposed comprehensive fix.

**Comment by auouymous** [comment]
What is the feed URL for that podcast? I tried https://www.fool.com/a/feeds/partner/googlechromefollow?apikey=5e092c1f-c5f9-4428-9219-908a47d2e2de but gpodder doesn't show any episodes for it.

**Comment by auouymous** [comment]
Are these the commands that fail for you?

```
gpo> download https://fool.libsyn.com/rss 0ac5476b-5302-4779-b5e4-94047dba57bf
Motley Fool Money
Downloading 0.25% Increase? No Problem!                                  [DONE]
1 episodes downloaded.

gpo> delete https://fool.libsyn.com/rss 0ac5476b-5302-4779-b5e4-94047dba57bf
Deleted episode "0.25% Increase? No Problem!".
```

**Comment by auouymous** [comment]
Thank you for reporting this. I was able to reproduce and it is now fixed in the master branch.
