### ISSUE TITLE
VirusTotal: 2 vendors flag as malicious windows-gpodder-3.10.21-installer.exe

### ISSUE THREAD

**Issue by jtmoon79** [gpodder/gpodder#1258]
The compiled installer [`windows-gpodder-3.10.21-installer.exe`](https://github.com/gpodder/gpodder/releases/download/3.10.21/windows-gpodder-3.10.21-installer.exe) appears to be malicious according to VirusTotal.

https://www.virustotal.com/gui/file/4ff9927cdb5433ada01865c22e7c9a5a3c5c4b205b2b69a6863bf5807171c504

**Comment by auouymous** [comment]
See #1013.

**Comment by joesmith222** [comment]
2 out of 67 isnt much

that one called MaxSecure returns a hit on half the files i check at VT

**Comment by Ryochan7** [comment]
Had to deal with this before. I doubt those results are even valid. Some of those virus check engines will flag an executable as malicious just because it is not digitally signed. Pretty much seems like extortion. Screws over a lot of open source projects.
