### ISSUE TITLE
Yards of error messages when trying to run latest version of gpodder from Github

### ISSUE THREAD

**Issue by brian-in-crawford** [gpodder/gpodder#1279]
gpodder was updated from Github just before 10pm USA Eastern time. Attempting to run gpodder just gave the menu bar, but nothing else. Running the executable from a terminal prompt gave a *LOT* of the following message (see below) - I suspect it was probably one instance per podcast to which I'm subscribed, but I can't verify that because the number fo lines exceeded the size of the buffer. I'm running 64-bit Linux Mint v 20.3 LTS. 
I know nothing about programming in Python so I'm stuck - if there's some other information I can provide, please tell me what you need. 

Traceback (most recent call last):
  File "/data3/git/gpodder/src/gpodder/gtkui/main.py", line 1342, in on_treeview_query_tooltip
    if not getattr(treeview, TreeViewHelper.CAN_TOOLTIP) or x > 50 or (column is not None and column != treeview.get_columns()[0]):
AttributeError: 'TreeView' object has no attribute '_gpodder_can_tooltip'
1650330604.018889 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/data3/git/gpodder/src/gpodder/gtkui/main.py", line 1342, in on_treeview_query_tooltip
    if not getattr(treeview, TreeViewHelper.CAN_TOOLTIP) or x > 50 or (column is not None and column != treeview.get_columns()[0]):
AttributeError: 'TreeView' object has no attribute '_gpodder_can_tooltip'

**Comment by auouymous** [comment]
What is the first error? When something fails at startup, causing a blank UI, there will usually be a lot of additional errors hiding the actual failure.

**Comment by brian-in-crawford** [comment]
I ran gpodder again with all output and error messages diverted to a log file. There were a couple of error messages, and a whole bunch of warnings, but this time the UI *did* come up, and if I had run gpodder via the desktop icon, it would have appeared to be functioning normally. There was no sign of the error messages I listed above. I've cut-and-pasted the error messages below, removing the warnings that just related to some missing files from the feeds, but again, the UI DOES appear to be functioning normally now. The only thing that has happened between the errors above and the current run is I closed the PC down overnight. 

Here's the top of the error log. I'm not sure why the messages about youtube_dl, I absolutely DO have it installed. 


  File "/data3/git/gpodder/src/gpodder/extensions.py", line 221, in require_command
    raise MissingCommand(msg, command)
gpodder.extensions.MissingCommand: Command not found: normalize-ogg
1650351192.663050 [gpodder.extensions] ERROR: Cannot load youtube-dl from /data3/git/gpodder/share/gpodder/extensions/youtube-dl.py: No module named 'youtube_dl'
Traceback (most recent call last):
  File "/data3/git/gpodder/share/gpodder/extensions/youtube-dl.py", line 14, in <module>
    import yt_dlp as youtube_dl
ModuleNotFoundError: No module named 'yt_dlp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data3/git/gpodder/src/gpodder/extensions.py", line 260, in set_enabled
    self.load_extension()
  File "/data3/git/gpodder/src/gpodder/extensions.py", line 302, in load_extension
    module_file = imp.load_module(basename, fp, self.filename,
  File "/usr/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data3/git/gpodder/share/gpodder/extensions/youtube-dl.py", line 16, in <module>
    import youtube_dl
ModuleNotFoundError: No module named 'youtube_dl'

**Comment by auouymous** [comment]
There should be logs in ~/gPodder/Logs/ that would have errors from the previous launches.

Did the youtube-dl extension work in your previous gpodder install, and was it an older git version or a release package?

**Comment by brian-in-crawford** [comment]
The youtube-dl extension is the up-to-date release according to the output if I run youtube_dl -U (dated 2021-12-17) and yes, it worked in the previous install, and is apparently working OK now. I have attached the logfile which contains the error messages that I originally mentioned. 

[2022-04-18.log](https://github.com/gpodder/gpodder/files/8510911/2022-04-18.log)

**Comment by auouymous** [comment]
This is what caused the UI to not load.

```
sqlite3.OperationalError: Could not decode to UTF-8 column 'description_html' with text '<style type="text/css">
    body > img { float: left; max-width: 30vw; margin: 0 1em 1em 0; }
    </style>
    <p>Melvyn Bragg and gues
```

If you can identify which episode that is based on the `Melvyn Bragg and gues`, you can check if the description is still corrupted and whether or not updating the feed fixes it or causes another corruption crash.

**Comment by brian-in-crawford** [comment]
Thanks - that's got to be one of the general BBC feeds, as I certainly wouldn't download anything specific to Melvyn Bragg! I'll work my way through them. There's something goofy with the BBC's feeds at times anyway, as occasionally *individual* messages give me an error 

HTTP Error 403: 403 Client error: Forbidden for url: <long url beneath open.live.bbc.co.uk> 

The BBC's support people insist that it's nothing to do with the settings on their server, but they're unable to (or won't) explain why other episodes in that feed aren't affected if it's something at my end.
