### ISSUE TITLE
RE enable podcast renaming

### ISSUE THREAD

**Issue by clort81** [gpodder/gpodder#1291]
the podcasts dirs have spaces

i used to be able to disable that, rename podcasts.  that is now gone.

the are you doing?

**Comment by auouymous** [comment]
Works fine for me. Open channel dialog, click the pencil next to channel name, change it, click save button, and close dialog. Nothing happens until the dialog is closed, reopening the dialog will show the new download location, and directory on disk will be the same.

**Comment by clort81** [comment]
Channel dialog? 
I used to change this right clicking the podcast in the "Podcast" list.
Change "settings"
The podcast name was clickable and editable.  
I renamed the podcast (removing spaces) and the directory on my filesystem adopted the new name, without spaces.
Who removed that? Why?  I need that.

**Comment by clort81** [comment]
Thank you that works.
