### ISSUE TITLE
Need suggestions to fix layout of the new delete dialog

### ISSUE THREAD

**Issue by auouymous** [gpodder/gpodder#1292]
The delete dialog now has an undownload checkbox added by #1284 (when deleting downloaded episodes), and I've discovered a few issues after merging it, oops.

The deleted episode titles are clipped to 60 characters and the "deleting removes files" message is shorter than that, at least in english. The problem is that the checkbox message increases the dialog width, and may or may not be an issue on mobile (@tpikonen). I could insert a newline into the message but translations might not position it properly. Wrapping the checkbox label with the following patch does nothing.

```patch
--- a/src/gpodder/gtkui/interface/common.py
+++ b/src/gpodder/gtkui/interface/common.py
@@ -124,6 +124,7 @@ class BuilderWidget(GtkBuilderWidget):
             dlg.set_markup('<span weight="bold" size="larger">%s</span>' % (message))
         if checkbox:
             cb = Gtk.CheckButton.new_with_label(checkbox)
+            cb.get_child().set_line_wrap(True)
             cb.set_active(default_checked)
             dlg.get_message_area().pack_end(cb, False, False, 0)
             dlg.get_widget_for_response(Gtk.ResponseType.NO).grab_focus()
```

Should we use a newline, force dialog to an unresizeable width or does someone have a better solution?

The checkbox is also too close to the message, making it too busy and harder to read. Should we add a separator, somehow move the checkbox out of the message area so it is closer to the buttons with padding above, or does anyone have a better idea?

```patch
--- a/src/gpodder/gtkui/interface/common.py
+++ b/src/gpodder/gtkui/interface/common.py
@@ -126,6 +126,7 @@ class BuilderWidget(GtkBuilderWidget):
             cb = Gtk.CheckButton.new_with_label(checkbox)
             cb.set_active(default_checked)
             dlg.get_message_area().pack_end(cb, False, False, 0)
+            dlg.get_message_area().pack_end(Gtk.Separator(orientation=Gtk.Orientation.HORIZONTAL), False, False, 0
             dlg.get_widget_for_response(Gtk.ResponseType.NO).grab_focus()
         dlg.show_all()
         response = dlg.run()
```

**Comment by elelay** [comment]
maybe a checkbox with a shote message + a longer paragraph in a multiline text container?

**Comment by tpikonen** [comment]
Yes, the checkbox label makes the dialog too wide for mobile screens.

A short label ('Mark deleted episodes as new') plus a longer wrapping explanation label, as suggested above, would solve this.

**Comment by auouymous** [comment]
The problem is that labels only wrap if their parent has a fixed size. Giving the label or checkbox label a max character count does work, and 50 should make it narrower than the longer title clipped to 60.

```patch
--- a/src/gpodder/gtkui/interface/common.py
+++ b/src/gpodder/gtkui/interface/common.py
@@ -124,8 +124,12 @@ class BuilderWidget(GtkBuilderWidget):
             dlg.set_markup('<span weight="bold" size="larger">%s</span>' % (message))
         if checkbox:
             cb = Gtk.CheckButton.new_with_label(checkbox)
+            cb_label = cb.get_child()
+            cb_label.set_line_wrap(True)
+            cb_label.set_max_width_chars(50)
             cb.set_active(default_checked)
             dlg.get_message_area().pack_end(cb, False, False, 0)
+            dlg.get_message_area().pack_end(Gtk.Separator(orientation=Gtk.Orientation.HORIZONTAL), False, False, 0)
             dlg.get_widget_for_response(Gtk.ResponseType.NO).grab_focus()
         dlg.show_all()
         response = dlg.run()
```

But translations of "Deleting episodes removes downloaded files." might also cause the dialog to stretch. And a chinese episode title, while limited to 60 characters, would be about twice as wide as an english title. So the correct fix should some how limit the width of the dialog or its entire message area. `dlg.set_size_request(480, -1)` and `dlg.set_default_size(480, -1)` don't have any effect on its width.

**Comment by elelay** [comment]
Would non-editable text area do the trick?

**Comment by auouymous** [comment]
The textview from show_message_details() solves the issue and looks really good with message in a scrolled window + textview and the checkbox in a second scrolled window with no border. Problem is that it requires a fixed height, which must be large enough to handle the largest of the nine cases that use the confirmation dialog, otherwise they will be forced to scroll. I have yet to figure out how to make it grow in height up to some maximum value.
