### ISSUE TITLE
Can't add youtube channel with accents in the name

### ISSUE THREAD

**Issue by ndias** [gpodder/gpodder#1318]
The subject says all.

This is the error

Could not parse feed: https://www.youtube.com/c/MárcioFrutíferasemVaso: <unknown>:1:44: Unsupported feed type: html

this is an example

https://www.youtube.com/c/MárcioFrutíferasemVaso
Version
gpodder-3.10.21-5.fc36.noarch

**Comment by tpikonen** [comment]
Can you subscribe to youtube URLs with channel names without accents (like https://www.youtube.com/c/NeoTechHD )? If not, then this is a known bug: #1290.

**Comment by auouymous** [comment]
I agree, as I was able to subscribe to https://www.youtube.com/c/M%C3%A1rcioFrut%C3%ADferasemVaso in the US.

**Comment by auouymous** [comment]
@ndias I am in the US, are you in Europe? If so, the problem is a GDPR consent page we are trying to fix in #1290.

**Comment by ndias** [comment]
Yes I'm in Europe, ok thanks.
