### ISSUE TITLE
Existing episodes not being recognized.

### ISSUE THREAD

**Issue by arbizm** [gpodder/gpodder#1337]
![gpod01](https://user-images.githubusercontent.com/73392799/178744733-12310ca8-8038-458b-b0f6-d24f9312055d.PNG)

![gpod02](https://user-images.githubusercontent.com/73392799/178744780-0b07fa70-84e8-45c1-8096-9b45424bccc9.PNG)

Notice episode 3, as displayed in the title attribute is already present in the download folder but is still in the new episodes window in the first picture.  After downloading both episodes, notice episode 3 still has the same name with only an updated modification date.

This is for the Unfinished podcast.  I'm uncertain how to duplicate it or document right now but thought it worth mentioning since I've seen this behavior recently.  I've said, "I downloaded that episode yesterday didn't I?"  It's been seen at least a dozen times on different podcasts in the last few weeks.  

Perhaps others can observe if they see similar behavior and some pattern can be discerned.

**Comment by arbizm** [comment]
I'll keep an eye on it and see if I see any patterns but thought it was worth reporting.  I'll close for now and see if anything repeatable emerges.

**Comment by auouymous** [comment]
@arbizm Look in gpodder's log files for any warnings related to the podcasts. Podcasts that don't use stable GUIDs do not work with gpodder because it has no way to track existing episodes. If this is the case, you will see GUID warnings in the log telling you to contact the feed author.
