### ISSUE TITLE
Would be nice if gpodder could call yt-dlp as external program instead of using it as a module

### ISSUE THREAD

**Issue by dieterdeyke** [gpodder/gpodder#1338]
Would be nice if gpodder could call yt-dlp as external program instead of using it as a module. While yt-dlp always works for me, is fast, and configured just the way I need it, I failed to make gpodder find and use it as a module.

**Comment by auouymous** [comment]
Are you using current git? 3.10.21 doesn't support yt-dlp.

If git, try running `python -c 'import sys ; print(sys.path)'`. Is yt-dlp installed in any of the directories it outputs? If not, try `PYTHONPATH='/a/b/c' gpodder`, where '/a/b/c/yt_dlp/' is the location you installed it.

**Comment by computerfreak105** [comment]
Would be awesome if this could be done on windows as well. Because I notice that many videos aren't downloaded at the moment. If I download them manually with yt-dlp it's no problem. So I hope that we all can update yt-dlp soon.
I downloaded an artifact about three days ago, but I guess the yt-dlp version there is not new enough at the moment.

**Comment by auouymous** [comment]
@computerfreak105 The Windows artifacts always use the most recent version of yt-dlp. Do you have the youtube-dl extension enabled and either manage downloads with it or manually use the download with ytdl menu option? If so, what is the reason it won't download?

**Comment by dieterdeyke** [comment]
auouymous ***@***.***> writes:

> Are you using current git? 3.10.21 doesn't support yt-dlp.
>
> If git, try running python -c 'import sys ; print(sys.path)'. Is yt-dlp installed in any of the
> directories it outputs? If not, try PYTHONPATH='/a/b/c' gpodder, where '/a/b/c/yt_dlp/' is the
> location you installed it.

I am using current git, and gpodder does find yt_dlp to import. But I
still get often the error:

Failed: Missing content from server

from gpodder, while the yt-dlp executable does not have the problem.

-- 
Dieter Deyke
***@***.***
Get my Gnupg key:
gpg --keyserver keys.gnupg.net --recv-keys B116EA20

**Comment by auouymous** [comment]
@dieterdeyke Is "manage downloads" enabled in the youtube-dl extension? Does "download with youtube-dl" appear in the menu when you right click an episode that hasn't been downloaded? That `Missing content from server` error should only happen when using gpodder's builtin youtube code.

**Comment by dieterdeyke** [comment]
auouymous ***@***.***> writes:

> @dieterdeyke Is "manage downloads" enabled in the youtube-dl extension? Does "download with youtube-dl" appear in the menu when
> you right click an episode that hasn't been downloaded? That Missing content from server error should only happen when using
> gpodder's builtin youtube code.

I finally understood what you meant with "manage downloads", it is part
of the config section, it is not in the menu. Enabling "manage
downloads" did indeed solve the problem, so I will close the enhancement
request now.

Thanks for you help,
-- 
Dieter Deyke
***@***.***
Get my Gnupg key:
gpg --keyserver keys.gnupg.net --recv-keys B116EA20

**Comment by dieterdeyke** [comment]
auouymous ***@***.***> writes:

> @dieterdeyke Is "manage downloads" enabled in the youtube-dl extension? Does "download with
> youtube-dl" appear in the menu when you right click an episode that hasn't been downloaded? That
> Missing content from server error should only happen when using gpodder's builtin youtube code.

I do not see "manage downloads". On my system there is something called
"Parse YouTube channel feeds..." and "Download all supported
episodes...", both which are disabled at the moment.  If I right-click
the failed episode I see "Download with youtube-dl", and using this the
download succeeds. Which of those buttons in the Preference menu should
be activated to make this automatic?

-- 
Dieter Deyke
***@***.***
Get my Gnupg key:
gpg --keyserver keys.gnupg.net --recv-keys B116EA20

**Comment by computerfreak105** [comment]
@auouymous
Thanks, the it yt-dl wasn't enabled yet ... my fault!
Should I let it amange my downloads or use the download yt-dl menu option for best results?
Can I set up the 2nd from the CLI or configure the settings.json file with an editor?

**Comment by auouymous** [comment]
The `manage_channel` setting is listed as "Parse YouTube channel feeds ..." in preferences. This slows down feed updating but allows you to access more than 15 episodes.

And the `manage_downloads` setting is listed as "Download all supported episodes ...". This is the setting needed to automatically use youtube-dl or yt-dlp for all youtube episodes.

@computerfreak105 Look for those two names in Settings.json.
