### ISSUE TITLE
After update "No downloadable content"

### ISSUE THREAD

**Issue by jake9wi** [gpodder/gpodder#1344]
Today I updated to gPodder 3.11.0.

A two podcast feeds that where working with gPodder 3.10.21 now gives the error message "No downloadable content. 
 
Feed URL:  `https://wheredidtheroadgo.com/show-archive?format=feed`
Feed URL: `https://www.strangefamiliars.com/home?format=rss`

### Setup
- OS: Win 10 x64
- gPodder 3.11.0 portable

### Update Method

Extracted the archive then copied the folder `data/` over the old `data/` folder

### Screenshots

![gppoder-noc2](https://user-images.githubusercontent.com/1775323/182027055-f9b77acf-7414-4bdf-8497-899442f2674b.png)

![gppoder-noc](https://user-images.githubusercontent.com/1775323/182026579-0671e8f0-cf16-40a9-9c4c-9005e27d8dfe.png)

**Comment by auouymous** [comment]
> Feed URL: https://wheredidtheroadgo.com/show-archive?format=feed

This feed does not contain enclosures and does not work in 3.10.21 (maybe it worked at sometime in the distant past). Until 3.11.0, gpodder would discard any episode without an enclosure (downloadable content). It now keeps those episodes so you can see informational episodes that only contain shownote text (text only updates, blog feeds, ...). Some feeds have links to media that must be viewed on the website and can't be downloaded.

The linux version of gpodder has optional support for HTML shownotes and this feed would have stream-only audio controls. If you open shownotes, you will see a download link which opens your browser and downloads the episodes outside of gpodder. You can also click the episode title in shownotes to open it in your browser and listen there. So the feed has chosen not to support podcast clients like gpodder.

> Feed URL: https://www.strangefamiliars.com/home?format=rss

This feed mostly has enclosures and a few patron-only episodes (read the shownotes for one of them). The episodes without downloadable content were never visible in 3.10.21.

**Comment by jake9wi** [comment]
Good to know
