### ISSUE TITLE
Gpodder Windows, ignore download errors and keep downloading?

### ISSUE THREAD

**Issue by computerfreak105** [gpodder/gpodder#1345]
I like to let run GPodder all the time and let it download every 90 minutes.
I know that gpodder sort of generates some messages and windows when a download fails. It seems to come from powershell.
I'm not sure if this was always the case, but I just noticed that gpodder stops pocessing the download list and restarts to download only if I hit escape a hundred times until all download error windows messages are closed.
Because download errors are quite often with youtube channels because of geo restrictions I'd be very happy if gpodder could be made to keep on downloading and maybe only write the errors in the log file?
Other than that I'd like to thank you all for the new release. Great job, thanks for all the time and hard work you invest in this.

**Comment by auouymous** [comment]
By "messages", do you mean notifications? My system lacks the ability to show notifications and gpodder has never spammed me with any dialogs that required closing. Take a look at the screenshot in #1323 for disabling notifications.

Do you have the youtube-dl extension enabled and let it `manage downloads`?

**Comment by auouymous** [comment]
@elelay Do you know if notifications block the download thread until acknowledged?

**Comment by computerfreak105** [comment]
I'm not sure. I think the notifications in windows are like a bubble but you don't have to do anything. The "messages" I mean are more like in GPodder itself. I have to press escape until all error messages are closed and then Gpodder is downloading again.

I'm blind and therefore can't see the screenshot to disable notifications. But now you mention that I have disabled all messages from windows PowerShell in the windows info center.
I'll see if this is the solution. I'll keep you informed.

I have youtube-dl extension enabled and have it manage channels enabled. But manage downloads is disabled.
Should I enable this as well for best results?

Thanks.

**Comment by auouymous** [comment]
What is the exact text on the error "messages"?

I also use youtube-dl with manage downloads disabled so I know if the native youtube support breaks. I do however manually download large episodes, and those with "missing content", using youtube-dl. Enabling manage downloads would use youtube-dl for all youtube episodes and eliminate the errors you receive.

**Comment by computerfreak105** [comment]
Hi, I enabled messages for powerShell in the windows info center again. But I haven't received any error messages so far anymore.
Don't know what this was all about.
I think it's best to have this issue closed until it starts again. In this case I'll note the exact error message which was popping up. As far I can tell it wasn't reported in the log files.
Thanks anyway.
