### ISSUE TITLE
Extract portable Windows version directly into the chosen directory

### ISSUE THREAD

**Issue by anewuser** [gpodder/gpodder#1346]
If you tell `-portable.exe` to extract gPodder to  `c:\gpodder`, it creates and uses `c:\gpodder\gpodder-x.xx.x-portable` instead, so you can't overwrite the previous version directly.

Since gPodder includes too many files (#1342), this makes the process of updating the portable version even longer on slower drives.

Consider extracting gPodder directly into the chosen directory, like [MAME](https://www.mamedev.org/release.html) does.

**Comment by auouymous** [comment]
I don't use Windows and don't know the purpose of gpodder's "portable app". Why do you use it instead of the installer?

**Comment by anewuser** [comment]
In short, a Windows folder with a portable program is like a Linux AppImage + the application settings.

If you copy the folder to a USB stick or another computer, the program is expected to work just the same as it worked where you originally used it.  Consequently, you can also have a full backup of all portable applications you use. Just extract it and everything's working again. This saves people a tremendous amount of time, besides keeping Windows installs safer and cleaner.

Here's a more detailed description: [What Is a “Portable” App, and Why Does It Matter?](https://www.howtogeek.com/290358/what-is-a-portable-app-and-why-does-it-matter/)

**Comment by auouymous** [comment]
Okay, so it extracts its versioned folder to the folder you specify, instead of extracting the contents of the versioned folder there. The portable version uses 7-Zip and might be limited by its runtime abilities.

I bumped the version from 1604 (2016?) to 2201 in ce9a2a7103c6d5ba2bbc78d348abefd6b4b2d557, and https://ci.appveyor.com/project/elelay/gpodder/builds/44356392/artifacts will have a new build ready in about an hour if you want to see if the updated UI allows you to extract contents from the versioned folder.

If that doesn't work, we would need to eliminate the versioned folder from the archive. You can probably see the issues that would cause if someone extracted to `c:\`.

**Comment by anewuser** [comment]
MAME uses the same kind of 7-Zip self-extracting executable. That's why I mentioned it in the first post. Unfortunately, the ce9a2a7 build presents the same behavior, and the root versioned folder isn't shown until I press `Extract`.  There's no root folder in MAME releases, but you've got a point. People might accidentally extract it to the wrong place and then end up deleting important files. 

The contents of these executables can be explored with the regular 7-Zip program, but that's counterintuitive. gPodder could instead be distributing the portable version in the regular `zip` or `7z` formats (like most portable applications do - [example](https://notepad-plus-plus.org/downloads/v8.4.4/)), especially since you already offer a conventional `.exe` installer. That's up to you, though.

This is actually something that can be improved by 7-Zip. I'm going to submit a suggestion to its developers for them to consider detecting this folder automatically and displaying it in the self-extracting GUI, as similar installers/extractors would do. Then, if the user manually erases `/gpodder-version` from the displayed path, extract it directly into the chosen directory. 

Thank you for looking into it. At least this has brought to your attention that the build script was pointing to an old 7-Zip version.

**Comment by auouymous** [comment]
> I'm going to submit a suggestion to its developers for them to consider detecting this folder automatically and displaying it in the self-extracting GUI, as similar installers/extractors would do. Then, if the user manually erases \gpodder-version from the displayed path, extract it directly into the chosen directory.

Simply detecting a single folder and displaying an unchecked checkbox to extract its contents to the chosen path would be better. Otherwise the user might change the path to `c:/` and not add the sub-folder.

Please open another issue if they implement this and we can bump the version.

**Comment by anewuser** [comment]
I wasn't clear. My suggestion is to automatically append your folder to the end of whatever path the user picks. So, if I pick `c:\apps\gpodder`, it targets and displays `c:\apps\gpodder\gpodder-version` in the destination input. Files would be extracted directly into `c:\` only if the user went out of his/her way to delete everything else in the text input. 

That's how similar applications handle this. Of course, the extractor could also have a built-in function to prevent leaving out just `c:\` in the text input.

**Comment by auouymous** [comment]
I understand what you meant and `c:\` is not the only path that could cause issues. A checkbox would make it quite clear what was going to happen.

```
Extract to: [ C:\                                          ]

Archive contains a single folder "gpodder-VERSION-portable".
[ ] Extract contents of folder to chosen path?
```

**Comment by anewuser** [comment]
Most Windows users never touch the text input with the destination path. If they want to change it, they use the directory picker.

When developers have the same fears as you, though, they simply disable that text input to make it impossible to delete the appended folder. That's a safer and easier solution. People wouldn't make accidents, and I'd see your hardcoded folder and be free to either accept it or explore the `.exe` with 7-Zip to manually extract the files the way I want.
