### ISSUE TITLE
FUI Virus scann

### ISSUE THREAD

**Issue by btrfsgd** [gpodder/gpodder#1349]
Hi ...
download from
https://gpodder.github.io/

The result:
360 Total Security
____________________________________
windows-gpodder-3.10.5-installer.exe
Type:		**Win32/Trojan.Generic.HgIASwQA**
Scan Engine:	360 Cloud Scan Engine
File path:	       ..\windows-gpodder-3.11.0-installer.exe
File size:	       26.08M (27,350,148 Bytes)
MD5:		be16a3b619049308d553fe03ed134a9c
Suggestion:	Quarantined files
_____________________________________
windows-gpodder-3.11.0-portable.exe
Type:		**Win32/Trojan.Generic.HgIASwQA**
Scan Engine:	360 Cloud Scan Engine
File path:	        ..\windows-gpodder-3.11.0-portable.exe
File size:	        25.59M (26,829,923 Bytes)
File version:	16.04
File description:	7z SFX
MD5:		d892e3a249b5bbb5685d4ee97f3ee692
Suggestion:	Quarantined files

Please check.

Regards
Gerd

**Comment by anewuser** [comment]
@btrfsgd  Please use this form to report this false positive to your antivirus vendor: https://www.360totalsecurity.com/en/suspicion/false-positive/ .

**Comment by auouymous** [comment]
See #1013.
