### ISSUE TITLE
Episode descriptions missing on New Episodes panel since 3.11.0

### ISSUE THREAD

**Issue by strawbeard** [gpodder/gpodder#1350]
When hovering over a new episode on the _New Episodes_ panel, its description should appear in a **tool-tip**. Almost all of these tool-tips  are **empty** now after installation of _version 3.11.0_. When displaying these entries on the _Episodes_ panel descriptions are shown in the lower half.

**Comment by auouymous** [comment]
What feed URL does it happen with?

**Comment by auouymous** [comment]
Fixed, thank you for reporting it.

**Comment by strawbeard** [comment]
Thank you for fixing it! 👏

**Comment by strawbeard** [comment]
Thank you for finally releasing (3.11.1) it.😁
