### ISSUE TITLE
3.11.0 Soft crashing when checking for new podcasts

### ISSUE THREAD

**Issue by WooodDevil** [gpodder/gpodder#1352]
Every time the program tries to check for new podcasts it won't crash but I won't be able to click on anything. When I mouse over the X and minimize buttons they will highlight like they are active but won't do anything when click on them so I need to use task manager to end the program. I've tried uninstalling and reinstalling. I'm on Windows 10.

**Comment by auouymous** [comment]
Does it become unresponsive when the progress bar in lower left is active or when downloading the episodes after the update has finished?

If it happens during an update, please start gpodder in debugging mode https://gpodder.github.io/docs/windows.html#debugging-gpodder-on-windows, start the update and wait for it to become unresponsive (don't kill gpodder yet). Then find the most recent log in the Logs folder https://gpodder.github.io/docs/user-manual.html#default-gpodder-home-folder and scroll to the bottom of the log file to see if it shows something useful. Close and re-open the file (every so often) to see if new messages have been logged. Post the last several lines of the log here, filtering any credentials.

**Comment by WooodDevil** [comment]
I can click on stuff while the progress bar is going but as soon as it's done and the bar goes away it's unresponsive. Should I still use the debug mode

**Comment by auouymous** [comment]
How many episodes are listed in the progress tab?

**Comment by WooodDevil** [comment]
it says "no active tasks"

**Comment by auouymous** [comment]
Ya, see what the log shows in debug mode.

**Comment by WooodDevil** [comment]
Sorry but where do I find the log folder? The only mentions of "log" in the link you gave me are for "dialog".

**Comment by WooodDevil** [comment]
NVM I found it

2022-08-03 00:25:17,858 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.9\site-packages\gpodder\gtkui\main.py", line 1285, in on_treeview_query_tooltip
    if not getattr(treeview, TreeViewHelper.CAN_TOOLTIP) or x > 50 or (column is not None and column != treeview.get_columns()[0]):
AttributeError: 'TreeView' object has no attribute '_gpodder_can_tooltip'

2022-08-03 00:25:18,390 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.9\site-packages\gpodder\gtkui\main.py", line 2783, in on_gPodder_delete_event
    self.close_gpodder()
  File "C:\Program Files (x86)\gPodder\lib\python3.9\site-packages\gpodder\gtkui\main.py", line 2817, in close_gpodder
    self.episode_list_model.background_update = None
AttributeError: 'gPodder' object has no attribute 'episode_list_model'

2022-08-03 00:26:32,130 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\Winamp.File\shell\Play\command ([WinError 2] The system cannot find the file specified)

2022-08-03 00:26:32,130 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\Applications\foobar2000.exe\shell\open\command ([WinError 2] The system cannot find the file specified)

The first two are most of the log and the last 2 are repeated a few times at the bottom of the file

**Comment by auouymous** [comment]
The HKEY warnings are harmless, and the tooltip error spam happens when the UI is broken, so ignore those. The middle is a call to close_gpodder(), did you try closing gpodder before looking at the logs? Can you provide the full log or look above the tooltip errors for the cause?

**Comment by WooodDevil** [comment]
[2022-08-03 save.log](https://github.com/gpodder/gpodder/files/9248637/2022-08-03.save.log)

This is the full log. I haven't touched the program besides to start the update

**Comment by WooodDevil** [comment]
Im checking the log occasionally and all it's showing is new HKEY errors

**Comment by auouymous** [comment]
What version of gpodder are you running? Gpodder 3.11.0 on Windows should be using python 3.10, so this log is from an earlier version. The error below suggests you ran a newer version of gpodder and are now trying to run an older version.

Go look at https://gpodder.github.io/docs/user-manual.html#moving-to-an-older-gpodder-release if you want to rollback to an older version. Otherwise figure out how to remove the older version or launch the new version instead.

```
2022-08-03 00:24:43,787 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.9\site-packages\gpodder\gtkui\app.py", line 189, in do_activate
    self.window = gPodder(self, self.bus_name, core.Core(UIConfig, model_class=Model), self.options)
  File "C:\Program Files (x86)\gPodder\lib\python3.9\site-packages\gpodder\gtkui\main.py", line 91, in __init__
    BuilderWidget.__init__(self, None, _builder_expose={'app': app})
  File "C:\Program Files (x86)\gPodder\lib\python3.9\site-packages\gpodder\gtkui\interface\common.py", line 36, in __init__
    GtkBuilderWidget.__init__(self, gpodder.ui_folders, gpodder.textdomain, parent, **kwargs)
  File "C:\Program Files (x86)\gPodder\lib\python3.9\site-packages\gpodder\gtkui\base.py", line 71, in __init__
    self.new()
  File "C:\Program Files (x86)\gPodder\lib\python3.9\site-packages\gpodder\gtkui\main.py", line 185, in new
    self.channels = self.model.get_podcasts()
  File "C:\Program Files (x86)\gPodder\lib\python3.9\site-packages\gpodder\model.py", line 1380, in get_podcasts
    self.children = self.db.load_podcasts(podcast_factory)
  File "C:\Program Files (x86)\gPodder\lib\python3.9\site-packages\gpodder\dbsqlite.py", line 158, in load_podcasts
    cur = self.cursor()
  File "C:\Program Files (x86)\gPodder\lib\python3.9\site-packages\gpodder\dbsqlite.py", line 99, in cursor
    return self.db.cursor()
  File "C:\Program Files (x86)\gPodder\lib\python3.9\site-packages\gpodder\dbsqlite.py", line 90, in db
    schema.upgrade(self._db, self.database_file)
  File "C:\Program Files (x86)\gPodder\lib\python3.9\site-packages\gpodder\schema.py", line 225, in upgrade
    assert version == CURRENT_VERSION
AssertionError
```

**Comment by WooodDevil** [comment]
Earlier i tried to go back yo the last 3.10 version but i didn't have any of  my podcasts so i uninstalled it and reinstalled 3.11 with the installer, that part of the log might be from when I booted up the 3.10 version.

**Comment by WooodDevil** [comment]
Also I only have python 3.9 installed, will 3.11.0 only work with python 3.10?

**Comment by auouymous** [comment]
The Windows build of gpodder contains python 3.10, I don't know if it will use your python 3.9 but gpodder would work fine with it. Run gpodder and open the About dialog, does it show 3.11.0?

**Comment by WooodDevil** [comment]
I updated to the latest version of python and it still has the same problem

**Comment by WooodDevil** [comment]
Yeah, the about section says 3.11.0

**Comment by auouymous** [comment]
Do you know how to use command.exe or whatever it is called? If so, change to the gpodder folder and run `sqlite3.exe Database 'select * from version;'`. Does it display `8`?

**Comment by WooodDevil** [comment]
![version command](https://user-images.githubusercontent.com/110516578/182549780-a4bc5024-eeae-43bd-8d94-843424bd3842.PNG)

I only know a tiny bit about how to work with command prompt, what am I doing wrong here.

**Comment by WooodDevil** [comment]
tried it in powershell and it didn't recognize ith there either

**Comment by auouymous** [comment]
Oh right, gpodder bundles an sqlite DLL but wouldn't have an executable.

Kill all instances of gpodder, and delete all log files inside the Logs folder. Then try running gpodder and open its log file. Is it now using python 3.10 and does it still have that version error?

**Comment by WooodDevil** [comment]
The new log folder just has the same Hkey errors as the ones as the end of the log I gave you.

**Comment by WooodDevil** [comment]
I really think that part of the log was when I booted up the gpodder 3.10 version because the time stamp matches up from when I did that

**Comment by auouymous** [comment]
Okay, try the debug URL in my first post here, you will then see a lot of new messages in the log file.

**Comment by WooodDevil** [comment]
I though I was using the debug version but I wasn't putting the -v at the end. 
This is the log from the debug version

[2022-08-03 debug.log](https://github.com/gpodder/gpodder/files/9249177/2022-08-03.debug.log)
.

**Comment by auouymous** [comment]
Nothing out of the normal in the log file. Do you use gpodder.net or any extensions that have credentials? If **not**, could you post your Settings.json file?

**Comment by WooodDevil** [comment]
I don't use gpodder.net as far as I know so here is my setting fil
[Settingsjson.txt](https://github.com/gpodder/gpodder/files/9249481/Settingsjson.txt)
e

**Comment by auouymous** [comment]
Okay, I found your problem. The new episode dialog has a negative Y value which places the window off screen. Find this chunk in Settings.json, change that `-5364` to `0` and save it. Kill gpodder before doing this.

```json
        "episode_selector": {
          "height": 401,
          "maximized": false,
          "width": 601,
          "x": 733,
          "y": -5364
        },
```

We should probably detect window placements that cause the entire window to be off the screen.

**Comment by WooodDevil** [comment]
Ok that fixed it, thank you.
