### ISSUE TITLE
Progress tab shows downloads remain in "Queued" state

### ISSUE THREAD

**Issue by jtmoon79** [gpodder/gpodder#1362]
I recently upgraded to 3.11.0.  The new version does not automatically download podcasts.  Viewing the _Progress_ tab, I see a few hundred podcasts _Queued_, yet they will not download.

### Review

I don't have a reliable bug reproduction sequence. Here's a review of events, as best as I can recall, that lead to this Issue.

1. I was previously running gPodder version 3.10.21 with 19 podcast subscriptions.
2. Upgraded to 3.11.0.
3. Restarted gPodder
_Limit Rate_ is `200 KiB/s`, _Limit Downloads to_ is `1`
4. Added a new podcast
_Subscriptions_ -> _Add new podcast via URL_ -> entered `https://feeds.simplecast.com/wgl4xEgL` (Econtalk) -> clicked _Add_
5. At some point, the _Progress_ tab filled with the several hundred econtalk podcast episodes.  However, none were downloading.  I was able to force several to download by highlighting them, right-click, clicking _Start Download Now_.
6. In _Podcasts_ tab, I clicked _Check for new episodes_.  A message read _Updating 20 feeds_.  After a few minutes, the progress bar completed.  The _Progress_ tab reads "_Progress (875 Queued)_".
7. restart gPodder 
    on startup, a pop reads "_there are unfinished downloads_"
8. on the _Progress_ tab, click _Resume All_
   (nothing happens)

#### other observations

The _Progress_ tab remains with many Queued podcasts ("_Progress (875 Queued)_"), yet they do not download.  I can manually force them to download via _Start Download Now_.  However, I don't want to force several hundred podcasts to download simultaneously as that would likely crash.
I have restarted gPodder a few times, and clicked other buttons in the application including unchecking _Limit Rate_ and _Limit Downloads to_, clicking _Resume All_. The podcasts remain _Queued_, and do not download.

I noticed that when I Quit gPodder, the main window closes, then some seconds later a popup window reads _Download Error: Download error while downloading ..._ (podcast title).  Sometimes it tens of these popups.

**Comment by jtmoon79** [comment]
I should have added, thanks for creating this very useful program! ☻

**Comment by auouymous** [comment]
Does your computer have a slow processor? We shipped 3.11.0 with a bug (https://github.com/gpodder/gpodder/issues/1311#issuecomment-1186788711) that was triggering around 2000 episodes (on a 14 year old machine), which was above the UI enforced limit of 1000. A slower computer would trigger with fewer episodes.

#1353 mostly fixes the issue, and a new release will be available when I finish it. It is a simple fix if you know how to apply patches or edit a system file, and Windows users can simply upgrade to the #1353 artifact.

**Comment by jtmoon79** [comment]
> Does your computer have a slow processor?

It's a relatively small embedded PC running Windows 10 Pro.  However, I have Sysinternals Process Explorer running. Process Explorer shows between 95% to 80% CPU availability. CPU and RAM are available.

> #1353 mostly fixes the issue

I'll wait for the fix in the next release.

Thanks!

**Comment by auouymous** [comment]
This has been fixed by #1452 and is available at https://ci.appveyor.com/project/elelay/gpodder/builds/46055110/artifacts.
