### ISSUE TITLE
Does not honor 'youtube-dl.manage-downloads' setting with youtube channels

### ISSUE THREAD

**Issue by tpikonen** [gpodder/gpodder#1364]
I have `extensions.youtube-dl.manage-downloads` config var set to True, but downloads from youtube still use the (throttled) code from `youtube.py`. Downloads fail completely with `gpodder.youtube.YouTubeError: No preferred formats found` if custom formats are enabled. This is with current master.

**Comment by auouymous** [comment]
Are you running #1347? New episodes are application/octet-stream but previously downloaded episodes have an audio/* or video/* mime type. With that patch, I can download never before downloaded episodes at full speed, but downloading them again is slow.

**Comment by tpikonen** [comment]
Yes, I'm on current master. I also have `extensions.youtube-dl.manage-channel` on, which sets the mime type of episodes to `video/mp4'. This breaks downloads with #1347.
