### ISSUE TITLE
is the copyright symbol read by setup.py really an issue?

### ISSUE THREAD

**Issue by elelay** [gpodder/gpodder#1370]
The debian package and ubuntu ppa include [a patch](https://sources.debian.org/src/gpodder/3.11.0-2/debian/patches/remove_copyright_character.patch/) to replace the :copyright: character with a `(c)`.
This is a pain to maintain because it's located around version strings so the patch has to be regenerated at each release.
@tmancill I don't think this still needed in python 3 because [we open](https://github.com/gpodder/gpodder/blob/master/setup.py#L36) `__init__.py` with the `utf-8` encoding? What 
If yes I'm willing to merge it in gpodder.
If no let's remove this little hurdle!

**Comment by tmancill** [comment]
Hi @elelay.  You are correct that [remove_copyright_character.patch](https://sources.debian.org/src/gpodder/3.11.0-2/debian/patches/remove_copyright_character.patch/) is no longer needed.  Thank you for bringing this up.

I also believe that the [utf-8_coding_for_setup.patch (https://sources.debian.org/src/gpodder/3.11.0-2/debian/patches/utf-8_coding_for_setup.patch/) is no longer needed.

I will drop these in the next upload.

**Comment by elelay** [comment]
OK, thanks Tony I'll remove the patch from the ubuntu ppa as well.
