### ISSUE TITLE
gpodder: New Episodes window disappears, locks app

### ISSUE THREAD

**Issue by tyggii** [gpodder/gpodder#1375]
Hi

I've been using gPodder for at least a decade but I can't make 3.11.0 work. Installation runs smooth. When I open the application it's fine. When I then run "check for new episodes" the new window with new episodes is visible for a split second and then disappears. The main gPooder window is then locked, nothing works and have to close down using Task Manager. It's almost like the new episodes window is open but hidden/ minimized, but I can't actually see it beyond the fist half second. I've tried re-installing several times, restarting PC again and again but always the same error. Tried older version gPodder as well but not working properly either any more, even though it did a couple fo weeks ago. 

I am running Windows 11, upadated this month KB5016629. 

As you an tell I am not an IT person, hope someone can offer some help or I'll have to try and find another podcast app.

**Comment by auouymous** [comment]
Are you able to access the new episodes dialog from taskbar? The dialog is some how being placed off-screen which will be fixed when #1356 is merged. My window manager on linux has a menu that shows all windows and clicking one of them either takes me to its area or brings the window to me if it is not in an area (off-screen). If Windows' taskbar doesn't have that ability, you will need to close gpodder and edit Settings.json (see https://github.com/gpodder/gpodder/issues/1352#issuecomment-1203694157, but change the `x` and `y` values to be zero).

Duplicate of #1352.

**Comment by tyggii** [comment]
Cheers, that seems to have fixed it. Happy. Only minor issue is that the Episode window appears to be locked, I can't drag it around the screens... BUT it's visible and I can keep using gPodder, Thanks!

**Comment by auouymous** [comment]
Can you paste that chunk from your Settings.json?

**Comment by tyggii** [comment]
Here you go, after the change obviouslY:

    "episode_selector": {
          "height": 816,
          "maximized": false,
          "width": 691,
          "x": 0,
          "y": 0
        },
        "episode_window": {
          "height": 400,
          "maximized": false,
          "width": 500,
          "x": -1,
          "y": -1
        },
        "export_to_local_folder": {
          "height": 400,
          "maximized": false,
          "width": 500,
          "x": -1,
          "y": -1
        },
        "main_window": {
          "episode_column_order": [],
          "episode_column_sort_id": 12,
          "episode_column_sort_order": false,
          "episode_list_size": 200,
          "height": 773,
          "maximized": false,
          "paned_position": 492,
          "width": 1038,
          "x": 2708,
          "y": 395
        },
        "preferences": {
          "height": -1,
          "maximized": false,
          "width": -1,
          "x": -1,
          "y": -1
