### ISSUE TITLE
Option to *not* mark episode as old when straming starts

### ISSUE THREAD

**Issue by umbellipher** [gpodder/gpodder#1376]
gPodder 3.11 on Windows 10.

I stream, rather than download, with VLC.

I have the episode list set to 'unplayed episodes'.

When I start streaming an episode, it gets marked as old and disappears from the list. I might listen to only part of the episode, and want to come back to it later (VLC retains play position). I would prefer not to have to 'view all episodes' every time and set the part-streamed episode as 'new', so that I don't forget to go back to it. I could leave VLC open, but would prefer not to.

Am I missing something, or can this be enabled?

**Comment by auouymous** [comment]
The MPRIS extension might not mark it played until you finish watching the episode (I don't know), but the Windows build won't support MPRIS until dbus is fixed in #1253.

Why not use `Hide deleted episodes` and delete each episode after watching it?

**Comment by umbellipher** [comment]
@auouymous, thanks. Hide deleted episodes does the trick.
