### ISSUE TITLE
Unable to use version 3.11.0 on Slackware (current) platform

### ISSUE THREAD

**Issue by oldpink** [gpodder/gpodder#1377]
I tried to use version 3.11.0 of gpodder on my Slackware (current) system, using the SlackBuild scripts from slackbuilds.www.slackbuilds.org for the purpose, but each time I try downloading podcasts with it, I get the following error that pops up in a window:

Unhandled exception

Please report this problem and restart gPodder:

&#x27;cairo.ImageSurface&#x27; object has no attribute &#x27;set_device_scale&#x27

I found that I was unable to revert to version 3.10.17 at first because the new gpodder had reformatted my data folder, so I had to restore the old folder and everything worked fine after that.
I love this program and stay current as much as possible, but I'm unsure about what the source of my problem is with this.

**Comment by auouymous** [comment]
Do you have pycairo 1.14 or newer?

**Comment by oldpink** [comment]
I have pycairo 1.20.1 installed.

**Comment by auouymous** [comment]
What version of cairo?

**Comment by oldpink** [comment]
Sorry if you already received my reply, but I have version 1.20.1 (directly from the Slackware-current site) installed.

**Comment by auouymous** [comment]
There are two packages: cairo and pycairo. Your pycairo is 1.20.1, which requires cairo 1.15.10+, but gpodder needs both cairo and pycairo to be at least 1.14.

If your cairo is higher than 1.14 you will need to check for an old version of /usr/lib/libcairo* that is less than 11400 and remove it.

**Comment by oldpink** [comment]
Oops!
Sorry about that...I had mistakenly believed your question was about the version of **pycairo** instead of cairo.
My installed Slackware package of cairo is version 1.16.0.
Here is the content of my /usr/lib64 directory:

/usr/lib64/libcairo-gobject.so@
/usr/lib64/libcairo-gobject.so.2@
/usr/lib64/libcairo-gobject.so.2.11600.0
/usr/lib64/libcairo-script-interpreter.so@
/usr/lib64/libcairo-script-interpreter.so.2@
/usr/lib64/libcairo-script-interpreter.so.2.11600.0
/usr/lib64/libcairo.so@
/usr/lib64/libcairo.so.2@
/usr/lib64/libcairo.so.2.11600.0

I also had the 32-bit compatibility libraries for cairo in /usr/lib, so I deleted those and tried recompiling gpodder that way, with the outside chance that it was seeing those instead of the 64-bit ones in /usr/lib64, but it still fails with the same error.

**Comment by auouymous** [comment]
1.16 has the function, and running `strings /usr/lib64/libcairo.so |grep set_device_scale` should show it is there. Do you have `LD_LIBRARY_PATH` set to something that contains an older version of cairo?

**Comment by oldpink** [comment]
The output of strings /usr/lib64/libcairo.so | grep set_device_scale:

cairo_surface_set_device_scale
cairo_surface_set_device_scale

I don't believe there is an older version of cairo, and here's what "locate libcairo" shows:

/usr/lib/libcairo-gobject.so.2
/usr/lib/libcairo-gobject.so.2.11400.6
/usr/lib/libcairo-script-interpreter.so.2
/usr/lib/libcairo-script-interpreter.so.2.11400.6
/usr/lib/libcairo.so.2
/usr/lib/libcairo.so.2.11400.6
/usr/lib64/libcairo-gobject.so
/usr/lib64/libcairo-gobject.so.2
/usr/lib64/libcairo-gobject.so.2.11600.0
/usr/lib64/libcairo-script-interpreter.so
/usr/lib64/libcairo-script-interpreter.so.2
/usr/lib64/libcairo-script-interpreter.so.2.11600.0
/usr/lib64/libcairo.so
/usr/lib64/libcairo.so.2
/usr/lib64/libcairo.so.2.11600.0
/usr/lib64/libcairomm-1.0.so
/usr/lib64/libcairomm-1.0.so.1
/usr/lib64/libcairomm-1.0.so.1.4.0
/usr/lib64/dia/libcairo_filter.la
/usr/lib64/dia/libcairo_filter.so

Deleting the 32-bit libcairo in /usr/lib for compatibility with any 32-bit programs doesn't help at all with my problem.

**Comment by oldpink** [comment]
I hate to reply to my own issue post, but is anyone out there able to help figure out my issue going by the post above this one from me?

**Comment by auouymous** [comment]
Do you know how cairo was configured? Are you able to upgrade pycairo to 1.21?

**Comment by oldpink** [comment]
Slackware hadn't upgraded their precompiled package of pycairo since 04NOV21, so I pulled down the source for 1.21 and used Slackware's own build script with "VERSION=1.21.0 ./pycairo.SlackBuild" to build, then install the version you suggested upgrading to.
Well, I'm happy to say that was the secret sauce that I needed, as I rebuilt gPodder after that and it works exactly as it should, so that might need to go into the notes of the current version.
Thank you so much, and please keep development active on your excellent program, still the best podcast downloader out there.

**Comment by auouymous** [comment]
Any chance you could re-install 1.20.1 and see if rebuilding it works? I'm wondering if pycairo found an older cairo and built its API against it, and then you upgraded cairo but pycairo didn't have the symbols.

**Comment by oldpink** [comment]
Okay, I compiled 1.20.1 of pycairo and installed it instead of using the pre-built Slackware package of it, and your guess that it might work proved correct.
You're right that gPodder doesn't require version 1.21.0 to run, only version 1.20.1 compiled against the installed cairo instead of pre-built.
Thanks yet again.

**Comment by oldpink** [comment]
Oh, one tiny thing here (it's not really a problem to me, but I'm unsure about whether you intended it to go this way), but the file save dialog is slightly different, which will be easier for me to show in screenshots below than explaining in words:

Old file save window:
![Old](https://user-images.githubusercontent.com/24418507/190505639-12bb6611-5411-4969-a2ba-593c6de766db.png)

New file save window:
![New](https://user-images.githubusercontent.com/24418507/190505727-51a8d703-01e3-48fb-ba7d-87961732acab.png)

This difference isn't really causing me problems, but it changed with the current version of gPodder, even as it left the filename without extension the same with all versions leading up to it.

**Comment by auouymous** [comment]
Thank you for testing pycairo.

Are you trying to say the old version selected part of the filename for easy renaming and the new version needs triple clicking which requires the user to retype the extension?

**Comment by oldpink** [comment]
Yep, that's it.
It's not a big deal at all to me, but I mentioned it because the previous versions auto-selected the filename minus the "dot extension" part.
