### ISSUE TITLE
Installed gPodder 3.9.0 and it won't launch.

### ISSUE THREAD

**Issue by lviolette** [gpodder/gpodder#138]
I downloaded gpodder 3.9.0, pygtk 2.24.2 and python 2.7.10.

When I double-click on gpodder, it doesn't do anything. (Starts and stops without UI).

In looking at Process Monitor, gpodder is attempting to access a series of sub-folders under the gpodder install folder just before it exits. Things like "site", "lib", etc.  I'm wondering if maybe there's supposed to be an environment variable or something that points gpodder to the python stuff?  Or was it supposed to be installed under gpodder?

Here's the contents of my gpodder install folder, including folders.
"C:\Program Files (x86)\gPodder\gpodder.exe"
"C:\Program Files (x86)\gPodder\README"
"C:\Program Files (x86)\gPodder\unins000.dat"
"C:\Program Files (x86)\gPodder\unins000.exe"
"C:\Program Files (x86)\gPodder\bin"
"C:\Program Files (x86)\gPodder\share"
"C:\Program Files (x86)\gPodder\src"
"C:\Program Files (x86)\gPodder\COPYING"
"C:\Program Files (x86)\gPodder\gpo.exe"

[gPodderProblem.zip](https://github.com/gpodder/gpodder/files/355690/gPodderProblem.zip)
leo.violette70@gmail.com
Leo V.

**Comment by thp** [comment]
Does gpo.exe work? Does running it from cmd.exe give any hints what's wrong?

The "bin", "share" and "src" folders should contain additional files, but I guess that's the case?

**Comment by lviolette** [comment]
Thank you very much for getting back to me.
When running gpo.exe from the command-line, it shows the following:
ImportError: No module named site.

Maybe I'm supposed to supply some parameters?  Sorry I'm kind of a noob here.

I ran it with ProcessMonitor and saw the same thing. Fails to find gpodder\site.py and fails out.

I'm attaching a zip of my program files (x86)\gpodder folder if it helps any.

I'd be curious to know if it looks like a typical installation under other peoples installation folder.

[gPodder.zip](https://github.com/gpodder/gpodder/files/360740/gPodder.zip)

**Comment by thp** [comment]
"No module named site" looks like your Python installation is incomplete. Please try the following:

* Uninstall Python 2.7 and PyGTK
* Install Python 2.7.10 (32-bit) "for all users" (system-wide) to C:\Python27
* Install PyGTK again

Try again to see if that helps. If that doesn't help, check your PYTHONPATH variables and see if you can run C:\Python27\python.exe normally or if it gives the same error about "site".

**Comment by lviolette** [comment]
Hmmm.  Thank you for helping me.  I followed your instructions.  It just won't run.
I do not have a PYTHONPATH environment variable.
I created one and set it to c:\python27.  Then I executed gpodder.exe again. Same result.  gpo.exe still says "ImportError: No module named site"
I went to the python27 folder and ran python.exe and it took me into the python environment.
I'm losing hope. :(
One thing I noticed is I also have Python 2.7.11 installed along with Python Tools 2.2.4 for Visual Studio 2015.  Maybe they're interfering with each other?
Maybe I'll try it again tomorrow.  The only thing I didn't do is manually select every installation option in the PyGTK installation.

**Comment by thp** [comment]
Oh yeah, Python 2.7.11 is actually problematic. Here's the fix (not yet released): https://github.com/gpodder/gpodder/commit/2a27cddf8c95da89791105da35e8fb48c1263b91

So if you have installed Python 2.7.10 to C:\Python27, then if you set the environment variable PYTHONHOME to C:\Python27, then it should start working. Otherwise, uninstall all versions of Python 2.7.11 and install only Python 2.7.10.

**Comment by lviolette** [comment]
Thank you for the feedback.  I was able to get gPodder running again by setting the Environment variable PYTHONHOME as you described.
Thank you for your support.
