### ISSUE TITLE
bug! when unsubscribeing from a podcast using gpo, the epesodes and folder are not deleted

### ISSUE THREAD

**Issue by mhussaincov93** [gpodder/gpodder#1388]
hi,
stepps to reproduce
1.
launch gpo
2.
unsubscribe from a podcast where you've downloaded epesodes from it.
3.
go to the location of where files for the podcast that you've unsubscribed from are downloaded.
what should happen
when the unsubscribe command is issued, the folder containing epesodes should be removed.
what happens currently?
the podcast folder and files are left on the filesystem.
Majid

**Comment by auouymous** [comment]
Fixed in eb2ceba7a9c8842ec9f37b0c7fe4911240eb1cff. Thanks for reporting.
