### ISSUE TITLE
tiny text in larger window in 3.11 on macos

### ISSUE THREAD

**Issue by JimH44** [gpodder/gpodder#1389]
Hi,
I love gPodder and have been using it for years.
It just prompted me to install a new version, and I downloaded 3.11 to my Macbook Pro running Big Sur (11.6.8).
I opened the zip file and copied gpodder.app to /Applications, and now the text is tiny in a corner of a normal-sized window.
<img width="869" alt="gPodder-tiny-text-in-corner" src="https://user-images.githubusercontent.com/8330030/188673907-b6103d7e-ece0-4f5a-babd-8b815ed52158.png">
Can you please help.

**Comment by elelay** [comment]
Yes, sorry about that: high-dpi screens (retina) don't work well in this release.
See https://github.com/gpodder/gpodder/issues/1348#issuecomment-1213315301 for a workaround.
