### ISSUE TITLE
Group subscriptions in exported OPML files

### ISSUE THREAD

**Issue by anewuser** [gpodder/gpodder#1405]
Exported subscriptions should be grouped according to the user's sections/categories. Example syntax from [Inoreader](https://www.inoreader.com/):

```
    <outline text="Music" title="Music">
      <outline text="Example 1" title="Example 1" type="rss" xmlUrl="https://example.com/feed" htmlUrl="https://example.com/"/>
      <outline text="Example 2" title="Example 2" type="rss" xmlUrl="https://example.net/feed" htmlUrl="https://example.net/"/>
    </outline>
    <outline text="Interviews" title="Interviews">
      <outline text="Example 3" title="Example 3" type="rss" xmlUrl="https://example.org/feed" htmlUrl="https://example.org/"/>
    </outline>
```

**Comment by auouymous** [comment]
This would be a nice improvement, assuming it can be imported by other clients.

**Comment by anewuser** [comment]
>assuming it can be imported by other clients.

Feedly, Feedbro, and other feed readers use the same markup structure. I just mentioned Inoreader as an example.

I personally just wanted to import a specific section of my subscriptions to a website today. If they were grouped, I'd just have to delete the other sections and then upload the file in a few seconds.

**Comment by auouymous** [comment]
To be safe, we could have two options to export with sections or without. And gpodder should also offer the ability to only import specific sections.

**Comment by anewuser** [comment]
In my opinion, offering two export options would make this function unnecessarily complex. OPML files have looked like in my suggestion [for at least 17 years](https://bugzilla.mozilla.org/show_bug.cgi?id=307724). When an application doesn't support nested tags in OPML files, it is expected to simply ignore the tree structure while still successfully importing all the subscriptions to the root folder of the application.

If someone somehow stumbles upon an obscure client that fails to import an OPML file with nested tags, then this person can manually edit the OPML file to remove the parent `outline` tags or a submit a bug report to the developer of the broken application.

**Comment by auouymous** [comment]
Current gpodder does ignore the sections so we don't need a second menu item to export an opml file that would work with older versions.
