### ISSUE TITLE
Download Path Changed in 3.11.0 Release

### ISSUE THREAD

**Issue by JesterZero** [gpodder/gpodder#1406]
Very new to GitHub, so apologies if I'm unaware of the best way to report this. This bug report concerns the Portable Apps version of gPodder.

After I upgraded gPodder 3.11.0, it no longer had any awareness of files previously downloaded onto the local machine. When I investigated, it seems like the default download / storage for podcasts has changed from 

**gPodderPortable\Data\config\Downloads\**

to

**gPodderPortable\Data\config\Test\**

The folder structures, .mp3 files, and folder.jpg files are still there (they were not deleted), but it looks like gPodder has been split in half: everything from 3.10 and before in \Downloads, and everything from 3.11 and after in \Test. I experimented with downloading a new episode, and it definitely stored it in \Test. \Test also has the same folders and album images that \Downloads has, just without the previously downloaded files.

Should I just copy over the contents of \Downloads to \Test?

(I tried to just reinstall 3.10 and that was a trainwreck; re-re-installing 3.11 seemed to go just fine, although once again I've got the issue described above. Honestly, I'm not in love with the idea of rolling back if there's a fix to just get this sorted out going forward).

Any guidance is appreciated; thank you very much!

**Comment by auouymous** [comment]
Weird, there is no "Test" string in the gpodder source. Is this the portable exe for Windows or a binary from a third-party site?

**Comment by JesterZero** [comment]
I'm guessing third-party since it's from here:

https://portableapps.com/apps/internet/gpodder_portable

I've used them for years without issue, but you've got no insight into what they might have done, I'd be happy to convert to the official portable app if you've got any guidance on how to do that.

**Comment by JesterZero** [comment]
If it helps, there seems to be some discussion here? (I know the original post is from 2012, but it catches up to present day at the end):

https://portableapps.com/node/32057

**Comment by auouymous** [comment]
We have no control over third-party builds or how they have been modified. You would need to open an issue on their site to get it fixed. The last comment there suggests it uses an ini file to alter `GPODDER_DOWNLOAD_DIR`. That file might set it to "Test" or you have overriden that variable in your environment.

Our portable exe is at https://github.com/gpodder/gpodder/releases/download/3.11.0/windows-gpodder-3.11.0-portable.exe. I don't know how to use it but https://github.com/portapps/portapps/issues/269 (yet another third-party) points to two of our issues that might help, or convince you to stay with the one you are using.

**Comment by elelay** [comment]
Indeed the exe they provide is not the same one.
- Our sha256 (as advertised on the [release page](https://github.com/gpodder/gpodder/releases/tag/3.11.0) and verified locally): 89a85604b5c664f53e1bd0eb8a0a1ed185b7f7de6482e040657dd516e23c6fa4
- Their sha256: 2b83e31f74c13d8b32831fe82f799cf72dd36402adac46b09dc3020157dde010

**Comment by elelay** [comment]
Please try our version. It doesn't have this bug!

**Comment by JesterZero** [comment]
Just wanted to say thank you to everyone here for the insight and pointing me in the right direction. I'll let the folks at portableapps.com know about the issue, and I'm 99% sure that I can straighten this out while I make sure that I don't accidentally lose any podcasts.

I'd absolutely be open to trying out your version once that's all taken care of.

Thank you very much again!
