### ISSUE TITLE
gPodder unable to find Mutagen on Windows 7

### ISSUE THREAD

**Issue by dear-reader** [gpodder/gpodder#141]
Windows 7
gPodder 3.9.0
Pip 8.1.2
Mutagen 1.34.1
Python 3.5.2

> C:\Users\aidan>pip install mutagen
Requirement already satisfied (use --upgrade to upgrade): mutagen in c:\program files (x86)\python35-32\lib\site-packages

Despite having installed mutagen, gPodder won't let me enable the tagging extension:

>Extension cannot be activated
Python module not found: mutagen

Mutagen works from the command line:

>Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)] on win32
\>\>\> from mutagen.mp3 import MP3
\>\>\> print(MP3("The Cardigans - 01 - Paralyzed.mp3").info.length)
296.8

**Comment by thp** [comment]
gPodder uses Python 2.x still, so you need to install Mutagen for Python 2.

**Comment by dear-reader** [comment]
Thank you! Installing with pip2 resolved the problem.
