### ISSUE TITLE
Download limit defaults to 16

### ISSUE THREAD

**Issue by Axpelle** [gpodder/gpodder#1413]
The following applies to gopodder 3.11.0 on OSX Mojave 10.14.6:

gpodder defaults to a concurrent download limit of 16 even when that value is changed manually in Edit Config. In other words, the entered value is not registered in Preferences when one closes the Preference dialog box.

Also, even when the "limit download" tick box is unchecked the application still limits the download to the default value of 16.

**Comment by auouymous** [comment]
Thanks for reporting, fixed by 557229c08c92153486981a56f506bcc6280da066.
