### ISSUE TITLE
question when syncing to a device and the opperation is interupted via the user, when rezumeing sed opperation will gpodder /gpo rezume from the epesode that was interupted?

### ISSUE THREAD

**Issue by mhussaincov93** [gpodder/gpodder#1416]
sorry for the long title
but when gpodder /gpo rezumes sync opperations will it continue from the last epesode that it was syncing before the interuption?
or will it resync the set epesode that was interupted?
thanks,
Majid

**Comment by auouymous** [comment]
It starts over and syncs every downloaded episode again. But when syncing to a local directory, it sees an existing file and does not write to the file again, even if the file is incomplete or different.

@elelay I don't know what capabilities devices have, should/can this compare file size and a checksum, and sync it again if different?

**Comment by mhussaincov93** [comment]
hey,

I like that plan.

verefication of files transfered and files yet to be transfered via a 
checksum of the source and file both before delivery and after.

also a check of files if they are present at the destination being checked.

via checksum.

**Comment by elelay** [comment]
Computing a checksum will always be supported but requires fully reading the file so may take a long time on slow storage. 

I'm not sure about MTP device capabilities. 

Filesystem based devices are often formatted as fat32, right? Per my testing on Linux on a fat32 (vfat) formatted loop device, file size is accessible, as well as creation/modification date:

Source file:
````
~> LANG=C stat  ~/gPodder/Downloads/99_\ Invisible/480-\ Broken\ Heart\ Park.mp3
  File: /home/elelay/gPodder/Downloads/99_ Invisible/480- Broken Heart Park.mp3
  Size: 35804087  	Blocks: 69936      IO Block: 4096   regular file
Device: 8,8	Inode: 264601      Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/  elelay)   Gid: ( 1000/  elelay)
Access: 2022-11-07 15:53:30.484284332 +0100
Modify: 2022-11-07 15:51:17.307085856 +0100
Change: 2022-11-07 15:51:17.307085856 +0100
 Birth: 2022-11-07 15:51:03.900700285 +0100
````
On device:
````
~> LANG=C stat /mnt/tmp/99%\ Invisible/480-\ Broken\ Heart\ Park.mp3
  File: /mnt/tmp/99% Invisible/480- Broken Heart Park.mp3
  Size: 35804087  	Blocks: 69930      IO Block: 512    regular file
Device: 259,0	Inode: 8           Links: 1
Access: (0755/-rwxr-xr-x)  Uid: ( 1000/  elelay)   Gid: ( 1000/  elelay)
Access: 2022-11-07 01:00:00.000000000 +0100
Modify: 2022-11-07 15:51:16.000000000 +0100
Change: 2022-11-07 15:51:16.000000000 +0100
 Birth: 2022-11-07 15:56:17.200000000 +0100
````

**Comment by auouymous** [comment]
I have reverted #1434 to fix #1496, and re-opened this issue. File size and checksum can not be used to detect partial uploads. The only partial solution for this I can think of is to check if the file on device is less than some fraction of the local file size, say 90%. This would catch most cases of partial uploads, but still allow some to remain undetected. However, if a device can add metadata, what prevents it from doing something else to the file, such as compression or re-encoding. So any significantly high percentage could trigger another #1496.

**Comment by elelay** [comment]
Would a checkbox "my device is evil and tampers with file size" be acceptable?
Additionally a popup when detecting that all files changed, controlling the same option?

**Comment by auouymous** [comment]
Good idea. So default to file size checking and notify those with mutating devices to toggle the checkbox, with a warning that partial uploads must be manually removed.
