### ISSUE TITLE
Can not subscribe to "Sicherheitshalber" podcast

### ISSUE THREAD

**Issue by Toniq8** [gpodder/gpodder#1418]
Podcast "Sicherheitshalber" cannot enter link to open a new subscription. The authors tell me, that gpodder should accept the RSS-link. It doesn't. Then they tell me to use the soundcloud search function in gpodder. However in my gpodder app I don't find such a function? Anybody has some tipps/clues? Thanks for

**Comment by auouymous** [comment]
Can you please provide a feed URL?

**Comment by Laborratte5** [comment]
I found this URL, I hope it is the correct one.
http://feeds.soundcloud.com/users/soundcloud:users:479331222/sounds.rss

However I can add this URL to gpodder (gPodder 3.11.0 (2022-07-30)) just fine

**Comment by Toniq8** [comment]
> 

It worked! GREAT! Thanks a lot. The feed the editors told me was truncated in the mail! thanks to anonymous too, I think s-he would have seen and solved the problem too.
