### ISSUE TITLE
Strange appearance on MacOS

### ISSUE THREAD

**Issue by birdjumper** [gpodder/gpodder#1419]
Hi 

I've tried installing version 3.11.0 via Homebrew and via the downloadable zip version but when I open either version the appearance is messed up. Please see screenshot.

![image](https://user-images.githubusercontent.com/17423648/194685805-b42a943e-a74d-43c9-a120-157704dd6e86.png)

Is there anything I can do to fix this?

Thanks

birdjumper
Mac M1 running MacOS v 12.6

**Comment by birdjumper** [comment]
<img width="1645" alt="Screen Shot 2022-10-08 at 12 23 59" src="https://user-images.githubusercontent.com/17423648/194685905-c2109c0f-df1a-4c0c-b40e-14cecf26c3b1.png">

**Comment by birdjumper** [comment]
My old version 3.10 no longer works either.

**Comment by auouymous** [comment]
See https://github.com/gpodder/gpodder/issues/1348#issuecomment-1213315301.

Did 3.10.21 work prior to upgrading to 3.11.0, or does it have the same display issue? You can use https://gpodder.github.io/docs/user-manual.html#moving-to-an-older-gpodder-release to downgrade back to 3.10.21 if it worked before upgrading.

**Comment by birdjumper** [comment]
It did work. I'll have to try and downgrade for the moment. But any idea why it's happening?

**Comment by auouymous** [comment]
We upgraded dependencies for the 3.11.0 build, and one of them is causing the issue. I need to downgrade some of them and see if if fixes the problem.

**Comment by birdjumper** [comment]
Thanks @auouymous. Following your advice I'm back on 3.10.21 for the moment. If you need anymore info from me, just holler!

**Comment by pinkneonsign** [comment]
+1 for this issue on 3.11.0 macOS app

**Comment by pinkneonsign** [comment]
#1348

**Comment by cenlios** [comment]
![上传image.png...]() m1 芯片，最新版本还是没有解决，请问怎么办？
