### ISSUE TITLE
How to don't delete older episodes of non media feeds on update?

### ISSUE THREAD

**Issue by Snippet24816** [gpodder/gpodder#1422]
I thought this setting does that but maybe it doesn't..

![image](https://user-images.githubusercontent.com/108145509/195157979-bea55576-ada5-455e-a06d-e10daafca3e9.png)

**Comment by Snippet24816** [comment]
Update: I can use "archiving"

**Comment by Snippet24816** [comment]
Okey I'm afraid since they are not downloaded older episodes are lost..

**Comment by auouymous** [comment]
Locking any undownloaded episode should probably prevent its removal if the feed drops it.

**Comment by Snippet24816** [comment]
> Locking any undownloaded episode should probably prevent its removal if the feed drops it.

I concur that is more expected behavior.

**Comment by Snippet24816** [comment]
Let me know if you want me to test it..
