### ISSUE TITLE
After downgrading to 3.10 I no longer have access to Preferences

### ISSUE THREAD

**Issue by birdjumper** [gpodder/gpodder#1424]
Hi 

After downgrading from 3.11 to 3.10 I no longer have access to Preferences.

When I delete a podcast entirely, the podcast is deleted but the Delete Dialog doesn't disappear.

"Quit" from the menu also doesn't work.

Are these odd things caused by my failed update to 3.11?

Thanks

birdjumper
Mac M1 running MacOS v 12.6
gPodder 3.10

**Comment by auouymous** [comment]
Did you follow the steps at https://gpodder.github.io/docs/user-manual.html#moving-to-an-older-gpodder-release?
