### ISSUE TITLE
gpodder/gpo when checking for updates new updates are not added to download cue

### ISSUE THREAD

**Issue by mhussaincov93** [gpodder/gpodder#1425]
hi,
when checking for updates for podcasts in gpo any new epesodes are not added to the download cue.
in gpodder-gtk i've set it so that when new epesodes are found, gpodder will auto add to download cue ready to be downloaded.
this does not happen for the gpo interface.
could this be looked at?
Majid

**Comment by auouymous** [comment]
Does `gpo update` followed by `gpo download` not work?

**Comment by auouymous** [comment]
Ah, so `gpo download` simply needs to create partial files for every episode before it begins downloading any of them. That way `gpo resume` will continue downloading anything listed in `gpo partial`. #1429 should implement this and if you use windows you can install https://ci.appveyor.com/project/elelay/gpodder/builds/45206196/artifacts when it is ready in an hour from now.

**Comment by mhussaincov93** [comment]
@auouymous
thank you so much sir!
i'm running gpodder via git so will wate till this trickles down to us :)
I will also cloze this issue after or you could doo this?
am i write in thinking that a new gpodder release may be on it's way soon?
cheers again for gpodder!
Majid

**Comment by auouymous** [comment]
The PR will automatically close this issue when it gets merged. There are a couple critical issues that need to be fixed before a release, but I won't have time until at least next week.

**Comment by mhussaincov93** [comment]
no worries sir,
I am greatful that you looked in to this for me.
