### ISSUE TITLE
Lost subscriptions and configuration

### ISSUE THREAD

**Issue by StephanieLabaule** [gpodder/gpodder#1426]
At startup (Windows version 3.11.0 portable), all subscriptions have disappeared, the configuration too.
Is there a way to fix it?

Thanks a lot.

**Comment by StephanieLabaule** [comment]
I found my subscriptions in the file named "Database".
But the configuration seems to have been overwritten.
Is there a way to save it for next time?
Thanks.

**Comment by mhussaincov93** [comment]
hi Stephanie,
your settings are all stored in the file named
settings.json.
copy that file after makeing all relevant changes via the gui interface.
your subscriptions are indeed stored in the file named database.
you should make a backup of the database file also incase of errors.
I doo it now and then as a failsafe.
to export your subscriptions in the gpodder interface there is a menu item called export subscriptions.
can come in handy.
Majid

**Comment by StephanieLabaule** [comment]
Thanks, Majid. 

That's what I did, in fact. 
After several years without problems, and without computer knowledge, I lost a day to understand how it worked (the documentation, in particular that of the extensions, is definitely not written for miss everyone). 
I think I put everything back in order. 
I actually put a copy of these two files aside. (I had an Oplm, but not up to date)
And also screenshots of the preferences. 

I won't be caught again! ;-)

**Comment by mhussaincov93** [comment]
greate news!
having a screen shot will help.
glad everything was sorted.
Majid
