### ISSUE TITLE
bugg gpodder_gtk when subscription is set to paused then manually updateing sed subscription, subscription updates

### ISSUE THREAD

**Issue by mhussaincov93** [gpodder/gpodder#1428]
I set a podcast to be paused.
I assumed that ment that when updateing manually or otherwize would mean that the podcast would not update.
what happens currently is I set the podcast to paused. press the okay button in the settings window for the subscription.
I then pressed update podcast on the feed that I had disabled.
the update process goes ahead.
and the episodes that were not downloaded yet were added to cue.
what I expect?
when checking for updates and the subscription is  paused it  would not update.
 this is for gpodder_gtk and other interfaces
Majid

**Comment by auouymous** [comment]
Pausing is only intended to prevent automatic updates. There are many useful reasons to manually update a paused feed.

**Comment by mhussaincov93** [comment]
hi,
does pausing get disregarded if the glowble check for updates button is pressed?
or only when check for updates for the disabled feed is ran?
Majid

**Comment by auouymous** [comment]
Automatic updates and manually updating all feeds will not check paused feeds. A paused feed is only checked when using `gpo update URL` or right clicking a channel in gtk and updating.

**Comment by auouymous** [comment]
>  if you don't wish me to submit issues anymore, I will cirtenly understand.

You can't learn without asking questions, bugs can't be fixed without users reporting them, and new features can't be implemented without someone to request them. Some bugs/features take a lot time to fix/implement and might never happen, but others are easy, interesting or extremely important and get done quick. Also, working on small issues can motivate developers to work on larger ones...

And thank you for answering questions of other users.
