### ISSUE TITLE
No Youtube downloads since Dec 24

### ISSUE THREAD

**Issue by computerfreak105** [gpodder/gpodder#1449]
[2022-12-25.log](https://github.com/gpodder/gpodder/files/10300492/2022-12-25.log)
Hi, just want to ask if youtube downloads are still working for you. I haven't got any videos since Dec 24 early Morning.
There are better christmas gifts than that for sure ...
Did YT change something?
Maybe have a look at the log, please. It talks about an uncaught exception quite often.

It happened with the portable build 932 on windows. After that I went back to 926 wich worked well before. But still no downloads from youtube. I don't use GPodder for anything else than Yt channels.

[2022-12-25.log](https://github.com/gpodder/gpodder/files/10300495/2022-12-25.log)
Thanks, your help is appreciated!

**Comment by tmancill** [comment]
I'm on a different platform (Debian Linux), and this is a sample size of 1, but YT video downloads are working or me running gPodder 3.11.0.

**Comment by auouymous** [comment]
You are using the unmerged PR #1432 which I haven't even reviewed or tested yet. It is apparently buggy and does not work. Unfortunately, it makes changes to the database which means you will need to go into your gPodder directory (https://gpodder.github.io/docs/user-manual.html#default-gpodder-home-folder) and replace `Database` with the older backup it made (https://gpodder.github.io/docs/user-manual.html#moving-to-an-older-gpodder-release).

**Be sure to install 929** (https://ci.appveyor.com/project/elelay/gpodder/builds/45712428) **before running gpodder** after you downgrade the database.

**Comment by computerfreak105** [comment]
Thanks for the instructions. I rolled back and it’s working again 😊

And @tmancill, thanks anyway for trying it on Linux.

 

 

 

Von: auouymous ***@***.***> 
Gesendet: Sonntag, 25. Dezember 2022 22:21
An: gpodder/gpodder ***@***.***>
Cc: computerfreak105 ***@***.***>; Author ***@***.***>
Betreff: Re: [gpodder/gpodder] No Youtube downloads since Dec 24 (Issue #1449)

 

You are using the unmerged PR #1432 <https://github.com/gpodder/gpodder/pull/1432>  which I haven't even reviewed or tested yet. It is apparently buggy and does not work. Unfortunately, it makes changes to the database which means you will need to go into your gPodder directory (https://gpodder.github.io/docs/user-manual.html#default-gpodder-home-folder) and replace Database with the older backup it made (https://gpodder.github.io/docs/user-manual.html#moving-to-an-older-gpodder-release).

Be sure to install 929 (https://ci.appveyor.com/project/elelay/gpodder/builds/45712428) before running gpodder after you downgrade the database.

**Comment by Happyrobot33** [comment]
> You are using the unmerged PR #1432 which I haven't even reviewed or tested yet. It is apparently buggy and does not work. Unfortunately, it makes changes to the database which means you will need to go into your gPodder directory (https://gpodder.github.io/docs/user-manual.html#default-gpodder-home-folder) and replace `Database` with the older backup it made (https://gpodder.github.io/docs/user-manual.html#moving-to-an-older-gpodder-release).
> 
> **Be sure to install 929** (https://ci.appveyor.com/project/elelay/gpodder/builds/45712428) **before running gpodder** after you downgrade the database.

my guess is they have the version before I merged in the latest changes, meaning if anything that fixed a youtube download issue occured between when I orignally forked and before I brought the version up to date, that would be why it was broke
