### ISSUE TITLE
gtk3 migration

### ISSUE THREAD

**Issue by elelay** [gpodder/gpodder#145]
The gtk3 branch launches gPodder but some things are broken.
Is it on the right track? What's left for gtk3 migration?
What are the tough points?

**Comment by elelay** [comment]
I'm trying to make progress in branch https://github.com/elelay/gpodder/tree/gtk3

**Comment by elelay** [comment]
see PR #150

**Comment by vossad01** [comment]
For what I know, I think anything labeled [[bug]](https://github.com/gpodder/gpodder/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A%22Python+3%22) in the [Python 3 milestone](https://github.com/gpodder/gpodder/milestone/1) would need to be addressed.

Additionally, #252 would be needed for sanity when supporting extensions and enough of the build kinks (#278) would need to be worked out to be able to cut a build and begin a beta period.

**Comment by vossad01** [comment]
I observed that the README indicates Python v3.5, but user dannn-o is running against v3.4.3.  Not sure if v3.5 was arbitrarily chosen because that is what was developed against, or if we have a known reason to need v3.5.

**Comment by elelay** [comment]
gPodder 3.10.0 is gtk3, Yay!
