### ISSUE TITLE
Gpodder window not opening after windows update

### ISSUE THREAD

**Issue by Grandozer** [gpodder/gpodder#1457]
Gpodder window not opening after windows update

Running on Windows 10.  Recent update 2023-01 Cumulative Update for Windows 10 Version 22H2 for x64-based systems KB5022282.

The gpodder window tries opening then retreats to the taskbar and can't be opened from there.  I still get notifications that downloads are happening.
Ran the command with debugger and results shown as attached.

![Untitled](https://user-images.githubusercontent.com/122526263/212040326-d919ef8f-b8a1-4ba2-a302-b993afa3ca56.png)

Thanks for any help

**Comment by auouymous** [comment]
The window is probably off-screen, see https://github.com/gpodder/gpodder/issues/1451#issuecomment-1369256000

**Comment by Grandozer** [comment]
I did reinstall yesterday after the update but that failed to help.  I used the link suggested in the comment above and re-installed the program again and it is now back up and running again.  Thanks.
