### ISSUE TITLE
Find new podcasts window Search field disabled when clicking quickly

### ISSUE THREAD

**Issue by elelay** [gpodder/gpodder#146]
When activating "gpodder.net search", Search is enabled.
When activating "gpodder.net top 50" and quickly back to "gpodder.net search", Search is disabled.
If I wait for "gpodder.net top 50" to load, I can go back to "gpodder.net search" and Search is enabled

**Comment by elelay** [comment]
fixed by 6937e34

**Comment by elelay** [comment]
needs a PR

**Comment by vossad01** [comment]
@elelay The referenced commit appears to have been integrated.  Can this be closed?

**Comment by elelay** [comment]
Yes.
