### ISSUE TITLE
gpodder ubuntu 22 hangs pauses and stops downloading

### ISSUE THREAD

**Issue by teddymills** [gpodder/gpodder#1462]
Before I start looking for a gpodder replacement I want to see if I can fix this gpodder issue.
I download hundreds of podcasts at a time. I have tried change the downloads and bandwidth. 
Internet connection is fine.  20MB/sec.  Maybe the DNS ?
gpodder queues up like 800+ or so podcasts and sometimes does nothing. Internet and dns works fine.
my primary drive is a small 256GB ssd so I moved all the gpodder tree+binarys AND podcasts to a 2TB drive on the Ubuntu linux box.

Most of the  time this works fine,
I have downloaded 5000+ podcasts episodes
This box is NOT the fastest..like AMD A6 with 2 cores.

I can restart gpodder like 25+times and over a period of days it usually will clear out the queue. 
But this seems odd to have to restart + resume gpodder so many times.

Is there a gpodder log I can check for errors.

**Comment by auouymous** [comment]
Are you using gpodder 3.11.0? If so, this issue has been fixed. You will however need to install the git version (https://gpodder.github.io/docs/run-from-git.html) or wait until the next release.

**Comment by teddymills** [comment]
Thank you. I will try the  git version.  I cannot recall how I installed gpodder. It is 3.11.0 
I may have installed it via snap or less likely apt-get..tia

**Comment by teddymills** [comment]
I had the gpodder binary tree as 775 teddy.teddy
Pretty sure I am in the sudoers list (did not check)
that that was good enough. anyways I changed it to

chown -R root.teddy 2023-Podcast/
chmod -R 775 2023-Podcast

check also gPodder error logs...all ok there
and it is working MUCH better now..working like a Champ!

Thanks for your quick support reply

Teddy

```
root@coolmaster:/home/teddy/2TB/2023-Podcast/gPodder# ll
total 33652
drwxrwxr-x  4 root teddy     4096 Jan 26 23:59 ./
drwxrwxr-x  3 root teddy     4096 Jan  8 18:18 ../
-rwxrwxr-x  1 root teddy 32276480 Jan 26 23:58 Database*
-rwxrwxr-x  1 root teddy   197504 Jan 27 00:04 Database-journal*
drwxrwxr-x 19 root teddy     4096 Jan 26 12:31 Downloads/
-rwxrwxr-x  1 root teddy  1953792 Jan 26 23:58 gpodder.net*
drwxrwxr-x  2 root teddy     4096 Jan 26 12:17 Logs/
-rwxrwxr-x  1 root teddy     3651 Jan 26 12:32 Settings.json*
```
