### ISSUE TITLE
Frequent 403 errors on youtube videos

### ISSUE THREAD

**Issue by matoro** [gpodder/gpodder#147]
gpodder fails to download a significant portion of youtube videos, reporting an http 403 error.  I suspect this has something to do with uploader settings, because it only happens on certain channels, usually larger ones and they are usually music-related, whereas I never have problems with smaller channels.  The videos download perfectly fine using youtube-dl.  How difficult would it be to add an option to hook into the installed version of youtube-dl, similar to what mpv does?

Example video: https://www.youtube.com/watch?v=Z0RO1SCcanY
from feed https://www.youtube.com/feeds/videos.xml?user=nyuualiaslucy

Specs:
Arch Linux x86_64, kernel version 4.7.4
gpodder3 version 3.9.1 (2016-08-31) "My BLT Drive Just Went AWOL"

**Comment by matoro** [comment]
With my limited knowledge of python I was able to hack together a solution for this.  Unfortunately it is not integrated whatsoever and thus I have not opened a pull request.  However if anyone comes across this issue, you can replace your ```youtube.py``` file with the one at https://my.mixtape.moe/pystev.py

It also does not do any error checking or anything, but if somebody wants to take this hack and integrate it cleanly into gpodder that would be awesome.  Many thanks for your hard work.

**Comment by thp** [comment]
Turned this into a pull request: https://github.com/gpodder/gpodder/pull/194

We can't integrate it yet, since it adds a new dependency, and since it doesn't support choosing the right format, but it's actually a good idea to use that (i wanted at some point to add support for YouTube-DL integration for other video sites as well, but never got around to doing it).

**Comment by matoro** [comment]
Thanks for getting around to this!  I would have expected it to be much more complicated than that.  Just a couple additions:  it will generate errors without ```from __future__ import unicode_literals``` above the .  Also youtube-dl does allow format specification, look into the --format option.  I would try adding it myself but I know very little python and would probably write something extremely terrible.

See also https://github.com/rg3/youtube-dl/blob/master/README.md#embedding-youtube-dl and https://stackoverflow.com/questions/18054500/how-to-use-youtube-dl-from-a-python-program for reference on how to specify format.
