### ISSUE TITLE
Odysee RSS feeds returning 401 error

### ISSUE THREAD

**Issue by aberja** [gpodder/gpodder#1470]
I have been using Odysee RSS links in gPodder to download and watch videos.  This worked great until January 31, 2023 when I started receiving 401 error messags.  For example:

<code>Failed: HTTP Error 401:401 Client Error: Unauthorized for url: https://player.odycdn.com/api/v3/streams/free/applebackdoor/b0aca64ec9900c58f0c479b7cbee48a6ced544f8/2be140.mp4</code>

While looking into this error, I found the same issue reported with those using jdownloader: https://board.jdownloader.org/showthread.php?t=88725

The engineers at jdownloader appear to have resolved the issue, but I don't know how.

**Comment by auouymous** [comment]
I can't read german but jdownloader appears to use an API for Odysee.

I've never used that site, do you have to login to watch the videos? If so, each channel in gpodder has a settings tab to add username and password.

How were you getting the RSS URL for a channel there?

**Comment by aberja** [comment]
@auouymous 

> do you have to login to watch the videos

No login required.  

> How were you getting the RSS URL for a channel there?

Odysee provides a RSS url on a channel's home page.  For example, if you go to https://odysee.com/@TheLinuxExperiment:e and click on the three vertical dots to the right of the Follow button, you have a drop down with an option to <code>Copy RSS Url</code>.

Once I copy the RSS url, I open gPodder and use the <code>Add Podcast via URL</code> option under Subscriptions to add the channel.

gPodder would then obtain the available shows and provide me with the option to download and watch them.

This worked perfectly until January 31.  Now, gPodder retrieves the new shows, but returns the 401 error when it trys to download the show.

**Comment by auouymous** [comment]
The feed is working fine, its enclosures are not. The enclosure URL fails in Firefox and curl with a 401 `this content cannot be accessed at the moment` message. The URL does contain `api` which might mean the content can only be accessed via their API. If that is the case, someone will need to write a plugin for gpodder.

I was able to download an episode with yt-dlp, so another option is to enable the youtube-dl extension, append `best` or `best[height<=720]` (where 720 is the max video height you want) to `youtube.preferred_fmt_ids` in `Edit config`, and enable `Download all supported episodes with youtube-dl`. Or manually use the context menu if that setting causes issues for another feed.

**Comment by aberja** [comment]
Quick update, Odysee RSS content started working again with gPodder.  It must have been something that Odysee fixed on their end.
