### ISSUE TITLE
After upgrading I lost all epidoses in queue, is there any way to re-add all episodes to the queue without updating

### ISSUE THREAD

**Issue by Snippet24816** [gpodder/gpodder#1473]
I'm worried about this because if I update the feeds, all the episodes that are not in queue may be lost.. I made a backup of all config files before upgrading but it seems the files created with 0bytes inside each feed downloaded folder are gone hence they are not in the queue, what should I do? I can re-add them to the queue manually but is there a abetter way? like re-creating all .mp4.partial files?

**Comment by Snippet24816** [comment]
Wait I did a mistake I upgraded to not the latest version :/

**Comment by Snippet24816** [comment]
Also I'm not sure that in this version https://ci.appveyor.com/project/elelay/gpodder/builds/45913710/artifacts
archived feeds are not deleted even if not in the queue..

**Comment by Snippet24816** [comment]
Also an idea: perhaps if I can sort all episodes by status: that is error, not in queue or downloaded, I can easily re-queue elements not in the queue and not already downloaded.

**Comment by auouymous** [comment]
> archived feeds are not deleted even if not in the queue

What?


> perhaps if I can sort all episodes by status

Press Ctrl-F and type or paste `(not deleted and not downloaded and not downloading)`.

**Comment by Snippet24816** [comment]
> What?
Sorry I poorly explained, I meant I know queued episodes wont be deleted even if they are no longer in the source, but currently if an episode is archived I think it gets removed, that was the question, if it does.

> Press Ctrl-F and type or paste (not deleted and not downloaded and not downloading).
Oh amazing!! I was manually re-adding them, thank you so much :+1:

**Comment by auouymous** [comment]
Archiving an episode does not prevent removal from database if it gets removed from the feed. I don't know if a queued episode is safe, probably only downloaded episodes, and maybe downloading episodes.

**Comment by Snippet24816** [comment]
Thanks for explaining/confirming, as far as I can tell if is in the queue it isn't removed.. but yes donwloaded are the safest choice of all.

**Comment by auouymous** [comment]
Good idea, 353a4cc8b69cdbf3a7a9357114e4edb3cd516121 now allows that. See the message at the top of that commit for how to use it. There will be a new Windows build at https://ci.appveyor.com/project/elelay/gpodder/builds/46409518/artifacts in about an hour.

**Comment by Snippet24816** [comment]
Amaziing!! Thank you so much!! :)
btw I have been giving the following some thought: how to make these filters more accessible to the users.. I'm not sure about this.. perhaps something like the following? 
![image](https://user-images.githubusercontent.com/108145509/222990234-d54c29fd-b5c2-4a48-b6a4-aec7d7fe39f0.png)

which on click could list as a checklist the different filters so they can be selected and applied in addition to direct commands?
