### ISSUE TITLE
How to allow to download duplicated episodes in differenet feeds?

### ISSUE THREAD

**Issue by Snippet24816** [gpodder/gpodder#1474]
I noticed if feed "A" has an episode and feed "B" has it as well it will only download the episode from feed "A"... End if I manually download from "B" then the episode in "A is gone..

**Comment by auouymous** [comment]
That should not be possible, what are the two feed URLs?

**Comment by Snippet24816** [comment]
mmm I'm afraid they are dynamic youtube feeds so not easy to test, but perhaps just adding a playlist from a channel and all the videos for that channel can recreate that, let me try it and I will report back.

**Comment by Snippet24816** [comment]
Ok confirmed this is happening in many feeds. This should recreate it:
https://www.youtube.com/@solarstone/videos
https://www.youtube.com/playlist?list=PLiV42ZGjG8cUQHV86h8oTkfjeATpe4ARH

**Comment by auouymous** [comment]
Which episode? I downloaded "RNX - Oscillate" from both feeds and they are both there. They are also there after restarting gpodder.

```
'Pure Trance Recordings/2023-02-10 - RNX - Oscillate.m4a'
'Solarstone/2023-02-10 - RNX - Oscillate.m4a'
```

The playlist feed has "The Blizzard - Memory Of A Lifetime" listed twice and causes a non-unique GUID error. That episode is not in the second feed and wouldn't cause any issues, even if it was.

Do you have any other errors in the logs?

**Comment by Snippet24816** [comment]
I'm happy to say,  that whatever it was is no longer happening in latest 3.11.1 portable :)
