### ISSUE TITLE
Youtube feeds not updating/downloading due to upstream issue in youtube-dl and yt-dlp

### ISSUE THREAD

**Issue by Snippet24816** [gpodder/gpodder#1476]
Do note this may be a yt-dlp problem but just in case I'm posting here to be aware of it.
I compared a youtube feed with newv releases from the day and while it reports no new episodes even though it should
Log:
```
yt_dlp.utils.DownloadError: ERROR: [youtube] q4q6M9qTy8M: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2023-02-17 23:24:21,627 [gpodder.my] WARNING: Flush requested, but sync disabled.
```

**Comment by auouymous** [comment]
Known issue. yt-dlp patched yesterday and put out a new release today. youtube-dl patched today but hasn't yet put out a new release. I am currently preparing a new release of gpodder.

Linux users can [patch](https://github.com/yt-dlp/yt-dlp/commit/149eb0bbf34fa8fdf8d1e2aa28e17479d099e26b.patch) yt-dlp now or update to version 2023.02.17 when their distro gets it. Windows and Mac users can wait until gpodder 3.11.1 is released or install an artifact below.

Windows https://ci.appveyor.com/project/elelay/gpodder/builds/46270006/artifacts

Mac https://app.circleci.com/pipelines/github/gpodder/gpodder/566/workflows/12975ed9-fb7e-4d12-895c-4ffe81daf72b/jobs/934/artifacts.

**Comment by Snippet24816** [comment]
Thank you so much! Getting the artifact :+1:

**Comment by computerfreak105** [comment]
I'd like to thank you as well, really kind of you!
