### ISSUE TITLE
Question: Did yt-dlp become very slow?

### ISSUE THREAD

**Issue by computerfreak105** [gpodder/gpodder#1486]
Gpodder used to download audio only from youtube very fast. Since about a week ago downloads are very slow, also from yt-dlp stand alone.
I switched internet bandwidth at my provider from 50mbps to 20mbps, so, I'm not sure if it's my fault or if yt-dlp really became slow? I mean, it's only audio ...

**Comment by auouymous** [comment]
I have a 600Mbps connection and have never seen more than 4MB/s downloads with yt-dlp, usually around 3MB/s. A 20Mbps connection should easily be able to do 2-2.5MB/s, unless the remote site has slower pipes in your area.

However, earlier this week yt-dlp began downloading at 300kB/s, 10x slower. yt-dlp put out a release today 2023.03.03 which fixes the throttling. I will try to commit something soon to generate new Mac and Windows builds.

**Comment by computerfreak105** [comment]
Thanks, I get about 30 and 60 KiB/s now.

**Comment by auouymous** [comment]
There is a new Mac build at https://app.circleci.com/pipelines/github/gpodder/gpodder/576/workflows/5aa30ad0-765f-4a0f-aa9a-dba331efcb02/jobs/941/artifacts, and there will be a Windows build at https://ci.appveyor.com/project/elelay/gpodder/builds/46409518/artifacts in about an hour.

**Comment by computerfreak105** [comment]
Thank you so much, it’s working, downloads are fast again 😊

 

 

Von: auouymous ***@***.***> 
Gesendet: Sonntag, 5. März 2023 03:39
An: gpodder/gpodder ***@***.***>
Cc: computerfreak105 ***@***.***>; Author ***@***.***>
Betreff: Re: [gpodder/gpodder] Question: Did yt-dlp become very slow? (Issue #1486)

 

There is a new Mac build at https://app.circleci.com/pipelines/github/gpodder/gpodder/576/workflows/5aa30ad0-765f-4a0f-aa9a-dba331efcb02/jobs/941/artifacts, and there will be a Windows build at https://ci.appveyor.com/project/elelay/gpodder/builds/46409518/artifacts in about an hour.

**Comment by auouymous** [comment]
This is fixed in 3.11.2.
