### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by markghostrock** [gpodder/gpodder#1491]
I've been getting this error off and on since I updated to the new version:

&#x27;GioSyncTask&#x27; object has no attribute &#x27;custom_downloader&#x27;

I'm running Linux Mint Cinnamon 5.2.7 Distro: 20.3 Una, syncing to a Sansa  e200 series mp3 player running Rockbox.

**Comment by auouymous** [comment]
This was fixed in 3d690633eeed914e7a1bb2b44c35dc959f41df3e. It is a single line change if you know how to edit gpodder's source files. I will try to get a new release out in the next few days.

**Comment by blokdk** [comment]
Checked the line 478? in sync.py and it was there. But everytime I use gpodder it hangs with this exception:
subtext
could not find foreign type Context &#x27
Not sure if yt-dlp is the culprit. As far as I know I don't use yt for downloads.

**Comment by auouymous** [comment]
@blokdk Can you please post the actual exception traceback? And what version of cairo do you have installed?

**Comment by blokdk** [comment]
As I have no idea what cairo is or does I installed catfish on my raspi3b and saw it needed a *cairo* package. Then I did a search with catfish. Could not easily copy the output so I followed this with a find command, the output of which can be found in the file cairo-best.txt.
[cairo-best.txt](https://github.com/gpodder/gpodder/files/11382694/cairo-best.txt). 
![2023-05-03-131314_640x480_scrot](https://user-images.githubusercontent.com/10912927/235922127-1446f95f-fc5d-4570-a87c-d6b823bfce77.png) Image of the trace message?
Oddly enough I could not open the log.file as it errored with a invalid byte sequence. The older log-file did not give me this error and opened nicely. I will add this log file:
[2023-04-29.log](https://github.com/gpodder/gpodder/files/11382763/2023-04-29.log)

TIA, peter

**Comment by blokdk** [comment]
I think the installing of catfish with a cairo module or package solved the problem. It is doing what is intended except that it is still using the local space for the downloaded files. There are two environment variables pointing to an external harddisk, but it won't use them.
