### ISSUE TITLE
Gpodder has stopped working due to previous episodes not downloading

### ISSUE THREAD

**Issue by arbizm** [gpodder/gpodder#1499]
Get two popups:
"loading incomplete downloads/some episodes have not finished downloading in a previous session"
"gpodder has stopped working"

Canceled some downloads earlier when the wrong ones were selected and now these two errors occur consistently and repeatedly and cannot download anything and gpodder dies.

Here are the last lines of the log (2500 lines similar to the first):
2023-03-31 07:08:06,519 [gpodder.model] WARNING: Unknown external file: d:\gpodder\A Tradition of Violence\09 Cowboys_and_Rattlesnakes.mp3
2023-03-31 07:08:06,534 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\Winamp.File\shell\Play\command ([WinError 2] The system cannot find the file specified)
2023-03-31 07:08:06,534 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\Applications\foobar2000.exe\shell\open\command ([WinError 2] The system cannot find the file specified)
2023-03-31 07:08:06,534 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\QuickTime.mp3\shell\open\command ([WinError 2] The system cannot find the file specified)

Looked in regedit and didn't find any of these keys.  Is there any other information you need before attempting restore it as suggested below?

Is there a quick way to reset this or should I do a restore from yesterday and if so, what folder should be restored?

**Comment by arbizm** [comment]
Not sure of the version I'm running as I can't get to the point where I can check.  The best I can for now is to give you the date of installation in c/programs(x86)/gpodder and that is on 2/18 (if it's useful or not)

I have restored the three files listed above.  The first two have modification dates of 3/30 (yesterday morning when it ran fine) and the json file on 3/28.  So I have properly restored files where as the originals have modification dates of 3/31 and 3/28.

However, I'm getting the same results of how it's failing upon start up with the same log errors.  I have saved a copy of the originals of the three files above, just in case.  I don't need podcast updates immediately, so we can troubleshoot as needed to find the issue.

**Comment by auouymous** [comment]
Can you run gpodder with `-v`? See https://gpodder.github.io/docs/windows.html#debugging-gpodder-on-windows for help. The full log might contain something to explain why it is locking up.

After that, try removing all files which contain `.partial` (including the leading period). You might need to manually do that in the gui unless something like `del Downloads\*\*.partial*` works on Windows when you are inside the gpodder folder. Do not run that command unless you know what it does, because I don't know if any of it is correct.

**Comment by arbizm** [comment]
Found two partial files (searched w/explorer rather than risk the above cmd :-).  They both showed up in the attached log (2k+ warnings removed).  I ran it from the cmd line w/the "-v" option and it started normally but didn't download anything and exited.  Searched for the partials again but they are gone.  Then ran it normally from the start menu and the podcasts from earlier today were downloaded successfully.  So, looks like it's working again but hopefully you have some clues.  If you need to run again, let me know.

[fails_2023-03-31.log](https://github.com/gpodder/gpodder/files/11127343/fails_2023-03-31.log)
and the

**Comment by auouymous** [comment]
The log file didn't show anything that could help. I'm glad removing the partial files fixed it.

**Comment by computerfreak105** [comment]
I'm a bit uncertain about something: Does deleting .partial files already affect the database of gpodder? If I delete such files, will gpodder notice that and won't download it anymore?

I usually have to kill the windows gpodder GUI in the taskmanager when this problem happens. Gpodder shows "queueing" in the window title and can't be closed anymore with alt+F4. After that I usually move all the finished downloads to another location and empty the whole download folder.

Sometimes switching location with a VPN (Mullvad) helps and gpodder downloads again. Just would like to mention this in case it could help in getting to the roots of the problem.

**Comment by auouymous** [comment]
> I'm a bit uncertain about something: Does deleting .partial files already affect the database of gpodder? If I delete such files, will gpodder notice that and won't download it anymore?

The partial file is the only indicator gpodder uses to download a file. It creates one for each episode you want to download, and the partial file remains zero bytes until gpodder begins downloading data to it. So yes, removing partial files while gpodder is NOT running will cause gpodder to forget it was downloading them.


> Gpodder shows "queueing" in the window title and can't be closed anymore with alt+F4.

When gpodder starts up, it scans for partial files and asks if you want to resume. There is no network activity until you click the resume button. Is it locking up after resuming or during the scan?

**Comment by computerfreak105** [comment]
[When gpodder starts up, it scans for partial files and asks if you want to resume. There is no network activity until you click the resume button. Is it locking up after resuming or during the scan?]

It locks up somewhere during scans. I have Gpodder scanning every 45 minutes, so it may happen 45 minutes after I start the program, sometimes I can go for maybe a week until it happens again. Resuming downloads after a start is possible without problems. Switching to other locations with VPN did result in the problem in the past, but on the other hand it fixed it as well.
