### ISSUE TITLE
environment variables; download dir

### ISSUE THREAD

**Issue by blokdk** [gpodder/gpodder#1508]
One of my wishes was to finaly get the home folder and the downloads folder on my external hard disk. 
Even before I installed from Git I added these two important environmental variables. 
But it is not working on my raspberry pi 3B.

Please advise.

**Comment by auouymous** [comment]
Did you use the correct names and how did you set them? When starting gpodder, you should always see a message in the console for each of the overridden variables, do you see those?

**Comment by blokdk** [comment]
Well, as I remember it it was not what I would call a clean install. It was rather messy with things not working. And I was not watching the console to see the overriden variables.
As to the variables, the were added by way of the export command and checked several times. As that did not do the job I later  added these directories to the .pam_environment file. To no avail.

As it was a rather troubled install and after reading your comment I decided to start anew. Deleted the gPodder directory and also the gpodder directory. Did not touch the environment variables.
Installed from Git.
Still no success.

**Comment by blokdk** [comment]
In a bold mood I decided on another install on a raspi 3b that is running Kodi. 
I added the environment variable for the download_dir; and boldly used sshfs to mount a dir on my Debian pc for this intended $GPODDER_DOWNLOAD_DIR.
After several reboots and no success I checked the environment and could not find the variable. So I started searching articles again and discovered that Raspian OS is based on Debian as is Ubuntu. But they are differing on some subjects, configs etc.

I found an article that pointed me to setting it. It suggested two places and I used them both. I am sorry to say I cann't find this article now. One solution was to add it to a **.profile.**  and the other to add it to **.bashrc**. I am not sure which one did the trick.

But it worked!

The podcasts were downloaded to the mounted directory on my PC.

Of course I tried this solution immediately on the intended raspi 3b and there it still does not work. 

The manual guides the linux user to read about environment variables on a Ubuntu site. But Raspian OS is no Ubuntu! And I am sorry to say that I have not found a clear guide in the forums of raspberrypi.com. 

So, I am still faced with a raspi 3b that runs gpodder but without the convenience of downloading the podcast to an external hard disk.

Please help.

**Comment by blokdk** [comment]
I consider this problem solved now.

When I restarted the intended raspi 3b and started gpodder from the bin/gpo I noticed messages that indicated that all was as I hoped it would be. 
Finally the download dir en home dir on the external hard disk were used. 
And I think that came about from the environment variables made in .profile & .bashrc. 
Raspian OS is no Ubuntu or Debian!
