### ISSUE TITLE
Client is opening an insane amount of parallel connections

### ISSUE THREAD

**Issue by Ratcreamsoup** [gpodder/gpodder#151]
We recently noticed a single IP address that had 199 connections open to one of our webservers. According to our logfiles the UserAgent used by this address was "gPodder/3.9.0 (+http://gpodder.org/)". Our anti-dos procedures effect an automatic ban against an IP when the number of concurrent active downloads cross a certain threshold. According to our logs, the client in question actually did start 199 concurrent downloads of 199 unique files from the same series of podcasts. This is a complete waste of resources both for the client in question and for the webserver it is downloading from. It would make much more sense to limit the number of parallel downloads to a more sane value of say four to six, so the user actually benefits from receiving complete files instead many dozens of incomplete ones before some firewall rule kicks in. The overall bandwidth consumed would probably stay the same, the overall transfer speed would probably increase as the overhead for handling so many connections in parallel would decrease; allowing the client to initialize several dozens of parallel connections just doesn't make any sense, unless you wish to promote this client as some kind of Denial of Service tool.

Kind regards

  Markus

**Comment by thp** [comment]
Thanks for the report!

The default is to only have one simultaneous download, but users can opt to increase this limit or even disable this limit. It might be useful to have a reasonable limit (maximum of 16 parallel downloads in parallel configurable from the UI, with more optionally when the user forcefully starts downloads, this should make it possible to avoid such situations.
