### ISSUE TITLE
Can't subscribe to a particular youtube channel

### ISSUE THREAD

**Issue by computerfreak105** [gpodder/gpodder#1510]
Hi, can someone please try to subscribe to this channel?

https://www.youtube.com/@skarbeqmsp8036

or the same as channel ID

https://www.youtube.com/channel/UC7Uwy_dVEDyknhuK71tMf4Q

Both don't work, regardless with VPN to US or not. I get the error message couldn't not retrieve channel ID.
I wonder what's up with this channel. Is there something in the title which result in problems?
I'm using built 998 right now.

Thanks!

**Comment by computerfreak105** [comment]
I think Everything works again, I deleted cookies. so I'll close the issue for now. Thanks.

**Comment by auouymous** [comment]
> I deleted cookies

Deleting cookies in your browser wouldn't help with issues in gpodder.


> couldn't not retrieve channel ID.

Youtube temporarily has issues every few months and that error is thrown by gpodder. It usually only lasts a few hours but has been down for several days before.

**Comment by computerfreak105** [comment]
Ah, thanks. 

Ah, thanks. It’s probably the time again when they change things on youtube. I subscribed to a few other channels. Some of them worked on the first hit, others needed a few tries. In most cases I was kicked out from the GPO CLI and had to restart GPO. I’ll just try the two remaining channels at a later time.

 

Take care.

 

 

Von: auouymous ***@***.***> 
Gesendet: Sonntag, 7. Mai 2023 06:10
An: gpodder/gpodder ***@***.***>
Cc: computerfreak105 ***@***.***>; State change ***@***.***>
Betreff: Re: [gpodder/gpodder] Can't subscribe to a particular youtube channel (Issue #1510)

 

I deleted cookies

Deleting cookies in your browser wouldn't help with issues in gpodder.

couldn't not retrieve channel ID.

Youtube temporarily has issues every few months and that error is thrown by gpodder. It usually only lasts a few hours but has been down for several days before.
