### ISSUE TITLE
Anyone having trouble download youtube videos since yesterday June 07?

### ISSUE THREAD

**Issue by computerfreak105** [gpodder/gpodder#1513]
Hi all! Gpodder seems to be queueing constantly since maybe yesterday late afternoon. I have 1.0.1002 portable running on Windows 10. Anyone here experiencing the same?

**Comment by auouymous** [comment]
Both internal and yt-dlp support work fine here, in America. Do the logs show any issues? What is your `youtube.preferred_fmt_ids` set to?

**Comment by computerfreak105** [comment]
All channels look like this:

 

2023-06-08 08:09:02,439 [gpodder.gtkui.main] ERROR: Error updating feed: Mira PurPur Toca, Rus: Could not retrieve YouTube channel ID for URL https://www.youtube.com/feeds/videos.xml?channel_id=UCEx6RUugMchbkjN0vlrg3Hw.

Traceback (most recent call last):

  File "E:\gpodder-3.11.1-portable 1002\data\lib\python3.10\site-packages\gpodder\gtkui\main.py", line 2905, in update_feed_cache_proc

    new_episodes.extend(channel.update(max_episodes=self.config.limit.episodes))

  File "E:\gpodder-3.11.1-portable 1002\data\lib\python3.10\site-packages\gpodder\model.py", line 1300, in update

    new_episodes = self._consume_updated_feed(result.feed, max_episodes)

  File "E:\gpodder-3.11.1-portable 1002\data\lib\python3.10\site-packages\gpodder\model.py", line 1184, in _consume_updated_feed

    feed.get_link() or self.link,

  File "E:\gpodder-3.11.1-portable 1002\data\lib\python3.10\site-packages\gpodder\model.py", line 113, in get_link

    self.feed['link'] = youtube.get_channel_id_url(self.feed['url'], self.fetcher.feed_data)

  File "E:\gpodder-3.11.1-portable 1002\data\lib\python3.10\site-packages\gpodder\youtube.py", line 463, in get_channel_id_url

    raise Exception('Could not retrieve YouTube channel ID for URL %s.' % url)

Exception: Could not retrieve YouTube channel ID for URL https://www.youtube.com/feeds/videos.xml?channel_id=UCEx6RUugMchbkjN0vlrg3Hw.

2023-06-08 08:09:53,207 [gpodder.gtkui.main] ERROR: Error updating feed: hominchang4604 Spicy, Kor: not found

 

 

and I've set:

 

   "preferred_fmt_id": 0,

    "preferred_fmt_ids": [

      "bestaudio"

    ],

    "preferred_hls_fmt_id": 0,

    "preferred_hls_fmt_ids": [

      91,

      92,

      93,

      94,

      95,

      96

    ]

  }

}

 

I usually get .webm files and sometimes .m4a files this way.

 

 

I downloaded without VPN and with Mullvad VPN to different locations. I've set it to new York and it didn't work.

 

Also, when GPodder is queueing it can't be closed and must be killed in the windows task manager.

I was away yesterday afternoon and I didn't experiment on my system yesterday, so I think I'm innocent this time :-)

 

 

 

Von: auouymous ***@***.***> 
Gesendet: Donnerstag, 8. Juni 2023 08:36
An: gpodder/gpodder ***@***.***>
Cc: computerfreak105 ***@***.***>; Author ***@***.***>
Betreff: Re: [gpodder/gpodder] Anyone having trouble download youtube videos since yesterday June 07? (Issue #1513)

 

Both internal and yt-dlp support work fine here, in America. Do the logs show any issues? What is your youtube.preferred_fmt_ids set to?

**Comment by computerfreak105** [comment]
Hi, now it's working again! I don't know what the problem was ... I thought I'd clear google chrome's history, but somehow I doubt this is the reason why it's working again. I think I'm closing this issue as solved.

Thank you anyway!

 

 

 

 

Von: auouymous ***@***.***> 
Gesendet: Donnerstag, 8. Juni 2023 08:36
An: gpodder/gpodder ***@***.***>
Cc: computerfreak105 ***@***.***>; Author ***@***.***>
Betreff: Re: [gpodder/gpodder] Anyone having trouble download youtube videos since yesterday June 07? (Issue #1513)

 

Both internal and yt-dlp support work fine here, in America. Do the logs show any issues? What is your youtube.preferred_fmt_ids set to?

**Comment by auouymous** [comment]
> Could not retrieve YouTube channel ID for URL

YouTube goes down all the time and causes gpodder to throw that error. It might also be a time of day issue so accessing with a VPN might not help.


> Also, when GPodder is queueing it can't be closed and must be killed in the windows task manager.

It probably opened an error dialog, and then the queueing progress dialog opened. This is a known issue that deadlocks gpodder and the reason I haven't made it throw sqlite errors yet. I did however recently think of something that might fix it, just need to find time to implement it.


> I thought I'd clear google chrome's history

That would never fix problems in gpodder.
