### ISSUE TITLE
Cant add live tab of a Yt channel

### ISSUE THREAD

**Issue by Snippet24816** [gpodder/gpodder#1515]
I can't seem to add a the live tab as a separated channel from the regular video tab, gPodder complains that it has already been added. I realized lots of videos are being preleased in the live tab which is not covered in the regular yt tab.

**Comment by auouymous** [comment]
This is a duplicate of your #1506 issue. For now, you will need to uncheck the top checkbox in the youtube-dl extension to get lives and shorts. It limits the number of past episodes you can access but is the only way until a solution can be found.

**Comment by tomasts248** [comment]
Oh I'm sorry for the duplicated issue. Ok thanks.

**Comment by Snippet24816** [comment]
Oh I'm sorry for the duplicated issue. Ok thanks.
