### ISSUE TITLE
[Enhancement] Add "Copy link location" to context menu for links in episode description

### ISSUE THREAD

**Issue by ushuc** [gpodder/gpodder#1516]
When hovering with the mouse over a link in the episode description, the link trarget is shown in a small popup towards the bottom of the description section. But it is not possible to copy the link URL. The context menu only allows for copying the URL of the whole episode, not the link URL inside the description.
In the case of the screenshot gPodder would copy the URL of the YouTube episode, not the URL to Facebook.

Please add a context menu entry to copy the link URL of links inside of the description to the clipboard (like web browsers have).

![grafik](https://github.com/gpodder/gpodder/assets/109863013/7dddb343-c751-4131-9d86-bd8dc54784bc)

**Comment by auouymous** [comment]
It is complicated, see existing issue #1097 and PR #1148.

**Comment by tpikonen** [comment]
I could try to get #1148 ready, but I'm not sure what the problem with the colors is. On superficial testing after rebasing it to current master it works fine here. Would you have time to test / work on it, @auouymous?
