### ISSUE TITLE
On opening gpodder disappears down into dock. How to prevent?

### ISSUE THREAD

**Issue by birdjumper** [gpodder/gpodder#1519]
On opening, gpodder disappears down into dock. How can I prevent this from happening?
Thanks

Mac M1 RAM 16GB running MacOS v 13.4 Audacity 3.2.1 IINA 1.3.1 Build 133 mpg 0.34.1 gPodder 3.11.0

**Comment by auouymous** [comment]
Are you using the official gpodder build or a third-party build? Have you tried 3.11.1?

**Comment by birdjumper** [comment]
Official gpodder from gpodder.net and I just tried 3.11.1 and it had the same behaviour.

It doesn't remember its position when I quit and always opens hiding in the docks bottom right hand corner. 

I can't imagine that being useful to anyone.

**Comment by auouymous** [comment]
Do the logs have any warnings or errors? Do you have the `minimize on start` extension enabled?

**Comment by birdjumper** [comment]
> Do you have the `minimize on start` extension enabled?

YES! I did. I didn't know that even existed. I don't know why it was checked either.
THANK YOU! I've learned something about gpodder.
