### ISSUE TITLE
Link to AppImages once they are in sync with our Linux builds

### ISSUE THREAD

**Issue by probonopd** [gpodder/gpodder#152]
Help -> Software updates -> "New version available" -> "Download the latest version from gpodder.org?" -> "Yes" -> Linux/BSD: Install via the package manager -> Available in most distributions (Debian, Ubuntu, Fedora, ...)

There is no newer one for my distribution.

Can gPodder provide a download on the homepage, like for Windows and macOS?

**Comment by thp** [comment]
We had that at some point, but due to the sorry state of packaging on Linux distributions, and incompatibilities even between e.g. RPM-based distros, we kind of gave up and now let the distributions take care of that. Or people can always use the Windows installer with Wine (!).

There are even "universal" packaging formats, like Snap or Flatpak, but even if those look as if they are universal, the fact is that they are still only properly supported on their "home" distro (Snap = Ubuntu, Flatpak = Fedora).

(..after looking at your profile..) It looks like you're involved in AppImage, something I didn't even know about until now.

![Standards](https://imgs.xkcd.com/comics/standards.png)

Sorry for the rant, but that's exactly what the state of packaging apps on Linux currently looks like, I have even [ranted](https://plus.google.com/+ThomasPerl4/posts/QuXt5j9gQRM) about this a few weeks ago.

**Comment by probonopd** [comment]
Would you be interested in a solution that [just works](https://plus.google.com/+LinusTorvalds/posts/WyrATKUnmrS)?

**Comment by thp** [comment]
I'd be willing to give it a try, but as a lazy bastard, I don't really have the time to investigate or maintain this if it's tedious, so a question: As gPodder needs Python 2 and Gtk+2 and PyGTK (at the moment), but most distros have those dependencies already installed (or at least available), would I need to ship Python and Gtk with the AppImage? Also, are there any examples of similar apps (Python/Gtk-based) or do you even have time to bootstrap us with a appimage config / build setup to get us up and running?

**Comment by probonopd** [comment]
> I'd be willing to give it a try

Cool :+1: 

> but as a lazy bastard, I don't really have the time to investigate or maintain this if it's tedious

The good news, I have already figured out the hard parts. The only thing that I don't have is application-specific knowledge, which means in practice that I can flush out a >80% version really quickly and usually need the upstream app developers to check for functionality and any remaining glitches.

But no, it's not tedious.

> As gPodder needs Python 2 and Gtk+2 and PyGTK (at the moment), but most distros have those dependencies already installed (or at least available), would I need to ship Python and Gtk with the AppImage?

Since AppImage is really nothing more than a self-mounting filesystem image that contains the app contained therein, it's really up to you to decide. Think of it as an `.app` inside a `.dmg` on macOS.

That being said, I __do strongly__ recommend that you bundle these things. In fact I already did for you, below, and the download is still _significantly_ smaller than the macOS one.

> do you even have time to bootstrap us with a appimage config / build setup to get us up and running?

There are two main routes to do this:
 1. Integrate with your build system. Recommended e.g., for projects with Travis CI in place. Can be used to bundle all your continuous builds as AppImages (makes it easy for testers!)
 2. Repackage pre-existing packages. Recommended e.g, for project that already maintain fine-tuned PPAs. This is the route I took below.

With that out of the way, here is the yaml file to convert the binaries from trusty ppa into an AppImage: https://github.com/probonopd/AppImages/blob/master/recipes/meta/gPodder.yml ([this](https://github.com/probonopd/AppImages/blob/master/recipes/meta/Recipe) script can run it).

And, most importantly, here is the AppImage:
https://bintray.com/probono/AppImages/gPodder#files

```
# Download it
wget https://bintray.com/probono/AppImages/download_file?file_path=gPodder-3.9.1.glibc2.15-x86_64.AppImage -O gPodder-3.9.1.glibc2.15-x86_64.AppImage

# Make it executable
chmod a+x gPodder-3.9.1.glibc2.15-x86_64.AppImage

# Run it
./gPodder-3.9.1.glibc2.15-x86_64.AppImage

# Extract it if you want to peek inside and modify it
./gPodder-3.9.1.glibc2.15-x86_64.AppImage --appimage-extract
cd squashfs-root/
ls

# From here you can fine-tune it: add/move/delete files,...
# These steps should go into the script: section of the yml file above
```

**Comment by thp** [comment]
Can we link to https://bintray.com/probono/AppImages/gPodder#files from the project's webpage? Will this repo there be updated when new versions of gPodder come out or do we need to trigger something?

**Comment by probonopd** [comment]
Sure you could link there, but keep in mind that my AppImages are just examples. The AppImage format is designed for upstream application projects to provide their own downloads, in order to control the end-to-end experience (and be able to support it). So I'd prefer for the project to roll your own.

If you still want to link to mine, the generation is automated but the triggering of new builds is not. Open a ticket in the probonopd/AppImages project to have a new version triggered.

**Comment by probonopd** [comment]
Synced to 3.9.2:
https://bintray.com/probono/AppImages/gPodder/3.9.2.glibc2.15#files

**Comment by vossad01** [comment]
Just a thought, but putting the note that it is surprisingly easy to run gPodder out of a git clone could be worthwhile for Linux users.  While not familiar suitable for all Linux users, I am sure there is a number who would take that as an appropriate solution if they wanted to stay up-to-date.

**Comment by probonopd** [comment]
Yes... indeed. Why not do both?

**Comment by thp** [comment]
This is now fixed, with the PPA, AppImage and Git instructions linked from gpodder.org.

**Comment by probonopd** [comment]
On https://gpodder.github.io/ the AppImage seems to be gone?

**Comment by elelay** [comment]
@probonopd I wasn't aware of this AppImage. In fact, there is a new issue #455 requesting it that I was not sure what to do with...
With gPodder 3.10 we moved to python 3 / gtk3.
If you're interested in creating the AppImage (again ;-) ), I'd be happy to test + provide a link to it on the website.
Please continue discussion in ticket #455...
