### ISSUE TITLE
Question: manually moving episode downloaded locked files results them in being removed from episode list?

### ISSUE THREAD

**Issue by Snippet24816** [gpodder/gpodder#1523]
I mean after restarting gPodder.. I know at least without it being locked it does delete the moved episode from the feed list. From the top of my head I was thinking how to free space since I cant set symbolic links because I don't know how the other paths are going to change, then perhaps (haven't tested it) I can create 0bytes mirros and just store them in the regular Gpodder feed. But If I can lock downloaded items that would be just simpler, either way I wonder, not a feature request.. I can just right click create some shortcuts then rename their name and extension I guess.
Update: worked :)

**Comment by auouymous** [comment]
I deleted some locked and unlocked downloads outside of gpodder and nothing strange happened after restarting. The episode is marked as deleted when its file vanishes, so it would be hidden if you hide deleted episodes in the view menu.

Setting the `GPODDER_DOWNLOAD_DIR` environment variable would let you move the `Downloads` folder out of `gPodder`, and place it on another drive.

**Comment by tomasts248** [comment]
Thank you!! :+1:

**Comment by Snippet24816** [comment]
Thank you!! :+1:
