### ISSUE TITLE
No youtube videos again since Saturday

### ISSUE THREAD

**Issue by computerfreak105** [gpodder/gpodder#1528]
Hi all
Guess youtube has it's famous days of disobedience again and gpodder can't download. Is there something which can be done for the next artifact? I use 3.11.1.1019 right now wich was working until about Saturday afternoon. On Sunday morning I could get some unfinished downloads of saturday afternoon but nothing new.
Do you guys still get youtube videos right now? I'm interested if this is location based or if everyone is affected. For experimenting I set my VPN to US, but no luck so far.
Thanks if something can be done. Otherwise I guess we just have to wait until it works again ...

**Comment by auouymous** [comment]
I updated a couple hours ago and it worked fine with gpodder's native youtube support and the yt-dlp extension.

Does youtube in the browser work when gpodder is unable to download?

**Comment by ndias** [comment]
@computerfreak105 
If you use yt-dlp-2023-07-06 maybe you get this bug
https://github.com/yt-dlp/yt-dlp/issues/7528

See in the logs what it says

**Comment by computerfreak105** [comment]
Thanks Auouymous and Ndias.

I just updated to 1020, but no luck yet. Youtube in browser works flawlessly and yt-dlp standalone for just downloading channels as well. The problem is only with gpodder. There is always the word "queueing" and gpodder can't be closed normally. I always have to kill it in the windows task manager.

 

 

The extension part in my config.json is like this:

 

  "extensions": {

    "enabled": [

      "rename_download",

      "youtube-dl"

    ],

    "rename_download": {

      "add_podcast_title": false,

      "add_sortdate": true,

      "sortdate_after_podcast_title": false

    },

    "youtube-dl": {

      "embed_subtitles": false,

      "manage_channel": false,

      "manage_downloads": true

    }

  },

 

And the end is set this way:

 

"youtube": {

    "preferred_fmt_id": 0,

    "preferred_fmt_ids": [

      "bestaudio"

    ],

    "preferred_hls_fmt_id": 0,

    "preferred_hls_fmt_ids": [

      91,

      92,

      93,

      94,

      95,

      96

    ]

  }

}

 

 

 

I haven't changed anything in a while. I'm mainly interested in audio files. I usually got a mix between .webm and .m4a. Can I specify which I want or is this dependent on certain videos or livestreams?

 

Or would it be more reliable to just use the smalles video size with best audio?

 

 

 

And just for speeding up things: There seems to be an extension which would search for episodes when one starts gpodder.

 

https://gpodder.github.io/docs/extensions/searchepisodeonstartup.html

 

IN other extensions there is a command for GPO how to enable or disable them. Is there a command for this one as well?

 

 

Thanks, your help is very appreciated.

 

 

Von: auouymous ***@***.***> 
Gesendet: Montag, 24. Juli 2023 12:29
An: gpodder/gpodder ***@***.***>
Cc: computerfreak105 ***@***.***>; Author ***@***.***>
Betreff: Re: [gpodder/gpodder] No youtube videos again since Saturday (Issue #1528)

 

I updated a couple hours ago and it worked fine with gpodder's native youtube support and the yt-dlp extension.

Does youtube in the browser work when gpodder is unable to download?

**Comment by computerfreak105** [comment]
Hi, now this morning it's working again! No idea what's the problem here. GPodder is working fine again and it's raining youtube videos from the last two days :-)

Here is the log after my last start and task kill of gpodder from yesterday.

Thanks a lot.
[2023-07-24.log](https://github.com/gpodder/gpodder/files/12157548/2023-07-24.log)

**Comment by auouymous** [comment]
The logs show the classic problem where youtube feeds vanish with 404 errors and the ones that do work don't contain all of the data, which causes the "Could not retrieve YouTube channel ID" errors. I don't know why the queueing dialog froze gpodder, unless the one IncompleteRead error opened an error dialog.
