### ISSUE TITLE
Progress tab is not updated in some cases

### ISSUE THREAD

**Issue by brian-in-crawford** [gpodder/gpodder#153]
Running v3.9.0 (latest version in the Debian testing repositories) and there's a minor problem in that the 'progress' tab never seems to update after the first few minutes. It looks like gpodder has hung, but if you fire up ksysguard then you can see that downloads are still progressing. It looks to me like you need a few screen repaints in there somewhere (sorry if that's Pascal-speak!) No shortage of CPU power here, AMD Phenom II 6-core with 8GB of memory, and the PC isn't doing much else at the time (Chromium and that's it).

**Comment by thp** [comment]
Did you try version 3.9.1 and see if you can repro the issue? Note that you can run gPodder from a Git checkout without having to compile anything, so that'd be an easy way to test.

**Comment by brian-in-crawford** [comment]
No, I haven't tried 3.9.1, I'll schedule a checkout for tomorrow night (I'm on satellite internet, I can only download between 0200 and 0700) and I'll let you know. I sort of assumed that the version in the Debian testing repositories would be the latest and greatest, but obviously not...  although as we're only talking the difference between 3.9.0 and 3.9.1 I'm slightly surprised that there isn't a list of fixes which could be checked.

**Comment by brian-in-crawford** [comment]
OK, I confirm that the problem is still present in v3.9.1 as run from the git checkout. 

I tell gpodder to download all the new podcasts (typically around 250 MB) with a restriction on downloading no more than 2 podcasts at a time, and it looks for all the world as if gpodder has hung. The progress tab is not updated after the first few seconds, it looks as if the downloads currently in progress have hung, only the lights on the modem tell me differently, and if I just leave gpodder to its own devices then eventually the downloads will complete and only then will the progress tab clear. This is 100% reproducible in v3.9.0 and it appears that v3.9.1 will be no different.

**Comment by elelay** [comment]
Closing since it's really and a similar bug has been fixed in the 3.10 branch (#550).
