### ISSUE TITLE
metadata

### ISSUE THREAD

**Issue by MvdSEnesco** [gpodder/gpodder#1530]
All the metadata (title etcetera) are not saved in the files. (windows 10)
So I have to rename every episode. Is there a solution to this?

Thx!

**Comment by auouymous** [comment]
Excluding sanitization, the filenames are exactly how they appear in the feed. There is the https://gpodder.github.io/docs/extensions/renameafterdownload.html extension that can put the published date and episode title in filename. Or the https://gpodder.github.io/docs/extensions/tagging.html extension that adds tags to mp3 and ogg files.

**Comment by auouymous** [comment]
Please reopen if that did not solve your problem.
