### ISSUE TITLE
gpodder on youtube channel : download a youtube video is at the slowest i have ever encountered

### ISSUE THREAD

**Issue by andrew-ysk** [gpodder/gpodder#1532]
Why when i use gpodder to download youtube video is slow like no other..  Something i made wrong ? 
It used to require to enter google API key for gpodder to retrieve youtube rss feed, but how come now no more place to enter the API key ? 

How i subscribed to  youtube rss :
simple add by url, example as below.. 
https://www.youtube.com/feeds/videos.xml?channel_id=UCKQVSNdzGBJSXaUmS4TOWww
it manage to fetch the rss feed, but to download (to watch), it takes ages.. but at the end, it will still able to download the video.. just too long.

**Comment by auouymous** [comment]
The API key was removed a long time ago because downloads worked fine without it.

A couple years ago Google began throttling downloads to about 50kB/s. You can enable the youtube-dl extension (requires yt-dlp or youtube-dl to be installed if on Linux), and either enable "Download all supported episodes with youtube-dl" or right click on episodes and use "Download with youtube-dl".

**Comment by andrew-ysk** [comment]
> You can enable the youtube-dl extension (requires yt-dlp or youtube-dl to be installed if on Linux), and either enable "Download all supported episodes with youtube-dl" or right click on episodes and use "Download with youtube-dl".
Hmm, must be my setting that is wrong. 
$ whereis yt-dlp
yt-dlp: /usr/bin/yt-dlp /usr/local/bin/yt-dlp  

$ whereis youtube-dl
youtube-dl: /usr/bin/youtube-dl /usr/local/bin/youtube-dl  

In gpodder preference > youtube-dl > ticked both "parse youtube channel feeds with youtube-dl to access more than 15 episodes" & "Download all supported episode with youtube-dl". 

On my system, if i download yt video using youtube-dl, either it will not work or it will be very slow.  
However yt-dlp will be able to download fast. 
Hence i believe gpodder is using youtube-dl. 
How can i make gpodder use yt-dlp instead? clipgrab is using yt-dlp i think.. it manage to download yt video lightning fast. 
Thx

**Comment by auouymous** [comment]
What does it say at the top of the youtube-dl preferences page in gpodder?

**Comment by andrew-ysk** [comment]
> What does it say at the top of the youtube-dl preferences page in gpodder?

Oh. yt-dlp 2023.02.17
It seems to be using yt-dlp. But why it takes ages to download an yt video ? while it take seconds for clipgrab or yt-dlp to download the same yt video ..

**Comment by andrew-ysk** [comment]
Since it is using yt-dlp already, why there is a check box underneath the same location " Download all supported episodes with youtube-dl" ?   I tried to check the option and it totally can't download anything. It throws " (Error: ERRO... download video data: HTTP Error 403: Forbidden) ".

**Comment by auouymous** [comment]
> 2023.02.17

I have no idea why it would download fast outside of gpodder, unless `yt-dlp --version` reports a newer version, since you do have it installed twice. Older versions are known to return a lot of 403 errors. You need to keep both of your yt-dlp installs update to date.

> Since it is using yt-dlp already, why there is a check box underneath the same location

The top checkbox uses ytdl do manage channels. While it allows more than 15 episodes, it is very very very slow, and not everyone wants it. The bottom checkbox is for anyone who only wants to use ytdl sometimes.

**Comment by rsramkis** [comment]
I thought I might chime in here as I am testing on Arch Linux.

```
❯ yt-dlp --version                                            
2023.07.06
```

When I download via terminal I get very fast speeds:
```
❯ yt-dlp -f22 'https://youtu.be/E_C3pgc1Iho?si=LgakLoz3fyY5Yd58'
[youtube] Extracting URL: https://youtu.be/E_C3pgc1Iho?si=LgakLoz3fyY5Yd58
[youtube] E_C3pgc1Iho: Downloading webpage
[youtube] E_C3pgc1Iho: Downloading ios player API JSON
[youtube] E_C3pgc1Iho: Downloading android player API JSON
[youtube] E_C3pgc1Iho: Downloading player f130aa11
[youtube] E_C3pgc1Iho: Downloading m3u8 information
[info] E_C3pgc1Iho: Downloading 1 format(s): 22
[download] Destination: Why Linux is better for (most) developers! [E_C3pgc1Iho].mp4
[download] 100% of   77.15MiB in 00:00:09 at 7.99MiB/s
```

When I try to download through gPodder:

![image](https://github.com/gpodder/gpodder/assets/14362317/8a871677-fad0-4d81-a0be-3b875a632d72)

![image](https://github.com/gpodder/gpodder/assets/14362317/43ff82de-5bca-4cd3-8efb-86f851062788)

Happy to help testing to try to figure out why download speeds are changing for the same video.

**Comment by rsramkis** [comment]
> What does it say at the top of the youtube-dl preferences page in gpodder?

Hi,

I'm looking under "gpodder Configuration Editor" and I am not seeing any options to change to yt-dlp when in Linux with Gnome Desktop:

![image](https://github.com/gpodder/gpodder/assets/14362317/6a9f7786-d7e4-4b59-b530-901edf4de743)

**Comment by neodyne** [comment]
@rsramkis In your screenshots, you do not have the youtube-dl extension enabled.

Open the hamburger menu -> Preferences -> Extensions -> tick youtube-dl. This should add an additional card to Preferences -> 'youtube-dl', after Extensions. Make sure both tickboxes there are checked. Also the first line there should be the used youtube-dl version; this ideally should be yt-dlp 2023.07.06 in your case, if you have the binary in a sane path location.

The youtube-dl extension in gPodder uses [yt-dlp by default](https://github.com/gpodder/gpodder/blob/master/share/gpodder/extensions/youtube-dl.py#L15), youtube-dl is only used as fallback.

Retry and hope for better speeds :)

**Comment by rsramkis** [comment]
Thank you for the help. I found the setting you mentioned in Extensions:

![image](https://github.com/gpodder/gpodder/assets/14362317/5811bb4f-e853-4772-81b5-b66ef0b60931)

Then I verified the 2 settings that were needed:
![image](https://github.com/gpodder/gpodder/assets/14362317/29b912e2-a685-4ddb-810c-cf95ef5c4425)

Confirmed massive improvement in download speeds (7mb/s)

![image](https://github.com/gpodder/gpodder/assets/14362317/3449df38-3106-4e6d-ada2-ed8c3fa2b97b)

**Comment by auouymous** [comment]
@andrew-ysk Please reopen if the above did not solve your problem.
