### ISSUE TITLE
Error while uploading when trying to sync to Nextcloud with Letsencrypt Cert

### ISSUE THREAD

**Issue by reibuehl** [gpodder/gpodder#1534]
I use gpodder 3.11.1 (2023-02-17) on Windows 10 64bit. When I try to sync my subscriptions to my Nextcloud system with the gpodder sync plugin, I get the error message:

Error while uploading
&lt;urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)&gt;

The Nextcloud server uses a valid Letsencrypt certificate. Sync from AntennaPod from my Android mobile phone to the same server works fine. 

Is there a way to fix this issue by installing a correct certificate in gpodder or the underlying libraries?

**Comment by reibuehl** [comment]
I tried adding the LetsEncrypt X1 Root and R3 Intermediate certs to C:\Program Files (x86)\gPodder\ssl\cert.pem but that didn't change the error message.

**Comment by elelay** [comment]
See #1251: the Nextcloud gpodder plugin is not compatible with gPodder: it takes its inspiration from gpodder.net but doesn't implement the api completely.  So even if you fix certificate issues you will not achieve what you want.

**Comment by reibuehl** [comment]
Okay, then I have to look for another Windows Podcast client that works with that sync module. Thanks!
