### ISSUE TITLE
GUI issues - Problem with accented letters in translation

### ISSUE THREAD

**Issue by bovirus** [gpodder/gpodder#1538]
@auouymous 

Please check screenshots.

![image](https://github.com/gpodder/gpodder/assets/1262554/6525303c-dc97-4ec8-a72c-7884a1942665)

![image](https://github.com/gpodder/gpodder/assets/1262554/c28ff186-2906-4214-8d31-e8d3776fed3a)

![image](https://github.com/gpodder/gpodder/assets/1262554/b8af50ed-2508-45a7-b478-7c795cf73fe3)

In some part of GUI the accented letters like à ì are now showed right.

**Comment by auouymous** [comment]
Is this with 3.11.2? Are you able to test 3.11.1, and does it have the problem?

**Comment by bovirus** [comment]
@auouymous 

Yes problem tested in 3.11.2.
The problem is rpesent on 3.11.2 eand not in 3.11.2
tested with original portable version.

version 3.11.1
![image](https://github.com/gpodder/gpodder/assets/1262554/97d085f1-d741-4fe0-b1f1-9deefa8e6611)

versione 3.11.2
![image](https://github.com/gpodder/gpodder/assets/1262554/637a5afb-fed6-44d0-a6ee-925716003aa7)

**Comment by auouymous** [comment]
The problem is 3e005d1055b5523484ca98f26fc2c090a5415a72. I assumed it had no purpose since gPodder didn't use it for Linux or Mac, and it prevented appveyor from building.

**Comment by bovirus** [comment]
@auouymous 

How can fix this?

**Comment by auouymous** [comment]
I don't yet know. The commit can't be reverted because that method no longer exists in python 3.11. And we would need to pin an older version of msys2 to get python 3.10.

**Comment by bovirus** [comment]
@auouymous 

Please merge italian language (https://github.com/gpodder/gpodder/pull/1537)
I will open a separate PR fro NSIS instalelr script changes.

**Comment by elelay** [comment]
@bovirus does the version in https://ci.appveyor.com/project/elelay/gpodder/builds/47833753/artifacts fix the issue for you? It seems good to me.

**Comment by bovirus** [comment]
Hi.
I will out for summer holiday until 05.09.
If you release it I will chech when I will be back.
Thanks.

**Comment by elelay** [comment]
Let's reopen until next release

**Comment by auouymous** [comment]
3.11.3 is now available.

**Comment by bovirus** [comment]
@auouymous 

Thanks.
