### ISSUE TITLE
Tagging extension broken on Manjaro 16.10

### ISSUE THREAD

**Issue by jstagge** [gpodder/gpodder#154]
Since updates over the past 2 months, the tagging extension does not appear to be working properly. For instance, after download, the genre is not changed to the default.

I have tried modifying the code, but cannot locate the problem.  Here are the versions I am using:
- gpodder 3.9.1
- mutagen 1.34.1-1
- python 3.5.2

I have tried downgrading my mutagen with no luck.  Any help would be greatly appreciated!

**Comment by thp** [comment]
Did you try this fix? https://github.com/gpodder/gpodder/commit/a87609ccdc1a5907c4f59e34927e861f13a7aa10

**Comment by jstagge** [comment]
I have tried this new file.

**Comment by thp** [comment]
Is there any way to reproduce this problem easily (step by step instructions, including feed, and settings and what to expect and what is actually happening)?

**Comment by elelay** [comment]
Closing issue because it's been blocked for too long.
