### ISSUE TITLE
Error getting podcast from link

### ISSUE THREAD

**Issue by bovirus** [gpodder/gpodder#1541]
@auouymous 

Getting podcast from link:

https://podcasts.apple.com/it/podcast/il-podcast-di-alessandro-barbero-lezioni-e/id1501956064

I got an error an the iterface has two strings untranslated

![image](https://github.com/gpodder/gpodder/assets/1262554/b9c53640-a149-4442-93c3-4e3bedcb606f)

What's about the error?

Please add relative untranslated string in language file.

Thanks.

**Comment by auouymous** [comment]
The message in the white area is a log message, and none of the log messages are translated. You are more likely to get a match when pasting the same english message as every other user into a search engine versus a translated message. And translated logs make it harder for developers to help users fix issues.

**Comment by bovirus** [comment]
@auouymous 

Ok. Thanks.
