### ISSUE TITLE
Patreon private podcast feeds unsubscribeable

### ISSUE THREAD

**Issue by srcdecay** [gpodder/gpodder#155]
I donate monthly to a couple podcasts on Patreon and they have a few exclusive episodes per month.  They all have a private RSS link for their exclusive episodes that looks like https://www.patreon.com/rss/campaign_name?auth={32 character hex string}

When I paste them into the subscribe by URL field in gPodder, nothing happens.  One (or both) of two things could be the issue: gPodder sees the URL as invalid or Patreon sees the User-agent string gPodder sends (gpodder.user_agent) and blocks it.  There's nothing in the log files to suggest what exactly is happening and gPodder doesn't pop any dialog windows up to report the error.

**Comment by thp** [comment]
Have you checked if changing the user agent in the code makes it work (to see if Patreon handles the user agent differently)? Also, can you test with `curl -I -L https://www.paetreon.com/rss/campaign_name?auth=...` (with the hex string filled in) if and where it redirects?

Also, what do you mean with "nothing happens" -- is there not even an error message? Maybe check the logs / terminal output for any unhandled errors.

**Comment by srcdecay** [comment]
Ran curl.  There are no redirects -- it seems the RSS is hosted on Patreon itself.  It does, however, set five cookies.  If you would like more detailed info on the cookies (if these could be causing a problem; i haven't gone through the gPodder code enough to see if it handles cookies or not), just ask and you shall receive.  

I haven't been able to change the user agent in the code just yet but I will when I have time.  I'm running the Windows version of gPodder so as far as I know there's no terminal output to be had.  I've gone through gPodder logs and there's no mentions of me trying to subscribe to that specific URL or any errors caused by it.  

By "nothing happens" I mean when I paste the URL into the Add Podcast by URL dialog and hit the Add button, the dialog closes and none of the behavior exhibited when I subscribe to other URLs is exhibited.  It seems like it just dumps it and doesn't log whatever issue it is encountering.

**Comment by thp** [comment]
Is there an easy way to get such a URL (either in private mail or by directing me to where I can obtain such a token) for testing locally here?

**Comment by elelay** [comment]
Here is the private feed for a private feed: `https://www.patreon.com/rss/ericgPodderTest?auth=369e9f75d5275ecd59535b3145ccef71`.
It is the creator's url but I don't think it changes anything (same url pattern as the OP).
And it works fine for me.
@srcdecay could you give it a try?
Thanks,

**Comment by vossad01** [comment]
The URL provided by @elelay also works for me.
