### ISSUE TITLE
saved filenames less useful now as hash or code

### ISSUE THREAD

**Issue by JimH44** [gpodder/gpodder#1554]
I find gPodder very good for downloading podcasts to my computer, from where I sync them to my phone so I can listen to them with Simple ABP. (I find Simple ABP great because it will keep playing even when another app is in the foreground, and when I pause it and restart, it will jump back 10 seconds and replay the last bit.) 

For some podcasts, the episodes come through with helpful names like
`ThePeterSchiffShowPodcast-FedMoneyMagiciansRunningOutofRabbitsEp917.mp3` or `Kate_Boyd_Science_and_the_Messy_Middle9zg5t.mp3`.

Others, however, come through with filenames like `5b.mp3` or `q0.mp3`, or names that seem to be based on hashes, such as `063c558ae2269acc4f708ed7abe0db60.mp3`.

These names are unhepful for me, because when my player gets to the end of a podcast and goes to the next file, the next in alphabetical order is played, and they are not played in historical order.

Is there (or could there be) an option to make the filenames more useful for playing in publication order? For example, gPodder used to download the files from `https://www.abc.net.au/listen/programs/allinthemind/` with names like `aim_20220731.mp3` (with the date in yyyymmdd format), but now they come through with names like `7a.mp3` or `mr.mp3`.

Perhaps this could be a _per-podcast_ option, rather than a global option.

Thanks for thinking about this, and for all your great work on gPodder.

(I am using gPodder version 3.11.2 on macos Ventura (13.5.2)).

**Comment by auouymous** [comment]
You can enable the `rename episodes after download` extension, and then use the edit config button to configure it, see https://gpodder.github.io/docs/extensions/renameafterdownload.html. It only applies to all podcasts so you will lose info such as `Ep917` in filenames.

**Comment by JimH44** [comment]
Thanks, @auouymous, I have enabled the extension and both options, and I'm looking forward to the next episode and how it arrives :-)

**Comment by JimH44** [comment]
Thanks again, @auouymous , that is working nicely for me now. I'll close the issue.
