### ISSUE TITLE
When setting the preferred Home and the Download directory in Arch Linux the ~ appears to not be parsed correctly

### ISSUE THREAD

**Issue by rsramkis** [gpodder/gpodder#1558]
Hi,

In Arch Linux I setup a ~/.config/environment.d/envvars.conf file to store the preferred HOME and Download Directories.

**Example of the failing envvars.conf file:**

```
GPODDER_HOME=~/.config/gPodder
GPODDER_DOWNLOAD_DIR=~/Music/Podcasts
```

After I re-login into  Gnome on Arch linux so the envvars.conf setting can be initialized I noticed  gPodder cannot find my preferred HOME or DOWNLOAD directories.

When I use the ~ this is what I see:

1. When I run gPodder from command line:

```
❯ gpodder
Storing data in /home/rsruser/~/.config/gPodder (GPODDER_HOME is set)
Storing downloads in ~/Music/Podcasts (GPODDER_DOWNLOAD_DIR is set)

```
![image](https://github.com/gpodder/gpodder/assets/14362317/2674296f-fe46-4de3-8814-d1378e989435)

2. You will see in the test users home directory a folder called "~" get created.

If I change the envvars.conf file to the explicit names of the home directory then gPodder can find the preferred HOME and DOWNLOAD directories.

**Example of the working envvars.conf file:**

```
GPODDER_HOME=/home/testuser/.config/gPodder
GPODDER_DOWNLOAD_DIR=/home/testuser/Music/Podcasts
```

**Environment Details:**
```
OS: EndeavourOS Linux x86_64 
Kernel: 6.5.3-zen1-1-zen
Shell: zsh 5.9
DE: GNOME 44.5
WM: Mutter 
```

***Note:** 
- gPodder is a packaged installed from the Arch Repository and not a Flatpak.

**Comment by auouymous** [comment]
This is partially a problem with 'envvars.conf' not expanding it like a shell would, because both `export GPODDER_HOME=~/foo` in something like .bashrc, and `GPODDER_HOME=~/foo gpodder` work fine. You might want to also open an issue with Arch or whatever project manages 'envvars.conf' so all programs that don't perform tilde expansion would just work.

However, it looks like Python's `os.path.expanduser()` will handle '~' and '~user', and it even works on Windows.

**Comment by rsramkis** [comment]
Hi @auouymous 

Thanks for looking into the issue. I found a work around of $HOME.

Example of the working envvars.conf file:
```
GPODDER_HOME=$HOME/.config/gPodder
GPODDER_DOWNLOAD_DIR=$HOME/Music/Podcasts
```

I wrote the below tech note. Any chance you can add it to your manual\help page for Arch Linux users?

# How to set the preferred Configuration and Download directory for gPodder Podcast Application

gPodder is a Podcast management application which has features like:

- Keep a listing of the Podcasts you have registered (with New and Listened statuses).
- Download offline copies of audio and video Podcasts.
- Download Youtube streams.

By default all configuration are stored in the ~\gPodder directory in Linux. The below steps allow you to use the follow variables to override the directories where:

- 'GPODDER_HOME' the configuration files are stored.
- 'GPODDER_DOWNLOAD_DIR' the audio\video files are stored when downloading a Podcast.

## Steps to custimize the data directories:
1. Launch Terminal.

2. Create your preferred directories to store the gPodder configuration and downloads:

```
mkdir ~/.config/gPodder
mkdir ~/Music/Podcasts
```

3. Create a local envvars.conf file to define the preferred configuration and download directory for gPodder

	a. Open envvars.conf in nano editor:

```
nano ~/.config/environment.d/envvars.conf
```


   b. Add the following local environment variable settings:


```
GPODDER_HOME=$HOME/.config/gPodder
GPODDER_DOWNLOAD_DIR=$HOME/Music/Podcasts
```

- $HOME will insert the Home Directory of the current signed in user.

4. To initialize the new settings in the envvars.conf file:

	a. Log out of your desktop session.
	b. Log into your desktops session.

**Source:**
https://gpodder.github.io/docs/user-manual.html#changing-the-downloads-folder-location-and-the-gpodder-home-folder
https://github.com/gpodder/gpodder/issues/1558
https://wiki.archlinux.org/title/environment_variables

**Comment by auouymous** [comment]
gPodder now expands the tilde in those two environment variables, and a new release should be out in a few days.

I also added your Arch link to https://gpodder.github.io/docs/user-manual.html#changing-the-downloads-folder-location-and-the-gpodder-home-folder. I don't see envvars.conf in the Ubuntu documentation. There is a section called "Session-wide changes on Ubuntu Linux" with "\~/.pam_environment" and "\~/.kde/env/setgpodder.sh" steps. I could add a similar looking section for Arch and envvars.conf. But is envvars.conf part of systemd, and does Arch support openrc instead of systemd? Would envvars.conf be available on any systemd distro?

**Comment by tpikonen** [comment]
> Would envvars.conf be available on any systemd distro?

At least it works in my Debian system (with systemd).

**Comment by rsramkis** [comment]
> gPodder now expands the tilde in those two environment variables, and a new release should be out in a few days.
> 
> I also added your Arch link to https://gpodder.github.io/docs/user-manual.html#changing-the-downloads-folder-location-and-the-gpodder-home-folder. I don't see envvars.conf in the Ubuntu documentation. There is a section called "Session-wide changes on Ubuntu Linux" with "~/.pam_environment" and "~/.kde/env/setgpodder.sh" steps. I could add a similar looking section for Arch and envvars.conf. But is envvars.conf part of systemd, and does Arch support openrc instead of systemd? Would envvars.conf be available on any systemd distro?

In the user manual I would just say the distributions the solution works with are Arch, EndeavourOS and Manjaro. 

Thank you for your support on this issue.
