### ISSUE TITLE
Menu/Extras/Extension is non-clickable (grey)

### ISSUE THREAD

**Issue by alexis26** [gpodder/gpodder#1568]
Hi,
[3.11.4-windows-portable version]

Extension in "Menu/Extras" is non-clickable
(I can't tell if it's from 3.11.4, I didn't notice it on 3.11.3...)

It works well by Menu/pref/extensions

**Comment by alexis26** [comment]
I've just realized that this problem doesn't exist with a clean blank version...
![blank](https://github.com/gpodder/gpodder/assets/3404404/f329ea41-4583-47d7-9807-7b8768039c91)

Maybe it's just because I've been manually updating with portable versions for a long time...
![manu](https://github.com/gpodder/gpodder/assets/3404404/6aac31ae-4e5e-4edd-9eff-05006b52ff0f)


(sorry if it is the case...)

**Comment by elelay** [comment]
Extensions is a "header".It's not meant to be clickable.
