### ISSUE TITLE
Question: what is the syntax for the smallest video size with best audio?

### ISSUE THREAD

**Issue by computerfreak105** [gpodder/gpodder#1576]
Hi, I've set the settings.json to download audio only for youtube videos:

 "youtube": {
    "preferred_fmt_id": 0,
    "preferred_fmt_ids": [
      "bestaudio"
    ],
    "preferred_hls_fmt_id": 0,
    "preferred_hls_fmt_ids": [
      91,
      92,
      93,
      94,
      95,
      96
    ]
  }
}

Large videos, maybe over 4 hours, seem to make GPodder download incomplete audio files. they can be played until maybe 4 hours and they are big, but not everything can be played afterwards.
so this is the reason why I wonder if I should switch to the very smallest video format and convert it to audio afterwards, because I'm blind and need only the audio.

what would the part in the settings.json file look like to have gpodder download the smallest video format with best audio quality? I don't understand the youtube fmt ids well enough to make a good decision how to put it into the settings.json file. So your help is very appreciated. Thank you :-)

**Comment by auouymous** [comment]
18 and 22 are the only formats that contain both audio and video, with 18 being the smallest. The audio in both is probably the same as the audio-only m4a 140 format. You would replace `bestaudio` including the double quotes around it with the number. Or try one of the webm format numbers in #1579.
