### ISSUE TITLE
Remember last selected channel

### ISSUE THREAD

**Issue by Snippet24816** [gpodder/gpodder#1578]
Hi,
I think currently on startup all the feeds are being shown, changing this may improve startup performance?
If yes I can think of two ideas:
1. Remember last selected feed on closing.
2. select last say x days for all feeds, if scrolled then load all (but no idea how feasible is so..)

**Comment by auouymous** [comment]
Every episode in the channel(s) is loaded into the episode list, even if not visible. It allows quick filtering via View menu or episode search entry. That can't be changed, and your second option can't be implemented.

I added numerous changes last year to improve the episode list update speed, and there probably isn't much else that can be done, other than loweing the episode limit or removing channels.

Remembering the selected channel should be doable. You could also disable the "all episodes" entry in the VIew menu and only enable it when you need to see or search all episodes.

**Comment by Snippet24816** [comment]
Thank you, I understand, well personally I was more interested in the perfomrnace side of things, rather than the use of remembering last channel.
