### ISSUE TITLE
Forcing .webm format for audio only

### ISSUE THREAD

**Issue by computerfreak105** [gpodder/gpodder#1579]
Hi all, I'd like to configure the settings.json file to download .webm files only because .m4a files are getting corrupted somehow. They take longer to open with mpc-hc media player and videos longer than 4-hours won't be downloaded completely. This doesn't seem to 
happen with .webm files, so this would be a working alternative to

#1576

and

#1573

The file format section for youtube looks like this:

 "youtube": {
    "preferred_fmt_id": 0,
    "preferred_fmt_ids": [
      "bestaudio"
    ],
    "preferred_hls_fmt_id": 0,
    "preferred_hls_fmt_ids": [
      91,
      92,
      93,
      94,
      95,
      96
    ]
  }
}

Right now I get mixed results: Most files are .m4a. But there are .webm files as well. I'd like to get 3.webm files only which don't have th problems I described above. I hope this is possible.

thanks for your help.

**Comment by auouymous** [comment]
Change `bestaudio` to 249, 250, or 251. Bigger number means better quality.

**Comment by computerfreak105** [comment]
I tried with this channel here, because I know that it has long live streams:

https://www.youtube.com/@ZackTrix

When I change bestaudio par example to 249 I get only 0 kb partial files.

"youtube": {
    "preferred_fmt_id": 0,
    "preferred_fmt_ids": [
      "249"
    ],
    "preferred_hls_fmt_id": 0,
    "preferred_hls_fmt_ids": [
      91,
      92,
      93,
      94,
      95,
      96
    ]
  }
}


And I get two main errors:

yt_dlp.utils.ExtractorError: [youtube] p5gsw8LBugg: Requested format is not available. Use --list-formats for a list of available formats

and 

During handling of the above exception, another exception occurred The latter is very strange because I have only one Gpodder running, I made sure of it by restarting my system.
I attach the log file.
[2023-11-03.log](https://github.com/gpodder/gpodder/files/13253074/2023-11-03.log)

**Comment by computerfreak105** [comment]
Ok, I think I declare myself as a retard soon. It still doesn’t work. Can you please write me the exact syntax? Here is what I did:

 

"youtube": {

    "preferred_fmt_id": 0,

    "preferred_fmt_ids": [

      249

    ],

    "preferred_hls_fmt_id": 0,

    "preferred_hls_fmt_ids": [

      91,

      92,

      93,

      94,

      95,

      96

    ]

  }

}

 

 

I tried several other combinations like 

    "preferred_fmt_ids": 249,

 

But nothing. Sometimes the settings.json file gets reverted back to the original. So, I guess I’m at the end of my inspiration and need the correct syntax.

Thanks for your patience!

 

 

 

Von: auouymous ***@***.***> 
Gesendet: Freitag, 3. November 2023 21:28
An: gpodder/gpodder ***@***.***>
Cc: computerfreak105 ***@***.***>; Author ***@***.***>
Betreff: Re: [gpodder/gpodder] Forcing .webm format for audio only (Issue #1579)

 

Remove the double quotes around 249.

**Comment by auouymous** [comment]
Ah, that channel only has the best quality audio, 251. If you want lowest quality use `249,250,251`. If you want best quality use `251,250,249`. That way it falls back to the other formats when the one you want the most isn't available. You could also add 140 on the end of that list to get m4a when none of the webm formats are available.

**Comment by computerfreak105** [comment]
Thank you so much! I took the highest .webm quality going downwards and 140 .m4a at the end, just in case. This works great now. The .webm format is playing long streams without problems, I just got a 6-hour video in full length. This is awesome!

 

 

Von: auouymous ***@***.***> 
Gesendet: Samstag, 4. November 2023 10:22
An: gpodder/gpodder ***@***.***>
Cc: computerfreak105 ***@***.***>; Author ***@***.***>
Betreff: Re: [gpodder/gpodder] Forcing .webm format for audio only (Issue #1579)

 

Ah, that channel only has the best quality audio, 251. If you want lowest quality use 249,250,251. If you want best quality use 251,250,249. That way it falls back to the other formats when the one you want the most isn't available. You could also add 140 on the end of that list to get m4a when none of the webm formats are available.
