### ISSUE TITLE
Windows portable doesn't start anymore since maybe one month ago

### ISSUE THREAD

**Issue by computerfreak105** [gpodder/gpodder#1593]
Hi, I'm under the impression that the portable windows version doesn't open anymore since maybe a month. I'm using 3.11.4.1093 right now, which still opens on my system. Today I thought I'd give it a try again with 1135, but still no luck. No log is created. Any idea or workaround?
Thanks.

**Comment by auouymous** [comment]
I broke the Windows build when adding Python 3.12 support, after 1093. I got it working again in 1118, but I am not able to test the binary, so it is possible that it doesn't work. @elelay Does it work for you?

**Comment by computerfreak105** [comment]
Oh man, but don’t beat yourself up over it. I’m amazed what you and the other developers here can do, so no hard feelings from my side.

For now I can say that on my Win 10 system the installer and the portable version 1144 don’t start yet. At least we still have a good working version 1093.

 

 

 

 

 

Von: auouymous ***@***.***> 
Gesendet: Freitag, 15. Dezember 2023 14:10
An: gpodder/gpodder ***@***.***>
Cc: computerfreak105 ***@***.***>; Author ***@***.***>
Betreff: Re: [gpodder/gpodder] Windows portable doesn't start anymore since maybe one month ago (Issue #1593)

 

I broke the Windows build when adding Python 3.12 support, after 1093. I got it working again in 1118, but I am not able to test the binary, so it is possible that it doesn't work. @elelay <https://github.com/elelay>  Does it work for you?

**Comment by elelay** [comment]
Latest master build (1131) is broken.

There is no gpodder subdir in site-packages (but gpodder_launch subdir is present, as well as a ~1.4MB gpodder-3.11.4-py3.11.egg).

The egg install causes an error: 
````
1702925576.747726 [gpodder.gtkui.app] ERROR: Cannot find gtk/menus.ui in ['C:\\gpodder-3.11.4-portable\\data\\share\\gpodder\\ui\\gtk', 'C:\\gpodder-3.11.4-portable\\data\\share\\gpodder\\ui'], exiting
````

**Comment by computerfreak105** [comment]
Hi, any chance that the installers for windows can be fixed again?

I’m still running 1093 and it’s working good so far. But the time will certainly come where a yt-dlp update will be necessary. Today I thought I’d check with 1161, but the portable installer isn’t running yet.

Thanks.

 

 

Von: Eric Le Lay ***@***.***> 
Gesendet: Montag, 18. Dezember 2023 19:59
An: gpodder/gpodder ***@***.***>
Cc: computerfreak105 ***@***.***>; Author ***@***.***>
Betreff: Re: [gpodder/gpodder] Windows portable doesn't start anymore since maybe one month ago (Issue #1593)

 

Latest master build (1131) is broken.

There is no gpodder subdir in site-packages (but gpodder_launch subdir is present, as well as a ~1.4MB gpodder-3.11.4-py3.11.egg).

The egg install causes an error:

1702925576.747726 [gpodder.gtkui.app] ERROR: Cannot find gtk/menus.ui in ['C:\\gpodder-3.11.4-portable\\data\\share\\gpodder\\ui\\gtk', 'C:\\gpodder-3.11.4-portable\\data\\share\\gpodder\\ui'], exiting

**Comment by masoudd** [comment]
The directory share/gpodder does not end up in the installers. At least for the portable version. All you need to do to make it work is to just copy the share/gpodder directory from the git repo to the data/share/ in the portable install dir. I'll investigate further for a fix

**Comment by computerfreak105** [comment]
Thank you, I appreciate that!

 

 

Von: Masoud Naservand ***@***.***> 
Gesendet: Dienstag, 6. Februar 2024 01:35
An: gpodder/gpodder ***@***.***>
Cc: computerfreak105 ***@***.***>; Author ***@***.***>
Betreff: Re: [gpodder/gpodder] Windows portable doesn't start anymore since maybe one month ago (Issue #1593)

 

The directory share/gpodder does not end up in the installers. At least for the portable version. All you need to do to make it work is to just copy the share/gpodder directory from the git repo to the data/share/ in the portable install dir. I'll investigate further for a fix

**Comment by computerfreak105** [comment]
Hi, I could get some sighted help and found the download button. It’s easy enough if you know where it’s hidden 😉

Thanks.

**Comment by auouymous** [comment]
The Windows build is now working again thanks to @masoudd.

https://ci.appveyor.com/project/elelay/gpodder/builds/50709611/artifacts
