### ISSUE TITLE
gtk3: `Gtk Status Icon` extension unavailable

### ISSUE THREAD

**Issue by adamvoss** [gpodder/gpodder#160]
The "Gtk Status Icon" under Extensions > Desktop integration does not work on the gtk3 branch.

    Extension cannot be activated

    'gi.repository.Gtk' object has no attribute 'status_icon_new_from_icon_name'

Initially reported as a comment on #150

**Comment by vossad01** [comment]
As @elelay pointed out, the underlying infrastructure in GNOME has been deprecated, meaning an alternative implementation and additional effort would be needed to provide this functionality.

> Gtk.StatusIcon is [deprecated](http://lazka.github.io/pgi-docs/#Gtk-3.0/classes/StatusIcon.html#Gtk.StatusIcon.new) since Gtk 3.14, but I don't see what to replace it with (notifications are not the same thing!).

Perhaps gPodder should just drop extension?

**Comment by adamvoss** [comment]
Closing as resolved, #321 gracefully drops the extension with the GTK3 release.  PRs welcome if someone wants to come up a new implementation.
