### ISSUE TITLE
How to DL One Ep At A Time + Rename The Mp3s?

### ISSUE THREAD

**Issue by GitAlexToTheGreek** [gpodder/gpodder#1600]
Hi there 👋

- Using both a fast pc and ISP connection, but attempting to download more than one episode at a time grinds the whole system to a halt...

⏩ How to adjust the settings to dl one at a time?

- Mp3s are downloaded/stored as "d2c7a93548217bc1fd46d646a3f0e0a0.mp3" for example..

⏩ Possible to adjust the settings to have them saved using the extensive title/date/artist details from the published episodes?

- It's unclear, from either the GP preferences, podcast settings or config, how to change the default download folder location?
(I do see how to open the designated location, but not change it.

⏩ How to do this?

Thanks in advance!

**Comment by tpikonen** [comment]
> How to adjust the settings to dl one at a time?

There is a 'Limit downloads to' checkbox in the Progress tab.

> Mp3s are downloaded/stored as "d2c7a93548217bc1fd46d646a3f0e0a0.mp3" for example..

There is an extension called 'Rename episodes after download' which may do what you want. See preferences.

> how to change the default download folder location?

Set the environment var `GPODDER_DOWNLOAD_DIR`. See the `README.md` file in this repository.

**Comment by auouymous** [comment]
I should have mentioned this was a duplicate of #1598.
