### ISSUE TITLE
^ is xor, not exponentiation

### ISSUE THREAD

**Issue by dcb314** [gpodder/gpodder#1611]
edora/pass54/20240310/libmygpo-qt.spec.out:/home/dcb38/rpmbuild/BUILD/libmygpo-qt-1.1.0/src/JsonCreator.cpp:35:37: warning: result of '2^64' is 66; did you mean exponentiation? [-Wxor-used-as-pow]
fedora/pass54/20240310/libmygpo-qt.spec.out:/home/dcb38/rpmbuild/BUILD/libmygpo-qt-1.1.0/src/EpisodeAction.cpp:29:37: warning: result of '2^64' is 66; did you mean exponentiation? [-Wxor-used-as-pow]
fedora/pass54/20240310/libmygpo-qt.spec.out:/home/dcb38/rpmbuild/BUILD/libmygpo-qt-1.1.0/src/JsonCreator.cpp:35:37: warning: result of '2^64' is 66; did you mean exponentiation? [-Wxor-used-as-pow]
fedora/pass54/20240310/libmygpo-qt.spec.out:/home/dcb38/rpmbuild/BUILD/libmygpo-qt-1.1.0/src/EpisodeAction.cpp:29:37: warning: result of '2^64' is 66; did you mean exponentiation? [-Wxor-used-as-pow]
fedora/pass54/20240310/libmygpo-qt.spec.out:/home/dcb38/rpmbuild/BUILD/libmygpo-qt-1.1.0/src/JsonCreator.cpp:35:37: warning: result of '2^64' is 66; did you mean exponentiation? [-Wxor-used-as-pow]
fedora/pass54/20240310/libmygpo-qt.spec.out:/home/dcb38/rpmbuild/BUILD/libmygpo-qt-1.1.0/src/EpisodeAction.cpp:29:37: warning: result of '2^64' is 66; did you mean exponentiation? [-Wxor-used-as-pow]
fedora/pass54/20240310/libmygpo-qt.spec.out:/home/dcb38/rpmbuild/BUILD/libmygpo-qt-1.1.0/src/JsonCreator.cpp:35:37: warning: result of '2^64' is 66; did you mean exponentiation? [-Wxor-used-as-pow]
fedora/pass54/20240310/libmygpo-qt.spec.out:/home/dcb38/rpmbuild/BUILD/libmygpo-qt-1.1.0/src/EpisodeAction.cpp:29:37: warning: result of '2^64' is 66; did you mean exponentiation? [-Wxor-used-as-pow]

**Comment by auouymous** [comment]
@elelay Can you transfer this to https://github.com/gpodder/libmygpo-qt ?
