### ISSUE TITLE
 gpo update && gpo download on flatpak

### ISSUE THREAD

**Issue by outusuke** [gpodder/gpodder#1621]
Is there any way to execute this command in the flatpak version, I used it on Windows to download my subscriptions with the task schedule, flatpak only gives me the option to subscribe

**Comment by tpikonen** [comment]
`flatpak run --command=gpo org.gpodder.gpodder update` works.

**Comment by outusuke** [comment]
interesting, I didn't know that, it works and I'm using it this way flatpak run --command=gpo org.gpodder.gpodder update && flatpak run --command=gpo org.gpodder.gpodder download
