### ISSUE TITLE
Sendto Folder sort

### ISSUE THREAD

**Issue by ndias** [gpodder/gpodder#1624]
I don't know if this is really an issue, or it's only my use case.

When I use the sendto option to save the podcasts to a folder, the save order used is from the first in the top of the window to the last in the bottom, in my use case I like to see, in the top of the windows the more recent podcasts and in the bottom the oldest.

But when I save to a folder I want the oldest to be the first to be sent, so I can sort in my player from the oldest to the newer everytime, doesn't matter the sort in the window at the moment.

So, when I was doing this https://github.com/gpodder/gpodder/pull/1620 I was think also to implement what I describe above.

Option 1: Sento Folder, sort everytime from older to new
Option 2: An option in config allow the user to select the option 1 or leave the Sendto Folder order as the order in the window.

**Comment by auouymous** [comment]
I'm not sure I understand the issue. Right clicking an episode and send to local folder opens a gtk dialog to select a folder to save into. Clicking the column headers changes the sorting, is that not saving, or am I in the wrong area?

**Comment by ndias** [comment]
Maybe I didn't explain my use case correctly, this case applies when several episodes are selected and then use the "Send to" -> "Local folder", obviously if it is only one episode that is sent to the folder  there are no issue.

Currently if I "sort" by "Release date" (New to Old) in the window of Episode list, when I save to the Local folder the order to be save is also  New to Old, that is bad if I want to sort in my player from old to new, obviously I can change the sort in the window before saving, but most of the times I forget and then is to late because I already deleted the episodes.

So,  my suggestion is the possibility to have an option to always when used the "Send to" -> "Local folder" save in the folder first the oldest until the newest, no matter what is the sort in the window

**Comment by auouymous** [comment]
Is it because the file timestamp doesn't transfer to the device, so the time when copied becomes the file on device timestamp?

**Comment by ndias** [comment]
Ok, I miserably fail to explain this, let me try in other way, lets say in gpodder I have 3 episodes
Episode     Released (Sort from New to Old)
----------   -----------
Episode 3   Today
Episode 2   Yesterday
Episode 1   Last Week

If I select all episodes and use the "Send to" -> Folder the first to be save to the folder is Episode3 then 2 and in the end the 1,  and in my File manager if I Sort (Old to New) I have this because of the timestamp of the files when they were saved to the disk, so where starts the problem, the sort New to Old is different from the same sort in gpodder.

Episode 3  (Released Today) 
Episode 2  (Released Yesterday)
Episode 1  (Released Last Week)

So lets says I move these episodes to my player (in my phone for example), all the timestamps are preserved and I will have this if I sort from Old to New once again in my player (I want to listen first the oldest episode)
Episode   
----------
Episode 3  (Released Today) 
Episode 2  (Released Yesterday)
Episode 1  (Released Last Week)

And here is my problem ... the oldest episode for the player is Episode 3 because of the date of the file, the date of the file is the date when the file was  written to the disk when used the "Send to" -> Folder in gpodder, Yes I know I can sort the column in gpodder from Old to New and do this before saving to the folder, but most of the times I forget about doing that.

**Comment by auouymous** [comment]
Sorry for the long delay getting back to this. Can you change the line at https://github.com/gpodder/gpodder/blob/master/src/gpodder/gtkui/main.py#L1982 from `copyfile` to `copy2` and tell me if that is what you want?

**Comment by ndias** [comment]
> Sorry for the long delay getting back to this. Can you change the line at https://github.com/gpodder/gpodder/blob/master/src/gpodder/gtkui/main.py#L1982 from `copyfile` to `copy2` and tell me if that is what you want?

No, this doesn't make anything for me, so here it is the code, for what I want, and if this  should be an option in config

*** 1997,2002 ****
--- 1997,2003 ----
          remaining = len(episodes)
          dialog = gPodderExportToLocalFolder(self.main_window,
                                              _config=self.config)
+         episodes.sort(key=lambda episode: episode.published)
          for episode in episodes:
              remaining -= 1
              if episode.was_downloaded(and_exists=True):

**Comment by auouymous** [comment]
Do you see any reason to make it optional? I would assume ordering oldest to newest is something everyone would want, and devices could play in either order with properly ordered timestamps. Unless some devices can't perform any kind of timestamp or duration reordering, and users depend on gpodder's ordering. Perhaps this could be the default and maybe have an option to disable it?

Would you like to make a PR?

**Comment by ndias** [comment]
No, I don't see a case for optional.
PR created.
