### ISSUE TITLE
GPO & Cron Job

### ISSUE THREAD

**Issue by vexillia** [gpodder/gpodder#1629]
I have specific locations set for :
- GPODDER_HOME=/home/vexillia/.gpodder/
- GPODDER_DOWNLOAD_DIR=/home/vexillia/Downloads/Podcasts/

And a simple script that I wish to automate with cron:

#!/bin/bash
gpo -q update
gpo -q download
sleep 5
exit

My problem is that cron does not have access to the set locations.  The script works when run as a user but not by cron.  I know the scripts has been run (by cron) as it creates a default (?) folder:

/home/vexillia/gPodder

(which I don't want) but does nothing else.

How do I get gpo to use the set locations from the .pam_environment file?

Thanks.

**Comment by auouymous** [comment]
I don't know about `.pam_environment` but you can add the environment variables to the top of your cron file.

crontab -e
```
GPODDER_HOME=/home/vexillia/.gpodder/
GPODDER_DOWNLOAD_DIR=/home/vexillia/Downloads/Podcasts/

00 0 * * * gpo-script.sh
```

**Comment by vexillia** [comment]
Thanks.  I switched to [podget](https://github.com/dvehrs/podget) for the cron job..
