### ISSUE TITLE
Send multiple episodes to the same folder

### ISSUE THREAD

**Issue by vossad01** [gpodder/gpodder#163]
If you select multiple episodes and choose "Send to -> Local folder", the user is prompted to specify the name and location individually for each episode.  This is slow and tedious if the user wants to put all episodes into the same folder and use the default name.

The desired behavior would be to choose only a folder when multiple episodes are selected.  All selected episodes would then be saved to that folder using the default name gPodder suggests for the episode.

Would changing the default behavior when multiple episodes are selected be accepted or is an alternate menu item needed?

**Comment by thp** [comment]
I'd be happy if when multiple episodes are selected, only a folder chooser is shown, or - to make things easier and more consistent - that only a folder chooser is shown, and the filename is always auto-generated from the pattern defined in the config.
