### ISSUE TITLE
YouTube downloads fail with HTTP Error 403: 403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by BobViolence** [gpodder/gpodder#1636]
Started a few days ago. All of my YouTube subscriptions are failing with:

HTTP Error 403: 403 Client Error: Forbidden for url: https:// ... (snipped)

GPodder is version 3.11.4 on Windows 11.

Subscriptions from non-YouTube RSS feeds work fine.

I've never fully understood the difference between youtube-dl and yt-dlp, so without some guidance, I'm not sure which one is being used or what version I'm on.

**Comment by auouymous** [comment]
See #1634.
