### ISSUE TITLE
ffmpeg not found in PATH on Mac

### ISSUE THREAD

**Issue by auouymous** [gpodder/gpodder#1638]
`shutil.which()` and `util.find_command()` are not finding ffmpeg in PATH on Mac.

Continued from https://github.com/gpodder/gpodder/issues/1634#issuecomment-2185044776

@RodRCode Can you try writing `os.environ.get('PATH', None)` to the trace file? Is it empty or does it contain some paths?

**Comment by RodRCode** [comment]
Here is what I get for the results when I added that to the trace file:

```
shutil value None
util.find value None
subprocess 
hardcoded value /opt/homebrew/bin/ffmpeg
Path resuls: /usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by RodRCode** [comment]
@auouymous When I do it from outside gpodder, this is the result:

```
Path resuls: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/opt/homebrew/bin:/opt/homebrew/sbin
hardcoded value /opt/homebrew/bin/ffmpeg
```

**Comment by auouymous** [comment]
@RodRCode Can you test #1649 and let me know if it fixes the issue after setting `path.alternate` and restarting gpodder?
