### ISSUE TITLE
Can't activate my account on gpodder.net

### ISSUE THREAD

**Issue by aotvio** [gpodder/gpodder#1639]
I use AntennaPod with my gPodder profile since 2022, and recently (more specifically, June 26, 2024) when I try to log in my account on gpodder.net, although my credentials are correct, (as of the time of my writing, June 28, 2024) the website shows a message to activate the profile. I also can't reset my password because it can't do that before activating it.

![Captura de tela_28-6-2024_104349_gpodder net](https://github.com/gpodder/gpodder/assets/86308005/82fbd304-126d-46ab-880c-78f5d7532d0c)

Now, when the activation e-mail comes to my inbox, the link is always invalid, because the messages come with this URL:
"https://gpodder.net/activate/None". No matter how many times I try to click, it never works, and that's why I can't access the account at all to link with the podcast app. If someone could write why this happened or try to fix it, I'd appreciate it a lot. I also couldn't find any other contact information so I am leaving this here if someone is also going through the same issue.

Just one more thing: Google OAuth also doesn't work either. I tried and it gives an error.

![Captura de tela_28-6-2024_104450_accounts google com](https://github.com/gpodder/gpodder/assets/86308005/0017a13f-9a3e-4e9f-9c85-370fca79b045)

![Captura de tela_28-6-2024_10467_gpodder net](https://github.com/gpodder/gpodder/assets/86308005/4af4fb24-fd39-4c54-80f2-f75fd07e6837)

If the dev team needs to reach me, my username is @ocaradospark on Telegram. Thanks for helping and I hope it gets fixed soon.

**Comment by auouymous** [comment]
The gpodder.net service is over at https://github.com/gpodder/mygpo/issues, and is unmaintained and likely to be removed in the future due to years of problems.
