### ISSUE TITLE
gPodder crashes when syncing after having been left open for over two days

### ISSUE THREAD

**Issue by Paculino** [gpodder/gpodder#1640]
Hello, this is just more properly reporting what I sent in the irc channel. I tried to sync episodes to device (with the 1 ms sleep modification air gave in the irc), but it just crashed. I've noticed it before the modification, but never thought much of it since it is not unexpected for programs to crash after being left open for days.

I am running Devuan 5 (based on Debian 12 stable) with gpodder 3.11.1-1, libgpod-common 0.8.3-17+b1, libgpod4:amd64 0.8.3-17+b1, python3-mygpoclient 1.9-1, and yt-dlp 2024.05.27-1~bpo12+1. My python version is 3.11.2-6+deb12u2 and gir1.2-gtk-3.0:amd64 is version 3.24.38-2~deb12u1

Closing the popup with 

> &#x27;GioSyncTask&#x27; object has no attribute
> &#x27;custom_downloader&#x27;

and gPodder itself (either with killall or manually; manually is slower) allows starting it up again with no issues at all, which is why it is not a big issue to me. It doesn't even crash every time it has been left open for a couple days and is synced.

**Comment by auouymous** [comment]
That bug was fixed in 3.11.2. You will need to upgrade to a newer version, or manually apply https://github.com/gpodder/gpodder/commit/3d690633eeed914e7a1bb2b44c35dc959f41df3e.
