### ISSUE TITLE
Gpodder only showing 200 episodes, changing episode limit didn't work

### ISSUE THREAD

**Issue by swilly97** [gpodder/gpodder#1641]
Hi, I have a few podcasts that have far more then 200 episodes, but I'm only able to view and download the most recent 200. I've already tried changing the episode limit from 200 all the way up to 5000, but it hasn't changed anything.

**Comment by auouymous** [comment]
What is the feed URL?

See also #907 and #835.

**Comment by swilly97** [comment]
After reading #907, I deleted and readded the RSS feed and its showing all of the episodes now. Still a bug, but a solvable one now.

**Comment by auouymous** [comment]
> Still a bug, but a solvable one now.

It is only solvable if we can reproduce it. Are you able to supply any details, such as feed URL, and how many downloaded, deleted, played, unplayed episodes you had in the feed?
