### ISSUE TITLE
How to change the Gpodder Download folder on mac

### ISSUE THREAD

**Issue by computerfreak105** [gpodder/gpodder#1644]
Hi

I'd like to change the download folder of Gpodder on my mac. All downloads should go to a shared directory on my Synology DS214Play NAS.
 The path which I can copy with finder is: 

/Volumes/SynologyPool/GPodderDownloads

I have problems with this destination path. I followed the manuals description with both approaches, the one with symbolic links and the one with setting the environment variables. But both don't work because I'm probably doing something wrong.

I'd like to set the paths in launcher.py. There is an instruction how to do it inside the file:

# To override gPodder home and/or download directory:
# 1. uncomment (remove the pound sign and space) at the beginning of the relevant line
# 2. replace ~/gPodderData or ~/gPodderDownloads with the path you want for your gPodder home
#    (you can move the original folder in the Finder first,
#     then drag and drop to the launcher.py in TextEdit to ensure the correct path is set)
# uncomment the following line to override gPodder home
# os.environ['GPODDER_HOME'] = expanduser('~/gPodderData')
# uncomment the following line to override gPodder download directory
# os.environ['GPODDER_DOWNLOAD_DIR'] = expanduser('~/gPodderDownloads')

So I made a copy of the last line in order to have it still available and wrote right below:

os.environ['GPODDER_DOWNLOAD_DIR'] = expanduser('/Volumes/SynologyPool/GPodderDownloads')

I even put the ~ before the path. But after I changed the line GPodder isn't starting anymore until I remove the line again.

Why isn't this working? Thanks for your help!

**Comment by computerfreak105** [comment]
Thanks for your instructions. No luck yet

 

So my line is:

os.environ['GPODDER_DOWNLOAD_DIR'] = expanduser('/Volumes/SynologyPool/GPodderDownloads')

 

 

and the debug information is:

 

----------------------------------------

Last login: Sun Jul 21 19:07:13 on ttys000

***@***.*** ~ % /Applications/gPodder.app/Contents/MacOS/gpodder -v

str=/Applications/gPodder.app/Contents/Resources

filename=

ARGV[0]=/Applications/gPodder.app/Contents/MacOS/gpodder

System Path:

/Applications/gPodder.app/Contents/Resources/lib/python3.11

/Applications/gPodder.app/Contents/Resources/lib/python3.11/plat-darwin

/Applications/gPodder.app/Contents/Resources/lib/python3.11/lib-dynload

/Applications/gPodder.app/Contents/Resources/lib/python3.11/site-packages

/Applications/gPodder.app/Contents/Resources

Traceback (most recent call last):

  File "", line 120, in <module>

NameError: name 'expanduser' is not defined

Run Simple File returned -1

***@***.*** ~ % 

----------------------------------------

 

What does this mean? Thanks for your patience.

 

 

 

 

 

 

Von: Eric Le Lay ***@***.***> 
Gesendet: Montag, 22. Juli 2024 19:27
An: gpodder/gpodder ***@***.***>
Cc: computerfreak105 ***@***.***>; Author ***@***.***>
Betreff: Re: [gpodder/gpodder] How to change the Gpodder Download folder on mac (Issue #1644)

 

The ~ before the path will be expanded to /Users/YOUR_USER so don't put it there.

Ensure that you removed the hash sign and space, so the line only consists in

os.environ['GPODDER_DOWNLOAD_DIR'] = expanduser('/Volumes/SynologyPool/GPodderDownloads')

Save launcher.py as you did before.

Follow the 

 <https://gpodder.github.io/docs/macos.html#debugging-gpodder-on-macos> debug instructions to run gPodder from the Terminal application, so you can tell us what error message appears. It could be for instance that it is not allowed to access /Volumes/SynologyPool...

**Comment by elelay** [comment]
Please remove the expanduser(), since you don't need it anyway:

````
os.environ['GPODDER_DOWNLOAD_DIR'] = '/Volumes/SynologyPool/GPodderDownloads'
````

**Comment by computerfreak105** [comment]
Yay, it’s working! Thank you very much for your help!

 

 

 

Von: Eric Le Lay ***@***.***> 
Gesendet: Montag, 22. Juli 2024 22:38
An: gpodder/gpodder ***@***.***>
Cc: computerfreak105 ***@***.***>; Author ***@***.***>
Betreff: Re: [gpodder/gpodder] How to change the Gpodder Download folder on mac (Issue #1644)

 

Please remove the expanduser(), since you don't need it anyway:

os.environ['GPODDER_DOWNLOAD_DIR'] = '/Volumes/SynologyPool/GPodderDownloads'

**Comment by elelay** [comment]
Thank you for the report. It appears the instructions have been broken for 2 years...

**Comment by auouymous** [comment]
I fixed the comments with https://github.com/gpodder/gpodder/commit/a965cfa2328c65db409904d4649efbae177c0edb so others won't run into this issue.

**Comment by elelay** [comment]
Thanks
