### ISSUE TITLE
[Windows] gpodder fails to name downloaded file from soundcloud feed

### ISSUE THREAD

**Issue by kju** [gpodder/gpodder#1659]
Creates `SoundCloud Download` (no extension) - instead of "filename.ext" / "name.mp3"

Subscripting works seemingly just fine and metadata is also shown correctly within gpodder.
Nothing shown in gpodder log either.

Feed: https://feeds.soundcloud.com/users/soundcloud:users:479331222/sounds.rss

Website: https://sicherheitspod.de/abo/

Might be due to soundcloud tho:
- #1167
- #1177

**Comment by auouymous** [comment]
See #1237.
