### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by tpikonen** [gpodder/gpodder#1660]
Last gPodder release was almost a year ago, and a good number of features have been added to `master`. Also the flatpak packages are now (after Gnome 47 release) two versions behind on their platform dependency.

I'm not too familiar with what's cooking in the pull requests at the moment, but it would be nice to have a new release soon.

**Comment by auouymous** [comment]
#1657 is required to fix the Windows build. #1652 is probably required to fix syncing via gpo on Mac. I can't do much of anything right now due to health issues.

**Comment by Snippet24816** [comment]
> #1657 is required to fix the Windows build. #1652 is probably required to fix syncing via gpo on Mac. I can't do much of anything right now due to health issues.

Take care, I hope you recover soon :)

**Comment by elelay** [comment]
3.11.5 is out
