### ISSUE TITLE
Fix depcheck.py to reduce install size on Windows

### ISSUE THREAD

**Issue by auouymous** [gpodder/gpodder#1662]
The depcheck.py step was commented out in #1657 due to it failing. The build works without it and it is more important to have a working build to get a release out. However, it might be responsible for removing unused DLLs and the installation size might now require more space, see https://github.com/gpodder/gpodder/pull/1657#issuecomment-2385038001.

```
Traceback (most recent call last):                                                               
  File "C:/projects/gpodder/tools/win_installer/misc/depcheck.py", line 27                       
    repo.require(namespace, version, 0)                                                          
        Typelib file for namespace 'GIRepository', version '3.0' not found (0)                   
```

Using the following code snippets before calling depcheck.py did not work.

```
 mkdir -p lib/girepository-1.0/                                                     
 cp /mingw64/lib/girepository-1.0/GIRepository-2.0.typelib lib/girepository-1.0/    
```

```
export GI_TYPELIB_PATH="${MINGW_ROOT}"/lib/girepository-1.0                          
```

```
export GI_TYPELIB_PATH=/usr/local/lib/girepository-1.0                               
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH                               
```

**Comment by masoudd** [comment]
Seems like there is two parallel girepository. One is [gobject-introspection](https://gitlab.gnome.org/GNOME/gobject-introspection) and the other (seemingly newer one) is included in [glib](https://gitlab.gnome.org/GNOME/glib/-/tree/main/girepository).

|  | gobject-introspection | glib girepository |
|--------|--------|--------|
| latest version on msys2 mingw32 | 1.82 | 2.82 |
| dll file provided in /mingw32/bin/ | libgirepository-1.0-1.dll | libgirepository-2.0-0.dll |
| typelib file in /mingw32/lib/girepository-1.0/ | GIRepository-2.0.typelib | GIRepository-3.0.typelib |

I found [https://docs.gtk.org/girepository/migrating-gi.html](https://docs.gtk.org/girepository/migrating-gi.html)
> As part of this move, the API version has been bumped from 1.0 to 2.0, and some fairly straightforward API changes have been made. Note that the GIR version was previously 2.0, and is now 3.0 — so the new version of libgirepository uses girepository-2.0.pc and GIRepository-3.0.typelib.

Which suggests that this situation is temporary and the old one is supposed to be faded out.

Unfortunately, the python GTK binding that we use ([pygobject](https://gitlab.gnome.org/GNOME/pygobject/)) which is providing the `gi` module we use in python, is still using the old one (gobject-introspection).

Upon further investigation I found [this commit](https://gitlab.gnome.org/GNOME/gobject-introspection/-/commit/171f1804dc76dfcc2857e809d49a2290b15612c4)

> A few applications such as gnome-music load the GIRepository typelib
and use it to adjust their search paths.
GLib 2.79.x now provides libgirepository-2.0.so.0 (GIRepository-3.0),
but each OS distribution is likely to have a transitional period during
which GLib's libgirepository-2.0.so.0 has become available, but bindings
like PyGI and gjs are still linked to gobject-introspection's
libgirepository-1.0.so.1 (GIRepository-2.0).
During this transitional period, interpreted languages that load the
GIRepository namespace could get the "wrong" version, which will result
in adjusting a search path that will not actually affect the language
binding's typelib lookup, and could also lead to symbol and type-system
conflicts.
We can avoid this collision by making GLib's GIRepository library refuse
to load versions of the GIRepository typelib that are not 3.0, and
similarly making gobject-introspection's GIRepository library refuse to
load typelib versions that are not 2.0. A relatively neat way to achieve
that is to make each version behave as if the other one doesn't exist.

And I believe that is why girepository pretends there is no `GIRepository-3.0.typelib` when in reality it is there.
