### ISSUE TITLE
gPodder fails to upload and sync subscriptions to gpodder.net

### ISSUE THREAD

**Issue by ushuc** [gpodder/gpodder#1663]
gPodder fails to upload and sync subscriptions to gpodder.net. I have entered my login credentials correctly but every time this error message appears. Do I need to install additional plugins or change some expert setting to make it work or is it really a bug?

![grafik](https://github.com/user-attachments/assets/4ba4bac4-a534-4bd2-b70d-376c970d5b92)

**Comment by auouymous** [comment]
gpodder.net is over at https://github.com/gpodder/mygpo/issues and has been having problems for several years.

**Comment by auouymous** [comment]
Can you provide the log file after producing this error?

**Comment by auouymous** [comment]
Also, after restarting gpodder, is that checkbox unchecked? If so, you will need to click it before trying to reproduce.

**Comment by auouymous** [comment]
```
      "uid": ""
```

It will work if you edit that file and put something in those empty quotes.

I will figure out why it doesn't set the host and make sure it always puts something there. Thanks for your help.
