### ISSUE TITLE
Most likely yt-dlp related: preferred video quality not honored?

### ISSUE THREAD

**Issue by Snippet24816** [gpodder/gpodder#1667]
Hi this is just to you know about it, and I hope it is something fixed in yt-dlp since theres an update about 2 days ago

**Comment by auouymous** [comment]
Do you mean getting a tiny video when you asked for a larger one? If so, Youtube keeps "fixing" their players to prevent yt-dlp from using them to download. Without a working player, it falls back to format 18 which is 640x480. The recent release changed the player again, but it will likely keep breaking, and eventually we could be stuck with only tiny videos.

**Comment by Snippet24816** [comment]
Yep that exactly,  I see :/
