### ISSUE TITLE
Error on startup with latest installer version on w7

### ISSUE THREAD

**Issue by Snippet24816** [gpodder/gpodder#1688]
Hi, I'm getting this: The procedure entry point CopyFile2 could not be located in the dynamic link library KERNEL32.dll.
Most likely is related to Windows 7 or some service, in case is useful to someone else, this appears to be the solution 
https://www.youtube.com/watch?v=uZddkN0iFcE
I will try and report back

**Comment by masoudd** [comment]
I found https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-copyfile2 says minimum is windows 8. gpodder uses NSIS to make the installer and [here they claim it supports all windows versions](https://nsis.sourceforge.io/Features).

**Comment by Snippet24816** [comment]
Ok didn't work out as it seems CopyFile2  is available from W8 onwards, this time no workaround seems to be possible so I'm closing this thread.

**Comment by Snippet24816** [comment]
I will reopen the thread just in case...

**Comment by masoudd** [comment]
I'm not sure about which version of windows gpodder wants to support, but I think windows 7 should still be supported if at all possible. I'm still not sure why the installer uses things that are win8 and above. I'll try to find out if we can avoid it

**Comment by Snippet24816** [comment]
Thank you

**Comment by elelay** [comment]
Hi @Snippet24816 @masoudd,
to clarify: the installer runs fine on windows 7 (tried it myself), but gpodder.exe or python.exe use CopyFile2.
We use python.exe from msysgit.
The portable version is also broken.

And gpodder 3.11.1 is the last version working with win7.
gpodder 3.11.2 to 3.11.4 complain of missing api-ms-win-core-path-l1-1-0.dll see #1540

**Comment by elelay** [comment]
Closing now because it is an "issue" with msys2 dropping windows 7 support, that we can't work around.

**Comment by Snippet24816** [comment]
Hi that can be worked around see here please: https://github.com/gpodder/gpodder/issues/1540#issuecomment-2221780643
What I cant workaround is the use CopyFile2 instead of CopyEx. I had been using 3.11.4 happily with that.

**Comment by elelay** [comment]
Indeed, we can't work around CopyFile2.

**Comment by Snippet24816** [comment]
May I ask for the latest build before using copyFile2, I know I been using some build in the 11.4 but I can't find it :(

**Comment by auouymous** [comment]
1299 (https://ci.appveyor.com/project/elelay/gpodder/builds/51044467/artifacts) is the oldest appveyor build that still has artifacts, does it work?

**Comment by auouymous** [comment]
@Snippet24816 Are you able to install virtualbox, qemu or something else that would let you run linux inside win7?

**Comment by Snippet24816** [comment]
> 1299 (https://ci.appveyor.com/project/elelay/gpodder/builds/51044467/artifacts) is the oldest appveyor build that still has artifacts, does it work?

Thank you, hum I'm afraid not :/ must had be an earlier build v11.4 I guess that I used did a little search and I maybe it was this one (but yea those artifacts expired :/) https://ci.appveyor.com/project/elelay/gpodder/builds/50144680/artifacts

> @Snippet24816 Are you able to install virtualbox, qemu or something else that would let you run linux inside win7?

Since I'm struggling monetary speaking getting a new computer is not feasible, I'm considering or VirtualBox  or trying W11 with Rufus without the official restrictions but no idea if the later will work properly. 

Thank you for suggesting Quemu looks a very performant virtualization will try it out in the coming days since been wanting also to run https://github.com/ArchiveTeam/grab-site

**Comment by Snippet24816** [comment]
Update: Found a portable installation of the W7 working artifact :-)

**Comment by therentabrain** [comment]
@Snippet24816 I am in the same boat, can you share whatever you made work?  Thanks!

**Comment by Snippet24816** [comment]
@therentabrain 
Sure, I'm using an older gpodder-3.11.4portable.exe let me know if you want me to upload it? else I can .zip the portable folder I have without the config data folder.

@auouymous 
If is okey with I can upload it, question: just where do you think is best to do it?

**Comment by Snippet24816** [comment]
> [@Snippet24816](https://github.com/Snippet24816) That release download should work after installing api-ms-win-core-path-l1-1-0.dll, right?

Yes oj that is from an older artifcat then the pointed here If I recap correctly.. https://github.com/gpodder/gpodder/releases/tag/3.11.4 

> Where to upload it... I wonder if it's relevant to upload it somewhere here on github

I cant seem to upload an .exe in this thread though..

> You would need to manually update yt-dlp if that is something you use.

May I ask how that was done, I would like too unless it requires compiling or super advanced stuff..

**Comment by auouymous** [comment]
@Snippet24816 Ah, so you have an artifact made after 3.11.4, before they stopped working. I have never been able to upload anything to github, not even patches.


> > You would need to manually update yt-dlp if that is something you use.
> May I ask how that was done

It is technically possible because the Mac and Windows builds ship with pip. However, no one has figured out how yet, or they haven't shared that with us to post on gpodder.org or add a button to gpodder client that would easily do the update.

**Comment by masoudd** [comment]
> [@Snippet24816](https://github.com/Snippet24816) Ah, so you have an artifact made after 3.11.4, before they stopped working. I have never been able to upload anything to github, not even patches.
> 
> > > You would need to manually update yt-dlp if that is something you use.
> > > May I ask how that was done
> 
> It is technically possible because the Mac and Windows builds ship with pip. However, no one has figured out how yet, or they haven't shared that with us to post on gpodder.org or add a button to gpodder client that would easily do the update.

I tested on windows 10 portable versions 3.11.4 and 3.11.5:

- go to `gpodder-3.11.5-portable/data/bin` (or `3.11.4` or the version you have installed)
- in the address bar type `cmd` and hit enter to open cmd in that directory.
- `python.exe -m pip install --upgrade distlib`
- `python.exe -m pip install --upgrade yt-dlp`

We need to reinstall the `distlib` because the file `t32.exe` is not copied in `gpodder-3.11.5-portable\data\lib\python3.12\site-packages\distlib` by the installer maker in the msys environment. We could potentially alter the installer maker steps to have that file and skip the distlib install step from above.

**Comment by Snippet24816** [comment]
> It is technically possible because the Mac and Windows builds ship with pip. However, no one has figured out how yet, or they haven't shared that with us to post on gpodder.org or add a button to gpodder client that would easily do the update.

I see.

> > [@Snippet24816](https://github.com/Snippet24816) Ah, so you have an artifact made after 3.11.4, before they stopped working. I have never been able to upload anything to github, not even patches.
> > > > You would need to manually update yt-dlp if that is something you use.
> > > > May I ask how that was done
> > 
> > 
> > It is technically possible because the Mac and Windows builds ship with pip. However, no one has figured out how yet, or they haven't shared that with us to post on gpodder.org or add a button to gpodder client that would easily do the update.
> 
> I tested on windows 10 portable versions 3.11.4 and 3.11.5:
> 
>     * go to `gpodder-3.11.5-portable/data/bin` (or `3.11.4` or the version you have installed)
> 
>     * in the address bar type `cmd` and hit enter to open cmd in that directory.
> 
>     * `python.exe -m pip install --upgrade distlib`
> 
>     * `python.exe -m pip install --upgrade yt-dlp`
> 
> 
> We need to reinstall the `distlib` because the file `t32.exe` is not copied in `gpodder-3.11.5-portable\data\lib\python3.12\site-packages\distlib` by the installer maker in the msys environment. We could potentially alter the installer maker steps to have that file and skip the distlib install step from above.

Excellent and thank you will try and report back in some days because im on a trip.

**Comment by auouymous** [comment]
> python.exe -m pip install --upgrade yt-dlp

@masoudd Thank you for looking into that. We can make sure that file gets copied and then add an update button in the youtube-dl extension preferences to run that command on Windows, and a similar command on Mac. It could use a progress dialog and upon success show a message to restart gpodder. If it fails, the output could be displayed in a message dialog. Does the command have a gui? If not, does `python.exe -m pip install --upgrade yt-dlp --progress-bar off` get rid of the progress bar? We wouldn't want any ANSI sequences in the output.

**Comment by auouymous** [comment]
I was originally thinking of a worthless progress bar like when subscribing to a channel. Simply opening a progress dialog, running the pip command in a subprocess and waiting for it to finish. Pressing cancel would terminate pip, and hopefully not cause any damage, or we disable the cancel button.

That `--progress-bar=raw` option would allow it to show actual progress, if we want to put a little more work into parsing its output and handling unknown output.

**Comment by Snippet24816** [comment]
Ok finally got back and tested on a sandbox: worked perfectly from my user standpoint.
@masoudd thank you so so much for looking into this ❤️

**Comment by Snippet24816** [comment]
Would it be good idea to check for updates automatically on startup maybe?

**Comment by auouymous** [comment]
> Would it be good idea to check for updates automatically on startup maybe?

Maybe. Gpodder checks gpodder.org every 5 days and opens a dialog if an update is available. The youtube-dl extension could perform a similar check when it loads.

**Comment by Snippet24816** [comment]
> > Would it be good idea to check for updates automatically on startup maybe?
> 
> Maybe. Gpodder checks gpodder.org every 5 days and opens a dialog if an update is available. The youtube-dl extension could perform a similar check when it loads.

Sounds good 👍
