### ISSUE TITLE
Installation Blocked:  Marked as Dangerous

### ISSUE THREAD

**Issue by sgelfond** [gpodder/gpodder#1692]
Both Windows Defender Trend Micro mark in the installation as dangerous and blocks it.
![image](https://github.com/user-attachments/assets/c9a0a238-0050-4853-8176-8c1b5f025aab)
![image](https://github.com/user-attachments/assets/8d30039b-bd13-41ae-bd34-35763feba804)

**Comment by elelay** [comment]
Both screens just tell you that we didn't pay the fee to get a signing certificate from microsoft.
Please use your own judgment on how you would like to proceed. 
Thanks,
