### ISSUE TITLE
Youtube video descriptions are not displayed

### ISSUE THREAD

**Issue by jesuspi6127** [gpodder/gpodder#175]
Running 3.9.1 Youtube video descriptions are not displayed. In older versions, e.g. 3.8.x, the issue could be resolved by installing the package libwebkitgtk (depending on the distribution, in my case OpenSUSE), however now the problem remains and any youtube channel only displays the title of the video and the channel name. The RSS feed associated with the channels follow the format:  https://www.youtube.com/feeds/videos.xml?channel_id=  followed by the alphanumeric sequence associated with the channel in the API (e.g. UCzH3iADRIq1IJlIXjfNgTpA for the RoosterTeeth channel.)

**Comment by thp** [comment]
Fixed in podcastparser Git here:
https://github.com/gpodder/podcastparser/commit/771009d58bea0d5da83f7f9284b8445061968402

This fix will be part of the next release.
