### ISSUE TITLE
Allow user to configure API key for Sound Cloud

### ISSUE THREAD

**Issue by f03el** [gpodder/gpodder#179]
Sometimes when trying to play or download an episode, nothing happens (at least in the Sailfish OS version). If running from the terminal I see that Sound Cloud complains about "Too many requests". The API key doesn't seem to allow enough requests. Would it be possible to ask them for a higher limit?

**Comment by thp** [comment]
Wonder if it would help if the users have to enter their own API keys similar to what we do with YouTube?

**Comment by elelay** [comment]
Soundcloud doesn't let one register apps anymore.
