### ISSUE TITLE
Pagination in Soundcloud

### ISSUE THREAD

**Issue by mprangenberg** [gpodder/gpodder#180]
gPodder currently only supports the Standard-API Limit of 50 tracks. Could you maybe raise that to the maximum of 200? I follow some podcasts on there, that are already at over 150 tracks. Even better would be to use pagination to always get all tracks: ttps://developers.soundcloud.com/docs/api/guide#pagination
Sadly i can't do it myself as i am a total noob to Python right now.
Cheers.

**Comment by thp** [comment]
Pull request merged, thanks a lot!
