### ISSUE TITLE
slice indices error occurring again (old issue 1590)

### ISSUE THREAD

**Issue by dbBerkeley** [gpodder/gpodder#190]
I tried to add podcast via url from http://feeds.thebuglepodcast.com/thebuglefeed and see the error indices must be integers of None...

**Comment by vossad01** [comment]
@dbBerkeley What version of gPodder are you using?  What operating system?

I encountered no issues adding the podcast on c7a4909eb37cfafd6f262c8568eb5d8609b3e5b3 (master) which is basically gPodder 3.9.2.  Also, no issues on gtk3 branch.  Linux Mint 18.

**Comment by dbBerkeley** [comment]
gPodder and Windows 10 are current. A reboot solved the problem. Sorry to bother you.
At least I tried restarting gPodder a few times before reporting a problem.

**Comment by vossad01** [comment]
No bother at all.

I don't know if gPodder keeps a log anywhere.  Perhaps @thp can comment if there is one you could post to get information on the error you saw.

If it were to happen again if you can then run gPodder from a command prompt and cause the issue to occur, the error and stack trace should appear in the command prompt.  That information could give developers more of a chance of fixing the issue even when the issue can not be reproduced.

A reproduction as you tried to provide with your initial feed url is always best of course :-)

**Comment by dbBerkeley** [comment]
Hi - thanks for your help again.
I can download an mp3 file from podtrac with no problems.
Using the command prompt to start gpodder did not display any errors in the command window. 
Starting Python in a command window shows this:
Python 2.7.2 (default, Jun 12 2011, 15:08:59) [MSC v.1500 32 bit (Intel)] on win32
If I install a later version, will gpodder find it?

**Comment by dbBerkeley** [comment]
Should I use Python 3.6.0 or 2.7.13?

**Comment by thp** [comment]
@dbBerkeley Use Python 2.7.x (whatever the latest 2.7 version is), Python 3 is not yet supported by gPodder, but we're working on it (in the `gtk3` branch if you are curious).

**Comment by RichardWilliamPearse** [comment]
I have this issue, python 2.7, gpodder 3.9.3-1 (via debian apt)

In trying to add the feed http://theunexplained.tv/podcasts/feed.xml

I get

```1493384099.728835 [gpodder.gtkui.main] ERROR: Subscription error: slice indices must be integers or None or have an __index__ method
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gpodder/gtkui/main.py", line 2256, in thread_proc
    max_episodes=self.config.max_episodes_per_feed)
  File "/usr/lib/python2.7/dist-packages/gpodder/model.py", line 1252, in load_podcast
    max_episodes)
  File "/usr/lib/python2.7/dist-packages/gpodder/model.py", line 837, in load
    tmp.update(max_episodes)
  File "/usr/lib/python2.7/dist-packages/gpodder/model.py", line 1023, in update
    self._consume_updated_feed(result.feed, max_episodes)
  File "/usr/lib/python2.7/dist-packages/gpodder/model.py", line 939, in _consume_updated_feed
    entries = entries[:max_episodes]
TypeError: slice indices must be integers or None or have an __index__ method
1493384116.028353 [gpodder.my] WARNING: Flush requested, but sync disabled.
1493384199.033732 [gpodder.gtkui.main] ERROR: Subscription error: slice indices must be integers or None or have an __index__ method
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gpodder/gtkui/main.py", line 2256, in thread_proc
    max_episodes=self.config.max_episodes_per_feed)
  File "/usr/lib/python2.7/dist-packages/gpodder/model.py", line 1252, in load_podcast
    max_episodes)
  File "/usr/lib/python2.7/dist-packages/gpodder/model.py", line 837, in load
    tmp.update(max_episodes)
  File "/usr/lib/python2.7/dist-packages/gpodder/model.py", line 1023, in update
    self._consume_updated_feed(result.feed, max_episodes)
  File "/usr/lib/python2.7/dist-packages/gpodder/model.py", line 939, in _consume_updated_feed
    entries = entries[:max_episodes]
TypeError: slice indices must be integers or None or have an __index__ method
1493384210.355933 [gpodder.my] WARNING: Flush requested, but sync disabled.
```

**Comment by elelay** [comment]
Setting any value for max_episode works for me in gPodder 3.10.3. Either through the GUI up to a certain point, or by editing `Settings.json`.
