### ISSUE TITLE
gpodder requires pygtk issue on Chinese-language system

### ISSUE THREAD

**Issue by MitchellClark666** [gpodder/gpodder#191]
I have installed  gPodder 3.9.2 ,32-bit Python 2.7 ,PyGTK 2.24.But when I open "gPodder.exe",it says "gpodder requires pygtk".My OS is "Windows 10 Version 1607 64 bit",and my computer is "Acer 4745G-372G50Mnks".

![default](https://cloud.githubusercontent.com/assets/13077075/21128032/8764572c-c132-11e6-9185-da2241b05c26.PNG)

![2](https://cloud.githubusercontent.com/assets/13077075/21128028/796255ca-c132-11e6-8262-0cd5af2ac680.PNG)

**Comment by vossad01** [comment]
gPodder does indeed require PyGTK.  Can you do the following and post here?

 * Open a command prompt (`cmd`)
 * Type `python --version` and hit <kbd>Enter</kbd>
 * Type `python` and hit <kbd>Enter</kbd>
 * Type `import gtk` and hit <kbd>Enter</kbd>
 * Copy all the text and post here or post a screen shot of the entire command prompt window

The above should hopefully diagnose installation problems.

**Comment by StephenWang2009** [comment]
Thank you for your reply.I did what you said and paste all the text below.

Microsoft Windows [版本 10.0.14393]
(c) 2016 Microsoft Corporation。保留所有权利。

C:\Users\wyj>python --version
Python 2.7.12

C:\Users\wyj>python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import gtk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\gtk-2.0\gtk\__init__.py", line 40, in <module>
    from gtk import _gtk
ImportError: DLL load failed: 找不到指定的程序。
>>>

![22](https://cloud.githubusercontent.com/assets/13077075/21228180/c8fb25da-c317-11e6-8a33-1d5b8d05126b.PNG)

---

When I open gPodder (CLI)，there are also some mistakes.
I paste all the text here.

Storing data in C:\Users\wyj\Documents\gPodder (GPODDER_HOME is set)
1481813055.220000 [gpodder.util] WARNING: html5lib not found, falling back to HTMLParser
1481813055.225000 [gpodder.util] WARNING: Running on Win32 but win32api/win32file not installed.
1481813055.729000 [gpodder.extensions] ERROR: Cannot load notification-win32 from C:\Program Files (x86)\gPodder\share\gpodder\extensions\notification-win32.py: No module named pywintypes
Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\src\gpodder\extensions.py", line 251, in set_enabled
    self.load_extension()
  File "C:\Program Files (x86)\gPodder\src\gpodder\extensions.py", line 295, in load_extension
    (extension, 'r', imp.PY_SOURCE))
  File "C:\Program Files (x86)\gPodder\share\gpodder\extensions\notification-win32.py", line 34, in <module>
    import pywintypes
ImportError: No module named pywintypes

gPodder 3.9.2 "Canyonero" (2016-11-30) - http://gpodder.org/
? 2005-2016 Thomas Perl and the gPodder Team
License: GNU General Public License, version 3 or later

Entering interactive shell. Type 'help' for help.
Press Ctrl+D (EOF) or type 'quit' to quit.

gpo>

![4](https://cloud.githubusercontent.com/assets/13077075/21228278/27746266-c318-11e6-9fea-0730bb116ba1.PNG)

**Comment by vossad01** [comment]
It looks like your problem is with pygtk.  Specifically, this: ImportError: DLL load failed: 找不到指定的程序。

I don't know what that means or how to fix it.  Perhaps, reinstalling pygtk would fix it?

**Comment by vossad01** [comment]
@nihokiolo Were you able to understand the Chinese error message?  Have you made any progress?  Is this still an issue?

**Comment by thp** [comment]
translate.google.com tells me: 找不到指定的程序。= Can not find the specified program.

However, that doesn't really help with the issue..

**Comment by adamvoss** [comment]
@thp Yeah I had done the same.  I hoped that OP would search the text themselves in response to my prompt and perhaps find the answer.

Given the age and the lack of actionable information, I am closing this.
