### ISSUE TITLE
Windows installer is in violation with GPLv3

### ISSUE THREAD

**Issue by aggsol** [gpodder/gpodder#196]
The windows installer requires acceptance of the GPLv3 license which is in violation with §9 of the license itself.

**Comment by vossad01** [comment]
Thanks for reporting this Kim.  I am not sure I entirely agree with your interpretation of the license text.  However, what would you see as an acceptable resolution?


Relevant GPLv3 text:

> 9. Acceptance Not Required for Having Copies.

> You are not required to accept this License in order to receive or run a copy of the Program. Ancillary propagation of a covered work occurring solely as a consequence of using peer-to-peer transmission to receive a copy likewise does not require acceptance. However, nothing other than this License grants you permission to propagate or modify any covered work. These actions infringe copyright if you do not accept this License. Therefore, by modifying or propagating a covered work, you indicate your acceptance of this License to do so.

**Comment by thp** [comment]
Related links:

 * https://www.gnu.org/licenses/gpl-faq#BitTorrent
 * https://ubuntuforums.org/showthread.php?t=1372951
 * http://opensource.stackexchange.com/questions/1634

I've seen the GPLv3 needing acceptance in other Windows programs' installers.

This is really a non-issue (but IANAL + TINLA):

* If you are going to distribute your modifications, you need to accept the GPLv3 anyway
* As long as you are not going to distribute your modifications, the GPLv3 doesn't apply

If you want use gPodder on Windows without having to "accept" the GPLv3 (which means you can't distribute any modifications you make), you can clone from Git or use the source tarball or use the Windows ZIP package, just do not use the installer.

Or in other words, the installer "propagates" the code to your installation directory, and "Therefore, by modifying or propagating a covered work, you indicate your acceptance of this License to do so.".
