### ISSUE TITLE
Download-progressbar overlapping percentage

### ISSUE THREAD

**Issue by plgruener** [gpodder/gpodder#198]
![screenshot_20161223_123846](https://cloud.githubusercontent.com/assets/5796100/21453195/0df833b2-c90d-11e6-9a41-aa7c1f429ddd.png)
As you can see, as the download progresses, the font (percentage) becomes invisible (transpareceny of bar missing?)

gPodder3 version: 3.9.3 (2016-12-22) from git, run from source.
python2 version: 2.7.12
my system: Arch Linux, KDE Plasma 5.8, Breeze-theme

**Comment by thp** [comment]
This might be a bug in the Breeze theme? Can you reproduce it with the default GNOME theme?

**Comment by plgruener** [comment]
As it seems, the progressbar is not opaque, but white text on a very light grey background (thus hardly readable).
Seems to be a bug in the Breeze-GTK2 theme, so I'm closing this issue (I could not find how to configure the color of the progress bar).
For anyone else using Plasma: change your GTK2-Design from Breeze to e.g. Adwaita, this gives you back readable blue progress bars (in change of a not-so-unified looking desktop).
