### ISSUE TITLE
gpodder3 crashing on startup after update to harfbuzz 1.4.1 on Arch Linux

### ISSUE THREAD

**Issue by gaude** [gpodder/gpodder#203]
Title says it all. Output of script command attached.

[gpodder3.txt](https://github.com/gpodder/gpodder/files/692061/gpodder3.txt)

**Comment by thp** [comment]
```
Script started on Sun 08 Jan 2017 11:14:50 GMT
1483874090.527071 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/usr/bin/gpodder", line 159, in <module>
    main()
  File "/usr/bin/gpodder", line 152, in main
    from gpodder.gtkui import main
  File "/usr/lib/python2.7/site-packages/gpodder/gtkui/main.py", line 22, in <module>
    import gtk
  File "/usr/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 40, in <module>
    from gtk import _gtk
ImportError: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates
```

Looks like harfbuzz has unmet dependencies -- is libfreetype installed and/or can you rebuild harfbuzz against the installed freetype version?

**Comment by thp** [comment]
Also, I'd assume that some (all?) of your other Gtk2-using apps are also broken?

**Comment by thp** [comment]
According to this, it has only been recently added to freetype:
https://lists.gnu.org/archive/html/freetype-commit/2016-10/msg00022.html

I guess you need to either install a newer version of freetype and/or rebuild your harfbuzz library against the freetype library you have installed.

**Comment by gaude** [comment]
Many thanks for the swift response thp. I should have searched more thoroughly in Arch forums before raising an issue here. Sorry. There is an issue with the freetype2 infinality bundle that I use and current harfbuzz. The update was only yesterday and posts are just starting to come in.
