### ISSUE TITLE
Local rss files not supported anymore

### ISSUE THREAD

**Issue by Vrihub** [gpodder/gpodder#206]
I just upgraded from 3.6.0 to 3.9.3 and the support for local (`file://...`) RSS feeds doesn't work anymore!
(see https://bugs.gpodder.org/show_bug.cgi?id=1229)

My existing local feeds are ignored.
If I try to add a new one I get:

    Could not add some podcasts
    Some podcasts could not be added to your list:
    file:///...: 'file' object has no attribute 'headers'

**Comment by thp** [comment]
Indeed, this has been a regression introduced at the time we added podcastparser support. This is now fixed in Git (see above), and the fix will be part of the next release.
