### ISSUE TITLE
After deleting an episode the selectin should be set on the next or previous episode

### ISSUE THREAD

**Issue by godot42** [gpodder/gpodder#208]
If I delete an episode - either via the DEL-key or via Episodes/Delete (my translation) - the next cursor up/down key press, will jump to the first episode in the window.
I would like to have it moving to the next episode after the deleted  one instead.
(The even better solution would be if gpodder remembers the last direction used and move it in this direction)

**Comment by thp** [comment]
Good idea; this has now been implemented. It will only works for single-selection episodes (so if multiple episodes are deleted at once via selection, it won't work) and it also works for the last direction, but only if the movement was only one row (so "jumping" back 3 rows via mouse doesn't work, but "stepping" back 3 rows via 3 key up presses does work).

**Comment by vossad01** [comment]
@thp In what environment did you reproduce this?

I went back to 6317cdb3 and this was working even before your changes for me on Linux Mint.  I was trying to reproduce this so I could confirm merging your work into the `gtk3` branch, but I am not able to reproduce the issue.
