### ISSUE TITLE
renaming files in Windows doesn't work

### ISSUE THREAD

**Issue by heatopher** [gpodder/gpodder#209]
Hi, I'm a bit of a podcast addict, and am surprised - no, dismayed - at how few reliable options there are out there. I used to use Miro, which was great it its peak, but is clearly in ruins now. I tried Media Monkey, but that seems like it's trying to do too much, and the worst thing was that it was *systematically* downloading podcasts more than once, without any apparent checking for duplicates. So that is clearly out of the game for me. And of course I *hate* iTunes :-1: 

So I'm trying gpodder just now. It's not so ambitious, not trying to do everything, which is fair enough, and which I understand. But one thing that I really do want it to be able to do is to rename files by date, for obvious enough reasons to do with continuity of listening (and whyyyyyy don't broadcasters think of this???? but that's not our issue here.....)

So, I went onto the preferences, and found this screen, and ticked these boxes (as shown in this image):

![screenshot 2017-01-17 20 40 37](https://cloud.githubusercontent.com/assets/25185065/22039774/80658bee-dcf8-11e6-9d40-b028eb936151.png)

Well, I thought that would work, but it doesn't. I restarted the program, even restarted the computer (for whatever difference that might make - none, I assume), but none of that was any good.

I've even been rummaging around in the program files, and found this rename_download.py, which I assume is where this stuff is supposed to happen. I don't know python, but just as an experiment I tried setting those DefaultConfig bits to True rather than False. I didn't crash the program, but that didn't work.  So I put them back to False, as you can see in the picture below. Well, please let me know. My decision whether to use gpodder probably depends on getting this to work!

![screenshot 2017-01-17 20 50 37](https://cloud.githubusercontent.com/assets/25185065/22039755/6f974834-dcf8-11e6-8d1e-f0e522597e4a.png)

**Comment by thp** [comment]
You need to enable the "rename downloads" extension in the preferences dialog (last tab). And the "add sortdate" option can be enabled in the advanced configuration editor that you found (although I see from your screenshot that it is already enabled).

Note that the "rename downloads" extension will only take effect for newly downloaded files, although with an SQLite 3 editor you could edit the database and rename the files (until a nicer method comes around).

The "downloads.chronological_order" is used to determine in which order files are downloaded if they are added to the download queue at the same time -- so if you download 10 episodes, instead of downloading them in the order they appear in the UI, they are downloaded in chronological order (so the oldest episode is downloaded first, etc..), the code for this is here:

https://github.com/gpodder/gpodder/blob/3c66825731bdf80488e414182c81bc16f0b0580b/src/gpodder/gtkui/main.py#L2449

**Comment by heatopher** [comment]
Hi, thanks very much. 

D'oh, there was me going all the way to look at the source code while missing the first button. Ha ha ha! All working fine now :~)

By the way, in case this is something you ever get asked about....... I have also solved the other thing that was bugging me. When I tried to export everything from one podcast directly from gpodder to play and queue up nicely in a player, all my players were messing up. Firstly, VLC mangled the order completely, even after sorting out the filenames, goodness knows why. Windows Media Player was predictably useless, while Winamp (yes, old school, I know) went bonkers and tried to play every single file individually in its own window!!!! It was like that scene in the Matrix where Neo is talking to the Architect in a thousand voices. All I could do was restart the PC.

Anyway, in the midst of looking for a podcatcher which neatly organises and also plays the files (this doesn't now seem to exist!), I found a program called foobar, which loads everything up very neatly, and also actually looks quite pretty. So far so good, at least!

So, I should be staying with gpodder. Thanks very much for your help, although I should have found that myself, of course!

**Comment by heatopher** [comment]
Oh, I didn't want to be back here, but so be it.....

All of that seemed to be working, impressive enough considering how many podcasts I had to catch up with! But there is something wrong. It's renaming some files, but not all. In some folders it's renamed dozens of them correctly, no mistakes, but in others there are a few files that haven't been renamed, and in some cases a lot. It does seem to be related a bit to the place where the pod comes from. The BBC files are mostly OK, but not all of them, while the Guardian's are hopeless. Is there any good reason for this?

But here's the really weird thing - that extensions.enabled setting has disappeared from the config!!! 

![screenshot 2017-01-18 23 10 11](https://cloud.githubusercontent.com/assets/25185065/22088515/77d02662-dddc-11e6-8fc9-ef4e4100af7e.png)

I have it checked on the extensions tab, like you told me. I haven't done any more fiddling with the python files, because I wouldn't know what to do anyway. I've also of course tried uninstalling and reinstalling, but that setting is still weird. Presumably the uninstall doesn't get rid of absolutely everything?

**Comment by heatopher** [comment]
Oh, I didn't want to be back here, but so be it.....

All of that seemed to be working, impressive enough considering how many podcasts I had to catch up with! But there is something wrong. It's renaming some files, but not all. In some folders it's renamed dozens of them correctly, no mistakes, but in others there are a few files that haven't been renamed, and in some cases a lot. It does seem to be related a bit to the place where the pod comes from. The BBC files are mostly OK, but not all of them, while the Guardian's are hopeless. Is there any good reason for this?

I've also tried uninstalling and reinstalling to try to put my settings in at first, before hopefully getting it to work to plan. But presumably the uninstall doesn't get rid of absolutely everything, as it's remembering the subscriptions that I had when I reinstall, Is there some other place that I would need to go and delete absolutely everything in order to do a completely clean reinstall?

**Comment by heatopher** [comment]
Let me ask you a completely different question. Is gpodder more reliable/powerful on Linux than it seems to be on Windows? The reason being that I am finally on the cusp of slowly migrating over, something that I've been meaning to do for many years.

**Comment by thp** [comment]
Cool stuff :) And yes, foobar2000 is nice.
