### ISSUE TITLE
gPodder and its growing forgetfullness

### ISSUE THREAD

**Issue by JohndSeka** [gpodder/gpodder#210]
gPodder has been exhibiting strange behaviours lately in relation to its database of podcasts and downloaded episodes. In particular, whenever a new episode is downloaded and played, that same episode will later turn up as new and not yet downloaded, even though it is downloaded and in its respective folder. This happens to several of my podcast subscriptions. I have about 50 podcast subscriptions in gPodder. I don't sync or have this option enabled so this rules out the cause. Is this an issue with gPodder where it cannot handle a large database of podcast subscriptions, since this has only recently started to occur? Any thoughts appreciated since gPodder is my favourite podcast manager and I'd hate to migrate to some other software just so I don't have this issue. It's quite annoying to see downloaded episodes as new since it can cause confusion especially with a large database of podcasts.

**Comment by thp** [comment]
For which feed does this happen? What is your limit of episodes set in the configuration (per-feed limit of episodes that are shown)? Which version of gPodder are you using and on which Operating System / distribution?

**Comment by romlok** [comment]
FWIW I had been experiencing something similar a couple of years ago (see: https://bugs.gpodder.org/show_bug.cgi?id=1907#c2 and https://bugs.gpodder.org/show_bug.cgi?id=1981), particularly with YouTube feeds IIRC.
Also this may be related to (past?) issues with how gPodder sometimes cannot find files with non-ASCII filenames? (eg. https://bugs.gpodder.org/show_bug.cgi?id=2005)

The workaround I ultimately found, which stopped gPodder forgetting podcasts for me, was to only ever "check for new episodes" ONCE per run. If I needed to check again, I would quit and restart gPodder entirely.

**Comment by elelay** [comment]
Closing since it's really and might be fixed in the 3.10 branch with the switch to python 3.
