### ISSUE TITLE
Feature request : "send to" enhancement

### ISSUE THREAD

**Issue by patdum** [gpodder/gpodder#212]
Hi,

I have a feature request.

I download episodes on my computer, and after download complete, copy them to Usb device with the "send to" gpodder feature.

1. For each file, a file dialog box appears to ask me folder/filename. I would like a unique dialog asking me the folder only one time, not asking me a confirmation for each file. (or a checkbox on the actual dialog box  : [x] use same folder for next files?)

2. During copying, on slow device like usb, ... the file dialog box stays "frozen" (submit button checked but dialog box staying visible... ).

3. Because copying is takes long time (slow device/big file), I switch to another app for working.... And, when gPodder finished copying current file, the file dialog box appears to ask about the next file, even gppoder is executing in background. So during entering data in the application, the dialog box appears and intercept keyboard entry... and what I was entering in my other app is erasing dialog box filename edition. 

Best regards,

Sorry for my poor english. 

(gPodder 3.9.0 /  xubuntu 16.10)

**Comment by vossad01** [comment]
If you are willing to [run from Git](https://github.com/gpodder/gpodder/wiki/Run-from-Git), I have implemented sending multiple files to a local folder in the 'gtk3' branch.  Instead of asking you where to save each file, it asks you what folder to save all selected files.  gPodder will still "freeze" while it is doing the transfer, but you won't be interrupted for every file.

**Comment by elelay** [comment]
I'm working on converting `Send To > Local File` to be asynchronous.

**Comment by vossad01** [comment]
Just as a word of warning, the `gtk3` branch is diverged here.  Depending on where you are implementing this, I just wanted you to know about the potential of merge conflicts.

**Comment by elelay** [comment]
Good point. I'm doing it in the gtk3 branch only, since it's not a blocking (no pun intended) bug in gtk2. Once I have sthing working we can reconsider this.

**Comment by elelay** [comment]
#300 makes "Send To" asynchronous, on top of the enhancements @vossad01 has already done.

**Comment by adamvoss** [comment]
Released with [3.10.0](https://github.com/gpodder/gpodder/releases/tag/3.10.0)
