### ISSUE TITLE
Start client at startup on Ubuntu

### ISSUE THREAD

**Issue by heatopher** [gpodder/gpodder#215]
Hallo, I've just switched over to Linux (Ubuntu 16.04, to be precise), and would like to be able to start the gpodder client from startup. The client, not some background process (which I suppose I might get into later, but I'm still used to having everything graphical a la Windows)

Simple question. What command do I need to put in the startup applications to make that happen? I've looked everywhere on the web, and rummaged around the installation, but I just don't know enough about Linux yet to know what I'm looking for. I'm used to files with a big EXE on them :~)

**Comment by thp** [comment]
This is probably not really gPodder-related, but more generic; the command you need is "gpodder" to start the GUI, and it can be added with one of those answers:
http://askubuntu.com/questions/459277/how-do-i-make-a-program-auto-start-everytime-i-log-in-in-ubuntu-14-04
