### ISSUE TITLE
podcast directory search error when result with no url

### ISSUE THREAD

**Issue by elelay** [gpodder/gpodder#222]
Yes, it's weird: a podcast in gpodder.net without url!
search for Linux Outlaws, you'll only see the first 3
gpodder.net [search page](https://gpodder.net/search/?q=linux+outlaws) shows way more.

Traceback (similar with gtk3 branch...)
```
1485726984.299862 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "src/gpodder/gtkui/desktop/podcastdirectory.py", line 267, in update_ui
    self.podcasts_model.load(podcasts or [])
  File "src/gpodder/gtkui/desktop/podcastdirectory.py", line 58, in load
    entry.subscribers, cgi.escape(entry.url)), entry.title, entry.url))
  File "/usr/lib/python2.7/cgi.py", line 1043, in escape
    s = s.replace("&", "&amp;") # Must be done first!
AttributeError: 'NoneType' object has no attribute 'replace'
```
The fix: don't show results that don't have `entry.url`.

**Comment by thp** [comment]
We might want to do this server-side. Pinging @stefankoegl

**Comment by adamvoss** [comment]
This issue was moved to gpodder/mygpo#50

**Comment by elelay** [comment]
This seems to have been fixed in mygpo. I can't reproduce it with Linux Outlaws.
