### ISSUE TITLE
Gpodder.net Sync issues

### ISSUE THREAD

**Issue by Woulouf** [gpodder/gpodder#223]
Hello everybody

I'm not sure that's the right place to talk about that but syncing service on gpodder.net seems to be down. (gpodder client windows 10 and mac os 10.9)

Some people talk about that issue on Twitter : https://twitter.com/search?f=tweets&vertical=default&q=%40gpoddernet&src=typd

Does someone knows something about that ?

Thanks a lot.
Regards

**Comment by adamvoss** [comment]
This issue was moved to gpodder/mygpo#43
