### ISSUE TITLE
A lot of failed 400 http errors, need to manually "download" I.E., use the mouse 

### ISSUE THREAD

**Issue by federerfanatic** [gpodder/gpodder#226]
I have noticed a lot of download errors (400 http), for example, try 

http://podcast.drpompa.com/feed

as an example. I would speculate that this may be a problem with the server setup of a particular podcast,
however, why doesn't gpodder keep reinitializing downloads after such errors? 

Version: 3.9.3, latest pull from master

See attached file for configuration.

[Settings.json.txt](https://github.com/gpodder/gpodder/files/750735/Settings.json.txt)

I am running LinuxMint/Betsy=Debian Jessie/

**Comment by vossad01** [comment]
> I have noticed a lot of download errors (400 http) [...] however, why doesn't gpodder keep reinitializing downloads after such errors?

According the the HTTP spec, [status code 400 is Bad Request](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.1):

> The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modifications. 

Given how the protocol is defined, wouldn't it be inappropriate for gPodder to automatically retry in this case?

**Comment by federerfanatic** [comment]
Perhaps it offer the user the opportunity to retry and do it politely?




--------------------------------------------------------------
 Roger Federer Fanatic Extraordinaire :-)

**Comment by vossad01** [comment]
Could you provide more details about your envisioned user experience.  Are you looking for a pop-up on failure with a retry button?

I may be mis-remembering but I thought when you right-click on failed downloads there is in option that triggers a retry.

**Comment by federerfanatic** [comment]
Perhaps that would be an option, ie., a pop-up failure AFTER all downloads
that worked finished.

I think your memory might be of the instance where if one stops gpodder in
mid download it offers that option of restarting
when restarting gpodder?

In any case, keep of the fine work!




--------------------------------------------------------------
 Roger Federer Fanatic Extraordinaire :-)

**Comment by vossad01** [comment]
I was curious, so I disabled the my network interface mid-download to cause an error.  If you right-click a failed download the "Download" option causes it to retry:

![image](https://cloud.githubusercontent.com/assets/965439/23220641/3d4f446a-f8e8-11e6-8d9d-1497d368fa92.png)

**Comment by federerfanatic** [comment]
OK. I try to test that approach when I find the moment.




--------------------------------------------------------------
 Roger Federer Fanatic Extraordinaire :-)

**Comment by thp** [comment]
Yes, HTTP 400 must not result in an automatic retry. Note that for those HTTP error codes that should cause a retry, we already retry 3 times or whatever the automatic retry configuration is:

```
            # HTTP Status codes for which we retry the download                                                          
            retry_codes = (408, 418, 504, 598, 599)                                                                      
            max_retries = max(0, self._config.auto.retries)                                                              
```

https://github.com/gpodder/gpodder/blob/master/src/gpodder/download.py#L760

**Comment by thp** [comment]
Closing this as "works for me", if the server wants us to retry, it should send the correct HTTP status.
