### ISSUE TITLE
[Regression] podcastparser fails on mktime_tz

### ISSUE THREAD

**Issue by wamserma** [gpodder/gpodder#230]
Somehow the offending entry made it again into the same RSS feed and it seems you lost my patch when moving to podcastparser, see https://github.com/gpodder/gpodder/pull/135
Grab a snapshot of http://www.br-online.de/podcast/kalenderblatt/cast.xml while it's there (GH would not let me upload it).

Opening the issue here, because I can't open it in the podcastparser repo.

**Comment by thp** [comment]
I guess I was too late with retrieving the feed, can you somehow send me your snapshot?

**Comment by wamserma** [comment]
I still can see the problematic entries at the end of the XML file:
```xml
   <item>
      <title>Der erste Garfield Comic erscheint - 19.06.1978</title>
      <pubDate>Mon, 19 Jun 1978 09:05:01 +0100</pubDate>
      <description>Müde, hungrig, fett - Garfield. 37 ist er inzwischen, aber: Psst! Er wird auf sein Alter nicht gern angesprochen. Doch Geschenke, die liebt er. "Er ist ein Mensch im Katzenfell", meint sein Erfinder Jim Davis. Autorin. Anja Mösing</description>
      <link>http://cdn-storage.br.de/iLCpbHJGNL9zu6i6NL97bmWH_-bP/_-OS/52kd_A4y/780619_0905_radioWissen_Der-erste-Garfield-Comic-erscheint.mp3</link>
      <enclosure url="http://cdn-storage.br.de/iLCpbHJGNL9zu6i6NL97bmWH_-bP/_-OS/52kd_A4y/780619_0905_radioWissen_Der-erste-Garfield-Comic-erscheint.mp3" length="4155394" type="audio/mpeg"/>
      <guid isPermaLink="false">780619_0905_radioWissen_Der-erste-Garfield-Comic-erscheint.mp3</guid>
      <itunes:author>Bayern 2</itunes:author>
      <itunes:summary>Müde, hungrig, fett - Garfield. 37 ist er inzwischen, aber: Psst! Er wird auf sein Alter nicht gern angesprochen. Doch Geschenke, die liebt er. "Er ist ein Mensch im Katzenfell", meint sein Erfinder Jim Davis. Autorin. Anja Mösing</itunes:summary>
      <itunes:keywords>Garfield, Comic, Jim Davis, Kater, Wissen, Geschichte, Das Kalenderblatt, radioWissen, Feuilleton, Podcast, Bayern 2, Bayerischer Rundfunk</itunes:keywords>
      <itunes:duration>00:04:19</itunes:duration>
    </item>
    <item>
      <title>Kaufhaus Schocken in Stuttgart abgerissen - 02.05.1960</title>
      <pubDate>Mon, 02 May 1960 09:05:01 +0100</pubDate>
      <description>Das Auge kauft mit! Das gilt nicht nur für die Ware, sondern für das Shoppingerlebnis insgesamt. Das denkt sich Salman Schocken und baut seine Kaufhäuser zu architektonischen Meisterwerken aus. Autorin: Leo Hoffmann</description>
      <link>http://cdn-storage.br.de/iLCpbHJGNL9zu6i6NL97bmWH_-by/_-ZS/9-k6528G/600502_0905_radioWissen_Kaufhaus-Schocken-in-Stuttgart-abgerissen.mp3</link>
      <enclosure url="http://cdn-storage.br.de/iLCpbHJGNL9zu6i6NL97bmWH_-by/_-ZS/9-k6528G/600502_0905_radioWissen_Kaufhaus-Schocken-in-Stuttgart-abgerissen.mp3" length="3434832" type="audio/mpeg"/>
      <guid isPermaLink="false">600502_0905_radioWissen_Kaufhaus-Schocken-in-Stuttgart-abgerissen.mp3</guid>
      <itunes:author>Bayern 2</itunes:author>
      <itunes:summary>Das Auge kauft mit! Das gilt nicht nur für die Ware, sondern für das Shoppingerlebnis insgesamt. Das denkt sich Salman Schocken und baut seine Kaufhäuser zu architektonischen Meisterwerken aus. Autorin: Leo Hoffmann</itunes:summary>
      <itunes:keywords>Kaufhaus Schocken, Stuttgart, Salman Schocken, Einzelhandel, Shopping, Architektur, Erich Mendelsohn, Wissen, Geschichte, Das Kalenderblatt, radioWissen, Feuilleton, Podcast, Bayern 2, Bayerischer Rundfunk</itunes:keywords>
      <itunes:duration>00:03:34</itunes:duration>
    </item>
```
FYI I just noticed that I'm still with gPodder 3.9.2 (PortableApps). If this is fixed in 3.9.3 I'm sorry for making a fuss.

**Comment by thp** [comment]
There is this that has been added recently:
https://github.com/gpodder/podcastparser/commit/dda45de84d77dd46ed8e3b69700d114b4c9a8598

I've now added a test that makes sure we parse those correctly:
https://github.com/gpodder/podcastparser/pull/6

I /think/ we handle negative values there correctly. Also make sure you have an up to date version of Python 2.7 installed.

**Comment by thp** [comment]
gPodder from Git on macOS (Python 2.7.10):
![screen shot 2017-02-24 at 14 09 13](https://cloud.githubusercontent.com/assets/135241/23304587/daef1282-fa9a-11e6-8794-fa01196a14ae.png)

**Comment by thp** [comment]
So, the tests seem to work in macOS and Linux (see https://github.com/gpodder/podcastparser/issues/6), however it could be that `mktime()` on Windows doesn't support negative return values?

**Comment by wamserma** [comment]
PortableApps bundles gPodder with 

```
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
```

In this version of python `time.mktime()`refuses dates that would generate negative values. This is sort of documented behaviour. ["The earliest date for which it can generate a time is platform-dependent."](https://docs.python.org/2/library/time.html#time.mktime)

```python
>>> parsed = parsedate_tz('Mon, 02 May 1960 09:05:01 +0100')
>>> parsed
(1960, 5, 2, 9, 5, 1, 0, 1, 0, 3600)

>>> mktime_tz(parsed)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Z:\gPodderPortable\App\Python\lib\rfc822.py", line 954, in mktime_tz
    t = time.mktime(data[:8] + (0,))
OverflowError: mktime argument out of range
```

So probably the call to `mktime_tz` should be wrapped in a try-catch block and return 0 if `mktime` fails (optionally log a debug message). That's what I did in https://github.com/gpodder/gpodder/pull/135.

In fact, this patch wass easy to port, see https://github.com/gpodder/podcastparser/pull/7

**Comment by wamserma** [comment]
I think this can be marked as fixed by https://github.com/gpodder/podcastparser/pull/7
