### ISSUE TITLE
Non-ascii characters excluded from URLs

### ISSUE THREAD

**Issue by LinAGKar** [gpodder/gpodder#232]
When trying to download an episode with non-ascii characters in the URL, the non-ascii characters are excluded rather than being correctly encoded, which leads to it getting a 404. For example if the word "frågor" is in the URL, the word will become "frgor", whereas it should become "fr%C3%A5gor".

**Comment by thp** [comment]
For which feed is this happening? On which OS? Which gPodder version? Do you have any extensions enabled?

**Comment by LinAGKar** [comment]
It happens for http://valpskott.se/Valpcast/valpcast.rss. I'm using gPodder 3.9.3 on openSUSE Leap 42.2, and I don't have any extensions enabled.

**Comment by thp** [comment]
I can reproduce this issue with the episode "Existentiella frågor".

**Comment by thp** [comment]
Should be fixed in master, please give it a try.
