### ISSUE TITLE
Error initialising mygpo

### ISSUE THREAD

**Issue by TalmarGrosskotz** [gpodder/gpodder#236]
Step by step I progress on running mygpo on my Raspberry Pi, but now I have run into a new error I can' t make sense of. It happens after running `python manage.py migrate`:

Traceback (most recent call last):
 File "manage.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in         
     execute_from_command_line utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/lib/python2.7/dist-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/mygpo/mygpo/api/__init__.py", line 27, in <module>
    from mygpo.utils import parse_request_body
  File "/root/mygpo/mygpo/utils.py", line 236
   print('\r', end=' ', file=stream)
                        ^
SyntaxError: invalid syntax

Can anybody help me?

**Comment by vossad01** [comment]
What is your python version?  (`python --version`)

@thp, should the issue tracker perhaps be enabled on [gpodder/mygpo](https://github.com/gpodder/mygpo)?

**Comment by vossad01** [comment]
@TalmarGrosskotz I don't know the right way to fix this for that code-base generally, but the issue is that it is using the [print function](https://docs.python.org/2/library/functions.html#print) (a la Python 3) rather than the print statement from Python 2.

Try adding,

    from __future__ import print_function

in the imports of utils.py to bring the print function into scope.

**Comment by TalmarGrosskotz** [comment]
I am using python 2.7.12


Am 02.03.2017 um 15:11 schrieb Adam Voss:

**Comment by TalmarGrosskotz** [comment]
That worked, thx.

⁣Gesendet mit BlueMail ​

**Comment by TalmarGrosskotz** [comment]
I am getting closer. It seems that I have to manually install everyting (every single package) under python 2.7 to get things running. `pip install -r requirements.txt` seems to do all under python3 while `pip2 install -r requirements.txt` fails to work.

**Comment by TalmarGrosskotz** [comment]
I am so close to giving up :(
Still trying to successfully run `python manage.py migrate`.
After working out several problems with `urllib` and so on i get the following error:
`FATAL:  password authentication failed for user "mygpo"`

I have absolutely no idea how and where to fix it.

**Comment by vossad01** [comment]
@TalmarGrosskotz What is the status of this?  Your last message seems to indicate you had a simple authentication error (bad password, wrong user name, etc).  Did you have a stacktrace for the error?

**Comment by TalmarGrosskotz** [comment]
Sorry for not getting back here. I kinda lost patience over it. I Thüringen kann the 



Gesendet mit BlueMail

**Comment by adamvoss** [comment]
This issue was moved to gpodder/mygpo#44
