### ISSUE TITLE
wiki serves the wrong site over https

### ISSUE THREAD

**Issue by 0x1f415** [gpodder/gpodder#237]
did someone configure nginx/apache impoperly?

![capture](https://cloud.githubusercontent.com/assets/6064300/23571204/e8d26746-0035-11e7-8d03-65ae6dbfffd7.PNG)

http://wiki.gpodder.org/

https://wiki.gpodder.org/

**Comment by paulgit** [comment]
Thanks for the report. This is now fixed.
