### ISSUE TITLE
Merge Duplicate Podcasts

### ISSUE THREAD

**Issue by go2null** [gpodder/gpodder#239]
Not sure where to post this, but based on the these, it seems that the bug tracker maybe used.  Please let me know otherwise.
* https://bugs.gpodder.org/show_bug.cgi?id=1863
* https://getsatisfaction.com/gpoddernet/topics/duplicate-podcasts
* http://wiki.gpodder.org/wiki/Web_Services/Merge_Queue

**StarTalk Radio**
*official feed*:  https://feeds.soundcloud.com/users/soundcloud:users:38128127/sounds.rss
* https://gpodder.net/podcast/feed-flipper-12 -> http://picklemonkey.net/flipper/convert.php?feed=http://itunes.apple.com/WebObjects/MZStore.woa/wa/viewPodcast?id=325404506&sender=Startalk
* https://gpodder.net/podcast/startalk -> http://rss.sonibyte.com/rssfeed/56.xml
* https://gpodder.net/podcast/startalk-1 -> http://rss.sonibyte.com/rssfeed/56.xm
* https://gpodder.net/podcast/startalk-2 -> http://picklemonkey.net/flipper/convert.php?feed=http://itunes.apple.com/podcast/startalk/id325404506
* https://gpodder.net/podcast/startalk-radio -> http://feeds.soundcloud.com/users/soundcloud%3Ausers%3A38128127/sounds.rss
* https://gpodder.net/podcast/startalk-radio-1 -> http://feeds.soundcloud.com/users/soundcloud:users:38128127/sounds.rss
* https://gpodder.net/podcast/startalk-radio-2 -> http://feeds.feedburner.com/StarTalkRadio
* https://gpodder.net/podcast/startalk-radio-3 -> https://feeds.soundcloud.com/users/soundcloud%3Ausers%3A38128127/sounds.rss
* https://gpodder.net/podcast/startalk-radio-show -> http://podcastrss.play.it/startalk-radio-show_mp3_32.xml

**StarTalk Blog**
*official feed*:  https://www.startalkradio.net/feed/
* https://gpodder.net/podcast/59fe2781c9eb361c0e701d18a14b8f0e -> http://startalkradio.net/feed/shows/
* https://gpodder.net/podcast/star-talk-feed -> http://startalkradio.net/feed
* https://gpodder.net/podcast/star-talk-feed-1 -> http://www.startalkradio.net/feed
* https://gpodder.net/podcast/startalk-radio-4 -> http://startalkradio.net/feed/shows
* https://gpodder.net/podcast/startalk-radio-show-by-neil-degrasse-tyson -> http://www.startalkradio.net/?page_id=354
* https://gpodder.net/podcast/startalk-radio-show-by-neil-degrasse-tyson-1 -> http://www.startalkradio.net/?page_id=354http://www.startalkradio.net/?page_id=354
* https://gpodder.net/podcast/startalk-radio-show-by-neil-degrasse-tyson-2 -> http://www.startalkradio.net/feed/
* https://gpodder.net/podcast/startalk-radio-show-by-neil-degrasse-tyson-shows -> http://www.startalkradio.net/feed/shows/
* https://gpodder.net/podcast/startalk-radio-show-by-neil-degrasse-tyson-shows-1 -> http://www.startalkradio.net/feed/shows

**Comment by adamvoss** [comment]
This issue was moved to gpodder/mygpo#45
