### ISSUE TITLE
gtk3: localdepends.py downloads an incompatible mygpoclient

### ISSUE THREAD

**Issue by adamvoss** [gpodder/gpodder#248]
When running from git on the `gtk3` branch, and you run the following do download dependencies:

    python3 tools/localdepends.py

The result when your try to run gPodder is:

> ERROR: Uncaught exception: Traceback (most recent call last):
  File "./bin/gpodder", line 159, in <module>
    main()
  File "./bin/gpodder", line 152, in main
    from gpodder.gtkui import main
  File "/home/vossad01/dev/gpodder/src/gpodder/gtkui/main.py", line 56, in <module>
    from gpodder import my
  File "/home/vossad01/dev/gpodder/src/gpodder/my.py", line 62, in <module>
    from mygpoclient.simple import MissingCredentials
  File "/home/vossad01/dev/gpodder/src/mygpoclient/simple.py", line 23, in <module>
    from mygpoclient import json
  File "/home/vossad01/dev/gpodder/src/mygpoclient/json.py", line 79
    except ValueError, ve:
                     ^
> SyntaxError: invalid syntax

clearly this version is not compatible with Python 3.

### Workaround
Clone [gpodder/mygpoclient](https://github.com/gpodder/mygpoclient) and manually copy the source files.

Issue first mentioned in #187

**Comment by elelay** [comment]
I'm not inclined to modify the script to fetch the archive from github.
A new version of mygpoclient will have to be released to solve the issue.

**Comment by vossad01** [comment]
@thp It looks like [you are the owner on pypi](https://pypi.python.org/pypi/mygpoclient), is there anything more that would need to be done before a new version could be published?

**Comment by adamvoss** [comment]
Reopening because a new release has not been published yet.

**Comment by adamvoss** [comment]
Verified using a new clone, checking out the gtk3 branch, then using the steps from [running from Git](https://gpodder.github.io/docs/run-from-git.html).  gPodder started and successfully checked for new episodes.
