### ISSUE TITLE
gtk3: race encountered when filtering on application start

### ISSUE THREAD

**Issue by vossad01** [gpodder/gpodder#250]
## Steps to Reproduce

The following steps need to be done with some quickness.

1. Launch gPodder (from the console so you can see log output)
2. Click into the episodes pane
3. Type some characters that will result in an empty match against your podcast list: ex. _asdf_
4. Notice the following error repeated many, may times:

    > Traceback (most recent call last):
  File "/home/vossad01/dev/gpodder/src/gpodder/gtkui/main.py", line 997, in on_episode_list_selection_changed
    self.play_or_download()
  File "/home/vossad01/dev/gpodder/src/gpodder/gtkui/main.py", line 2092, in play_or_download
    if episode.file_type() not in ('audio', 'video'):
AttributeError: 'NoneType' object has no attribute 'file_type'
1490492811.207519 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/home/vossad01/dev/gpodder/src/gpodder/gtkui/main.py", line 997, in on_episode_list_selection_changed
    self.play_or_download()
  File "/home/vossad01/dev/gpodder/src/gpodder/gtkui/main.py", line 2092, in play_or_download
    if episode.file_type() not in ('audio', 'video'):
AttributeError: 'NoneType' object has no attribute 'file_type'

**Note:** if you wait a few seconds before engage in step 3, the error will not occur.

I could reproduce this readily on the `gtk3` branch but not at all in `master`.
Issue identified while writing up #249.

**Comment by elelay** [comment]
I can't reproduce.
Maybe add `if episode is None: continue` in `play_or_download`

**Comment by vossad01** [comment]
Workaround integrated, root cause not investigated.
