### ISSUE TITLE
investigate gpodder.net performance

### ISSUE THREAD

**Issue by elelay** [gpodder/gpodder#259]
I've tested gpodder.net sync with a friend and we noticed really poor performance.
1. the web ui took tens of seconds to load
2. sync from antenna pod failed multiple times
3. sync from gpodder at exit took also tens of seconds.
4. search from the gpodder.net showed 502 overloaded, then when I tried a minute later it worked

Yes, gpodder.net is feature-rich and I appreciate the service to the community, but can we do something to make it perform better?

**Comment by adamvoss** [comment]
This issue was moved to gpodder/mygpo#46
