### ISSUE TITLE
some podcasts not updated in gpodder.net web ui

### ISSUE THREAD

**Issue by elelay** [gpodder/gpodder#260]
For instance https://gpodder.net/podcast/si-tu-ecoutes-jannule-tout shows latest from jan. 15, 2016 even if the feed has entries as fresh as Yesterday.

**Comment by ldexterldesign** [comment]
+1

**Comment by adamvoss** [comment]
@elelay I think you have done some work with mygpo, know if a local install of mygpo is affected by this?  See https://github.com/gpodder/gpodder/issues/314#issuecomment-307839308

/cc @ldexterldesign

**Comment by elelay** [comment]
I was able to install my own instance of mygpo.
Unfortunately, I wasn't interested in the web ui at the time, and didn't setup feed refreshes, so I can't help you in configuring that.

**Comment by adamvoss** [comment]
This issue was moved to gpodder/mygpo#47
