### ISSUE TITLE
sslv3 alert handshake failure

### ISSUE THREAD

**Issue by dannn-o** [gpodder/gpodder#265]
I am running gPodder v 3.9.3, and when I tried to add a new podcast recently by RSS feed (https://rss.art19.com/wrongful-conviction-with-jason-flom), it produced the following error:

```
Could not add some podcasts

Some podcasts could not be added to your list:

https://rss.art19.com/wrongful-conviction-with-jason-flom: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
```

Doing some internet searches, it seems this might be caused by OpenSSL restrictions and Python, but I didn't really understand many of the posts I came across.  My version of Python is v2.7.6.  Any ideas or suggestions?

**Comment by vossad01** [comment]
> Any ideas or suggestions?

Try updating to Python 2, v2.7.9 or newer.

This may be the same issue as #234.

**Comment by dannn-o** [comment]
Was just reading that post as you added your comments.  I also noticed #254 (I am running Linux Mint), so I have the same challenge in updating the Python version from the standard repositories.  Any advice you can give would be appreciated.

**Comment by vossad01** [comment]
I think [the options I outlined there are still accurate](https://github.com/gpodder/gpodder/issues/254#issuecomment-289654909):

> * to find a [backports] PPA with a newer python (you need at least 2.7.9)
> * install a newer python manually
> * [run gPodder from a git clone](https://github.com/gpodder/gpodder/wiki/Run-from-Git) and switch to the `gtk3` branch that runs under Python 3

**Comment by dannn-o** [comment]
I'm a bit wary about attempting the first 2 suggestions, as although I've been running Linux for several years, I've seen many online posts advising against trying to update the version of Python, as it may render the OS unusable.  Or, at a minimum, this seems to be only suggested for those who are confident with such an update, and I haven't found any online documentation that seems rock-solid.

I did also find that Mint 17.3 has Python 3 installed as well (looks like v3.4.3).  In considering your 3rd suggestion above, I read through the instructions about running gPodder from a git clone, but how do I "switch to the gtk3 branch" to use Python 3?  Thanks for your patience...I just want to make sure I understand everything before proceeding.

**Comment by vossad01** [comment]
The process for running the `gtk3` branch is largely the same.

After you clone and `cd gpodder`, execute `git checkout gtk3` to switch to the `gtk3` branch.  Then follow the rest of the steps as usual.

However, when you are done, I expect you will encounter Issue #248, which is not fixed yet but can easily be worked around:

 1. In some other location, clone mygpoclient: `git clone https://github.com/gpodder/mygpoclient.git`
 2. Copy all the files from the newly created _mygpoclient/mygpoclient_ folder to _gpodder/src/mygpoclient_, replacing the existing files.
 
Assuming you have all the system dependencies installed, which is fairly likely, it will just work after that.
___
From your comment I recognize this is likely beyond your comfort/skill, but for the sake of other readers I want to mention that it should be possible to install a local, isolated Python 2 that does not replace the system Python 2 that you explicitly configure gPodder to use instead of the system install.  However, I agree that is not the easiest solution here.

**Comment by dannn-o** [comment]
Thanks for the additional directions (and, for the terrific program!).  I expect to have some time this week to try and work on this - I will post back here with any additional instructions if I'm successful, to potentially help others on Mint (or similar Linux variants).

**Comment by dannn-o** [comment]
I gave a try to your suggestion of installing a local, isolated Python 2.  I downloaded the latest version (2.7.13) from python.org, used "make altinstall" to avoid updating the system /usr/bin/ python files, and it appears to have installed successfully:
```
dan@varmint ~ $ python2.7 -V
Python 2.7.13
```
I next attempted to run gPodder with this local install, but got the following error:
```
dan@varmint / $ cd usr/bin
dan@varmint /usr/bin $ python2.7 gpodder

    Warning: python-dbus not found. Disabling D-Bus support.
    
Traceback (most recent call last):
  File "gpodder", line 159, in <module>
    main()
  File "gpodder", line 84, in main
    import gpodder
ImportError: No module named gpodder
```
Am I approaching this incorrectly?

**Comment by vossad01** [comment]
You have approached it correctly.

The Python you installed lives separately from the system's Python and, by default, will not utilize system installed libraries.  The failures you are seeing are because the `gpodder` script is trying to access things that are not installed in your local Python.  [This is controlled through the python path](http://stackoverflow.com/q/15252040/1072626).

Your options would be:

- Modify `/usr/bin/gpodder` to make it smart enough to look at the system installed packages even when run from your local gPodder (namely, modify `sys.path` at runtime).
- Modify your environment's PYTHONPATH so your local install will have access the needed system-installed libraries.
- Run gPodder from a git clone rather then running the system-installed gPodder.  gPodder then would be on the search path because it is in the same directory as the script you are running.
- Install the needed packages into your local python install (possibly by copying them from the system install).

Depending on the path you take, you may find [this helpful for locating the modules you want to have on your path](http://stackoverflow.com/q/269795/1072626)

**Comment by dannn-o** [comment]
I thought this might be a good exercise that would help strengthen my proficiency with Python, but my confidence is fading fast...

In case it matters:  I am not using anything like virtualenv or any custom scripts.  I went with the 3rd suggestion (running gPodder from a git clone), and followed the directions given at [https://github.com/gpodder/gpodder/wiki/Run-from-Git](url), using "python2.7" to run the Python scripts.  I then launched the gPodder (Git) desktop icon, and tried to import the problematic RSS feed URL, but encountered the same error as before (sslv3 alert handshake failure).  I then gave a try to executing the git clone gPodder with python2.7, but got:
```
dan@varmint /usr/src/gpodder/bin $ python2.7 gpodder

    Warning: python-dbus not found. Disabling D-Bus support.
  
  Error: Module "sqlite3" not found.
         Build Python with SQLite 3 support or get it from
         http://code.google.com/p/pysqlite/
```
Not sure why it couldn't find sqlite3 since that should be[ included in the standard 2.7.13 library I built](http://stackoverflow.com/questions/19530974/how-can-i-install-sqlite3-to-python), but I must be, once again, missing something fundamental.

If you think I'm getting fairly close to having this figured out, and are willing to continue trying to help, then please let me know if you have any more words of wisdom.  I did find that one of the music apps I use, Clementine, was able to successfully process the RSS URL for the podcast in question, so I could use that if you think I'm a lost cause for getting the Python route figured out.  My preference, though, would be to use gPodder because I like the interface (much better than Clementine), the "Sync to Device" option makes it easy to get my podcasts onto a flash drive for use in my car, and I can imagine that I might encounter this same problem with other podcast web sites down the road.

**Comment by vossad01** [comment]
Thanks for doing your research!  According to [this comment on the answer you linked sqlite3 support may be conditional on presence of a system package at compile time.](http://stackoverflow.com/questions/19530974/how-can-i-install-sqlite3-to-python#comment60138964_19530987)  I don't have experience to know whether that is applicable to Python 2, but it conceivably could, so you would need to install that package then rebuild your Python 2.  Does your local Python install provide `pip`?  If [so you you can try the other answer to that question](http://stackoverflow.com/a/28959692/1072626)?  If not you could try installing pip into it or you could manually download and install the [package](https://pypi.python.org/pypi/pysqlite) manually. (Alternatively, options 2 and 4 would be equally valid for gaining access to not gPodder dependencies.)

Now that you have the git clone, I think the path of least resistance would be try the `gtk3` branch.  Then you would be back on a system-installed Python so would not have to worry about ensuring every dependency in your own install.  If that cannot be made to work, all you have to do to switch back is run `git checkout master` and you will be back where you started with to the Python 2 based version (the action you took regarding mygpoclient will not need to be reverted).

**Comment by dannn-o** [comment]
Well, your patience has paid off, as I believe I've got the git clone / gtk3 branch installation working successfully.  I was able to load the podcast RSS feed that had been giving the 'sslv3 alert handshake failure', and it appears that all of my previously-added podcast libraries are in tact.  

So far, I did encounter one (minor) error:  after downloading an episode of the podcast I just added, when the download was complete, an error appeared saying:
```
Unhandled exception
Please report this problem and restart gPodder:
boxed cannot be created directly; try using a constructor, see: help(Gtk.TreeRowReference)
```
After clicking OK to this error, the podcast episode was still showing in the "Progress" tab with a green checkmark by it.  I believe entries there are normally deleted after a successful download, if I remember correctly.  The title bar also still showed "94%" complete, with the last download speed, in parentheses.  I then restarted gPodder, and the entry was no longer visible under the Progress tab, and everything appeared normal to me.

Could my environment still not be complete, or is this possibly a bug with the gtk3 version?   Let me know if you would like any screen captures or other data.  BTW - I like the reorganization of the menu with the gtk3 layout.

**Comment by vossad01** [comment]
@dannn-o I'm glad to hear your SSL issue is resolved.  Would you do me the favor of opening a new issue with the Progress tab issue you have encountered?  I think it is most likely a bug in the gtk3 branch.

Particularly helpful would be if you could give the stack trace that corresponds to the error.  If you launch gPodder from the console, you will see error messages and details there.  If you started it from a desktop icon (or such) there should be a **Logs** folder in **GPODDER_HOME** (where your gPodder database lives) that should have the information if you find the right log.

**Comment by dannn-o** [comment]
Incident #274 has been opened for the "Unhandled Exception" error.

After downloading some additional podcast episodes, I attempted to "Sync to device" (to transfer new episodes onto my 32 GB USB flash drive).  However, after gPodder creates the playlists on the flash drive (which I have enabled within the "Preferences"), all further activity with the flash drive ceased.  The "Progress" tab shows the queued episodes, but none of the progress indicators show movement, and the flash drive LED stops flashing.  

This had always worked fine with the Python 2 version.  Is there anything you can think of for me to investigate, or is this possibly a different bug?

**Comment by vossad01** [comment]
@dannn-o I am closing this because we have worked past the SSL issue.  Please open new issues for anything else you encounter, as they will be more likely to get attention that way.  Thanks!
