### ISSUE TITLE
podcastparser should not return HTML in description

### ISSUE THREAD

**Issue by adamvoss** [gpodder/gpodder#267]
`podcastparser` should not return an episode `description` as HTML.  HTML should be provided under `description_html` while `description` should not be HTML.

Providing HTML under `description` requires downstream clients to handle it such as at https://github.com/gpodder/gpodder/blob/master/src/gpodder/model.py#L153

**Comment by vossad01** [comment]
Relevant: [more complete suggestions on html detection](http://stackoverflow.com/q/15458876/1072626).

**Comment by elelay** [comment]
This has been fixed and released in podcastparser.
