### ISSUE TITLE
Indicate Python 2.7.9 as minimum required Python version

### ISSUE THREAD

**Issue by adamvoss** [gpodder/gpodder#269]
It could be helpful to indicate Python 2.7.9 or newer is needed on the website (instead of just 2.7).  While gPodder will run with Python < 2.7.9, users will encounter SSL errors that we do not have control over (ex. #234, #265).  I expect this to only increase as websites become more secure.  I have not experienced any resistance yet that we don't somewhere say 2.7.9 will be needed, but might be good to cover the bases.

If you would be interested, I could import the website into GitHub Pages, so PRs could be submitted against it.  The only real complication would be switching over the DNS entry when done.

**Comment by elelay** [comment]
We should also change it in the README.

**Comment by adamvoss** [comment]
Resolved.
