### ISSUE TITLE
Use urllib2 for downloading podcasts

### ISSUE THREAD

**Issue by rjhorn-agfa** [gpodder/gpodder#285]
This is an enhancement request based on tracking down what was happening with https://github.com/gpodder/gpodder/issues/244 .  Can the podcast download code be switched to use urllib2, instead of the current urllib.

Some portions of gPodder already use urllib2, but the download still uses urllib.  There is a bug in urllib traversing some HTTP proxies.  This bug is fixed in urllib2.  (Test results are in the https://github.com/gpodder/gpodder/issues/244 issue.)

The developmental gtk version of gPodder also uses urllib, not urllib2, and has the same downloading problem.

**Comment by vossad01** [comment]
As I understand it, `urllib2` is a separate library and not directly related to `urllib`.  My looking showed that `urllib2` is really only used for [**mygpo**](https://github.com/gpodder/mygpoclient) and everything else in gPodder uses `urllib`.  It is interesting this extends into Python 3 as well; there is not even a `urllib2` in Python 3.

If this is a bug in `urllib` it would be best to get it tracked and fixed upstream.  All we know at this point is that in one particular environment one of the libraries works and the other fails.  Without knowing more, it seems just as likely that we could switch it and break things for another environment.

I note that the documentation for both [`urllib`](https://docs.python.org/2/library/urllib.html) and [`urllib2`](https://docs.python.org/2/library/urllib2.html) indicate [requests](docs.python-requests.org) as the recommended high-level API.  If a push it to be made to switch the API, perhaps that would be the best choice?

**Comment by rjhorn-agfa** [comment]
The response upstream seems to be "urllib is beyond fixing.  use urllib2". 
 In Python 3 the modules were re-structured into "urllib.request" and 
"urllib.error".  The 2to3 tool does that conversion.

Kind Regards,

Robert Horn | Agfa HealthCare
Interoperability Architect | HE/Technology Office
T  +1 978 897 4860

Agfa HealthCare Corporation, Gotham Parkway 580, Carlstadt, NJ 07072-2405, 
USA
http://www.agfahealthcare.com
http://blog.agfahealthcare.com
Click on link to read important disclaimer: 
http://www.agfahealthcare.com/maildisclaimer

**Comment by vossad01** [comment]
> The response upstream seems to be "urllib is beyond fixing.

I would be interested in reading more, do you have a source or citation for that?  You indicated that the problem still exists under Python 3, so it almost sounds like the Python maintainers are abandoning this functionality without deprecation.

**Comment by elelay** [comment]
urllib api (FancyURLopener) is deprecated since python 3.3.

**Comment by elelay** [comment]
Also, for instance https://bugs.python.org/issue1368368 where in 2010 they broke compatibility on FancyURLopener.prompt_user_passwd() in the python3 branch.

**Comment by elelay** [comment]
gPodder will use requests and urllib3 from now on
