### ISSUE TITLE
Handshake fail with NYT's The Daily

### ISSUE THREAD

**Issue by brownbat** [gpodder/gpodder#289]
Not sure if this is just me, or if it's on NYT's end, but could someone let me know if they are able to successfully download any episodes from this feed:

http://feeds.podtrac.com/zKq6WZZLTlbM

gpodder is able to grab the feed info and the file size for me, but on download fails with:

    Failed: I/O Error: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure: None - The Daily

Sorry if this shouldn't be an issue. Still needs confirmation and it's a new podcast, so very likely isn't on gpodder's end...

**Comment by vossad01** [comment]
@brownbat You will need to update your Python 2 version to at least 2.7.9.  Please see #234 (Windows), #254/#265 (Linux)

**Comment by brownbat** [comment]
Oh thanks, sorry for the oversight. I pretty much just use 3 so my maintenance of 2 is pretty weak...
