### ISSUE TITLE
Youtube: Notification window for failed download should show podcast name

### ISSUE THREAD

**Issue by phobeus81** [gpodder/gpodder#296]
Especially when using gpodder to download lots of youtube channels, it can happen that some channels are closed and are not available anymore. In this case gpodder will fail to retrieve a new list of videos from that channel and a notification window is shown giving the URL that was attempted to download. As channel ids are difficult to read and most notification are closed when clicking on it in order to copy the text into the clipboard, this makes it very difficult to identify the affected channel.

Instead of just showing the URL that failed to download videos, the notification should also contain the podcast name, making it easier to identify what download exactly failed, so the user can investigate the reasons more easily.

While it should be fairely easy to implement, this might increase the user experience quite a lot.

**Comment by auouymous** [comment]
```
diff --git a/src/gpodder/gtkui/main.py b/src/gpodder/gtkui/main.py
index a58c13b9..495b94c7 100644
--- a/src/gpodder/gtkui/main.py
+++ b/src/gpodder/gtkui/main.py
@@ -2574,11 +2574,11 @@ class gPodder(BuilderWidget, dbus.service.Object):
                     channel.update(max_episodes=self.config.max_episodes_per_feed)
                     self._update_cover(channel)
                 except Exception as e:
-                    d = {'url': cgi.escape(channel.url), 'message': cgi.escape(str(e))}
+                    d = {'title': cgi.escape(channel.title), 'url': cgi.escape(channel.url), 'message': cgi.escape(str(e))}
                     if d['message']:
-                        message = _('Error while updating %(url)s: %(message)s')
+                        message = _('Error while updating %(title)s at %(url)s: %(message)s')
                     else:
-                        message = _('The feed at %(url)s could not be updated.')
+                        message = _('The %(title)s feed at %(url)s could not be updated.')
                     self.notification(message % d, _('Error while updating feed'), widget=self.treeChannels)
                     logger.error('Error: %s', str(e), exc_info=True)
 
```

**Comment by elelay** [comment]
@auouymous great, thanks. Could you make a pull request out of it?

**Comment by auouymous** [comment]
I don't have the time to learn how to do pull requests. Is that a problem even if I don't want credit for the patch?

**Comment by elelay** [comment]
OK, no pb. I'll commit it.

**Comment by phobeus81** [comment]
And also from me many thanks for that patch. Its nice to see that it is handled now :)
