### ISSUE TITLE
gpodder GUI does not update progress tab (ubuntu 17.04)

### ISSUE THREAD

**Issue by geejaytee** [gpodder/gpodder#298]
Running gPodder on ubuntu 17.04 - the GUI does not update the progress tab. The progress bars show file still downloading, even once finished, and I have to remove the entries in the progress tab through the right-click context menu (which forces a redraw to update the other progress bars)

This is probably due to the change in unity version from 16.10 -> 17.04, as I've had similar issues with other programs following upgrade.

**Comment by elelay** [comment]
Can't reproduce with gPodder 3.10.1-1 in Ubuntu 18.04 LTS VM
