### ISSUE TITLE
gPodder opens as blank window

### ISSUE THREAD

**Issue by allanmcpherson** [gpodder/gpodder#299]
After an attempt to move my download directory for gPodder to my internal SSD, when I try to open gPodder, all I get is a blank window. At the same time, I started having issues with the Software Centre. I can pull up the list of installed software, and I can search for software, but when I click on the "more information" or "install/uninstall" button, nothing happens.

I've uploaded a screenshot to better illustrate the problem.

![screenshot_from_2017-05-03_09-33-25](https://cloud.githubusercontent.com/assets/22438472/25729652/f1f4e828-30f3-11e7-8ac5-b85876cd0db2.png)

**Comment by allanmcpherson** [comment]
A little searching yielded results for issues with the Software Centre. Running this command fixed that issue, but not the issue with gPodder:

`sudo apt-get update && sudo apt-get install --only-upgrade gnome-software`

**Comment by elelay** [comment]
Can you run gpodder from the command line?
```
gpodder -v
```
Thanks,

**Comment by allanmcpherson** [comment]
No change. Here's the output from the command line.
`1493985857.960672 [gpodder.log] DEBUG: ==== gPodder starts up (ui=gtk) ===
1493985857.965160 [__main__] INFO: Activating existing instance via D-Bus.
`

**Comment by allanmcpherson** [comment]
The problem has resolved itself as mysteriously as it arose.
