### ISSUE TITLE
Failed downloads of Nature Podcast

### ISSUE THREAD

**Issue by schlindb** [gpodder/gpodder#302]
For a few days now the Nature Podcast http://www.nature.com/nature/podcast/rss/nature.xml does not download any more with gpodder (works with other podcast clients)
![screenshot_20170513_105259](https://cloud.githubusercontent.com/assets/26975273/26024098/d6f5ea94-37ca-11e7-9ef3-6ca960968953.png)

**Comment by elelay** [comment]
You will need to update your Python 2 version to at least 2.7.9. Please see #234 (Windows), #254/#265 (Linux).


The mp3 hosting server ads-creative-cdn.acast.comads-creative-cdn.acast.com requires Server Name Identification, which is not supported on older python versions.
From the command line:
````
openssl s_client -connect ads-creative-cdn.acast.com:443
````
fails in initial handshake, while
````
openssl s_client -connect ads-creative-cdn.acast.com:443 -servername ads-creative-cdn.acast.com
````
succeeds.

**Comment by schlindb** [comment]
Thank you for your quick answer and your assistance.

Sorry, but I have Python 2.2.27 installed.
Could there be a problem as I have Python 3.5 installed as well?

About the problem with the Nature Podcast: I did not have this error untill lately and I do not have the problem with all my other feeds. There doesn't seem to be anything wrong with the podcast, it's alive.

**Comment by schlindb** [comment]
sorry, the Python is version 2.7.13

**Comment by schlindb** [comment]
So, I reinstalled everything anew: Python, Pygtk, Gpodder - and it downloads again!!

**Comment by elelay** [comment]
@schlindb thanks for the follow up.
