### ISSUE TITLE
Stuck in activation loop

### ISSUE THREAD

**Issue by procyon12lotor** [gpodder/gpodder#303]
Deleted my account to quickly reset settings, and now:

-Cannot re-register account because username and email address are already taken.
-Cannot log into account on any synced devices.
-Cannot log into website, because my account needs activation which results in the following email.

> Click on the link below to activate your account on gpodder.net
> 
> https://gpodder.net/activate/None

-Cannot activate account because the link in the email "https://gpodder.net/activate/None" doesn't work.

Would be nice to have some way of releasing my account. I don't really want to have an entire email address only for this account.

Login is "rodneybblack". Is there a way to free the email address associated with this account?

**Comment by vossad01** [comment]
Pinging @stefankoegl since I have gathered from context that he is the maintainer of gpodder.net/mygpo.

**Comment by rxccxxn** [comment]
Thanks vossad01. @stefankoegl
Update: I just tried to activate again, and I receive the same email with the broken link to activate, so there is not a 24-48 hour cooldown for re-registration.

**Comment by adamvoss** [comment]
This issue was moved to gpodder/mygpo#48
