### ISSUE TITLE
gPodder requires python 2.7

### ISSUE THREAD

**Issue by Uo124** [gpodder/gpodder#304]
Hi, I have installed gPodder on windows, and python [64bits].
How can gPodder find python?
I couldn't find any answer or help installing, in the website.

**Comment by vossad01** [comment]
Adding [Python to PATH should suffice](https://stackoverflow.com/a/6318188/1072626).  There was probably a checkbox offering to do this automatically during you Python install.  You will need to log out and log back in (or just restart) after you make this change.

**Comment by vossad01** [comment]
> python [64bits]

I missed that you indicated a 64-bit python.  gPodder for Windows requires a 32-bit Python. The gPodder launcher is a 32-bit application so will need to call 32-bit code and it is not clear if PyGTK (which is needed for the gPodder gui) supports 64-bit Python on Windows.

**Comment by Uo124** [comment]
Thank you! It's working
