### ISSUE TITLE
Runtime error R6034

### ISSUE THREAD

**Issue by smaragdus** [gpodder/gpodder#305]
When **gPodder** version **3.9.3** starts it triggers an error message:
```
Runtime Error!

Program: C:\Portable Programs\gPodder\App\gPodder\gPodder.exe

R6034
An application has made an attempt to load the C runtime library incorrectly.
Please contact the application's support team for more information.
```
[Screen](https://s20.postimg.org/h7o93w0zx/g_Podder_3.9.3_-_2017-05-25_-_error_-_001.png)

![Screen](https://s20.postimg.org/h7o93w0zx/g_Podder_3.9.3_-_2017-05-25_-_error_-_001.png)

Possible solution:

[C Run-Time Error R6034](https://msdn.microsoft.com/en-us/library/ms235560(v=vs.90).aspx)

**Comment by vossad01** [comment]
It appears you are using [PortableApps](https://portableapps.com/apps/internet/gpodder_portable) which is a third-party packaging of gPodder.  Does this issue also occur with the official distribution from http://gpodder.org/?

Also, can you provide information on what version and edition of Windows this was experienced on?

**Comment by smaragdus** [comment]
**@vossad01**

Yes, you are right, the error message was generated by the unofficial PortableApps version and I used it mainly because it is portable and it is bundled with **Python** and **PuGTK**.

In order to test the official version I installed all the dependencies (however **gPodder** didn't like **Python x64** and insisted on **Python x32** so I had to install it too) and **gPodder** installer (**gpodder-3.9.3-setup.exe**). The problem persisted:

[Screen](https://s20.postimg.org/rveogvnrh/g_Podder_3.9.3_-_2017-05-25_-_error_-_002.png)

![gpodder 3 9 3 - 2017-05-25 - error - 002](https://cloud.githubusercontent.com/assets/9025757/26470186/78fb2fe6-41a5-11e7-9a6b-8a2200f8ba67.png)

However when I close the error message **gPodder** runs just fine.

My system- Windows 8 x64.

**Off-topic**

The developers may consider bundling all the necessary dependencies in a single package like for example [Pidgin](https://pidgin.im/)- running through 3 heavy **MSI** installers is not fun.

**Comment by JohnTHaller** [comment]
The copy of gPodder within gPodder Portable is unmodified with the exception of the addition of the msvcp100.dll, msvcr100.dll, and python27.dll files necessary for it to run on systems without the appropriate Visual C runtimes or Python installed locally.  You can try removing them and running gpodder.exe directly to see what the error would be on a standard unzipped version of gPodder (it will likely give you a different error).  Please post what that error is.

In theory, this sort of error should be impossible with an application compiled correctly as version 10 and up of the runtime isn't supposed to include a manifest.  We used to add the manifests to gpodder.exe when it used msvcr90 to allow it to run correctly in side by side DLL mode but stopped when the app switched to 10.  Is there a chance that some portion of the Visual C++ runtimes is registered improperly on your system?

Note that I am unable to reproduce this on my Windows 10 Pro x64 production box nor on a Windows 10 Enterprise virtualbox image from the IE virtual machine test images (in theory a clean VM image from Microsoft).

**Comment by smaragdus** [comment]
**@JohnTHaller**

Deleting **msvcp100.dll** and **msvcr100.dll** generates the same error message, while deleting **python27.dl** shows the standard message:
```
gPodder requires Python 2.7.
See http://gpodder.org/dependencies
```
> Is there a chance that some portion of the Visual C++ runtimes is registered improperly on your system?

It is possible. I have several different versions of **Visual C++** installed (in fact 9 versions) because they are e required by different programs and some were installed automatically with other installations.

**Comment by smaragdus** [comment]
**@vossad01** & **@JohnTHaller**
If you think this problem is specific to my system please close this ticket.

**Comment by vossad01** [comment]
@smaragdus I believe it is specific to your system and I do not have the Windows programming background that would be needed to help you debug the issue.

**Comment by JohnTHaller** [comment]
Looking into this further, I think this could be due to a misconfiguration in the side by side DLL setup with the included Python.  I've prepared a test build of what I think may solve this issue for you if you could please try it: https://downloads.sourceforge.net/portableapps/gPodderPortable_3.9.3_Rev_2_Dev_Test_1.paf.exe

**Comment by smaragdus** [comment]
**@JohnTHaller**
Thank you for investigating this problem further.
I tested the test build (**gPodderPortable_3.9.3_Rev_2_Dev_Test_1.paf.exe**), the same error message appeared again. I am more and more inclined to think that the problem is hard to reproduce on other systems. So when I have time I will uninstall all **Visual C++** versions and then install some several and then check whether this would resolve this problem. Once again- thank you for taking your time to search for explanation and solution.

**Comment by JohnTHaller** [comment]
@smaragdus - Ok, since this isn't an issue with gPodder itself, I'm going to stop posting anything additional here.  If you find the issue or would be up for some additional troubleshooting steps, please post in the PortableApps.com Forums and I'll assist further as I can.  If there's anything further that's specific to your system you can think of, please include that as well.  Even if it's only a small number of PCs affected by this, if we can include a fix in gPodder Portable to address it, I'd like to.

**Comment by kireta** [comment]
Just installed Gpodder 3.9.6 on Windows 7 64 bit, latest updates installed, with Python 2.7.13 and pygtk-all-in-one-2.24.2.win32-py2.7. 

Get R6034 error on start-up of GPodder

Just reporting that this in an issue with this configuration.

Hopefully someone can figure out the issue. Not sure if occurs on Win 10
