### ISSUE TITLE
Missing Podcast Episodes

### ISSUE THREAD

**Issue by bigt2000** [gpodder/gpodder#309]
I am running into a consistent issue where episodes will disappear from the episode list in Gpodder, but the files still exist in the folder location on my drive.  I can't figure out what is causing this as it seems to effect both unplayed and played episodes.  

I am running windows 10 version 1607.  This has been an ongoing issue for about a year.

**Comment by adamvoss** [comment]
Can you provide feeds this has happened with?

**Comment by bigt2000** [comment]
Sure.  Do you just want the names of the podcasts or something else?  It 
seems to happen with all feeds.

------ Original Message ------

**Comment by adamvoss** [comment]
What would be most helpful would be a examples of specific feed urls, with specific episode identification (if possible, may not be if it has completely disappeared, even knowing between episode X and episode Y would be useful), and the file name of the file that was left behind.

**Comment by lmjk** [comment]
I have been affected by a similar problem for a very long time, too. Every now and then gPodder has been forgetting that it has downloaded a few podcast episodes already. After checking for new episodes I have noticed sometimes that it has started to download some episodes as new – episodes I may have already listened.

Today I encountered the episode amnesia again and investigated it a little. There were at least three relatively recent episodes that I remembered having been downloaded before (and two of which I had listened), but now gPodder showed them all as new and not yet downloaded.

The other of the episodes I had both downloaded and listened is titled 'Ihminen ja kieli' (2017-09-09) from the feed [http://feeds.yle.fi/areena/v1/series/1-1853467.rss](http://feeds.yle.fi/areena/v1/series/1-1853467.rss) (which redirects to https nowadays, I see). The feed file: [https-1-1853467.rss.zip](https://github.com/gpodder/gpodder/files/1303120/https-1-1853467.rss.zip)

Looking in the podcast's downloads folder `~/gPodder/Downloads/Kalle Haatanen/` I found that the before downloaded episode file was still there (with the new download partial) so it had not been deleted:

    Size  Modification time           File name
      0   2017-09-14 11:42:36 +0300   f5334dd1608b456a819fa80dd74d6641.mp3.partial
    49M   2017-09-09 18:35:59 +0300   f5334dd1608b456a819fa80dd74d6641.mp3


In `~/gPodder/Logs/` I found a file `2017-09-14.log` which contained several lines with `WARNING: Unknown external file`, including this one for the above file:

    2017-09-14 11:39:15,638 [gpodder.model] WARNING: Unknown \
        external file: /home/lassi/gPodder/Downloads/Kalle Haatanen/\
        f5334dd1608b456a819fa80dd74d6641.mp3


Other remarks:

*   Network connection went down while downloading new episodes last time (2017-09-09).
*   Downloads were resumed or new episodes rechecked and downloaded after network was back.
*   GPodder may possibly have been running without restart from that last time until today. (Can't remember.)
*   Today I canceled the re-downloads and restarted gPodder some time later. The forgotten files seemed to be found again. They all were marked new, however.


System: Linux, Fedora 26, x86_64  
gPodder version: 3.9.3 (gpodder-3.9.3-2.fc26.noarch)

**Comment by lmjk** [comment]
Seems related: https://github.com/gpodder/gpodder/issues/210

**Comment by andrew-karapostolakis** [comment]
This has happened to me as well. The episodes in question are episodes 59 (Cortex_059.mp3) and 60 (Cortex_060.mp3) of Cortex (https://www.relay.fm/cortex/feed) as well as episodes 46 (Remaster_046.mp3) and 47 (Remaster_047.mp3) of Remaster (https://www.relay.fm/remaster/feed). There are a few log files from the past few days. At the top, each says:

    WARNING: Could not find gpod
    WARNING: Could not find eyed.mp3
These are followed by several lines beginning with `WARNING: Unknown external file`. Some of these refer to the missing episodes, but some refer to episodes that do appear in gPodder.

The log files are attached here:
[2017-11-20.log](https://github.com/gpodder/gpodder/files/1503471/2017-11-20.log)
[2017-11-22.log](https://github.com/gpodder/gpodder/files/1503472/2017-11-22.log)
[2017-11-24.log](https://github.com/gpodder/gpodder/files/1503473/2017-11-24.log)
[2017-11-25.log](https://github.com/gpodder/gpodder/files/1503474/2017-11-25.log)

**Comment by andreas-31** [comment]
I'm running into the same situation: for some subscribed feeds all but two episodes have disappeared from the episode list in the gPodder GUI. When looking into the log file I can see many entries like these:
`2018-09-03 06:58:02,766 [gpodder.model] WARNING: Unknown external file: /home/pi/gPodder/Downloads/hr-iNFO Wissenswert/hrinfo_wissenswert_20170611_74621497.mp3`
`2018-09-03 06:58:02,769 [gpodder.model] WARNING: Unknown external file: /home/pi/gPodder/Downloads/hr-iNFO Wissenswert/hrinfo_wissenswert_20150711_73412690.mp3`
`2018-09-03 06:58:02,771 [gpodder.model] WARNING: Unknown external file: /home/pi/gPodder/Downloads/hr-iNFO Wissenswert/hrinfo_wissenswert_20160709_69464125.mp3`
`2018-09-03 06:58:02,773 [gpodder.model] WARNING: Unknown external file: /home/pi/gPodder/Downloads/hr-iNFO Wissenswert/hrinfo_wissenswert_20171029_76559821.mp3`

As far as I can tell, the files listed in these warnings are the episodes that have disappeared from the GUI although they are still stored on disk.
[2018-09-03.log](https://github.com/gpodder/gpodder/files/2344277/2018-09-03.log)

I have approx. 30 subscriptions. For some reason, only three subscriptions are concerned:
http://podcast.hr-online.de/hr-info_fit_gesund/podcast.xml
http://podcast.hr-online.de/hr_info_explorer/podcast.xml
http://podcast.hr-online.de/hr2_wissenswert/podcast.xml
Interestingly, all from the same site/provider.

gPodder version is 3.9.3 (2016-12-22). This is the version that gets installed by running "apt-get install gpodder" on Raspbian Stretch (2018-06-27).

**Comment by elelay** [comment]
@andreas-31 the podcast  http://podcast.hr-online.de/hr_info_explorer/podcast.xml seems broken to me: the `guid` element of the `item` elements should contain the guid as text content, not as a `guid` attribute. This mistakes makes all episodes with the same (empty) guid, preventing them from being inserted in the episode database : they appeared the time I added them to gPodder, but were missing at  the next reload.
References:
http://www.rssboard.org/rss-profile#element-channel-item-guid
Wrong content:
```
    <guid isPermaLink="true" guid="http://mp3.podcast.hr-online.de/mp3/podcast/hrinfo_wissenswert/hrinfo_wissenswert_20140927_56167587.mp3"/>
```
Should be:
```
    <guid isPermaLink="true">http://mp3.podcast.hr-online.de/mp3/podcast/hrinfo_wissenswert/hrinfo_wissenswert_20140927_56167587.mp3</guid>
```

**Comment by elelay** [comment]
This must be a recent bug on hr-online.de site, causing your episodes to disappear...

**Comment by andreas-31** [comment]
@elelay Thanks for looking into this! I will keep an eye on the hr-online.de podcasts. Maybe I can get them to correct the XML syntax. If I should notice the behavior of disappearing episodes with other podcasts, I will make a new comment.

**Comment by elelay** [comment]
@andreas-31 thanks for raising the issue to them. They should definitely fix it...

**Comment by elelay** [comment]
podcast still broken. Closing the issue now.
