### ISSUE TITLE
Update third party apps

### ISSUE THREAD

**Issue by psamim** [gpodder/gpodder#312]
Hi,
Third party apps in the Github wiki is a link to the old wiki which is very out-dated.
Thanks

**Comment by adamvoss** [comment]
I believe [this](http://wiki.gpodder.org/wiki/Web_Services/Clients) is the indicated page.

@stefankoegl this is one of the pages in limbo pursuant to https://github.com/gpodder/gpodder/issues/218#issuecomment-276472167.

@psamim Do you have specific issues with the page? Would you be willing to help update it?  I will move it to the new wiki if you are.

**Comment by psamim** [comment]
Yes! I headed to update the Wiki and saw the message that it is being migrated to Github.

I wanted to add one app which was missing, [SoundWaves](https://github.com/bottiger/SoundWaves). Also some others are deprecated like the Mopidy plugin.

I would be happy to help.

**Comment by adamvoss** [comment]
Awesome, thanks!  It's late here and I'm on mobile, but I'll move it first thing tomorrow then let you know.

**Comment by adamvoss** [comment]
@psamim Happy Editing! https://github.com/gpodder/gpodder/wiki/Web-Service-Clients

**Comment by elelay** [comment]
@psamim it seems you had access and modified the page.
Can we close this?
