### ISSUE TITLE
Cannot open gPodder because PyGTK installation not found

### ISSUE THREAD

**Issue by VFA-87** [gpodder/gpodder#313]
I already have PyGTK & Python 2.7 installed

**Comment by adamvoss** [comment]
@VFA-87 I'm sorry to hear you are encountering difficulties.  Can you please provide specifics?

**Comment by VFA-87** [comment]
When I open up the regular gPodder program it says that the PyGTK installation is not found. When I open up gPodder (CLI) it pops up briefly saying this:

![gpodder](https://user-images.githubusercontent.com/13461863/27000393-21706430-4d76-11e7-9601-aa78ae2b1c76.PNG)

**Comment by adamvoss** [comment]
@VFA-87 The fastest possible solution is probably to uninstall Python and PyGTK then reinstall them using the download links on our website.

If you want to troubleshoot your existing installation:
- Are you sure you are not using a 64-bit version of Python (#304)?  The fact it is failing to load a ctype makes me wonder if it is not a 64-bit process trying to load a 32-bit dll.
- If it is not that, [these steps](https://github.com/gpodder/gpodder/issues/191#issuecomment-266855709) would be relevant in trying to get more information on what is happening.

**Comment by VFA-87** [comment]
OK, I did the steps and this is what happened:
![cmd_2017-06-11_23-31-47](https://user-images.githubusercontent.com/13461863/27019452-3b25846c-4efe-11e7-8016-8402867fb4e6.png)

**Comment by bonkeman** [comment]
I also have this problem. Says "gPodder requires PyGTK". I have downloaded and installed both Python and PyGTK, following the links on your website. Any ideas?

![image](https://user-images.githubusercontent.com/29395946/27070738-83107d00-501a-11e7-9f66-8bbacba53e5b.png)

**Comment by adamvoss** [comment]
@VFA-87 That seems to indicate your dependencies are good.  The next step I can think of would be to ensure gPodder is on Python's path and then import it from the Python REPL.  I'd need to get to a windows box to work out for certain how to to that.  I expect it is along the lines of editing PYTHONPATH and then doing `import gpodder`.

**Comment by msl86131** [comment]
I had this exact same issue. I solved it by uninstalling everything, rebooting, then making sure the "install for all users" was checked, in addition to the "add python.exe to path" was checked. I also selected for everything in the GTK to be installed, instead of the default selection. Now it works for me.

**Comment by elelay** [comment]
Python and Gtk are bundled in the install directory since 3.10.2
