### ISSUE TITLE
Copying Podcasts to mp3 Player

### ISSUE THREAD

**Issue by merriander** [gpodder/gpodder#315]
When I have downloaded the podcasts I want I have found the easiest way to copy them to my Sansa Clip player is to select the multiple files in the Episode list and right click to select "Send to Local Folder" where I can pick out my player. This works well apart from having to click Save each time the next podcast is ready to be copied across. Is it possible to have a Save All option?

**Comment by elelay** [comment]
This is implemented in the gtk3 branch. It will be in next release.
Cheers,
