### ISSUE TITLE
Can't parse a specific feed (WarOnTheRocks)

### ISSUE THREAD

**Issue by PeteLawler** [gpodder/gpodder#316]
Hi!
https://warontherocks.com/feed/ seems to validate, albeit with Recommendations https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwarontherocks.com%2Ffeed%2F but I can't seem to get gpodder.net to find it, https://gpodder.net/search/?q=https%3A%2F%2Fwarontherocks.com%2Ffeed%2F or if I use the straight up http version of the feed it's empty http://gpodder.net/search/?q=https%3A%2F%2Fwarontherocks.com%2Ffeed%2F

Maybe the backend is broken idk, suggestions?

**Comment by elelay** [comment]
Hi,
are you using a gPodder client or only gpodder.net?

Besides, there is no attached content to episodes.
gPodder is a podcatcher, not an RSS reader. So it will ignore all the episodes of this podcast.

**Comment by PeteLawler** [comment]
Oh right duh yeah I should have realised. Totally my bad at misunderstanding...

**Comment by elelay** [comment]
No worries :-)
