### ISSUE TITLE
Running scripts on download

### ISSUE THREAD

**Issue by Moilleadoir** [gpodder/gpodder#317]
The [User Manual](https://github.com/gpodder/gpodder/wiki/User-Manual#advanced-topics) suggests that you can run a script/external program using the variable `cmd_download_complete` in the Configuration Editor, but that variable doesn’t appear in the Configuration Editor.

Is it still possible to do this? Do I have to edit a config file somewhere?

Ubuntu 14.04, gpodder 3.9.3

**Comment by elelay** [comment]
I'm afraid it's not available [since gPodder3](https://www.freelists.org/post/gpodder/cmd-download-complete).
Writing an extension is quite easy:
 - create an Extensions folder in your GPODDER_HOME
 - copy [normalize_audio.py](https://github.com/gpodder/gpodder/blob/master/share/gpodder/extensions/normalize_audio.py) to the Extensions directory you just created, with a new name
 - modify it to suit your needs.

Don't hesitate to ask for help in doing so.

**Comment by Moilleadoir** [comment]
Thanks, that sounds doable. Is GPODDER_HOME supposed to be an environment variable? I don’t have it, but ~/gPodder looks like the place.

Is there some documentation for writing extensions? For example, what info can I get about the episode that triggers the on_episode_download? Can I get the RSS URL of the podcast? That might be the most consistent identifier. I just want to trigger generating an M3U playlist for particular podcasts.

**Comment by adamvoss** [comment]
Yes, documentation on the environment variable is [here](https://gpodder.github.io/docs/user-manual.html#changing-the-downloads-folder-location-and-the-gpodder-home-folder); you've identified the default path correctly.  The most [documentation for writing extensions exists on the extensions page](https://gpodder.github.io/docs/extensions.html#how-to-write-your-own-extension). (Spoiler: it says TODO, but there is a link to a Hello World extension if that serves you better than the normalize_audio elelay pointed you at.)

**Comment by Moilleadoir** [comment]
I did look at the hello world example in the mean time and had a quick look at some of the gPodder code, but I’m still not clear on what info I can access. I only want to run this on particular podcasts, not on every thing that’s downloaded. If I have to read and understand all the source code then it’s probably not worth it and I can probably find another way.

**Comment by elelay** [comment]
See [model.py](https://github.com/gpodder/gpodder/blob/master/src/gpodder/model.py) for a definition of the `PodcastEpisode` that you get as the `episode` parameter. Also see [extensions.py](https://github.com/gpodder/gpodder/blob/master/src/gpodder/extensions.py#L397) for the declaration of all available extension methods.

episode has a `channel` property to get the `PodcastChannel`, also defined in `model.py`, which has a `url` field.

So you'd do
```python
def on_episode_downloaded(self, episode):
    print("DOWNLOADED AN EPISODE OF %s" % episode.channel.url) # debug message so you get the correct URL
    if episode.channel.url == 'http://my.target.podcast':
        generate_my_playlist()
```

And if you want to invoke external code to generate your playlist,
```python
cmd = ['/path/to/command', 'arg1']
p = subprocess.Popen(cmd, stdout=subprocess.PIPE,
		stderr=subprocess.PIPE)
stdout, stderr = p.communicate()

if p.returncode == 0:
	logger.info('command successful.')
	gpodder.user_extensions.on_notification_show(_('Playlist done'),
			episode.title)
else:
	logger.warn('playlist generation failed: %s / %s', stdout, stderr)
```

**Comment by Moilleadoir** [comment]
Thank you, that’s very helpful. I may even get some time to look at it soonish.

**Comment by elelay** [comment]
I'll make it an example extension.

**Comment by thp** [comment]
@elelay should the branch `command_on_download_ext` be a pull request?

**Comment by elelay** [comment]
Yep: #402.

**Comment by elelay** [comment]
@Moilleadoir The extension is now in master.
