### ISSUE TITLE
Followup on: "Can't add podcast feed #224"

### ISSUE THREAD

**Issue by Lakis01** [gpodder/gpodder#318]
Hi there,

since ARD changed their feed about a year ago, I can no longer listen to their podcast services. This issue was first brought up by the user "saigkill" in January.

To quote the response of the user "elelay" the problem seems to be: "This podcast is served with a bad content type: text/html instead of application/xml so gPodder thinks it's a web page containing a link to the actual feed. It doesn't find any link and fails."

http://www.tagesschau.de/export/podcast/tagesthemen/

In the following a bug report was submitted, the issue was closed but the problem wasn't resolved to my knowledge.

I am running ver 3.9.3 on Linux Ubuntu and I am wondering if the xml feed could be hardcoded - that is via terminal or by manually editing gpodder's config files. Any guidance on that or general advice is much appreciated!

Kind regards!

Markus

**Comment by adamvoss** [comment]
/References
* Referenced issue: #224
* Referenced tagesschau publishers bug: location unknown

* Possible work around: https://gpodder.github.io/docs/user-manual.html#using-yahoo-pipes-to-fix-feeds.  Don't know if that service exists, but it used to be the given instructions.  You may be able to find an alternative.

* Related issue: #225 
* Related pull request: #261 

Please follow up on the linked pull request.  Thanks!
