### ISSUE TITLE
Gpodder Manual link is broken

### ISSUE THREAD

**Issue by Gwillison415** [gpodder/gpodder#324]
when following this link - http://gpodder.org/docs/user-manual.html one will get a 404

in addition:
i'm a newish developer (so please excuse the possible dumb question) but i'm still not able to build a proper call to your API so i'm 8 hours into your [docs](http://gpoddernet.readthedocs.io/en/latest/api/reference/directory.html#retrieve-episode-data), they seem pretty extensive! however i'm not sure if the base URL is always ```http://feeds.gpodder.net```   OR ```https://gpodder.net/``` or differs based on the API  .

i'd suggest that below each sample response where you've got ```::query podcast-url: ``` hasn't illuminated for me where that'll go when building a query. Any help would be appreciated.. 

Thanks!

**Comment by adamvoss** [comment]
@Gwillison415 Thanks for the report!  I cannot fix the redirect, but I have changed all the links in the wiki to point to `gpodder.github.io` and the wiki is the only place those links should exist.

Regarding the API, it appears you are talking about the gpodder.net API, which I know nothing about.  However, you may be interested in [mygpoclient](https://github.com/gpodder/mygpoclient/), a Python library for interacting with that API.

Alternatively, you may find see gpodder/gpodder.github.io#9 helpful.  It links to the [Web Services pages on the old wiki](http://wiki.gpodder.org/w/index.php?title=Special%3APrefixIndex&prefix=Web+Services&namespace=0), which have not been moved to the website.  I would be surprised if there is much difference, but there is a chance the documentation would be out-of-date relative to the **mygpoclient** implementation.

**Comment by elelay** [comment]
The documentation is indeed outdated: query params are `podcast` and `url` .
e.g.
```
 http -v http://gpodder.net/api/2/data/episode.json "url==http://feedproxy.google.com/~r/themothpodcast/~5/2BXSb46ziM8/moth_451_mrh_1618_9_6_16.mp3" "podcast==http://feeds.feedburner.com/themothpodcast"
```

**Comment by Gwillison415** [comment]
Thanks so much for the responses! I really appreciate the help, and as a newer developer, the 'unknown-unknowns' were stacking up quick. as the calls kept failing. I'll have a look at mygpoclient! and again - big thanks for being able to address some of this for me @adamvoss  and @elelay

**Comment by adamvoss** [comment]
@Gwillison415 Happy to help!  It sounds like your immediate questions have been answered and the title-issue, "Gpodder Manual link is broken" has been fixed so I am closing this item.  Feel free to open another if needed.

**Comment by gandhiamarnadh** [comment]
@adamvoss @elelay I'm working on a ios app to use these services and I couldn't figure out a way to retrieve media .mp3 url. Is episode.josn service used for this? If so what should be value of query param url

**Comment by gandhiamar2** [comment]
@adamvoss @elelay I'm working on a ios app to use these services and I couldn't figure out a way to retrieve media .mp3 url. Is episode.josn service used for this? If so what should be value of query param url

**Comment by adamvoss** [comment]
@gandhiamar2 It sounds like this is about [gpodder.net](https://gpodder.net/).  Please open an issue over at https://github.com/gpodder/mygpo to get your question to the right audience.

**Comment by gandhiamar2** [comment]
@adamvoss sure thanks for the help!
