### ISSUE TITLE
can not sync with device on win10

### ISSUE THREAD

**Issue by Sheeperich** [gpodder/gpodder#325]
Hi there.
In my config files i can not get hold of my Windows Phone. I tried several things now but i just think that it's impossible to sync my phone with gpodder via usb.

The problem is the structure of windows. On my Linux system i can sync whatever i want because Linux mounts my phone the correct way. 
On Windows 10 my phone looks like that:
![gpodder](https://user-images.githubusercontent.com/21007581/27661598-31fa0aec-5c5b-11e7-993a-4288b96e777c.png)
So is there any way that i can acces my phone in gpodder?

regards

Emanuel

**Comment by adamvoss** [comment]
@Sheeperich this is an area PRs would certainly be welcome.  Even just confirmation that Python's IO can actually handle these paths on Windows confirming it is fault of gPodder's handling would be helpful.

> Is there any way that i can access my phone in gpodder?

As a workaround, before I switched to Linux, I always went to a folder first then copied the folder or files to my device.  It is also probably possible to somehow link a drive letter to the devise storage, but that seems awfully heavy just to make gPodder work.
