### ISSUE TITLE
Can't subscribe to some RSS feeds

### ISSUE THREAD

**Issue by michellichand** [gpodder/gpodder#326]
I've been getting the following issues on these RSS feeds:

"https://rss.art19.com/levar-burton-reads" gives me "https://rss.art19.com/levar-burton-reads: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>"

"https://rss.acast.com/moviemaintenance" similarly gives me "https://rss.acast.com/moviemaintenance: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>"

Removing the s lets me add the feed to gPodder, but trying to download an episode gives me a similar error.

**Comment by adamvoss** [comment]
I'm processing this from my phone, so please excuse the brevity.  I believe you will find you answer here: https://github.com/gpodder/gpodder/issues/289#issuecomment-296452228
