### ISSUE TITLE
Request: XML backup of blog

### ISSUE THREAD

**Issue by adamvoss** [gpodder/gpodder#328]
https://support.google.com/blogger/answer/41387?visit_id=1-636352382779818974-4144947015&rd=1

I don't know what the format looks like, but if I get the time, I would like to see if I can match blog entries to tags and use the blog to populate [GitHub Releases](https://github.com/gpodder/gpodder/releases) with descriptions.

Alternatively, this could also be used for [import into Jekyll](http://import.jekyllrb.com/docs/blogger/).

**Comment by thp** [comment]
Here you go: [blog-07-30-2017.xml.zip](https://github.com/gpodder/gpodder/files/1185938/blog-07-30-2017.xml.zip)

**Comment by adamvoss** [comment]
@thp @elelay Checkout https://github.com/adamvoss/gpodder/releases.  If that is desirable, I can do the same in this repository.

**Comment by elelay** [comment]
Looks great! Can you add the release date?

**Comment by adamvoss** [comment]
How's that?

**Comment by elelay** [comment]
That's perfect 👍

**Comment by elelay** [comment]
@adamvoss: can you replicate what you did on your repository to gPodder's repo?
Thanks,

**Comment by adamvoss** [comment]
I actually just checked on this the other day.  I do still have the code (thought I may have lost it with a computer).  I had just been waiting for @thp to sign off.

**Comment by thp** [comment]
@adamvoss yes, please do. i'm fine with that :)

**Comment by adamvoss** [comment]
Done!  Source is [gpodder-blog-migration](https://github.com/adamvoss/gpodder-blog-migration).  Happy to transfer the repository if you want it somewhere else.  Thanks for your help with this.
