### ISSUE TITLE
Unknown Podcast from XXXX

### ISSUE THREAD

**Issue by shooftie** [gpodder/gpodder#331]
I was having big problems when using GPodder alongside AntennaPod where [feeds were becoming duplicated]((https://github.com/AntennaPod/AntennaPod/issues/2267) ). I tracked this down to the BBC changing their URLs and thus GPodder assuming that these were new podcasts:

`http://www.bbc.co.uk/programmes/p002vsnk/episodes/downloads.rss`

became

`http://podcasts.files.bbci.co.uk/p002vsnk.rss`

The former simply redirects to the latter now.

I have been through most of my podcasts which used the old format and resubscribed using the new URL. However, all of the new URLs result in an 'Unknown Podcast from XXXX' on GPodder.net whilst AntennaPod can interpret the feeds perfectly, titles and images etc.

![image](https://user-images.githubusercontent.com/2161844/28489990-78562408-6f02-11e7-941b-44e238e23438.png)

I've seen this bug mentioned in AntennaPod [here](https://github.com/AntennaPod/AntennaPod/issues/771) and it was stated that:

> We take the title from the (RSS/Atom) feed, not from Gpodder.net itself. We do not sync any feed information apart from the feed's/episode's URL which are used as identifiers

With this being the case, what is AntennaPod doing that GPodder.net is not which enables it to recognise the title and image? I'm happy to send you anything that might help identify the issue, as a donator I am just keen to see this awesome project succeed.

**Comment by elelay** [comment]
I think it's because gpodder.net has not parsed the feed.
gpodder.net is composed of different components: one of them is handling episode status sync, another parsing title, description, etc. The latter is not run anymore or not on all feeds. @stefankoegl could explain it better.

**Comment by shooftie** [comment]
Thanks for responding positively.

Two more questions:

* Will the component responsible for parsing the title, description etc be rekindled or is it dead to the world?
* Would it be tricky to display tags as a comma separated list in the main 'subscriptions' list as I have somewhat mitigated the issue by tagging the feeds with their actual names and having them displayed would be a simple work around.
![image](https://user-images.githubusercontent.com/2161844/28491918-c59aa15c-6f2b-11e7-9a96-a790177a16be.png)

**Comment by shooftie** [comment]
![image](https://user-images.githubusercontent.com/2161844/28492213-a507dd1e-6f31-11e7-873d-7892476b4a43.png)

**Comment by elelay** [comment]
I have no idea if it would be possible.
You could also use the gPodder application on desktop.

**Comment by adamvoss** [comment]
This issue was moved to gpodder/mygpo#49
