### ISSUE TITLE
Soundcloud feed empty

### ISSUE THREAD

**Issue by fap-** [gpodder/gpodder#343]
I'm having issues with the soundcloud integration for some users.
For example this user: https://soundcloud.com/thisissomenoise-893392236
I can add him through the soundcloud search but the feed stays empty.
When I call the api myself I get a list of his tracks back:
`https://api.soundcloud.com/users/187068715/tracks?client_id={id}`

I'm running gpodder from git on the [latest commit](https://github.com/gpodder/gpodder/commit/051e1fab3b5354281fdae5aa986cb9a12b46e467)
I don't get any errors on the console or otherwise.

**Comment by elelay** [comment]
This user doesn't allow downloading her track.
See https://help.soundcloud.com/hc/en-us/articles/115003565708-Enabling-downloads-for-your-track for how she would enable it.
