### ISSUE TITLE
Can't show properties for a podcast with a corrupt image thumbnail

### ISSUE THREAD

**Issue by ideasman42** [gpodder/gpodder#349]
Currently running into a bug where a corrupt image prevents "RMB -> Podcast Settings" from opening.

I get the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gpodder/gtkui/services.py", line 120, in __get_cover
    pixbuf = gtk.gdk.pixbuf_new_from_file(filename)
GError: Failed to load image '/home/ideasman42/gPodder/Downloads/The Bugle/folder.png': Fatal error in PNG image file: iTXt: chunk data is too large
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/gpodder/gtkui/services.py", line 75, in <lambda>
    custom_url, True, avoid_downloading))
  File "/usr/lib/python2.7/site-packages/gpodder/gtkui/services.py", line 127, in __get_cover
    pixbuf = gtk.gdk.pixbuf_new_from_file(filename)
GError: Failed to load image '/home/ideasman42/gPodder/Downloads/The Bugle/folder.png': Fatal error in PNG image file: iTXt: chunk data is too large

```

This is the file: http://members.iinet.net.au/~ideasman42/random/folder.png

Although I expect any corrupt file will do.

Note that from checking the code it looks like this should fail gracefully. But currently the settings dialog fails to open. Edit, the thread seems to be waiting for a valid image - on moving a valid image into the directory. The dialogs open.

**Comment by elelay** [comment]
Interesting: by looking at the code, the image has to be corrupt on server.
What podcast produces the error?

**Comment by ideasman42** [comment]
Linking although I'm not sure it matters? - (if they fix, gpodder will still have this error)
http://feeds.thebuglepodcast.com/thebuglefeed

**Comment by elelay** [comment]
It allowed me to reproduce and made fixing the bug easier.
Thanks,
