### ISSUE TITLE
Feed works in Linux but not in Windows

### ISSUE THREAD

**Issue by LostPuppy24** [gpodder/gpodder#350]
Hello, this URL "http://www.creationmoments.com/daily-rss" works on my Linux machine in gPodder. When I try to run the same feed in Windows10 it gives me an error msg: Could not add some podcasts.
http://www.creationmoments.com/daily-rss: Got HTML document instead.

Is there a way to get this to work in Windows?

Linux version of gPodder: 3.5.2 / Windows 10 version of gPodder: 3.9.3
Linux: Mint 17.3

Thanks for the help.

LostPuppy24

**Comment by elelay** [comment]
This podcast is misconfigured (web server replies with content type HTML for its XML RSS feed). We now (in 3.9.3) reject it.
There is a Pull Request in progress to still try to parse feeds with HTML content type at https://github.com/gpodder/gpodder/pull/261.
It's safe to apply if you also update the podcastparser module to its master version.
Or you can wait for next release.
See #225.
