### ISSUE TITLE
GPodder 3.9.3 won't open on MacOS High Sierra

### ISSUE THREAD

**Issue by tameware** [gpodder/gpodder#358]
I can't be certain it was the system update that stopped gPodder from working, but it seems likely. It was working under Sierra.

I installed gPodder from the disk image. I have tried reinstalling and rebooting.

I'm using Mac OS 10.13 on a MacBook Pro (13-inch, Late 2016, Four Thunderbolt 3 Ports).

My Mac has plenty of free RAM and hard disk space.

When I launch from the command line I get the following message:

$ open -a gPodder.app
LSOpenURLsWithRole() failed for the application /Applications/gPodder.app with error -10810.

Any suggestions or reports from others running High Sierra will be gratefully received!

**Comment by thp** [comment]
Did you try the updated one from https://github.com/gpodder/gpodder-osx-bundle/releases/tag/gPodder-3.9.3_1 ? We should update the download link if that build works @elelay

**Comment by tameware** [comment]
That did the trick – thanks!

Also, kudos to the author of the build scripts. This is the first open source project I can recall where I was able to follow the instructions in the README and build successfully under OS X with no hiccups.

**Comment by thp** [comment]
Yes, @elelay did a great job with the macOS build :)

**Comment by elelay** [comment]
Thanks to open source! @lazka did the cleanup and improvements from my original scripts for quodlibet and I stole it back for gPodder

**Comment by elelay** [comment]
Download link updated.
