### ISSUE TITLE
Album tag

### ISSUE THREAD

**Issue by dmaglio** [gpodder/gpodder#359]
in mp3 file missing album tag, the other information are displayed correctly

**Comment by elelay** [comment]
@dmaglio please give more details on your issue:
1. what did you do?
2. what was the expected result?
3. what happened instead?

**Comment by dmaglio** [comment]
1. Nothing, i sync my podcast from gpodder;
2. I expect to find the mp3 tags completely compiled;
3. Album tag is missing, the other are compiled (artist, title, etc.)

**Comment by elelay** [comment]
Enabling the **Tag downloaded files using Mutagen** extension will add the album tag.

**Comment by dmaglio** [comment]
It's already enabled

Il 5 novembre 2017 12:23:38 CET, Eric Le Lay <notifications@github.com> ha scritto:
>Enabling the **Tag downloaded files using Mutagen** extension will add
>the album tag.
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/gpodder/gpodder/issues/359#issuecomment-341965809

-- 
Davide Maglio
Ingegnere Informatico,
p: +39 3480725133
a: via A. D'Andrea, 22, Castromediano (LE)
e: dmaglio@gmail.com

tw: https://twitter.com/dmaglio
li: https://it.linkedin.com/in/davidemaglio82

**Comment by elelay** [comment]
It works for me, for instance for http://feeds.99percentinvisible.org/99percentinvisible where there is no album tag in the original and one once gPodder downloads the episode.

What's your system?
What version of gPodder?
What podcast?
How do you know there is no album tag?

**Comment by dmaglio** [comment]
Fedora 26 x86_64
gPodder 3.9.3
Podcast from Radio 2 (IT) like "Il Ruggito del coniglio" (http://www.radio.rai.it/radio2/podcast/rssradio2.jsp?id=150)
because in my music player missing tag and if i read file with easytag i see that haven't album tag (and artist album but it isn't important)

**Comment by elelay** [comment]
I'm afraid this is something in your setup: I've tried the exact same podcast in a fresh gpodder profile, enabled the tagging extension, downloaded *EXTRA del 09/11/2017* and inspected with easytag: it has the Album tag set to *Il Ruggito Del Coniglio* as expected.
I'm on ArchLinux with mutagen 1.39-1 which is slightly newer but nothing in the changelog relates to simple ascii tags like TALBUM

Can you try the exact same steps by 

1. running:
````
    GPODDER_HOME=/tmp/testgpo gpodder -v
````
2. enabling the tagging extension
3. subscribing to the podcast
4. downloading the episode
5. checking that you have a line like that: 
````
[tagging] INFO: tagging.on_episode_downloaded(Il Ruggito Del Coniglio/IL RUGGITO DEL CONIGLIO EXTRA del 09/11/2017 - Freaks Men)
````
5. running `easytag /tmp/testgpo/Downloads/Il\ Ruggito\ Del\ Coniglio/A46542023.mp3`

You will have to do further debugging on your side, if you're able, by inserting `logger.info(...)` statements in `/usr/share/gpodder/extensions/tagging.py`

**Comment by dmaglio** [comment]
with that test works.... now i try to delete everything my settings and restore to default

**Comment by elelay** [comment]
great! Let me know if you find what was wrong

**Comment by dmaglio** [comment]
after the reset has resumed to work. I had to disable normalization because the lame process occupied 100% of the cpu. now I have to find the way to reorder more than 100 episodes because the year label does not accept the full format and the date in the file name does not help ...

**Comment by elelay** [comment]
Good to know that it works.
I guess the issue with reordering is related to your player, isn't it?
