### ISSUE TITLE
Feature request: Add 'Resume downloads' to gpo. 

### ISSUE THREAD

**Issue by albij** [gpodder/gpodder#360]
If downloads are interrupted for some reason, unfinished downloads are stuck in limbo.
For more automation goodness, it would be great if either, an auto resume option was added in the GUI.
Or a command was added in gpo, so it could be triggered with crontab.

**Comment by elelay** [comment]
This will be in next release, with 2 new gpo actions:
partial [--guid] List partially downloaded episodes with or without GUIDs
resume [--guid]  Resume partially downloaded episodes or single GUID

**Comment by elelay** [comment]
released in gPodder 3.10.7
