### ISSUE TITLE
gPodderShownotesText.text_view hardcodes white background, doesn't respect GTK theme

### ISSUE THREAD

**Issue by blaabjerg** [gpodder/gpodder#369]
In src/gpodder/gtkui/shownotes.py line 125, the text_view background is hardcoded to white. This looks fine with a light GTK theme, but it looks bad with a dark theme.

It only affects the margin of the text view, so perhaps there is a way to query for the actual text bgcolor and use that instead?

**Comment by elelay** [comment]
It's ok since 3.10.0 with the text shownotes, but still an issue with webkit2 html shownotes.
I don't thing real html shownotes should be changed. Only textual shownotes displayed as html should be.
I'm working on a prototype using webkit user stylesheets.
