### ISSUE TITLE
Youtube feeds with underscore will not work

### ISSUE THREAD

**Issue by jaygroh** [gpodder/gpodder#371]
When trying to add a youtube channel to gpodder with an underscore _ it fails with "Got HTML document instead. I have verified it with other channels with underscores and I get the same result. All other channels seem to work fine so far.

Here is an example of one.
https://www.youtube.com/channel/UC7_gcs09iThXybpVgjHZ_7g

**Comment by elelay** [comment]
This doesn't seem to have anything to do with the underscore: the `<link rel="alternate" type="type="application/rss+xml">` is missing for this user's channel but is present for other (maybe signed up earlier?) users. Can you check if working users are all before one date and non working users are all after one date?
I've created a dummy channel: https://www.youtube.com/channel/UCGJQBfi1hGeJzK4gclgsjEg which has no underscore but can't be imported in gPodder either.

**Comment by jaygroh** [comment]
Never looked at the dates. I guess I'm just unlucky because I have tried a hand full of ones with underscores after hunting them down and none of them worked. Every other channel that I add has worked fine.

So does this mean newer channels cannot be added? Or is it something to do with how the channel owner has it set up? Or does gpodder just need some code change to grab the channel videos?

**Comment by elelay** [comment]
As far as I can tell, newer channels lack the RSS feed link and this is not something the creator can change.
We'll update gPodder to deal with it. I've already made a PR #373 to fix it, but I'm not familiar with the Youtube integration so I'm waiting for review.
