### ISSUE TITLE
What happened to the filename dialogue?

### ISSUE THREAD

**Issue by oldpink** [gpodder/gpodder#374]
I saw that there was a new version of Gpodder, version 3.10.0, so I gave it a try, as I already had all the dependencies installed.
The GTK3 interface unsurprisingly looks a bit different, but the one thing that made me uninstall it and go back to version 3.9.6 was the lack of a filename dialogue in the "Select destination" window when saving the downloaded files.
In fact, it doesn't even show what filenames are being saved at all, much less allow those filenames to be changed within the "Select destination" window, as it has always been before.
I'm unsure about whether this is a bug or a feature, but speaking for myself, the option to save each podcast file under an alternative name than its default is essential, and having that removed permanently is a total deal-breaker.
Does anyone know what the story is about this?
Oh, and before I come off sounding ungrateful, allow me to just say that I am very thankful that there are people maintaining Gpodder, the **only** podcast feed downloader that's worthwhile for Linux and other supported Unixish platforms.

**Comment by adamvoss** [comment]
See #163 and #212 regarding this change.

How or why are you needing to change the file name?  I'm wondering you for problem would be better solved by a configurable file-name template (there may already be one, I have not looked).

**Comment by oldpink** [comment]
The reason that I need to be able to modify the filename on the fly is because I have a script that automates saving under a set filename scheme to make it much easier and quicker to load into Audacity and edit by splitting each audio file to listen to later.
Having the ability to enter an alternate filename in the "Send To" dialogue totally short circuits that.
I understand the rationale of being able to save all podcasts with their default filenames to a set folder, but couldn't the option to save with the old way be added as a second choice?
I'm not switching to 3.1x at all because this new behavior is too much of a deal breaker.
Thanks

**Comment by oldpink** [comment]
Thanks for making this possible, but I'm having a terrible time finding a way to get that checkbox at all.
Here's a screenshot of what I get when I try using the "Send To" function after having built version 3.10.5.
![save_dialog](https://user-images.githubusercontent.com/24418507/46910829-88241c00-cf19-11e8-8e99-8075dcc00ac5.jpg)
As you can see, there is no checkbox where you have one in your own screenshot.

I'm unsure about the look of the main window will be useful, but here's how mine looks:
![gpodder](https://user-images.githubusercontent.com/24418507/46910839-b144ac80-cf19-11e8-9265-6ccf49905e81.jpg)

Finally, I get a screen full of errors when executing Gpodder from an RxVT, with two specific errors repeated, so I just scrolled up enough so that you can see those errors clearly.
I don't know if those could be the source of the problem, but it's possible
![errors](https://user-images.githubusercontent.com/24418507/46910853-008add00-cf1a-11e8-884a-64e761a9f7e2.jpg)

For what it's worth, I built then installed the new version of Gpodder via the SlackBuild found here - https://www.slackbuilds.org/repository/14.2/multimedia/gpodder/

I really appreciate you responding to my suggestion, so don't take me as being ungrateful.
It's just that, until I can get the new version of Gpodder to allow a specified file name save dialog (your checkbox would almost certainly work perfectly), I'm sticking to version 3.9.6.
Thanks in advance for whatever you can tell me about my problems to get 3.10.5 working as it should for me.

**Comment by elelay** [comment]
This is not in 3.10.5: only in master, so you'll have to [run from git](https://gpodder.github.io/docs/run-from-git.html)

**Comment by oldpink** [comment]
Ah, thanks!
Yes, it definitely now has the provision to either go with default filenames or with a user-specified filename.
I can't imagine anyone having a problem with this eventually going into the main release stream now.
The only suggestion I can think of for it as it is now (a tiny one, but usability would probably be enhanced) would be to have the filename right up to the extension (.mp3 or .ogg or ???) automatically selected at the top when saving only one file at a time or when saving multiple files, going from this:
![unselected](https://user-images.githubusercontent.com/24418507/46918967-5b6a1600-cfa6-11e8-8da4-bae79a415538.jpg)

...to this:
![selected](https://user-images.githubusercontent.com/24418507/46918979-6ae95f00-cfa6-11e8-9ba8-243a492d783b.jpg)

That would be a really small change, but it makes the behavior of 3.10.x a bit more in line with the way that 3.9.x worked, and without compromising usability, but still allow people like me to leave our scripts as is that we use to automatically save under our own naming scheme, as I do with a combination of Xdotool and Xclip.

While I'm at it, I also noticed another small change with "Send To" when saving multiple files that is a step in the right direction away from 3.9.x by allowing clicking "Cancel" once to stop saving the rest of the files instead of requiring a separate click of "Cancel" for all files currently selected.
That's certainly an improvement, so there's one change from the old behavior that makes perfect sense.

Again, thanks a bundle for responding and for continuing to make Gpodder the best podcast program out there.
I'll be testing it out to see how it runs for now.

**Comment by elelay** [comment]
@oldpink thanks for your detailed answer. As much as I would like to (changing the extension doesn't make sense), I'm afraid I can't select the filename. In fact, it's not selected for the first file, but then selected for remaining files (without me asking for it either way). The only change is that I reuse the file chooser dialog, so it has already been realized when I prompt for the remaining files. It might be a race condition somewhere in the gtk file chooser code (the folder contents loading faster or slower) ?! I've not managed to trace it to something concrete yet.

**Comment by elelay** [comment]
OK, there may be a way: when constructing the file chooser dialog in code rather than using the ui file from glade it works as expected, selecting the filename minus extension each time.

**Comment by elelay** [comment]
you can check it now :-)

**Comment by oldpink** [comment]
Wow!
Yep, works exactly as hoped.
Nicely done.
I can't imagine anyone having a beef with this slight change, so once again, I'm running your bleeding edge Git build of Gpodder, and it works (I have a few tiny announces caused by xdotool, but not fatal and not from Gpodder per se) for my scripts again.
Hoping you'll have good luck chasing down that race condition (maybe already squashed, but I'm no programmer) and swatting any other bugs for the next release.
Thanks so much for keeping at it, and even implementing suggestions on the fly.
