### ISSUE TITLE
can't build gpodder-3.10.0 on Crux linux

### ISSUE THREAD

**Issue by timcowchip** [gpodder/gpodder#376]
gpodder Pkgfile >> https://pastebin.com/h6iHwNF6

Traceback (most recent call last):
  File "setup.py", line 31, in <module>
    main_module = open('src/gpodder/__init__.py').read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1008: ordinal not in range(128)
make: *** [makefile:85: install] Error 1

**Comment by elelay** [comment]
Is it possible to ensure you have set an UTF-8 locale before building?

**Comment by therealfun** [comment]
@timcowchip , make sure you export "LANG=en_US.UTF-8" not "LANG=en_US.utf8".

**Comment by timcowchip** [comment]
Thanks therealfun, I change it to "UTF8". gPodder-3.10 still won't build

**Comment by adamvoss** [comment]
@timcowchip Hate to be a pedant when I really don't know which is proper, but @therealfun suggested using "en_US.UTF-8" not "en_US.UTF8".  Hopefully that will help.

**Comment by timcowchip** [comment]
Thanks again therealfun, I changed "UTF8" to "UTF-8", but its still giving the same error.

**Comment by timcowchip** [comment]
going to close this issue as it is probably distro-dependent
