### ISSUE TITLE
Incorrect links on https://gpodder.github.io/

### ISSUE THREAD

**Issue by FeetInTheCrowds** [gpodder/gpodder#381]
The web page https://gpodder.github.io/ states that v3.10.0 is available but then has links to v3.9.6.

Kind regards,

Robin

**Comment by elelay** [comment]
Yes, gPodder 3.9.6 and 3.10.0 were released simultaneously and are **functionally equivalent**.
The 3.10.0 version is the first built on gtk3 so it's less polished and is out for early adopters and packagers.
So nothing wrong with the links : 3.10.0 source code is available for download.
Packages will be linked when they're ready.
Thanks,
