### ISSUE TITLE
OPML Import Error

### ISSUE THREAD

**Issue by abc-mikey** [gpodder/gpodder#382]
Trying to import an OPML file results in the OPML data import dialogue appearing but without anything being shown. The command prompt outputs the following when trying to import the file:

```
1515935128.441291 [gpodder.gtkui.desktop.podcastdirectory] WARNING: Ignoring update from old thread
```

*txt file extension added for sake of uploading to github.*
[DoggCatcherExport-2.opml](https://github.com/gpodder/gpodder/files/1629341/DoggCatcherExport-2.opml.txt)

```
Name         : gpodder
Version      : 3.9.3
Release      : 3.fc27
Arch         : noarch
Größe        : 3.0 M
Quelle       : gpodder-3.9.3-3.fc27.src.rpm
Paketquelle  : @System
Aus Paketque : fedora
```

**Comment by elelay** [comment]
@abc-mikey thanks for the report. I'll look into it.

**Comment by elelay** [comment]
gPodder requires the OPML `outline` element to have a `type` attribute with value `rss` or `link`.
So edit your file to add it, reading:
```
<outline type="rss" text="The Titanium Physicists Podcast" xmlUrl="http://titaniumphysics.libsyn.com/rss" />
```
Is this the OPML export from doggcatcher?

**Comment by abc-mikey** [comment]
Sure is!

Am 14.01.2018 6:05 nachm. schrieb "Eric Le Lay" <notifications@github.com>:

**Comment by elelay** [comment]
We basically only support OPML 2.0 import/export.
Luckily conversion from Doggparser OPML 1.1 export is easy: just add a type attribute.

**Comment by abc-mikey** [comment]
Quick perl one liner to convert across based on description from @elelay.

```bash
perl -e 'my $f = $ARGV[0]; -f $f || die "File not found: $f\n"; open my $fh, "<", $f || die "Unable to open file: $f\n"; $_ = do { local $/; <$fh> }; close $fh; s/<outline /<outline type="rss" /g; print;' DoggCatcherExport.opml > DoggCatcherExport-Updated.opml
```

Is there a particular reason not to support the 1,1 version, by the way? I would've thought DoggCatcher for one is pretty widely used.
