### ISSUE TITLE
Can't add podcast

### ISSUE THREAD

**Issue by stefankoegl** [gpodder/gpodder#383]
*Copied from gpodder/mygpo#80, originally reported by @bonkeman*

----

Hi,

Does anybody know why I can't add this podcast? It worked a couple of months ago, but not on my newly reinstalled computer. 

![image](https://user-images.githubusercontent.com/29395946/33803945-8bd8ff7a-dd9b-11e7-9c38-6926342553a9.png)

**Comment by elelay** [comment]
@bonkeman adding http://api.sr.se/api/rssfeed/rssfeed.aspx?Poddfeed=4023 works fine in gPodder 3.10.0. What version are you using?
