### ISSUE TITLE
Found a way to add youtube channels, users and playlists without an api key

### ISSUE THREAD

**Issue by ghost** [gpodder/gpodder#384]
i found this on stackoverflow, all you have to do is parse the channel id, username or playlist number and swap it into the urls below

https://www.youtube.com/feeds/videos.xml?channel_id=CHANNELID
https://www.youtube.com/feeds/videos.xml?user=USERNAME
https://www.youtube.com/feeds/videos.xml?playlist_id=YOUR_YOUTUBE_PLAYLIST_NUMBER

is it possible for this to be implemented into the application soon?

**Comment by predator8bit** [comment]
Too bad it doesn't work any more. It used to play just fine, but now I have to use the 'Open website' plugin and then use 'open with...' in my browser to play my videos with mpv.
![player](https://user-images.githubusercontent.com/27356954/36075635-f766f3c2-0f51-11e8-8c1e-5809d6975123.png)
Arch Linux + Gpodder 3.10.0

**Comment by XIncognito10** [comment]
hmm thats odd. All 3 methods are working for me right now

**Comment by XIncognito10** [comment]
I'm actually watching a youtube channel that i subscribed to about 15 minutes ago

**Comment by predator8bit** [comment]
Opened a separate issue for my problem.

**Comment by pantar85** [comment]
have been doing this for as long as i have been using gpodder and never needed a api key.

go to channel i want to subscribe to and beside the home tab, select the videos tab. copy and paste this link.

will look something like https://www.youtube.com/user/CHANNEL_NAME/videos

has always worked for me since i first started using gpodder back in 2012/2013.

always presumed the youtube api key requirement was for 4k videos or something- never bothered with it.

**Comment by XIncognito10** [comment]
Should i try to work on a PR that implements this and phases out the youtube api?

**Comment by elelay** [comment]
Yes, please! Don't hesitate to ask if you have questions on the way ;-)
The YouTube API is to convert things like https://www.youtube.com/user/sixguntv/videos to https://www.youtube.com/channel/UCaITiY0rLVsRr71dP-kQgEg but I agree it's not needed for the (majority?) of urls with the id.

**Comment by XIncognito10** [comment]
Where would i add the code to change it? i tried podcastparser but that doesnt work

**Comment by elelay** [comment]
Right into https://github.com/gpodder/gpodder/blob/master/src/gpodder/youtube.py I guess...
