### ISSUE TITLE
windows: missing libraries/dependencies

### ISSUE THREAD

**Issue by bugreport0** [gpodder/gpodder#385]
Unfortunately the gPodder 3.9.6 Windows build is not fully functional due to missing libraries:
> [gpodder.util] WARNING: html5lib not found, falling back to HTMLParser
> [gpodder.util] WARNING: Running on Win32 but win32api/win32file not installed.
> [gpodder.sync] WARNING: Could not find gpod
> [gpodder.sync] WARNING: Could not find eyed3.mp3
> [gpodder.extensions] ERROR: Cannot load notification-win32

Tested on Win7 64bit & Win10 64bit, steps to reproduce on clean Win7 SP1 VM:
1) Install Python 2.7.13 from https://www.python.org/ftp/python/2.7.13/python-2.7.13.msi
2) Install PyGTK 2.24.2 from http://ftp.gnome.org/pub/GNOME/binaries/win32/pygtk/2.24/pygtk-all-in-one-2.24.2.win32-py2.7.msi
3) Install gPodder 3.9.6 from https://github.com/gpodder/gpodder/releases/download/3.9.6/gpodder-3.9.6-setup.exe
4) Run gPodder and check the 2018-01-18.log file to see the warnings listed.

**_This is a major problem due to the need of notification-win32 in order to see the error messages from gPodder in Windows._**

I was able to partially fix the problem by adding **html5lib**, **webencodings** & **six** from https://sourceforge.net/projects/gpodder/files/macosx/gPodder-3.9.6_0.deps.zip/download and the **notification-win32** by adding the necessary files from https://github.com/mhammond/pywin32/releases/download/b221/pywin32-221.win32-py2.7.exe to my Python folder now I only have the other errors to fix:
> [gpodder.util] WARNING: Running on Win32 but win32api/win32file not installed.
> [gpodder.sync] WARNING: Could not find gpod
> [gpodder.sync] WARNING: Could not find eyed3.mp3

Any information what files/libraries I need for them and where I can find and need to put them would be welcomed.

**P.S.** Can we have all the missing libraries added in the installation package or listed (other than Python 2.7.13 & PyGTK 2.24.2) on the https://gpodder.github.io/ page?

**P.P.S.** The same problems are present in the gPodder Portable 3.9.6 (https://portableapps.com/apps/internet/gpodder_portable). The discussion about them with John T. Haller (the user creating/updating gPodder Portable 3.9.6) can be seen here: https://portableapps.com/news/2018-01-13--gpodder-portable-3.9.6-released

**Comment by JohnTHaller** [comment]
The correct link for the referenced download files is: https://portableapps.com/news/gpodder/files/macosx/gPodder-3.9.6_0.deps.zip

**Comment by GordCaswell** [comment]
You both mean https://sourceforge.net/projects/gpodder/files/macosx/gPodder-3.9.6_0.deps.zip

**Comment by ForestFeather** [comment]
As someone brand new to trying to use this, who doesn't find any instructions on requiring additional items or how to install them... it makes me very much find this to be a poorly maintained product.  Is there a fix, or is my solution to go find a different application for podcast management?

**Comment by elelay** [comment]
Any help in the windows packaging is always welcome! Especially since we have moved development to python3/gtk3 and don't yet have a clear idea how to package this.

**Comment by bugreport0** [comment]
@ForestFeather you can start by installing https://github.com/mhammond/pywin32/releases/download/b221/pywin32-221.win32-py2.7.exe or by adding the files from http://www53.zippyshare.com/v/PECqUk4C/file.html if you are using the portableapps version and if you find a good alternative to gPodder drop us a line.

@elelay You can start by adding **Windows Python extensions package** and **html5lib**, **webencodings** & **six** as dependencies with links to them on the page to download the windows version or adding the missing files from them to the binary you are distributing.

**P.S.** This problem is not new, I have previously (in 2015 or 2016) reported it and was ignored, but then there was a fall back solution for the displaying of error messages and I didn't make fuss about it.
