### ISSUE TITLE
about screen has wrong release date

### ISSUE THREAD

**Issue by Strubbl** [gpodder/gpodder#391]
About screen in gpodder 3.10.0 currently [has 2016-12-29 as date](https://github.com/gpodder/gpodder/blob/98ec45a712d400120ee57eee2a782fa0e9f863e4/src/gpodder/__init__.py#L24). I would have expected it to be [the release date](https://github.com/gpodder/gpodder/releases/tag/3.10.0), exactly one year later 2017-12-29

**Comment by elelay** [comment]
Fixed, thanks!
