### ISSUE TITLE
pycodestyle checks

### ISSUE THREAD

**Issue by elelay** [gpodder/gpodder#393]
@MarkusHackspacher has begun fixing whitespace errors and the like and enabling pycodestyle checks.
Going further, additional checks should be discussed here before submitting pull requests, to prevent loosing time  on fixing rules we don't agree on.

Here is current list of errors with the default config (first column is error count):
Error codes are here : https://pycodestyle.readthedocs.io/en/latest/intro.html#error-codes
```
> pycodestyle share src/gpodder tools *.py
```
- [x]   1     E114 indentation is not a multiple of four (comment)
- [x]   1     E227 missing whitespace around bitwise or shift operator
- [x]   1     E271 multiple spaces after keyword
- [x]   1     E272 multiple spaces before keyword
- [x]   1     E703 statement ends with a semicolon
- [x]   1     E711 comparison to None should be 'if cond is not None:'
- [x]   1     E721 do not compare types, use 'isinstance()'
- [x]   2     E129 visually indented line with same indent as next logical line
- [x]   2     E266 too many leading '#' for block comment
- [x]   2     E712 comparison to True should be 'if cond is True:' or 'if cond:'
- [x]   3     E125 continuation line with same indent as next logical line
- [x]   3     E211 whitespace before '('
- [x]   3     E222 multiple spaces after operator
- [x]   3     E713 test for membership should be 'not in'
- [x]   8     E115 expected an indented block (comment)
- [x]   8     E124 closing bracket does not match visual indentation
- [x]   8     E262 inline comment should start with '# '
- [x]  11     E228 missing whitespace around modulo operator
- [x]  11     E401 multiple imports on one line
- [x]  13     E305 expected 2 blank lines after class or function definition, found 1
- [x]  13     E306 expected 1 blank line before a nested definition, found 0
- [x]  13     E731 do not assign a lambda expression, use a def
- [x]  18     E221 multiple spaces before operator
- [ ]  21     ~~E127 continuation line over-indented for visual indent~~
- [x]  27     E202 whitespace before ')'
- [ ]  31     E701 multiple statements on one line (colon)
- [x]  33     E303 too many blank lines (2)
- [x]  34     E225 missing whitespace around operator
- [x]  48     E111 indentation is not a multiple of four
- [ ]  50     E722 do not use bare except
- [x]  58     E261 at least two spaces before inline comment
- [x]  64     E251 unexpected spaces around keyword / parameter equals
- [x]  67     W391 blank line at end of file
- [ ]  78     E231 missing whitespace after ','
- [x]  84     E265 block comment should start with '# '
- [x] 147     E201 whitespace after '('
- [x] 156     E302 expected 2 blank lines, found 1
- [x] 178     E502 the backslash is redundant between brackets
- [ ] 278     E402 module level import not at top of file
- [ ] 361     ~~E128 continuation line under-indented for visual indent~~
- [ ] 857    ~~E501 line too long (122 > 79 characters)~~

**Comment by elelay** [comment]
I'm in favor of not fixing
 - E127 (continuation line over-indented)
 - E128 (continuation line under-indented)
 - E501 (line too long)
 - E722 (don't use bare except)

I'm not sure about:
 - E701 (multiple statements on one line (colon)
   It's used in `class XyzException(Exception): pass` and one-liners `if yyy return xx`
 - E201, E202 (extra space inside parenthesis and square brackets)

If E402 (module level imports not at top of file) is fixed, maybe also sort by (system/lib/current project) and alphabetically.

What do you think?

**Comment by MarkusHackspacher** [comment]
I would fix first the things that I make no or very less change in the code, 
start with this ones:
- 67 W391 blank line at end of file
- 13 E305 expected 2 blank lines after class or function definition, found 1
- 13 E306 expected 1 blank line before a nested definition, found 0
- 33 E303 too many blank lines (2)
- 8 E262 inline comment should start with '# '

at later time
- 48 E111 indentation is not a multiple of four

in my opinion, the checks with 1, 2 or 3 found things should fix the core team. Time for discus take longer as for the change.

> If E402 (module level imports not at top of file) is fixed, maybe also sort by (system/lib/current project) and alphabetically.

For fix this isort a great  tool. https://github.com/timothycrosley/isort And all files looks uniform.

**Comment by elelay** [comment]
Great! I didn't know about isort.

**Comment by MarkusHackspacher** [comment]
W503 line break before binary operator
E221 multiple spaces before operator
E225 missing whitespace around operator
E226 missing whitespace around arithmetic operator
solve other E22x 


With sorting import you can use "isort -y -rc"
I try it with: https://github.com/MarkusHackspacher/gpodder/tree/importsort

**Comment by elelay** [comment]
Thanks @MarkusHackspacher for the continous work on this.
I'm revisiting my rejection of E722. Maybe bare `except` should be fixed.

**Comment by MarkusHackspacher** [comment]
In the project are now this: 
25      E127 continuation line over-indented for visual indent
358     E128 continuation line under-indented for visual indent
10      E402 module level import not at top of file
200     E501 line too long (122 > 100 characters)
29      E701 multiple statements on one line (colon)
50      E722 do not use bare except'

E402 is not better possible, E722 is difficult, E501, E128 and E127 is lot of work, E701 not sure.

How we go on?

**Comment by elelay** [comment]
We should finish E127 and say it's done.
Thanks,

**Comment by elelay** [comment]
Thanks @MarkusHackspacher for your hard work!
