### ISSUE TITLE
Too many values to unpack when adding BBC podcast.

### ISSUE THREAD

**Issue by kwhitefoot** [gpodder/gpodder#395]
While adding this url:

https://podcasts.files.bbci.co.uk/p02pc9qx.rss

Failed with 'too many values to unpack' and a request to report the error and restart gpodder.

It seems that the url has nonetheless been added because attempting to add it after restart gives a message saying that it is already there.

**Comment by elelay** [comment]
It works for me with latest master (should be equivalent to 3.10.0 for this purpose).
What version of gPodder are you running?

**Comment by elelay** [comment]
@kwhitefoot please reopen if still an issue with recent releases
