### ISSUE TITLE
Request: Make play speed sticky for a playlist

### ISSUE THREAD

**Issue by craig22** [gpodder/gpodder#396]
Is it possible to retain the play speed setting while playing a playlist?  I play podcasts at 1.3x but the speed resets to normal speed after each podcast ends and I have to set it back to 1.3 each time.

**Comment by elelay** [comment]
What is your media player?
gPodder isn't related to playback speed.
If you would like to code something special, maybe an extension could set the player rate on track change (look at `mpris-listener.py` for inspiration).

**Comment by craig22** [comment]
Wrong place to post, sorry!  I use SMPlayer.  I found a solution by using the setting "scaletempo=scale=1.3" in preferences->advanced -> mplayer/mpv -> audio filters.  Thank you for responding.
