### ISSUE TITLE
YouTube RSS feed content doesn't play or download

### ISSUE THREAD

**Issue by predator8bit** [gpodder/gpodder#403]
[2018-02-11.log](https://github.com/gpodder/gpodder/files/1714646/2018-02-11.log)
![player](https://user-images.githubusercontent.com/27356954/36076341-247fc8bc-0f5b-11e8-92bd-469769680e1d.png)
I used the same method of adding the feeds as described in:
#384 
Ordinary Podcast feeds work, both audio and video.
I'm on Arch Linux an using Gpodder 3.10.0

**Comment by elelay** [comment]
Please check 
 - the player in preferences
 - the location of the downloaded files
 - run the command to open downloaded files in your player from command line

**Comment by elelay** [comment]
Why do you say it doesn't download?

**Comment by predator8bit** [comment]
![download](https://user-images.githubusercontent.com/27356954/36076637-1d0d8836-0f5f-11e8-899a-8f693650f9c9.png)
This is what happens when I try to download a YouTube RSS feed item, again, downloading works with regular RSS items, both video and audio.

My download location is the default /home/predator8bit/gPodder/Downloads/
The player is set to mpv in the preferences and it works as intended with regular feeds, this issue only affects the YouTube stuff.

**Comment by elelay** [comment]
> This is what happens when I try to download a YouTube RSS feed item
Yes: definitely bug #386. Either checkout gPodder master and run it from there or wait for next point release.

Regarding download folder, can you check the non-working feed download directory (the Downloads subdirectory)?

**Comment by predator8bit** [comment]
![folder](https://user-images.githubusercontent.com/27356954/36076765-ec1afcde-0f60-11e8-9279-e08045d20545.png)
Looks normal, nothing in it, just the channel picture.

**Comment by predator8bit** [comment]
I edited /usr/lib/python3.6/site-packages/gpodder/youtbe.py according to #386 and it seems to have fixed the issue, thanks for the help, please close this duplicate.
