### ISSUE TITLE
gpo download command is broken

### ISSUE THREAD

**Issue by matoro** [gpodder/gpodder#404]
Since 3.10.0 the gpo tool fails to download any episodes.  `gpo update` still works and queues the new episodes, but `gpo download` will run through all of them instantly without downloading, and display `[DONE]` for each episode anyway.  It does not seem to mark them as downloaded in the sqlite database since running `gpo download` again will display the same statuses.

The GUI seems to be unaffected and works as expected.  I hope the `gpo` tool is not deprecated as of this latest version; I really like using it.

**Comment by elelay** [comment]
Don't worry: it's not deprecated. I'll look into this.
