### ISSUE TITLE
Episode download hangs at 100%

### ISSUE THREAD

**Issue by matoro** [gpodder/gpodder#408]
Occurs both with GUI and gpo CLI.  In CLI it maxes out 1 CPU continually writing status message as fast as it can and prevents other downloads.  In GUI it causes threads to freeze.

Feed: https://www.animenewsnetwork.com/anncast/rss.xml?podcast=audio
Episode: https://www.animenewsnetwork.com/anncast/2018-02-09/.127610
Direct link: https://www.animenewsnetwork.com/images/cms/anncast/127610/anncast320.mp3

Note that there's currently a weird issue with their CDN so there are a number of redirects, but it does eventually get to the payload.

Haven't tried to duplicate on other systems.

**Comment by elelay** [comment]
Do you see a status message ? I can reproduce the CPU spike.

**Comment by elelay** [comment]
OK, now I get an error 500 on download:  '//www.animenewsnetwork.com/images/cms/anncast/126971/anncast318.mp3', 500, 'Internal Server Error: Redirect Recursion')

**Comment by matoro** [comment]
@elelay No, no status message.  Earlier it was giving the 500 but I assumed since it had stopped they had fixed it.  You may have to try again later, it is working for me now but it may go back to the 500.

Could it have something to do with expecting a Content-Length header?  Here's what I'm getting back from cloudflare, example response:

```
< HTTP/2 200 
< date: Fri, 16 Feb 2018 21:18:28 GMT
< content-type: audio/mpeg
< set-cookie: __cfduid=d7c04a1b26f10622abb8523f2631be1d11518815886; expires=Sat, 16-Feb-19 21:18:06 GMT; path=/; domain=.animenewsnetwork.com; HttpOnly
< cache-control: max-age=86400
< cf-ray: 3ee3899c3c2e82eb-ATL
< display: staticcontent_sol
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< expires: Sat, 17 Feb 2018 21:18:06 GMT
< last-modified: Fri, 16 Feb 2018 19:14:21 GMT
< response: 200
< set-cookie: __cfduid=d7c04a1b26f10622abb8523f2631be1d11518815886; expires=Sat, 16-Feb-19 21:18:06 GMT; path=/; domain=.animenewsnetwork.com; HttpOnly
< set-cookie: ezoadgid_53527=-2; Path=/; Domain=animenewsnetwork.com; Expires=Fri, 16 Feb 2018 21:48:06 UTC
< set-cookie: ezouid_53527=90300656; Path=/; Domain=animenewsnetwork.com; Expires=Thu, 06 Feb 2020 21:18:06 UTC
< set-cookie: ezoref_53527=; Path=/; Domain=animenewsnetwork.com; Expires=Fri, 16 Feb 2018 23:18:06 UTC
< set-cookie: ezoab_53527=mod6-; Path=/; Domain=animenewsnetwork.com; Expires=Fri, 16 Feb 2018 21:48:06 UTC
< set-cookie: ezoic_percentile=7; Expires=Sun, 16 Feb 2020 21:18:28 GMT; Domain=.animenewsnetwork.com; Path=/
< vary: Origin,Accept-Encoding,X-APP-JSON
< x-middleton-display: staticcontent_sol
< x-middleton-response: 200
< server: cloudflare
```

**Comment by elelay** [comment]
Now everything's fine : downloaded a couple episodes without issue.
I'll try again later

**Comment by matoro** [comment]
@elelay It managed to download 2 episodes from the same show without issue, but `anncast320.mp3` still hangs.  I understand the issue is server-side and sporadic which makes it difficult to test.

**Comment by elelay** [comment]
anncast320.mp3 downloaded a couple of times with no issue Yesterday and Today.
I'm closing it now. Please reopen if issue comes back.

**Comment by matoro** [comment]
@elelay Thanks for investigating, seems to have been resolved server-side which makes debugging not really feasible anymore.  Much appreciated
