### ISSUE TITLE
Installation dependencies script or instructions incorrect?

### ISSUE THREAD

**Issue by burbleflurp** [gpodder/gpodder#410]
Attempting to install gpodder from git following instructions from 
https://gpodder.github.io/docs/run-from-git.html

Running python tools/localdepends.py leads to the following error...

bruce@z170ar:~/gpodder$ python tools/localdepends.py
  File "tools/localdepends.py", line 40
    print('Fetching', module, '...', end=' ')
                                        ^
SyntaxError: invalid syntax

(Note: copy and pasted from terminal - caret points to equals sign in terminal)

Is it user error or a problem with the script under Ubuntu 16.04?

**Comment by burbleflurp** [comment]
Further comment/observation - has code swapped to use python3??
python3 tools/localdepends.py command ran without error!
(Can't remember where this was spotted or prompted, but command worked.)

If python3 now code base - will need to correct installation instructions which seem to imply python 2 used (where Dependencies Python 2, PyGTK and Git are listed on page)

**Comment by elelay** [comment]
Good catch: we recently switched master to Python3 and forgot to update the documentation.
It's fixed now.
