### ISSUE TITLE
Add support for none-Latin characters path.

### ISSUE THREAD

**Issue by Explorare** [gpodder/gpodder#411]
**Version**: 3.9.6
**Environment**: 
Windows 10 1709 16299.248
Python 2.7.13
PyGTK 2.24.2

It seems that gPodder doesn't support CJK characters or even none-Latin characters path due the the lack of support for Unicode in Python 2.7. Will this issue be fixed in the future?

**Error Message**:
```
Download error while downloading #66：太医谈字: [Errno 22] invalid mode ('w') or filename: 'D:\\Music\\Podcast\\Downloads\\??\\typechat066.mp3.partial'
```

**Comment by elelay** [comment]
Thanks for reporting. Please can you give an example feed where the error occurs?

**Comment by elelay** [comment]
We have switched to Python3/gtk3 since 3.10.0, but we don't support it on windows yet.

**Comment by Explorare** [comment]
https://www.typeisbeautiful.com/feed/typechat/
http://itgonglun.com/rss

**Comment by elelay** [comment]
gPodder Home directory and episodes can now have Unicode in their name since gPodder 3.10.2.
Please try with the latest 3.10.3 release.

**Comment by Explorare** [comment]
Thanks for your great work. It works like a charm.
