### ISSUE TITLE
Mac version 3.10.1 crashes when exporting an OPML in high sierra

### ISSUE THREAD

**Issue by ghost** [gpodder/gpodder#413]
Problem Report for Python3 (Dialog box title) -> Python3 quit unexpectedly (Dialog box text)

**Comment by mckenziec** [comment]
This is a huge problem for me. The last gPodder version I used was 3.9.3 and it had no problems on MacOS exporting to a local folder. Now with the latest version I keep running into Python3 unexpected errors with no information. Is there a log or something I can grab and post here?

**Comment by elelay** [comment]
I can reproduce it on macOS El Capitan.
This is due to a missing `share/glib-2.0/schemas/org.gtk.Settings.FileChooser.gschema.xml` file

**Comment by mediamode** [comment]
I just ran into this problem today.  In addition though, after I deleted  mac version 3.10.1, I attempted to open 3.9.3 (which I kept in a separate folder) and now it will not open at all.

**Comment by samirsushah** [comment]
can somebody fix this. i am not a developer. i put on GitHub so that somebody notices the problem.

**Comment by elelay** [comment]
Fixed in gPodder 3.10.3.
