### ISSUE TITLE
Lack of support for hyperlink and Emoji in episode details.

### ISSUE THREAD

**Issue by Explorare** [gpodder/gpodder#414]
**Version**: 3.9.6

**Environment**: 
Windows 10 1709 16299.248
Python 2.7.13
PyGTK 2.24.2

**Issue**
It seems that gPodder doesn't support hyperlinks and Emojis in episode details. Here are two screenshots for [TypeChat](https://www.typeisbeautiful.com/feed/typechat/) ep.64 in gPodder and Antenna Pod (for Android). You could use [Source Han Sans](https://github.com/adobe-fonts/source-han-sans) if you need a CJK font.

**Screenshot**
![gPodder](https://user-images.githubusercontent.com/5090766/36636616-109395cc-1a05-11e8-8a64-1d99309bfffb.png)
![AntennaPod](https://user-images.githubusercontent.com/5090766/36636669-dd90b55a-1a05-11e8-8b41-7699d725711d.png)

**Comment by elelay** [comment]
Thanks for the report.

Regarding emojis, could it be a font issue on Windows? On my machine on Linux, I do see the first 2 (microphone, wide laugh with tears) and the last one (smile), but not the 2 in the middle (glass and money faces).

**Comment by Explorare** [comment]
I agree with you, it's a font issue. Add an option for font family would fix the Emoji issue, I think. And I think the hyperlink support is more import than the Emoji one.
Thanks for your support.

**Comment by elelay** [comment]
Emoji in episode show notes now display nicely in gPodder since 3.10.2.
Please try with the latest 3.10.3 release.

**Comment by Explorare** [comment]
Most of the emojis can be rendered correctly, which is nice. Thanks for your great work. But the hyperlinks in episode details are still rendered as plain text. Should I open a new issue for it?
![image](https://user-images.githubusercontent.com/5090766/41508041-84b32a58-7270-11e8-81fb-02b37eb36aea.png)

**Comment by elelay** [comment]
@Explorare good point: gPodder was prefering the stripped text for shownotes, so hyperlinks were losts.
