### ISSUE TITLE
Unable to delete partial download (WindowsError 32) with v3.9.6

### ISSUE THREAD

**Issue by Vhati** [gpodder/gpodder#420]
I'm using the [PortableApps](https://portableapps.com/apps/internet/gpodder_portable) 3.9.6 release on Win7.

When I download several new episodes at once (from various podcasts), limiting the queue to one transfer at a time, I sometimes get this error.

	2018-03-08 15:00:12,631 [gpodder.download] ERROR: Download failed: [Error 32] The process cannot access the file because it is being used by another process: '[...]\\gPodderPortable\\Data\\config\\Downloads\\Nature Podcast\\media.mp3.partial'
	Traceback (most recent call last):
	  File "[...]\gPodderPortable\App\gPodder\src\gpodder\download.py", line 864, in run
		shutil.move(self.tempname, self.filename)
	  File "[...]\gPodderPortable\App\Python\Lib\shutil.py", line 303, in move
		os.unlink(src)
	WindowsError: [Error 32] The process cannot access the file because it is being used by another process: '[...]\\gPodderPortable\\Data\\config\\Downloads\\Nature Podcast\\media.mp3.partial'

I'm new to gPodder and haven't pinned down the curcumstances yet (whether the queue slot matters, etc.). In the latest occurrence, I think the problem episode was queued in slot 4 out of 6.

.
This is the relevant code ([GitHub link](https://github.com/gpodder/gpodder/blob/35fcc8b81aa434ad0a651619633a5d748ff0fd58/src/gpodder/download.py#L859-L867)).

	# Re-evaluate filename and tempname to take care of podcast renames
	# while downloads are running (which will change both file names)
	self.filename = self.__episode.local_filename(create=False)
	self.tempname = os.path.join(os.path.dirname(self.filename),
		os.path.basename(self.tempname))
	shutil.move(self.tempname, self.filename)

	# Model- and database-related updates after a download has finished
	self.__episode.on_downloaded(self.filename)

A copy IS made with the episode's filename, but "media.mp3.partial" DOES NOT disappear. Thus the move() call fails.

That 'in use' error prevents gPodder from acknowledging the successful download (no musical note icon), and my custom "on_downloaded" extension doesn't run.

The partial file's continued existence, in turn, prevents re-download attempts ("[gpodder.download] ERROR: HTTP 416: [...] Requested Range Not Satisfiable"), even if I tell gPodder to 'delete' the episode.

If I go through the filesystem and delete the partial file myself, I can then re-download the episode without errors.

**Comment by Vhati** [comment]
In case it was a threading race condition, I'd inserted a sleep() call just before the move() as a lazy kludge to make the problem go away.

Still happened again today. I had three downloads queued. While that was going on, I told gPodder to play an existing episode in VLC. While I was listening, two downloads completed, and one failed (partial file couldn't be deleted because it's in use by another process).

I checked with ProcessExplorer, and VLC has the open handle for the partial file!?

VLC wasn't spawned with any args that point to the partial file. VLC was a child process of gPodder; maybe a problem of inheritance?

**Comment by elelay** [comment]
That's interesting! Thanks for the report and fix.
Can you tell us if it's not a definitive fix (if you still sometimes get download failed)?

**Comment by Vhati** [comment]
I removed the useless sleep() I'd added before.

I haven't run into the problem in the two days since the close_fds fix. VLC **definitely** doesn't have a handle on partial downloads when I check. gPodder does, but that closes when the transfer completes, as intended.

**Comment by Vhati** [comment]
Hrm. I fetched a batch of 6 episodes - this time with no VLC - and it happened again. Second in the queue. Nothing but gPodder had the handle, and that closed it after the transfer.

Maybe there IS a race condition, too?

    WindowsError: [Error 32] The process cannot access the file because it is being used by another process: '[...]\\gPodderPortable\\Data\\config\\Downloads\\History Extra podcast\\media.mp3.partial'

**Comment by Vhati** [comment]
I put the sleep() back. Didn't help. =/

Batch of ten.
1/10 completes. My custom post-download extension runs ffmpeg during the next transfer, probably finishes first.
2/10 completes. Extension starts ffmpeg.
3/10 completes before 2's ffmpeg finishes. Fails: in use. (They were entirely different podcasts!?)
4-10 each complete after the prior's ffmpeg finished.

**Doh !**
My extension was spawning ffmpeg via - wait for it - Popen()!

I forgot to fix my own script the way I had fixed gPodder!

New hypothesis (unconfirmed but likely)...

A transfer completes. My script spawns ffmpeg to process that file. But ffmpeg **also inherits** a handle on the next transfer's partial file. If the prior ffmpeg is still running when that transfer completes, ffmpeg's extra open handle interferes with the move().

**Comment by Vhati** [comment]
Over a month - and lots of downloads - later, everything's been fine.

It was just a matter of fixing Popen(), both in gPodder and in my extension.

**Comment by elelay** [comment]
Great news,
would you like to make a pull request with your changes?
