### ISSUE TITLE
Unable to add new YouTube subscriptions

### ISSUE THREAD

**Issue by allanmcpherson** [gpodder/gpodder#421]
I have been using gPodder to watch videos from the channels I am subscribed to on YouTube for a couple years now, and it's always been quite good. Recently, though I added a new subscription that won't show up in gPodder. I've tried clicking Extras > Update YouTube subscriptions, and I've even tried deleting my API key and creating a new one, to no avail.

**Comment by elelay** [comment]
Can you share a link to the channel?
What gPodder version are you using?
Thanks,

**Comment by allanmcpherson** [comment]
The channel is: http://yt.vu/c/UCvG04Y09q0HExnIjdgaqcDQ
I'm using gPodder 3.9.0.

Thanks

**Comment by elelay** [comment]
YouTube from url shorteners isn't supported.
Even with the real YouTube URL (https://www.youtube.com/channel/UCvG04Y09q0HExnIjdgaqcDQ), you hit bug #371 in gPodder 3.9.0. This is caused by newer YouTube channels no longer including rss links: we added special code to infer the rss location from channel identifier in gPodder 3.10.1.
So you'll have to update to gPodder 3.10.1 (python3+gtk3) or backport changes to your version of gPodder.

**Comment by allanmcpherson** [comment]
Sorry, I should clarify. I wasn't trying to add it with the shortened URL. I just used that for here to try to keep it brief and easy to read. I had subscribed on YouTube and then clicked Update YouTube Subscriptions.

I will try updating gPodder and seeing if that helps, though. Thanks.

**Comment by allanmcpherson** [comment]
When I try to pull from Github, it says that it is already up -to-date. Is verison 3.10.1 available for Linux?

**Comment by elelay** [comment]
Yes, it's available for Linux. Are you on branch master? Use `git checkout 3.10.1` to extract the 3.10.1.
Are you sure you're running gpodder from the checkout?
Maybe try from a new clone, see https://gpodder.github.io/docs/run-from-git.html

**Comment by allanmcpherson** [comment]
I'm still new to using git. I tried following the instructions on the page you provided, and it returned a message that gPodder was up-to-date, but when I check the version number, it still shows as 3.9.0. When I tried checking out 3.10.1, it told me I was in a detached head state, and when I tried to pull, it asked me to specify which branch I want to pull from.  Is there something I'm doing wrong?

**Comment by allanmcpherson** [comment]
I've managed to update to 3.10.1, but when I click on Update YouTube Subscriptions, I get a list of subscriptions that it could not migrate, with the message, "Already subscribed." The new subscription is not added.

**Comment by elelay** [comment]
Now that you updated to 3.10.1, you only have to try to subscribe to the channel again and it should succeed. `Update YouTube Subscriptions` was only needed when YouTube introduced channel ids instead of plain identifiers.
So, try again to subscribe and it should just work.
Thanks

**Comment by elelay** [comment]
@allanmcpherson did it work for you in the end?
