### ISSUE TITLE
New version available dialog triggered but no new version available

### ISSUE THREAD

**Issue by ongobongo** [gpodder/gpodder#422]
![billede](https://user-images.githubusercontent.com/6172897/37288625-0b86ab14-2608-11e8-9c8d-5d1f489a3214.png) appears when I start the program.
But when I click yes, it opens https://gpodder.github.io/ which shows `Windows: gPodder 3.9.6 (also as ZIP)`

I imagine it is because version 3.10.1 was released only for MacOS.

**Comment by elelay** [comment]
Indeed, 3.10 is only for Linux and macOS.
We are lacking on the Windows front.
