### ISSUE TITLE
gPodder Requires PyGTK

### ISSUE THREAD

**Issue by jasonpriestly** [gpodder/gpodder#423]
Hello.

I've been using gPodder for years now. Reinstalled my OS, Windows 7, then reinstalled gPodder and when I attempt to run it I get the message "gPodder Requires PyGTK See http://gpodder.org/dependencies."

I went here and grabbed "pygtk-2.24.0.win32-py2.7.msi":

http://ftp.gnome.org/pub/GNOME/binaries/win32/pygtk/2.24/

Installed it, same message.

Oh, and that URL in the error message doesn't work, also.

Any ideas? Thanks!

**Comment by elelay** [comment]
Did you try uninstalling gPodder and reinstalling it, now that you have pygtk ?

Can you do the following and post here?

 * Open a command prompt (`cmd`)
 * Type `python --version` and hit <kbd>Enter</kbd>
 * Type `python` and hit <kbd>Enter</kbd>
 * Type `import gtk` and hit <kbd>Enter</kbd>
 * Copy all the text and post here or post a screen shot of the entire command prompt window

The above should hopefully diagnose installation problems.

**Comment by hortensius72** [comment]
I have the same problem now. It began after the last Win10 update.

I had all 32-bit-python, pyGTK, gpodder 3.9.6. I deleted all, including registry, reinstalled, same problem again:
 "gPodder Requires PyGTK See http://gpodder.org/dependencies."

The command prompt shows:
PS C:\> python --version
Python 2.7.13
PS C:\> python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import gtk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Python27\lib\site-packages\gtk-2.0\gtk\__init__.py", line 40, in <module>
    from gtk import _gtk
ImportError: DLL load failed: The specified procedure could not be found.
>>>

The same problem shows up, when it is installed in another directory (reinstallation after complete deinstallation) under  C:\Python27\

**Comment by jasonpriestly** [comment]
Hey elelay,

Thanks for the reply, sorry for the delay in responding. Here's what happens when I enter "python --version":

C:\>python --version
'python' is not recognized as an internal or external command, operable program or batch file.

I sure do have Python installed, though. Two versions, in fact:

C:\Python27\
and
C:\Program Files (x86)\Python36-32

Any idea where I go next to get gPodder working?

**Comment by TZocker** [comment]
I have only a work around for you use https://portableapps.com/apps/internet/gpodder_portable ^^

**Comment by elelay** [comment]
Please use a Gtk3-based version of gPodder (i.e. 3.10.4).
Thanks,
