### ISSUE TITLE
Failed: I/O Error: [SSL: Certificate verify failed] certificate verify failed (_ssl.c:777): None

### ISSUE THREAD

**Issue by ehardy101** [gpodder/gpodder#428]
I downloaded GPodder to use in conjunction with Plex to archive podcasts. I got the following error when trying to download an episode "Failed: I/O Error: [SSL: Certificate verify failed] certificate verify failed (_ssl.c:777): None". I am using MacOSX with Python 2.7.10. I have seen similar errors be resolved by updating Python but not in conjunction with the _ssl.c:777 error.

**Comment by matoro** [comment]
Have you verified that the cert for the site you are trying to download from is, in fact, valid?

**Comment by ehardy101** [comment]
Using an SSL Checker I found that I got the following error.
![sslcert](https://user-images.githubusercontent.com/37640096/37778854-5da4c7c6-2dc1-11e8-871b-5f9c90b7fd51.PNG)

**Comment by ehardy101** [comment]
Do I need to add this cert as a trusted cert? How do I do that in gpodder?

**Comment by ehardy101** [comment]
when I add this rss feed into other apps (Miro is what I used) it works.

**Comment by ehardy101** [comment]
I am not even specifying https when I enter the rss url. The link doesn't require it because I can go to it using http and view the xml in a browser. Why is it using a SSL Cert if its not HTTPS?

**Comment by matoro** [comment]
If you are able to update the feed without problems but not download an episode, it's probably that the episodes are hosted somewhere other than the feed, like a CDN, which might have the broken cert rather than the site hosting the feed.  Can you download an episode using your browser?

**Comment by ehardy101** [comment]
I installed gpodder on one of my other windows machines, added the URL and it was able to download fine so I don't think its hosted elsewhere.

**Comment by wade56** [comment]
I am having this same problem on Win7.  I newly installed Win7 and then installed gPodder. Some of my feeds work but others don't.  The thing is, I kept my old Win7 disk and went back to it to try gPodder and all the same podcast URLs work just fine! Same OS, same version of gPodder, same feed URLs!

I've even tried completely uninstalling gPodder and deleting the home directory and installing some older versions of gPodder. Same error. Nothing works. I'm attaching a screenshot of the error. This is for gPodder 3.9.6 on Win7. Any help is appreciated.

<img width="514" alt="gpodder_failed_downloads" src="https://user-images.githubusercontent.com/10822357/38576322-ac537ea8-3cb2-11e8-9e99-1937b2b7de7b.PNG">

**Comment by elelay** [comment]
No issue with gPodder 3.10.3 (essentially identical to 3.10.2 on windows) on windows 10: the download is fine.
I'll try in a Win7 VM someday...

**Comment by schwarem** [comment]
I upgraded to 3.10.3 yesterday.  I am getting this same issue on several of my podcasts that were working with the old version.  The podcasts are hosted at fireside.fm and podbean.  Has anyone found a resolution to this?

**Comment by alexis26** [comment]
For those who are on windows and have this pb, try something
Open Internet Options (either via your control panel or within Internet Explorer's Options menu) ; select the Advanced tab, scroll to the bottom and you'll see checkboxes for various SSL and TLS cyphers. Active all SSL and TLS and click OK. reboot, apply win update.reboot 
and try again one the same feed...

**Comment by elelay** [comment]
gPodder should use the bundled version of openSSL, so shouldn't care about Internet Options settings. Worth a try anyway...

**Comment by schwarem** [comment]
For my issue, I have determined it is something with my company's proxy server.  If I run it from home on my laptop without VPN, it works fine, but when I run it through the work network I get these errors.

**Comment by elelay** [comment]
Thanks for the reply @schwarem. Closing now

**Comment by bityob** [comment]
@jaybyrrd @elelay 

Any updates on this?
Is it possible today to ignore ssl verification for specific subscriptions? 
or choose manually to trust the certificate of the site?
