### ISSUE TITLE
sonos extension: SoCo 0.7 deprecates SonosDiscovery

### ISSUE THREAD

**Issue by lingfish** [gpodder/gpodder#431]
Seems that SoCo 0.7 depricates (read: seems to have completely blown it away, which would be different from deprication ;)) SonosDiscovery:

`1521939148.955798 [gpodder.extensions] ERROR: Cannot load sonos from /usr/share/gpodder/extensions/sonos.py: 'module' object has no attribute 'SonosDiscovery'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gpodder/extensions.py", line 251, in set_enabled
    self.load_extension()
  File "/usr/lib/python2.7/dist-packages/gpodder/extensions.py", line 310, in load_extension
    self.module = module_file.gPodderExtension(self)
  File "/usr/share/gpodder/extensions/sonos.py", line 30, in __init__
    sd = soco.SonosDiscovery()
AttributeError: 'module' object has no attribute 'SonosDiscovery'
`

See [release notes](https://github.com/SoCo/SoCo/blob/6cd3b96b0769cced9a27a10854d226647a540034/doc/releases/0.7.rst#sonosdiscovery)

**Comment by elelay** [comment]
Thanks for the heads-up. 0.7 has been released in 2015
If you manage to make it work with the newer code, a pull request would be welcome ;-)

**Comment by stefankoegl** [comment]
SoCo/SoCo#80 contains an example on how to replace ``SonosDiscovery``.

**Comment by stefankoegl** [comment]
The rest of the functionality should still be the same. If you can implement the fix, I could test it on my Sonos at home, and make further changes if necessary.

**Comment by elelay** [comment]
Great! Thanks

**Comment by lingfish** [comment]
Sorry, been busy this week... I obviously have Sonos at home and can't help/test. If I had time, I'd have already thrown a PR over.

**Comment by elelay** [comment]
#440 implements changes

**Comment by elelay** [comment]
I merged #440 in master. It should be fine, since it's the code you tested @lingfish.
Thanks!
