### ISSUE TITLE
gPodder update for Windows 10

### ISSUE THREAD

**Issue by hrasky** [gpodder/gpodder#438]
gPodder tells me to update from 3.9.6 to 3.10.1, but download page still shows 3.9.6 for windows but 3.10.1 for Linux.
Help/Software Updates still shows 3.9.6 even after downloading and installing the file gPodder-3.9.6-setup.exe from https://gpodder.github.io/

**Comment by elelay** [comment]
gPodder 3.10.3 has been released for Linux, macOS and ... windows ;-)
Enjoy!
