### ISSUE TITLE
Update raspberry pi

### ISSUE THREAD

**Issue by Rafaxel** [gpodder/gpodder#445]
I can not update the software Gpodder 3.9.3>3.10.1 
when I use the line "python3 tools/localdepends.py" it says :

> Fetching podcastparser ... 21 KiB
> Skipping: /home/pi/gpodder/src/podcastparser.py
> Fetching mygpoclient ... 65 KiB
> Traceback (most recent call last):
> File "tools/localdepends.py", line 47, in <module>
> tar = tarfile.open(fileobj=io.BytesIO(data))
> File "/usr/lib/python3.5/tarfile.py", line 1562, in open
> raise ReadError("file could not be opened successfully")
> tarfile.ReadError: file could not be opened successfully

Raspberry pi 3B+ Ubuntu mate

**Comment by elelay** [comment]
I can't reproduce it on my machine (PC, ArchLinux).
I've added a line to show the download url to master.
Can you try from a git checkout?
```shell
> git clone https://github.com/gpodder/gpodder.git
> cd gpodder
> python3 tools/localdepends.py
Fetching podcastparser ... 21 KiB
  downloaded from https://files.pythonhosted.org/packages/9f/cb/8114def4ca683116e5eece8347e692588941fb25662e35022abfe38f5c7f/podcastparser-0.6.3.tar.gz
Extracting: /tmp/gpodder/src/podcastparser.py
Fetching mygpoclient ... 42 KiB
  downloaded from http://gpodder.org/mygpoclient/mygpoclient-1.8.tar.gz
Extracting: /tmp/gpodder/src/mygpoclient/__init__.py
Extracting: /tmp/gpodder/src/mygpoclient/api.py
Extracting: /tmp/gpodder/src/mygpoclient/api_test.py
Extracting: /tmp/gpodder/src/mygpoclient/feeds.py
Extracting: /tmp/gpodder/src/mygpoclient/http.py
Extracting: /tmp/gpodder/src/mygpoclient/http_test.py
Extracting: /tmp/gpodder/src/mygpoclient/json.py
Extracting: /tmp/gpodder/src/mygpoclient/json_test.py
Extracting: /tmp/gpodder/src/mygpoclient/locator.py
Extracting: /tmp/gpodder/src/mygpoclient/locator_test.py
Extracting: /tmp/gpodder/src/mygpoclient/public.py
Extracting: /tmp/gpodder/src/mygpoclient/public_test.py
Extracting: /tmp/gpodder/src/mygpoclient/simple.py
Extracting: /tmp/gpodder/src/mygpoclient/simple_test.py
Extracting: /tmp/gpodder/src/mygpoclient/testing.py
Extracting: /tmp/gpodder/src/mygpoclient/util.py
```

**Comment by tmancill** [comment]
@Rafaxel Can you provide more detail on what version of Ubuntu you're running on and where the gpodder package is coming from?  I'm the Debian maintainer of gpodder and the [Ubuntu distribution package](https://packages.ubuntu.com/bionic/gpodder) appears to track the Debian package closely.  Therefore, I might be able to address the issue in Debian.
