### ISSUE TITLE
MacOS crashes with Python3 unexpected error when exporting to local folder

### ISSUE THREAD

**Issue by mckenziec** [gpodder/gpodder#460]
This is very disappointing because it used to work fine and I can't figure out what the problem is. When trying to export an episode to a local folder gPodder 3.10.1 crashes with an unexpected, and unspecified Python3 error. All I want to do is grab the mp3 files that are already in the gPodder download directory, named according to the episode. I don't know if its an untested file write/check issue, but if you let me know how to diagnose what the error could be I'll post a follow up. Thanks.

**Comment by elelay** [comment]
This is a duplicate of #413.
Some files are missing in the app resources. I'll release a fixed version shortly
