### ISSUE TITLE
Windows v3.9.6 reports "New version available", but new version is NOT available for Windows

### ISSUE THREAD

**Issue by Drascic** [gpodder/gpodder#464]
Version 3.9.6 automatically checks for updates at startup. The Windows version always reports:

##     New Version Available

    Installed version: 3.9.6
    Newest version: 3.10.1
    Release date: 2018-02-19T21:33:31Z

    Download the latest version from gpodder.org?

However, the latest version available for Windows is 3.9.6.

Rather than updating the code for the Windows version, it might be simpler to update the server settings. If the server can recognize the platform  from which an update query is coming, it could customize its answers so as to report the most recent version available for that platform.

**Comment by elelay** [comment]
A Windows version will be out soon
