### ISSUE TITLE
gpodder.net website is throwing 502's on register and password endpoints (POST)

### ISSUE THREAD

**Issue by MaikuMori** [gpodder/gpodder#466]
Considering everything else is working, maybe email sending integration is failing?

**Comment by alanpost** [comment]
This report started in #gpodder on Freenode.  I lurk there but am not able to provide much operational help beyond confirming gpodder.net is up.  @MaikuMori kindly moved that conversation here.  Thank you to whomever is able to investigate this.

**Comment by stefankoegl** [comment]
Hi, thank for bringing this here. I have just fixed the issue, and will now resend the emails that have been reported.
