### ISSUE TITLE
Add option to hide New Episodes

### ISSUE THREAD

**Issue by JohnCLeBlanc** [gpodder/gpodder#468]
Hi,
I"m using gpodder 3.9 on Win10 64-bit. The link below shows that I see a list of all podcasts even when I try to filter to downloaded episodes only.
![image](https://user-images.githubusercontent.com/39671598/40586024-b76d8726-6191-11e8-8273-5ada0606248a.png)
this is a critically important feature. Any fixes or suggestions?
Thanks.

**Comment by elelay** [comment]
This doesn't happen for me on Linux (but with a newer version).
Can you try this [updated pre-version](https://ci.appveyor.com/api/buildjobs/tt6kub3awim30hjr/artifacts/tools%2Fwin_installer%2Fgpodder-3.10.1-portable.exe)?
Thanks,

**Comment by JohnCLeBlanc** [comment]
Thanks. Got a warning from Windows 10 stating I shouldn’t run this but I ignored it. However, when I clicked on gPodder, I got the following. Is this a false or a true positive?


[cid:image002.jpg@01D3F784.4D6402A0]

**Comment by elelay** [comment]
@JohnCLeBlanc thanks for testing it.
Unfortunately the image attachmnent was lost when you replied by mail instead of on the web page. Also it showed your address. So I've deleted the comment.

**Comment by JohnCLeBlanc** [comment]
Thanks for responding so quickly.
Here’s the antivirus warning I got. I took a risk and allowed the software to run anyway. I hope this is a false positive.
https://www.dropbox.com/s/5xqlmxxj93wy10b/gpodder%20false%20positive.png?dl=0
V 3.10 still won’t filter to downloaded episodes.
https://www.dropbox.com/s/ji0uglpom8yzx1b/gpodder%20view%20doesn%27t%20filter.png?dl=0

Regards, John LeBlanc

**Comment by elelay** [comment]
OK, I understand, this is the expected behaviour: `View` > `Downloaded Episodes` shows Downloaded and New episodes. Actually, new episodes are always shown.
Cheers,
PS.  To the best of my knowledge, Avast antivirus flagging libgio-2.0-0.dll as a threat is a false positive.

**Comment by JohnCLeBlanc** [comment]
OK thanks but could you consider changing? I'm seeing 5-10 new episodes for every one that is downloaded so that is not functioning much as a filter for downloads only. One has the choice of all episodes if that is what one wants.

**Comment by elelay** [comment]
@JohnCLeBlanc I'm hearing what you say: I've reopened and modified the title to match your request.

**Comment by JohnCLeBlanc** [comment]
Thanks.

**Comment by marcorichetta** [comment]
Hi!

I ran the Git version with [these instructions](https://gpodder.github.io/docs/run-from-git.html) and I'm having the same behaviour as John.

> OK, I understand, this is the expected behaviour: View > Downloaded Episodes shows Downloaded and New episodes. Actually, new episodes are always shown.

I think **Unplayed Episodes** serves the purpose of viewing the New episodes, and **Downloaded episodes** could show downloaded only, like some sort of "hear later" list.

### Downloaded View
![Screenshot](https://user-images.githubusercontent.com/19599150/60980322-a1bc8d80-a30a-11e9-915f-b69b1959b886.png)

I want to contribute if I can, but maybe I need some guidance on a gtk app.
Where do I find the "filter by downloaded" function?

**Comment by elelay** [comment]
Hi @marcorichetta, you're welcome to contribute.

Here is how it works now
 - *Unplayed* episodes are for downloaded new episodes (strongest filter)
 - *Downloaded* episodes are for downloaded episodes, regardless of new or not (less filter)
 - *All* episodes to show all episodes (weakest filter).
On top of this, New episodes undownloaded episodes are always shown, to let you select them for downloading.

This really fits my personal workflow, where I *Check for new episodes* once a week and make my selection in the popup dialog: uncheck all episodes I want to download, click *Mark Old*, select all, click *Download*. I choose to view *Downloaded episodes*.
Also, sometimes I don't want to select what to download right now, so new undowloaded episodes are a reminder of choices to make: either mark them old or download them.

OK for changing the meaning of Downloded episodes to exclude new undownloaded, but I would like an extra checkbox to be added after *Always show new episodes* named *Always show New Episodes* and checked by default to implement this. What do you think?

**Comment by marcorichetta** [comment]
Hi! I want to clarify that I tested the filters in the **All Episodes** section and after your comment I realized maybe I was using it in the wrong way.

> Unplayed episodes are for downloaded new episodes (strongest filter)
> Downloaded episodes are for downloaded episodes, regardless of new or not (less filter)

Currently I have 2 *new* episodes, 1 downloaded and one not, and both **Unplayed** and **Downloaded** filters shows the 2 episodes.

**Downloaded**
![imagen](https://user-images.githubusercontent.com/19599150/61063350-33dd9800-a3d6-11e9-86c2-0f798638e812.png)

**Unplayed**
![imagen](https://user-images.githubusercontent.com/19599150/61063413-4eb00c80-a3d6-11e9-9825-e3a5ac8d1868.png)

>OK for changing the meaning of Downloded episodes to exclude new undownloaded, but I would like an extra checkbox to be added after Always show new episodes named Always show New Episodes and checked by default to implement this. What do you think?

So if that box is _unchecked_ it will show **only downloads** and if checked (By default) it will have the current behaviour?
I like the idea, and if you want I can try to implement it.

**Comment by elelay** [comment]
> So if that box is unchecked it will show only downloads and if checked (By default) it will have the current behaviour?

Exactly.


Filtering happens here: https://github.com/gpodder/gpodder/blob/master/src/gpodder/gtkui/model.py#L145
based on attributes set here: https://github.com/gpodder/gpodder/blob/master/src/gpodder/gtkui/model.py#L385
Menus are created in an xml file https://github.com/gpodder/gpodder/blob/master/share/gpodder/ui/gtk/menus.ui#L194
Actions related to them are created in https://github.com/gpodder/gpodder/blob/master/src/gpodder/gtkui/main.py#L242

**Comment by elelay** [comment]
Regarding your example, I consider *Python's Tale* unplayed (because new and not downloaded).
If it appears to be too confusing, we could also apply the checkbox : unplayed would mean *downloaded and new* excluding undownloaded episodes when the checkbox is unchecked.

**Comment by marcorichetta** [comment]
> Regarding your example, I consider Python's Tale unplayed (because new and not downloaded).

I'm ok with that and I consider it useful too.

For me, the "wrong" behaviour is with the _Downloaded Episodes_ filter.
