### ISSUE TITLE
Unable to follow the YouTube API key creation tutorial 

### ISSUE THREAD

**Issue by bug-re-port-er** [gpodder/gpodder#473]
I'm unable to follow 5th step in the [YouTube API key creation tutorial](https://gpodder.github.io/docs/youtube.html) - no such option is available.

Additionally one of the links (https://developers.google.com/youtube/v3/getting-started?hl=fr) forces language change to french and there is no reason why it should do that, if anything it should force english since that post is in english.

**Comment by elelay** [comment]
Thanks for reporting.
Since 3.10.2, the YouTube API key is not necessary anymore. Have you tried a newer version of gPodder (e.g. 3.10.3)?
