### ISSUE TITLE
Adding YouTube channel to 'Subscriptions' has no effect.

### ISSUE THREAD

**Issue by bug-re-port-er** [gpodder/gpodder#474]
Adding YouTube channel to 'Subscriptions' has no effect.

gPodder 3.9.6 / Windows 10

**Comment by elelay** [comment]
Thanks for the report,
YouTube handling has been improved in gPodder 3.10.3. Have you tried it?

**Comment by elelay** [comment]
Please reopen if you have the issue with gPodder 3.10.3.
