### ISSUE TITLE
Connect through proxy

### ISSUE THREAD

**Issue by Perflyst** [gpodder/gpodder#477]
Would be nice if gpodders supports http and/or socks5 proxies.

**Comment by elelay** [comment]
It does.
See https://gpodder.github.io/docs/user-manual.html#using-a-http-proxy-server

**Comment by elelay** [comment]
Thanks for reporting. Let us know if it doesn't work.

**Comment by Perflyst** [comment]
Thanks, I searched an in-app option.
Would it be possible to integrate the proxy setting into the gpodder preferences?

**Comment by niyumard** [comment]
Given that Iranian government blocks many podcast hosts it'd be nice if there were an in-app option.

**Comment by chromer030** [comment]
Please provide support for socks proxy.

**Comment by masoudd** [comment]
> Please provide support for socks proxy.

gpodder supports socks proxy!
According to [requests docs](https://requests.readthedocs.io/en/latest/user/advanced/#proxies), you just have to set the `ALL_PROXY` environment variable to something like `socks5://localhost:8123` before running gpodder.
Sadly Iranian gov also modifies dns responses so I still haven't been able to download anything through socks yet @niyumard
