### ISSUE TITLE
Python error after install of 3.10.3

### ISSUE THREAD

**Issue by spynumber** [gpodder/gpodder#480]
I get a Python error when I try to start gpodder. Just installed 3.10.3 for Windows.
Message just says "There was an error running bin\gpodder in Python."  Any help for this?

**Comment by elelay** [comment]
Windows version, install directory, screenshot of the error?

**Comment by Baelspar** [comment]
I'm have the same issue.   
Running Windows 7 Home Premium.
Computer/E:/Program Files (x86)/ gPodder/ gPodder app

![image](https://user-images.githubusercontent.com/40309239/41494651-fab7b3ce-70ca-11e8-9e10-3b3cd5278244.png)

**Comment by OMalenfantThuot** [comment]
I have the same issue on Windows 10 Home 64 bit. I'll be glad to do further investigations if you need it.

**Comment by OMalenfantThuot** [comment]
I went back to version 3.10.2 and obtained the same error. I have to go back to 3.9.6 for the program to work. Hope that can help.

**Comment by elelay** [comment]
Maybe try procmon to see all loaded libraries and see if any library is loaded from a funky path.

You'll want to adjust filters to:

    include when 'Process Name' is gpodder.exe
    include when Operation is CreateFile
    include when Result is Success
    include when Path 'ends with' dll

Here is the result on windows 10:
![win10_libs](https://user-images.githubusercontent.com/222469/43006450-0c1a9bc8-8c36-11e8-8c3c-15bf40a313a5.png)

**Comment by elelay** [comment]
I've just tried installing gPodder 3.9.6 and then launching gPodder 3.10.3 in a [Windows 7 VM](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) and it works fine!?

**Comment by OMalenfantThuot** [comment]
I got a new laptop since I commented and 3.10.3 works just fine on it. I don't know what was the problem on the other machine. Thanks for the help.

**Comment by elelay** [comment]
Thanks for reaching back to me.
Maybe it was an old version of some library in C:\Windows making gpodder fail.
