### ISSUE TITLE
Translation no take effect on right clic

### ISSUE THREAD

**Issue by alexis26** [gpodder/gpodder#484]
Hi, i come for help with .po because i think translation is not complete for my language in this new version ... but i see is not the case ; translation is ok.

I looked more thoroughly, and I realize that this is all the right click where translation not take effect : on each flux (left list), on each episodes (central list)

(in fact, not all the right clic, because the right clic on episode detail area - below episodes' list - is translated)

edit : i'm on win7, using 3.10.3 (2018-06-12) in portable version

**Comment by elelay** [comment]
Hi,
thanks for the report.
Confirmed also on windows 10 portable and installer versions.
It works on Linux, though.
