### ISSUE TITLE
Sort by release time or date doesn't work.

### ISSUE THREAD

**Issue by lb-d** [gpodder/gpodder#489]
Both on Arch-linux and Ubuntu with gpodder 3.10.1-1 and it doesn't work right for anything: all episodes, single feed, rss or youtube.  Neigher is the sorting by date when adding new feeds.

**Comment by elelay** [comment]
It works fine for me. Can you provide more info, maybe a screenshot?

**Comment by lb-d** [comment]
![screenshot from 2018-07-04 12-50-26](https://user-images.githubusercontent.com/40788882/42273575-d7c415d8-7f89-11e8-802c-c33deaa3306e.png)

Many of those episodes are downloaded days ago but are tagged 'today'.  I don't have a clue why but it's curious that it happens on both arch and ubuntu.

**Comment by elelay** [comment]
Nice desktop, by the way: is it budgie?

**Comment by lb-d** [comment]
Thanks. That's ubuntu 18.04 with suru ++ gtk theme and zafiro icons with suru folder icons.

**Comment by elelay** [comment]
Thanks,
Is it something with your locale?
Do you have any clue when running `gpodder -v` from terminal?

**Comment by elelay** [comment]
Closing now, due to no response from OP
