### ISSUE TITLE
Error opening file for writing

### ISSUE THREAD

**Issue by dechasso** [gpodder/gpodder#491]
Attempted to install gpodder 3.10.3.  Getting error that it cannot open file for writing for libffi-6.dll.  Even if I skip this one, it errors out on another.  I then tried to just re-install my old rev 3.10.2, but I get the same error.  I am running the installation as administrator.  Have never had this problem on previous revisions of gpodder.

**Comment by elelay** [comment]
Does the portable version expand correctly? Is your destination disk full? Could it be an antivirus blocking the installation?

**Comment by elelay** [comment]
@dechasso I'm closing the issue now, since I can't reproduce it.
