### ISSUE TITLE
gPodder on Win10 won't start

### ISSUE THREAD

**Issue by grumble1965** [gpodder/gpodder#493]
When I try to start a fresh install of gPodder on Windows 10, I get a dialog box with "Episode actions from gpodder.net are merged.", there's a progress bar at 0%, and nothing else happens.

Any ideas?

Thanks!
![gpodderhang](https://user-images.githubusercontent.com/1594290/42552002-1e160014-848f-11e8-8b73-37989de932d2.png)

**Comment by elelay** [comment]
Maybe gpodder.net was not responding at the time.
See #363 for a solution: edit gPodder Settings.json to disable mygpo.
