### ISSUE TITLE
Windows File renaming doesn't work when filename is too long

### ISSUE THREAD

**Issue by doubletissue** [gpodder/gpodder#494]
I'm using gPodder 3.10.3 on Windows, with the "Rename Episodes after Download" extension, and additionally set the add podcast title and add podcast date boxes checked in the config. Most podcasts are renamed fine, but a couple consistently aren't. Here are links to the two I've found:

https://gpodder.net/podcast/biggerpockets-podcast-real-estate-investing-and-wealth-building

https://gpodder.net/podcast/the-radical-personal-finance-podcast-financial-planning-budgeting-frugality-investing-lifestyle-design-financial-independence-1

If there are logs or anything else I can provide to help debug, please let me know.

**Comment by ranthonissen** [comment]
I've experienced the same behavior when podcast titles have accented or other special characters in the titel

**Comment by elelay** [comment]
Thanks for reporting. It's not special character issue, but rather a length issue.

See for instance the ep. 558 of the second podcast: the path will be `C:\gpodder-3.10.3-portable\config\Downloads\Radical Personal Finance_ Financial Independence, Early Reti\2018-07-06 - Radical Personal Finance_ Financial Independence, Early Retirement, Investing, Insurance, Financial Planning - 558-Friday Q&A_ a Financial Independence Checkup, Investing in Private Businesses, How to Do Productive Work While Traveling.mp3`
With the filename 252 chars, the total path 357 chars, it exceeds the [260 chars path limit on NTFS](https://docs.microsoft.com/fr-fr/windows/desktop/FileIO/naming-a-file).
Prepending a '\\?\' prefix, it's possible to give it this filename.

Then, on Windows 7, it's difficult to do anything with it: you can't rename it from windows explorer, or move it to another folder.
On Windows 10, no problem for copying and renaming.

A maximum file length parameter is missing in the call to `sanitize_filename` in the `rename_download.py` extension. But `sanitize_filename` should keep the extension.
I'll fix it.
