### ISSUE TITLE
gPodder does not work with https after update to 3.10.3

### ISSUE THREAD

**Issue by TinoJ** [gpodder/gpodder#495]
Hi,
yesterday a notice window popped up and I updated to version 3.10.3 for windows. Portable Version on Win 7 64bit.
After that gPodder stopped to work with anything over HTTPS.
HTTP works fine.

See screenshots for adding youtube feed:
![17 07](https://user-images.githubusercontent.com/18018490/42843365-29c664b8-8a10-11e8-9424-522da8cd4f91.png)

See error for audio feed update
![17 07b](https://user-images.githubusercontent.com/18018490/42843445-6d992c8e-8a10-11e8-9607-78fe816b42e2.png)

See error for download of content:
![17 07c](https://user-images.githubusercontent.com/18018490/42843617-f7a4a264-8a10-11e8-973d-8396e757612f.png)

lib/
gdk-pixbuf-2.0
girepository-1.0
python3.6
sqlite3.21.0
thread2.8.2

Is it a bug or a different problem? Any advice?
Thank you very much,
Tino

**Comment by elelay** [comment]
Thanks for reporting.
Do you have another installation of python?

Maybe try [procmon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) to see all loaded libraries and see if any library is loaded from a funky path.

You'll want to adjust filters to:
 - include when 'Process Name' is gpodder.exe
 - include when Operation is CreateFile
 - include when Result is Success
 - include when Path 'ends with' dll

Here is the result on windows 10:
![win10_libs](https://user-images.githubusercontent.com/222469/43006450-0c1a9bc8-8c36-11e8-8c3c-15bf40a313a5.png)

**Comment by TinoJ** [comment]
I have tried procmon on Win7 64bit Prof with gPodder portable from Portable Apps. The included python seems to be loaded: C:\PortableApps\gPodderPortable\App\gPodder\data\lib\python3.6\lib-dynload

![25 07a](https://user-images.githubusercontent.com/18018490/43229843-73454ab2-9066-11e8-8480-ca41c9583a41.png)
![25 07b](https://user-images.githubusercontent.com/18018490/43229849-7a3d306e-9066-11e8-8e05-21a337f26838.png)
![25 07c](https://user-images.githubusercontent.com/18018490/43229856-7c2ba432-9066-11e8-9b88-96a7df32bb5c.png)

**Comment by TinoJ** [comment]
And then I tried again the portable version directly from your website and got this result:

![26 07a](https://user-images.githubusercontent.com/18018490/43230038-208b3042-9067-11e8-9cb1-4a43f9b330e7.png)
![26 07b](https://user-images.githubusercontent.com/18018490/43230042-222c7884-9067-11e8-9e78-1db781d9c160.png)
![26 07c](https://user-images.githubusercontent.com/18018490/43230044-248198bc-9067-11e8-805f-da87025572ec.png)

**Comment by elelay** [comment]
@TinoJ  thanks for investigating.
Indeed, there is an issue, as `c:\Windows\libeay32.dll` is loaded instead of the one in `C:\PortableApps\gPodderPortable\App\gPodder\data\bin`.
Can you rename  `c:\Windows\libeay32.dll` to  `c:\Windows\libeay32.dll.broken` and retry https in gPodder? Preferably with procmon on (you are familiar with it by now ;-)) to confirm `C:\PortableApps\gPodderPortable\App\gPodder\data\bin\libeay32.dll` is now loaded?

**Comment by TinoJ** [comment]
The other dll seems to be loaded, but unfortunately it does not fix the issue.

![28 07a](https://user-images.githubusercontent.com/18018490/43349420-f11fd282-91ff-11e8-9025-fe04be48784a.png)
![28 07b](https://user-images.githubusercontent.com/18018490/43349424-f31e496a-91ff-11e8-981b-aea6c1dae873.png)
![28 07c](https://user-images.githubusercontent.com/18018490/43349426-f515f3a8-91ff-11e8-966d-0360923f2194.png)

**Comment by elelay** [comment]
Well, ssleay32.dll is also part of openssl and is also shipped in gpodder\bin. As we see in the last image, it is loaded from windows directory.
Can you rename `c:\Windows\ssleay32.dll` to `c:\Windows\ssleay32.dll.broken` and retry?
Don't worry: there are not that many libraries affected (see #478) so I wont keep asking you to rename all your DLLs one after the other...

**Comment by TinoJ** [comment]
It works with this last proposed work-around.
To be sure I restored libeay32.dll.broken and rebooted. The problem reoccurred.
So it seems both files have a connection to the problem.

**Comment by elelay** [comment]
Great! Next release has a fix for this kind of problems: ensuring it prefers libraries from gpodder bin directory to from windows directory.
