### ISSUE TITLE
gpodder 3.10.3 doesn't start on windows 10

### ISSUE THREAD

**Issue by Chrits55** [gpodder/gpodder#501]
after i upgraded to GPodder 3.10.3 for Windows on my Windows 10  machine i get an error message that "there was an error running bin\gpodder in Python." ?? whta's going on and how do i get GPodder work :????

**Comment by elelay** [comment]
Please try 3.10.4 : it loads all libraries from gPodder install directory.

**Comment by elelay** [comment]
Closing now, due to no response from OP
