### ISSUE TITLE
Missing translatable content

### ISSUE THREAD

**Issue by TZocker** [gpodder/gpodder#503]
1. No translate ID for Search.

![search](https://user-images.githubusercontent.com/20260822/43370697-041d5d02-9384-11e8-8fcb-4185f85eb0b0.png)

2. Link isn't open in the Webbrowser (Bug-Tracker / Website) / ID for Translation?

![uber](https://user-images.githubusercontent.com/20260822/43370716-42d7d608-9384-11e8-8134-26521839a251.png)

**Comment by TZocker** [comment]
Sry i have found more....

![addons](https://user-images.githubusercontent.com/20260822/43545982-b1d012e6-95d7-11e8-87c7-2a66011cf836.png)

**Comment by elelay** [comment]
Fixed, thanks for reporting

**Comment by TZocker** [comment]
thx,

can you merge 

#: src/gpodder/gtkui/desktop/podcastdirectory.py:188
msgid "Search:"
msgstr ""
#: src/gpodder/gtkui/desktop/podcastdirectory.py:189
msgid "Search"
msgstr ""

together like "stringSearch": and only "stringSearch"

thx

**Comment by elelay** [comment]
I'd rather not: in French, for instance, there is a space before and after colon, in English only after...
