### ISSUE TITLE
AttributeError: module 'gpodder' has no attribute 'log'

### ISSUE THREAD

**Issue by dieterdeyke** [gpodder/gpodder#504]
On debian testing with gpodder git commit 7e20eb1a50743ec306c204198fa5a66464dd26dd I get

deyke@deyke2> gpo                                                             ~
Traceback (most recent call last):
  File "/usr/local/gpodder/bin/gpo", line 128, in <module>
    gpodder.log.setup(verbose)
AttributeError: module 'gpodder' has no attribute 'log'

gpodder git commit a1da47dfaeff0205be83acce168aaeb703fe8c0e does not show this error.

**Comment by elelay** [comment]
Thanks for the report! I didn't catch the error.
