### ISSUE TITLE
Limited number of downloadable episode

### ISSUE THREAD

**Issue by jameshkk** [gpodder/gpodder#508]
Hello, 

It seems that this program has a limit on the number of episodes to access, probably around 200, when the podcast has more than 200 episodes.

**Comment by TZocker** [comment]
I have also he bug e.g. Podcast:

http://www.monstercat.com/podcast/feed.xml

greetz

**Comment by elelay** [comment]
There is an option to control that in Preferences > Update.
It lets you increase it up to 1000, but you can increase it further for even more prolific podcasts, by editing the configuration key `limit.episodes`.

**Comment by fake-name** [comment]
Yes, you can hand-edit a config file to work around the issue, but why is there a limit in the first place?

**Comment by cj1985** [comment]
This is really annoying, please just remove the limit. Surely it's easier for someone who wants to download fewer episodes to choose the episodes she wants than for someone who wants to download all the episodes to go edit all this.

**Comment by auouymous** [comment]
I've never agreed with the limit, but it did come in handy when 3.11.0 shipped with a bug that broke gpodder on slow machines exceeding the limit. I have some patches almost ready to go that fix the bug and improve UI responsiveness when downloading thousands of episodes. I also have plans to further improve the responsiveness, and maybe after that we can increase the limit a little.

**Comment by cj1985** [comment]
I think one simple thing that could help is to add a simple message stating that there are actually more than 200 episodes in the podcast.

It took me downloading several podcasts and noticing that weirdly enough all of them somehow had exactly 200 episodes before I realized this was just a restriction by gPodder.

**Comment by auouymous** [comment]
It would be nice to display the total number of feed episodes on the channel page or in its tooltip, with something indicating limit.episodes was discarding some of them. But I doubt that would have helped you. Some feeds are also paginated and gpodder stops loading pages when the limit is reached. For these feeds, the total count would be clamped, so any message could only inform the user that an unknown number of episodes were discarded by the limit.

The easiest solution would be to log a message that some episodes were discarded, but no one would see that either. Do you have suggestions on how to notify the user about this without an intrusive notification every time they update the feed?

**Comment by cj1985** [comment]
I'm not sure why it's so difficult/complicated to have a simple message like this:

"This podcast has more than 200 episodes, but gPodder will download only the last 200 episodes. To increase this limit, go to XXX."

**Comment by auouymous** [comment]
I have the limit set to about 10, which means I will receive this message daily, for ~100 feeds. Would this intrusion be a message dialog or a notification? That is the complication, finding a non-intrusive way to notify the user, without nagging those who only need the newest episode and want a small database file.

**Comment by cj1985** [comment]
Well yea, if you've already manually changed the limit to something else, then gPodder doesn't need to show you the message.

The message would be for most new users (like myself) who assume (incorrectly) that when they copy-paste a link, they're downloading all of the podcast's episodes.

You could also just show it once.

**Comment by LinuxArie** [comment]
> There is an option to control that in Preferences > Update. It lets you increase it up to 1000, but you can increase it further for even more prolific podcasts, by editing the configuration key `limit.episodes`.

Unfortunately that does not work with 3.11.3 Linux
Tried to set the limit to 2000 but still no more then 1000 episodes are downloaded. Planetary Radio has at the momen just over 1200 episodes.

**Comment by auouymous** [comment]
@LinuxArie Does it have 1200 episodes in the RSS file, or does it use pagination and only has 1000 in the first page? Some feed sites implement their own pagination not supported by gpodder. There might also be a bug that requires you to resubscribe after changing the limit.

**Comment by LinuxArie** [comment]
Used the OPML file from Antennapod. Antennapod and PodcastAddict (both Android apps) show 1211 episodes. Gpodder says 1211 episodes but only download 1000, even if I change the config file to a limit of 2000 episodes.

**Comment by auouymous** [comment]
@LinuxArie Can you provide the feed URL?

**Comment by LinuxArie** [comment]
Sorry for my late response.

planetary radio, 1is from the OPML file, the other from the search with Rhytmbox Linux
https://podcasts.apple.com/us/podcast/planetary-radio-space-exploration-astronomy-and-science/id91689834?uo=4

https://www.omnycontent.com/d/playlist/d95da206-8ee8-4ba5-ba8d-ad1200b4e5a4/cf13d5f5-6040-458d-ab5a-ad200189747d/b75c9f7f-4a63-438e-b506-ad2001897499/podcast.rss

It looks like the problem is solved. Re-installed Gpodder. Before adding the podcast from the OPML file I changed first the setting for limit.episodes to 2000. After adding the podcast subscription I have now 1212 files in the download folder, most of them partial because he's still downloading.
