### ISSUE TITLE
3.10.3 locking under Win 10

### ISSUE THREAD

**Issue by cmtonkinson** [gpodder/gpodder#509]
reproduction: Add new show, queue all episodes for download, after variable number of successful downloads, gPodder locks, "Not Responding." Kill from taskman, restart, and is able to resume failed episodes (but again, hangs after an unguessable number of items).

**Comment by cmtonkinson** [comment]
With or without bandwidth cap, with or without simultaneous downoads.

**Comment by cmtonkinson** [comment]
And it does seem to lock up mid-download, and not upon finishing (at least, according to the progress reported through the UI). Doesn't matter whether using the GUI or CLI.

**Comment by cmtonkinson** [comment]
Also (sorry for the spam) worth noting that when it locks, it spins at about 10% CPU (on a hexcore i7) with about 35-40MB memory, no network or disk activity to speak of.

**Comment by cmtonkinson** [comment]
Sometimes I've had to restart twice just to finish one episode. Once in a while I get a run of 10 or 20 before it locks up, but that's rare. Average 3-5. I can hear my fans kick up when it locks. Only thing in the Windows Event Log is the boilerplate application failed to respond and was terminated.

**Comment by elelay** [comment]
Thanks for reporting.
Please, can you collect the debug log, following [these instructions](https://gpodder.github.io/docs/windows.html#debugging-gpodder-on-windows)?

**Comment by elelay** [comment]
Just downloaded 20 episodes (~1GB) with no lock...

**Comment by jonathangodoy** [comment]
@cmtonkinson @elelay, I also have been experiencing "locking" under MacOS 10.13.6. Only way to solve the problem is to force quit the app several times (2 or 3 times) until a video completes its download. There's also another case where some videos that are broadcasting live on YouTube try to download; this also seems to cause a lockup in MacOS. I'm currently running gPodder 3.10.3. Thanks!

**Comment by cmtonkinson** [comment]
Sorry I never responded. Nothing interesting in the logs (no traces, no unnecessary repetition, nothing).

One other thing I have seen, however, is that when this happens, the "current download speed" indicator in the title bar increases dramatically as the program locks up. e.g. it will download steadily at some rate (say 10-20Mbps) and then when it freezes I notice it's reporting some extreme download rate. I've seen everything from 800Mbps to 3Gbps (note that my download limit per my ISP is about 400Mbps).

**Comment by jonathangodoy** [comment]
@cmtonkinson, same here.

<img width="1156" alt="gpodder" src="https://user-images.githubusercontent.com/9908527/44611699-a5f5c000-a7b7-11e8-955a-a9a36580101e.png">

**Comment by elelay** [comment]
Thanks for the screenshot.
Please, can either of you collect the debug log, following [these instructions](https://gpodder.github.io/docs/windows.html#debugging-gpodder-on-windows)?

**Comment by elelay** [comment]
In retrospect, it was definitely #550
