### ISSUE TITLE
Can I avoid empty downloaded files?

### ISSUE THREAD

**Issue by stefankoegl** [gpodder/gpodder#513]
*From @RichardV22 in gpodder/mygpo#78*

> When I check for new episodes and download them, in my PC's Downloads folder I get a file for every podcast programme on my list, whether or not a new podcast episode has been downloaded. This makes it tedious to go through and find the new podcasts and delete the blank files (actually the 'blank files' contain a thumbnail link, which is irrelevant).
> Can I avoid downloading the programme name as a folder when there is no new episode?

**Comment by elelay** [comment]
@RichardV22 this is not possible at the moment. For instance, the thumbnail is used to display the podcast icon in the left pane.
