### ISSUE TITLE
"Preferences" no longer in pulldown menu

### ISSUE THREAD

**Issue by whenelvisdied** [gpodder/gpodder#514]
Upon upgrading to Ubuntu 18.04 a few weeks ago, I discovered that the Preferences dialog is no longer visible in the gpodder "Podcast" pull-down menu. The preferences dialog does come up with a CTRL-P keyboard shortcut, but isn't visible in the menu itself. Not sure if this was by design or accident, but I use the Preferences menu fairly regularly as I have an issue with an MP3 player USB syncing location so I notice it.

**Comment by elelay** [comment]
Don't you see it in the application menu?

**Comment by whenelvisdied** [comment]
Nope--if I click on the "Podcasts" menu, where Preferences used to be, it shows "Check for New Episodes" "Download New Episodes" and "Delete Episodes" and that's it.

**Comment by mhussaincov** [comment]
hi,
ubuntu 18.04 is using an older version of gpodder,
it is faulty
if you go and check for updates what does gpodder do?
does it tell you that it is up to date?
Majid

On 06/08/2018, whenelvisdied <notifications@github.com> wrote:
> Nope--if I click on the "Podcasts" menu, where Preferences used to be, it
> shows "Check for New Episodes" "Download New Episodes" and "Delete Episodes"
> and that's it.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/gpodder/gpodder/issues/514#issuecomment-410791155


-- 
kind regards,
Majid Hussain

**Comment by whenelvisdied** [comment]
current installed version is 3.10.1-1

**Comment by mhussaincov** [comment]
i'm running 3.10.3
here on arch linux,
and menus for me display fign,
I use a screen reader so shortcuts are assential for me you see,
I would ask you to use the gpodder ppa, but it's not been updated for
along time,
would you be aposed to running via git?


On 06/08/2018, whenelvisdied <notifications@github.com> wrote:
> current installed version is 3.10.1-1
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/gpodder/gpodder/issues/514#issuecomment-410793126


-- 
kind regards,
Majid Hussain

**Comment by whenelvisdied** [comment]
It's not really worth it to me, as CTRL-P still pulls up the menu and so the bug isn't particularly inconvenient. I guess I just wanted to let devs know in case this bug had gone unsquashed. I'll keep an eye out for new versions and install from GIT if it gets too difficult.

**Comment by elelay** [comment]
See in this capture:
![menu](https://user-images.githubusercontent.com/222469/43734386-d8faa276-99b7-11e8-9139-3bb0d2e92e0b.png)

Preferences are not in the **Podcasts** menu anymore but in the **gPodder** (aka application) menu.
Depending on your desktop, it maybe is detached from the menubar.

**Comment by whenelvisdied** [comment]
Mine doesn't have a gpodder or application menu. Weird. I'll poke around a bit. 

Thanks for the assistance, all!
