### ISSUE TITLE
gpodder does not recognize new episodes as new and therefore does not download them

### ISSUE THREAD

**Issue by dieterdeyke** [gpodder/gpodder#516]
gpodder does not recognize new episodes as new and therefore does not download them. This happens with this feed:

https://www.tagesschau.de/export/video-podcast/webl/tagesschau_https

workaround is to manually set the new flag

**Comment by elelay** [comment]
It appears this export link has an error, even if it's still listed on [tagesshau website](https://www.tagesschau.de/infoservices/podcast/index.html).
That one still works: https://www.tagesschau.de/export/video-podcast/tagesschau_https/

**Comment by elelay** [comment]
Also there is an error in the feed for episode **26.07.2018 - tagesschau 20:00 Uhr**: the published date is `Sun, 26 Aug 2018 20:00:00 +0200`, placing it before the others.
I'll keep an eye on it, see if I can reproduce your issue...

**Comment by dieterdeyke** [comment]
Eric Le Lay <notifications@github.com> writes:

> It appears this export link has an error, even if it's still listed on tagesshau website.
> That one still works: https://www.tagesschau.de/export/video-podcast/tagesschau_https/

Even this other one did not work for me.

-- 
Dieter Deyke
mailto:dieter.deyke@gmail.com
Get my Gnupg key:
gpg --keyserver keys.gnupg.net --recv-keys B116EA20

**Comment by elelay** [comment]
Yes, I can reproduce the issue.
This is really due to the episode **26.07.2018 - tagesschau 20:00 Uhr** publish date in August.
It will resolve itself in 10 days or with next release.
