### ISSUE TITLE
Strip whitespace around RSS links before adding

### ISSUE THREAD

**Issue by Marundu** [gpodder/gpodder#520]
I noticed you cannot add podcasts via RSS link if there is a space at the beginning of the link. I tried with two podcasts and an error occurred (see screenshots). Also, gPodder does not pick up the link from the clipboard if it has beginning whitespace. I'm running 64-bit Linux Mint 18. 

![whitespacepodcasterror1](https://user-images.githubusercontent.com/6661880/44024255-7355a7de-9ef5-11e8-982a-ac5c9a68bf35.png)

![whitespacepodcasterror2](https://user-images.githubusercontent.com/6661880/44024256-73b3c508-9ef5-11e8-933e-397e029bd0b7.png)

**Comment by elelay** [comment]
Good point.
That would be a an easy improvement if you're interested.
Everything happens in [addpodcast.py](https://github.com/gpodder/gpodder/blob/master/src/gpodder/gtkui/interface/addpodcast.py).

**Comment by Marundu** [comment]
Seeing this now...
Let me give it a go.

**Comment by Marundu** [comment]
Thanks. Let me look into it. 

How do I get started contributing to the project?

**Comment by elelay** [comment]
1. Fork the project (button on top-right of this page).
    this will create a copy of the code at https://github.com/Marundu/gpodder
2. clone your fork to work on the code on your computer
3. `python3 tools/localdepends.py` to install dependencies
3. `./bin/gpodder -v` to show debug messages
3. make the changes, commit in a branch and push the branch to your fork
4. on your forked repository webpage on github, a "Make pull request" banner will appear for your new branch.
5. submit a pull request. I'll review it and help you get it in shape for incorporating in gPodder
6. Thanks and well done ;-)
