### ISSUE TITLE
gpodder 3.10.3 starts under windows 10 with RunDLL error

### ISSUE THREAD

**Issue by svrnwnsch** [gpodder/gpodder#521]
I installed gpodder fresh under windows 10 but on a second hard disk. 
When I start the application I get always the following error window
![rundll error](https://user-images.githubusercontent.com/1852828/44026162-6f808c6c-9ef2-11e8-8c52-596db0a9c600.PNG)

Translation: Problem during start of D:\Program
The specified module could not be found.

The installation path of gpooder is: "D:\Program Files (x86)\gPodder"

The program nevertheless starts normal and as far as I can tell works normal.

**Comment by svrnwnsch** [comment]
Installing the latest build did not change the error.

**Comment by elelay** [comment]
Do you start gpodder.exe from a shortcut?
Is is the same if you browse to D:\Program Files (x86)\gPodder and then double click gpodder.exe?
Can you try collecting a debug log using [this procedure](https://gpodder.github.io/docs/windows.html#debugging-gpodder-on-windows)?

**Comment by ArgleKargle** [comment]
@elelay I've got the same issue so I followed the instructions you left for svrnwnsch. I've also tried re-installing. This is after installing the latest build, 3.10.6.

Here's what appears in logs as soon as I run into the error. It's followed by a lot of stuff that looks pretty normal and then some dbsqlite errors that seem unrelated. 

Let me know if you need more complete log output. 

```
1546558574.289572 [gpodder.log] DEBUG: ==== gPodder starts up (ui=gtk) ===
1546558574.375569 [gpodder.util] WARNING: html5lib not found, falling back to HTMLParser
1546558574.638562 [gpodder.gtkui.shownotes] INFO: No WebKit2 gobject bindings, so no HTML shownotes
1546558574.692560 [gpodder.sync] WARNING: Could not find gpod
1546558574.693560 [gpodder.sync] WARNING: Could not find eyed3.mp3
```

**Comment by elelay** [comment]
Thanks for reporting.
The WARNINGs are normal: not all libraries are shipped on windows (#581), so they wouldn't explain the RunDLL error.
I'd be interested in the dbsqlite errrors, though.

Also, can you try running [procmon](https://github.com/gpodder/gpodder/issues/495#issuecomment-406609555)?

**Comment by elelay** [comment]
Only, don't put the 'result is success' filter

**Comment by elelay** [comment]
Closing due to no response from OP
