### ISSUE TITLE
YouTube playlists seem to cap at 15

### ISSUE THREAD

**Issue by trlkly** [gpodder/gpodder#523]
I've subscribed to this playlist: https://www.youtube.com/playlist?list=PL_sYhAj0WXRNAq14rcgKF7KZmGz8R3Xrh by putting it as a new podcast URL. It contains 24 videos as of this post. However gPodder only seems to detect the first 15. 

This seems to be a problem with the videos.xml feed: it is only showing the first 15 videos. Checking the feed for other podcasts seems to have the same limitation. 

Channels seem to be unaffected by this limitation, as they update in reverse chronological order (newest on top), just like an RSS feed.

**Comment by elelay** [comment]
Unfortunately, there's no way around this.

**Comment by elelay** [comment]
Re. scraping the webpage, that's not a direction I want to go to.
Another way would be to use the YouTube data api. We tried it but it was a nuisance, requiring each user to generate an api key.
Responsiveness from the developers is something I find valuable. Unfortunately, I don't have time to be as fast to answer to all issues: I batch them when I have a little time, like Today.
