### ISSUE TITLE
feature request enable convertion to opus file format after podcast download

### ISSUE THREAD

**Issue by mhussaincov** [gpodder/gpodder#526]
after a podcast is downloaded have the ability to convert to the opus file format, I believe this would be a post download step?
I believe that there is the ability to convert to mp3/ogg after download could opus be also added?
the opus audio format is perfect for podcasts this is my apinion.
thanks for considdering my feature request.

**Comment by elelay** [comment]
Thanks for submitting the idea. It should be possible to extend the [audio_converter.py](https://github.com/gpodder/gpodder/blob/master/share/gpodder/extensions/audio_converter.py) extension to handle more formats. Would you like to try to do it?

**Comment by mhussaincov** [comment]
hi there master erick,
i'm not a programmer in any way shape or form, I so wish I was,
I myself am unable to do this,
if anyone could give a helping hand, I would be greatful :)
Majid Hussain

On 20/08/2018, Eric Le Lay <notifications@github.com> wrote:
> Thanks for submitting the idea. It should be possible to extend the
> [audio_converter.py](https://github.com/gpodder/gpodder/blob/master/share/gpodder/extensions/audio_converter.py)
> extension to handle more formats. Would you like to try to do it?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/gpodder/gpodder/issues/526#issuecomment-414426030


-- 
kind regards,
Majid Hussain

**Comment by elelay** [comment]
OK, so I leave it open as Easy Pick, if somebody wants to try :-)

**Comment by elelay** [comment]
Closed by #533

**Comment by mhussaincov** [comment]
hi there,
just tryed the opus convertion by ticking the box that says
extention use opus set to true,
after the file downloads i check in the podcast dir of the podcast and there is just the mp3 file in there the opus file does not exist.
could there be an issue with this?

**Comment by elelay** [comment]
Have you activated the *Convert After Download* extension?

**Comment by mhussaincov** [comment]
hi,
is it named
extentions.command on download.command?

if so I have this in the entery box

zenity --info --width=600 --text="file=$filename podcast=$podcast
title=$title published=$published section=$section
playlist_title=$playlist_title"

if not then i'm not able to find it.

On 15/11/2018, Eric Le Lay <notifications@github.com> wrote:
> Have you activated the *Convert After Download* extension?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/gpodder/gpodder/issues/526#issuecomment-439156281


-- 
kind regards,
Majid Hussain

**Comment by mhussaincov** [comment]
hi there,
it's gold!
it works!
thanks!
being cheeki but is  it possible to change the bitrate of the audio file?
thanks for all your work, so happy now!
Majid

On 15/11/2018, Eric Le Lay <notifications@github.com> wrote:
> No, it's *Convert Audio Files* in the Extensions tab of preferences.
> But you're right: even when the extension is loaded, conversion from mp3
> doesn't happen.
> I've just pushed (5dee1203) new code to fix this and to fix the opus
> conversion command.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/gpodder/gpodder/issues/526#issuecomment-439178722


-- 
kind regards,
Majid Hussain

**Comment by elelay** [comment]
Just edit the extension. It's the easiest way for now.

**Comment by mhussaincov** [comment]
sorry for being a pain, but how do i edit  the extention?
my thanks,
Majid Hussain

On 15/11/2018, mhussaincov <notifications@github.com> wrote:
> hi,
> is it named
> extentions.command on download.command?
>
> if so I have this in the entery box
>
> zenity --info --width=600 --text="file=$filename podcast=$podcast
> title=$title published=$published section=$section
> playlist_title=$playlist_title"
>
> if not then i'm not able to find it.
>
> On 15/11/2018, Eric Le Lay <notifications@github.com> wrote:
>> Have you activated the *Convert After Download* extension?
>>
>> --
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/gpodder/gpodder/issues/526#issuecomment-439156281
>
>
> --
> kind regards,
> Majid Hussain
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/gpodder/gpodder/issues/526#issuecomment-439162307


-- 
kind regards,
Majid Hussain

**Comment by elelay** [comment]
How did you get the latest fix I made? `cd /home/.../gpodder && git pull`? If so, edit the file `share/gpodder/extensions/audio_converter.py` inside the folder you cloned gpodder to. Replace `-b 64k` with what suits you best (and let me know what you use, I'm curious: is it too high or too low?).

**Comment by mhussaincov** [comment]
hia erick,
i'm running arch linux with yay as my aur helper.
there is a git pkg build which builds and all
it makes git retreve gpodder in to a bare reposatory so I am not shure
where the files are stored.


currently the bitrate is 56kbps,
I would say 32 kbps monow would be okay personally.
thanks,
Majid Hussain

On 16/11/2018, Eric Le Lay <notifications@github.com> wrote:
> How did you get the latest fix I made? `cd /home/.../gpodder && git pull`?
> If so, edit the file `share/gpodder/extensions/audio_converter.py` inside
> the folder you cloned gpodder to. Replace `-b 64k` with what suits you best
> (and let me know what you use, I'm curious: is it too high or too low?).
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/gpodder/gpodder/issues/526#issuecomment-439538606


-- 
kind regards,
Majid Hussain
