### ISSUE TITLE
Tag downloaded files not functioning if I change download directory

### ISSUE THREAD

**Issue by rwoodpecker** [gpodder/gpodder#531]
As per the title, if I change the download directory on gpodder from the default (i.e export GPODDER_DOWNLOAD_DIR=/media/BigDisk/Podcasts/) the tagging extension won't do anything to the files. If I remove this and go back to the default download directory, the tagging works perfectly..

I tried moving both the gpodder home directory and download directory to my external hardrive and running things from there, but tagging does not work that way either. The renaming after download extension is functioning correctly.

All I can see in the logs are:
[gpodder.sync] WARNING: Could not find gpod
[gpodder.sync] WARNING: Could not find eyed3.mp3

1535204851.847794 [gpodder.dbsqlite] DEBUG: Commit.
1535204852.164257 [tagging] INFO: tagging.on_episode_downloaded(Astonishing Legends/Mystery of the Flannan Isles Lighthouse Part 2)
1535204852.164697 [gpodder.download] INFO: No more tasks for Thread-9 to carry out.
1535204853.026887 [gpodder.gtkui.main] INFO: All tasks have finished.
1535204853.115782 [gpodder.gtkui.main] INFO: All tasks have finished.
1535204856.336757 [gpodder.config] INFO: Flushing settings to disk

I'm running the latest version on OSX, installed via brew cask.

**Comment by elelay** [comment]
Interesting, I'll investigate.
Thanks,

**Comment by rwoodpecker** [comment]
Hi @elelay 

I've done some more experimenting. I couldn't reproduce this issue on another hardrive so I suspect it may be some kind of permission problem. However what confuses me is that the podcasts are getting downloaded and renamed just fine, so I'm not sure why only mutagen would be affected.

In any case, it is failing silently with nothing showing on the debug logs.

**Comment by elelay** [comment]
Indeed, I can't reproduce it.
