### ISSUE TITLE
v3.10.4 - downloads not renamed (add_sortdate)

### ISSUE THREAD

**Issue by jvarsoke** [gpodder/gpodder#540]
Recently upgraded from v3.10.1 to v3.10.4.  Now podcasts are no longer being renamed with their episode title, nor sortdate.  Instead, the native filename is being used.  (was working correctly in v3.10.1)

Confirmed "Renamed After Download" is checked.  "extensions.rename_download.add_sortdate" also checked.

**Comment by elelay** [comment]
Thanks for reporting!
It's broken indeed.
To not wait for the next release, you can simply edit the [rename_download.py extension](https://github.com/gpodder/gpodder/blob/master/share/gpodder/extensions/rename_download.py#L50) and change `utils` to `util` line 50.

**Comment by jvarsoke** [comment]
Brilliant.  Thank you so much for the quick-fix.  (don't suppose there's a way to fix the files downloaded since then . . . other than manually)?

**Comment by elelay** [comment]
Yes, manual rename or re-download :-(

**Comment by omoknen** [comment]
Just so that people know, if you do this fix for the Windows version, there is a problem (probably for longer titles only? or titles with periods?  I have vision problems) for some podcasts.

filenames are renamed but the extension doesn't have a "." period so file names become
NameOfThePodcastmp3

**Comment by kmkrebs** [comment]
> filenames are renamed but the extension doesn't have a "." period so file names become
> NameOfThePodcastmp3

I had this problem after editing as well.  I don't know much about python programming, but I fixed it by changing line 64 in the same file from:

`new_filename = os.path.join(dirname, new_basename + ext) `

to:
`new_filename = os.path.join(dirname, new_basename + '.' + ext)`

So far it doesn't appear I've broken anything else.

**Comment by elelay** [comment]
@omoknen, @kmkrebs thanks: I had not tested the extension after the first fix. It indeed needs re-adding the dot because sanitize_filename strips it...

**Comment by elelay** [comment]
gPodder 3.10.5 is out, with the fix.
