### ISSUE TITLE
Documentation shows wrong gPodder_home & gPodder_download_dir shell var names

### ISSUE THREAD

**Issue by mbmcf** [gpodder/gpodder#543]
I had to move gPodder to another slice, and followed the documentation I found for shell variable names, but gPodder couldn't find the moved 1.5TB of files. After much back & forth, I tried ALL CAPITALS for the shell variable names and that worked.

Would someone please gPodder_home and gPodder_download_dir in the documentation to reflect the correct case ? That would save other folks some agony.

Love gPodder !

Thanks,
Bruce

**Comment by elelay** [comment]
Please tell me where you found gPodder_home and gPodder_download_dir?
They are correctly capitalized in [the user manual](https://gpodder.github.io/docs/user-manual.html#changing-the-downloads-folder-location-and-the-gpodder-home-folder)
