### ISSUE TITLE
Windows version 3.10.5 won't start except in debug mode 

### ISSUE THREAD

**Issue by pnielsenz** [gpodder/gpodder#548]
When I try to start v 3.10.5 in normal mode, the startup fails with a message "cannot find the file specified".

But when I run in debug mode as specified in the documentation, I get the following messages:

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Home>"C:\Program Files (x86)\gPodder\bin\gpodder-cmd.exe" v
Calling SetDllDirectoryW(C:\Program Files (x86)\gPodder\bin)
Successfully SetDllDirectoryW
D: windows build; registry home = E:\gPodder
1537126921.680189 [gpodder.util] WARNING: html5lib not found, falling back to HTMLParser
1537126924.331436 [gpodder.sync] WARNING: Could not find gpod
1537126924.332436 [gpodder.sync] WARNING: Could not find eyed3.mp3
1537126927.131680 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CL
ASSES_ROOT\Winamp.File\shell\Play\command ([WinError 2] The system cannot find the file specified)
1537126927.132680 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CL
ASSES_ROOT\Applications\foobar2000.exe\shell\open\command ([WinError 2] The system cannot find the file specified)
1537126927.133680 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CL
ASSES_ROOT\QuickTime.mp3\shell\open\command ([WinError 2] The system cannot find the file specified)

But then the GUI shows up, and the program runs anyway.

**Comment by pnielsenz** [comment]
I discovered that this is because my shortcut for gPodder had as target "C:\Program Files (x86)\gPodder\gpodder.exe" left from version 3.9.6  When I changed to "C:\Program Files (x86)\gPodder\bin\gpodder.exe" the program starts from the shortcut. 

Thanks to elelay for the hint about shortcuts in a previous post.

**Comment by elelay** [comment]
Glad you figured it out :-)
