### ISSUE TITLE
Gpodder 3.10.15 (Windows) no longer synchronize with device

### ISSUE THREAD

**Issue by Assanica** [gpodder/gpodder#549]
Since 3.10.15 update (on Windows 10), synchronization with device no longer work.
Even though checked settings were unchanged and OK.

**Comment by elelay** [comment]
Thanks for reporting!
Can you try running gPodder in debug mode, to gather more info about the issue ?
See [this link](https://gpodder.github.io/docs/windows.html#debugging-gpodder-on-windows).
What kind of device is it?

**Comment by Rohaq** [comment]
I'm not even seeing the MTP device option in Windows 10, and can't find any instructions on how I might get it working.
