### ISSUE TITLE
Need step by step instructions on how to change downloads location.

### ISSUE THREAD

**Issue by Pollllll** [gpodder/gpodder#551]
Hi, it's not issue, per se, but can someone give me step by step instructions on how to change the downloads folder? I've read the manual but it seems to assume more knowledge than I have. I'm using Windows 10, 64-bit.

**Comment by swinokur** [comment]
Hi there, 
You can set an "environment variable" that will tell gpodder the download directory.

There are a few different ways to set environment variables in windows 10, have a look here:
https://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10

Once you have the panel open to add an environment variable for your account (or system-wide if you prefer), you want to add an environment variable called GPODDER_DOWNLOAD_DIR 

Set that variable to the location of your downloads folder. (i.e. d:\podcasts)

At a minimum you will want to exit and restart gpodder to pick up the change. If you've made it a system variable you will need to at least log off & log back in to your account. If you really want to be sure, reboot.

hope this helps!

**Comment by Pollllll** [comment]
Thanks, I added the environment variable. I can't really test it yet, because gPodder is freezing when I try to download or check for new podcasts (see #550). I'm still waiting to see if someone comes up with a solution for that. I moved the gPodder folder from the Documents folder on the main (C:) drive to another drive (the same place as the value I entered into the environment variable). Then I opened gPodder and it said I had no podcasts and needed to subscribe to some. So I moved the folder back and the podcasts show up again.

**Comment by swinokur** [comment]
Remember, there are **two** environment variables. one is GPODDER_HOME which tells gpodder where to find the database & settings files. Those are the items that will control if you see any podcasts / episodes in the application.

GPODDER_DOWNLOAD_DIR is a separate environment variable you can set if you want the downloaded podcasts themselves to go a different place. (In my case the podcasts go onto a much bigger set of drives than the settings / database, which are small)

**Comment by Pollllll** [comment]
Ok, that worked. I created the GPODDER_HOME variable where the database and other files were already. Then I moved the downloads folder to another, bigger, drive matching the GPODDER_DOWNLOAD_DIR variable. Now gPodder sees the podcasts. I was even able to download a single podcast to the new drive because I had had the program look for new podcasts before it started freezing.

**Comment by Pollllll** [comment]
And thank you.

**Comment by elelay** [comment]
@swinokur @Pollllll congratulations on solving this together.
It's true that the user manual was expecting a bit too much.
It's now updated with a link to the superuser question and similar doc for Linux/macOS.
