### ISSUE TITLE
gpodder 3.10.5 on windows is missing "gpodder-migrate2tres"

### ISSUE THREAD

**Issue by swinokur** [gpodder/gpodder#552]
I'm (very belatedly) migrating from 2.20 to 3.10. It appears that 3.10.5 is missing the migration script from 2 to 3. 

Could a Windows executable version of the script be provided? 

thanks!

**Comment by elelay** [comment]
I'm sorry, migrate-to-tres is not supported anymore so I've not included it in the new Windows bundle.
