### ISSUE TITLE
Gpodder 3.9.6 migration script error / migration issues

### ISSUE THREAD

**Issue by swinokur** [gpodder/gpodder#553]
Hi,

Trying to migrate using gpodder 3.9.6.

gpodder 2.20 was downloaded as a zip file and placed in c:\ (gpodder-2.20-win32)

gpodder 3.9.6 - 3.96 was downloaded as a zip file and placed in c:\ (c:\gpodder-3.9.6-win32)
I have installed as prereqs:
- python-2.7.15.msi
- pygtk-all-in-one-2.24.2.win32-py2.7.msi

- c:\python27 is in the system path

trying to run the migration script as:

C:\gpodder-3.9.6-win32\bin>python ./gpodder-migrate2tres
Initial results did not work because the config files were not in the expected location so I edited these lines to become:
```
old_database = os.path.expanduser('C:\gpodder-2.20-win32/config/database.sqlite')
new_database = gpodder.database_file

old_config = os.path.expanduser('C:\gpodder-2.20-win32/config/gpodder.conf')
new_config = gpodder.config_file

```
running the script results in:

```
C:\gpodder-3.9.6-win32\bin>python ./gpodder-migrate2tres
Storing downloads in F:\podcasts_new (GPODDER_DOWNLOAD_DIR is set)
No handlers could be found for logger "gpodder.util"

  Would carry out the following actions:
      Move downloads from F:\podcasts
                       to F:\podcasts_new
      Convert database from C:\gpodder-2.20-win32/config/database.sqlite
                         to C:\Users\swinokur\gPodder\Database

Continue? (Y/n)
Traceback (most recent call last):
  File "./gpodder-migrate2tres", line 120, in <module>
    schema.convert_gpodder2_db(old_database, new_database)
  File "C:\gpodder-3.9.6-win32\src\gpodder\schema.py", line 249, in convert_gpodder2_db
    row = dict(zip(columns, row))
sqlite3.OperationalError: Could not decode to UTF-8 column 'foldername' with text 'Brooklyn Radio » Guilty Pleasures'
```

thanks!

**Comment by swinokur** [comment]
Hi,
I attempted a work-around by using a sqlite editor to change the offending character » to a _. I made the change in the foldername in the database and in the title of the podcast. I also changed the foldername in the podcast download directory itself.

After doing this the script ran without complaint, but when I started gpodder 3.10 (and 3.9.6) there were no podcasts or episodes appearing in gpodder.

Checking the converted database with the sqlite editor showed tables with episodes and channels.

thanks!

**Comment by swinokur** [comment]
okay, this is more tracked down now.
It appears that the python script by default wants to put the converted database into C:\Users\<Username>\gpodder

But, the windows versions of 3.9.6 and 3.10.5 want to see the database in C:\Users\<Username>\Documents\gpodder

This isn't super obvious, it took a while to realize that is what was going on and why even though the conversion completed more or less properly after changing the offending characters, I didn't see any of the database in the new version.

Another thing that I am seeing is a lot of warnings similar to:
2018-10-02 14:48:52,310 [gpodder.model] WARNING: Unknown external file: F:\podcasts\This American Life\435.mp3

These items have entries in the "podcast" list, and I can find the mp3 file referred to in the warning, but they do not have a "duration" shown in the list.

I see this in both 3.9.6 and 3.10.5

**Comment by elelay** [comment]
@swinokur sorry, but migrating from 2.20 is not supported anymore.
Congratulations on solving it by yourself, though
