### ISSUE TITLE
[Request] - Save file download state immediately after each download

### ISSUE THREAD

**Issue by auouymous** [gpodder/gpodder#555]
When downloading multiple episodes, it seems like gpodder waits until all have finished or failed before writing to the database. Restarting after a crash dumps messages about files on disk that aren't in the database, and those files must be re-downloaded.

Would it be easily possible to write out (flush) the database immediately after each file finishes? I realize it would increase disk I/O, but re-downloading multiple videos is far worse. This is more about reliability than being a bandaid until a crash can be fixed. Bugs that cause crashes will always happen and there are even issues out of gpodder's control, such as power failure, OS crashes and OOMs.

**Comment by elelay** [comment]
Aren't downloaded files picked up upon next gPodder restart? Do you really need to re-download them?

**Comment by auouymous** [comment]
It looks like gpodder creates a '*.partial' file for every queued episode. Sometimes it warns about them at startup, other times it doesn't. I might have missed the 'partial' and thought they were fully downloaded episodes.

**Comment by auouymous** [comment]
So gpodder crashed again today and warned about an unknown external file after being restarted.

> 1541740583.971416 [gpodder.model] WARNING: Unknown external file: /home/gpodder/gPodder/Downloads/Isaac Arthur/Reclaiming the Deserts.mp4

The episode is not in the resume list with the other episodes that didn't get downloaded before the crash, and it only has the option to re-download it. Restarting multiple times and cancelling the resume list doesn't pick up the episode.

**Comment by elelay** [comment]
Yes, it's not in resume list because it's been fully downloaded.
It should be picked by gPodder and shown as downloaded. Is it from the `Isaac Arthur` youtube channel (I searched the name on google)?
I've tried myself inserting a file with the right name (`Colonizing the Oceans.mp4`) and it was picked by gPodder on restart even if I never downloaded it.

**Comment by auouymous** [comment]
Yes. Is it possible to get the episode filename from the gpodder UI? How did you get it?

```
             for episode in all_episodes:
+                logger.warn('Episode file: %s', episode.download_filename)
                 wanted_filename = episode.local_filename(create=True,
```

I added that line to model.py and restarted gpodder. The problem is that the filename gpodder was looking for had a ".a" extension instead of the ".mp4". So crashing and other downloading issues causes gpodder to store the wrong filename, and it is unable to pick up the files.

There is code to import files with different extensions but it seems to be comparing basename to the full path wanted_filename, getting basename of wanted_filename fixes the import for different extensions. It might be better to rename wanted_filename to wanted_basename though.

```
             for episode in all_episodes:
-                wanted_filename = episode.local_filename(create=True,
-                        return_wanted_filename=True)
+                wanted_filename = os.path.basename(episode.local_filename(create=True,
+                       return_wanted_filename=True))
                 if basename == wanted_filename:
```

But the converted extension retains the icon for the old extension. Would it be possible to change it when converting?

**Comment by elelay** [comment]
You're right!
For already downloaded episodes, episode.local_filename(return_wanted_filename=True) returns the path, while for not downloaded episodes it returns the filename (aka basename).

**Comment by elelay** [comment]
It's fixed now.
You have the wrong icon (not video) for the imported file? On Linux, it uses gio, which looks at the file contents. What does the `file` command show on the imported file with wrong icon?

**Comment by auouymous** [comment]
Thank you for fixing it.

I no longer have the imported file and it was probably empty which would have thrown off `file` and shown the wrong icon.

**Comment by elelay** [comment]
OK, thanks for the confirmation.
Cheers,
