### ISSUE TITLE
Install from source in Debian 9

### ISSUE THREAD

**Issue by ViniciusBRodrigues** [gpodder/gpodder#558]
I followed the steps to install it from source and, after installing I'm having this issue:
```

Traceback (most recent call last):
  File "/usr/bin/gpodder", line 158, in <module>
    main()
  File "/usr/bin/gpodder", line 81, in main
    import gpodder  # isort:skip
ImportError: No module named 'gpodder'
```
The installation:

```
sudo make install
python3 setup.py install --root=/ --prefix=/usr --optimize=1
running install
running build
running build_py
running build_scripts
running install_lib
writing byte-compilation script '/tmp/tmpu3m4ldii.py'
/usr/bin/python3 -O /tmp/tmpu3m4ldii.py
removing /tmp/tmpu3m4ldii.py
running install_scripts
changing mode of /usr/bin/gpo to 755
changing mode of /usr/bin/gpodder-migrate2tres to 755
changing mode of /usr/bin/gpodder to 755
running install_data
running install_egg_info
Removing /usr/lib/python3.5/site-packages/gpodder-3.10.5-py3.5.egg-info
Writing /usr/lib/python3.5/site-packages/gpodder-3.10.5-py3.5.egg-info
```

**Comment by elelay** [comment]
I've tried it myself on a kubuntu 18.04 livecd in a virtual machine and it doesn't work indeed.
This is because `/usr/lib/python3.5/site-packages` is not in python3 default search path, as demonstrated by this screenshot:
![notfound](https://user-images.githubusercontent.com/222469/46973653-2e128a80-d0c2-11e8-8749-d14837e8839d.png)
What is your Linux distribution? Why doesn't it have site-packages in its sys.path?

To fix it, edit `bin/gpodder` to insert `/usr/lib/python3.5/site-packages` in `sys.path`. Add line 80:
```
import sys; sys.path.append('/usr/lib/python3.5/site-packages')
```
and run `sudo make install` again. Now gpodder should be found...

**Comment by ViniciusBRodrigues** [comment]
I'm using Debian 9. But still not working, but I think that I don't know the exact way to add the line in **/bin/gpodder**

The error now:

```
gpodder
  File "/usr/bin/gpodder", line 81
    import sys; sys.path.append('/usr/lib/python3.5/site-packages')
                                                                  ^
TabError: inconsistent use of tabs and spaces in indentation
```

I tried different ways of indentation.

The code in **bin/gpodder**:

```
    if os.path.exists(os.path.join(src_dir, 'gpodder', '__init__.py')):
        # Run gPodder from local source folder (not installed)
        sys.path.insert(0, src_dir)

    # on Mac OS X, read from the defaults database the locale of the user
    if platform.system() == 'Darwin' and 'LANG' not in os.environ:
        locale_cmd = ('defaults', 'read', 'NSGlobalDomain', 'AppleLocale')
        process = subprocess.Popen(locale_cmd, stdout=subprocess.PIPE)
        output, error_output = process.communicate()
        # the output is a string like 'fr_FR', and we need 'fr_FR.utf-8'
        user_locale = output.decode('utf-8').strip() + '.UTF-8'
        os.environ['LANG'] = user_locale
        print('Setting locale to', user_locale, file=sys.stderr)

    # Set up the path to translation files
    gettext.bindtextdomain('gpodder', locale_dir)

	import sys; sys.path.append('/usr/lib/python3.5/site-packages')

    import gpodder  # isort:skip
```

Many thanks

**Comment by elelay** [comment]
Yes: debian 9: it's the title of the issue...

There should be 4 spaces before `import sys; sys.path.append('/usr/lib/python3.5/site-packages')`.
Or insert it line 37, without any space in front.

**Comment by elelay** [comment]
A better solution: 

remove installed files (manually, unfortunately):
 - /usr/bin/gpo*
 - /usr/lib/python3.5/site-packages/gpodder/*
 - /usr/share/applications/gpodder* /usr/share/dbus-1/services/org.gpodder.service /usr/share/gpodder /usr/share/icons/hicolor/*/apps/gpodder.* /usr/share/locale/*/LC_MESSAGES/gpodder.mo /usr/share/man/man1/gpo

Install gpodder modules to the correct directory for debian:
```
sudo python3 setup.py install --root / --prefix /usr/local --optimize=1 --install-lib=/usr/local/lib/python3.5/dist-packages
```
Reference: https://wiki.debian.org/Python#Deviations_from_upstream

**Comment by ViniciusBRodrigues** [comment]
> Yes: debian 9: it's the title of the issue...
> 
> There should be 4 spaces before `import sys; sys.path.append('/usr/lib/python3.5/site-packages')`.
> Or insert it line 37, without any space in front.

I tried this one first. Now it's getting the following error:

```
gpodder

  Error: Module "podcastparser" (python-podcastparser) not found.
         The podcastparser module can be downloaded from
         http://gpodder.org/podcastparser/

  From a source checkout, you can download local copies of all
  CLI dependencies for debugging (will be placed into "src/"):

      python3 tools/localdepends.py
```
But the python-podcapster is already installed:

`python-podcastparser is already the newest version (0.6.1-1).`

**Comment by ViniciusBRodrigues** [comment]
> python -c "import sys; print(sys.path)"

This is strange once there is no path to python3.5:

```
python -c "import sys; print(sys.path)"
['', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7']
```

However python3.5 is in /usr/local/lib/python3.5. So removed the files I installed again and:

```
gpodder

  Error: Module "podcastparser" (python-podcastparser) not found.
         The podcastparser module can be downloaded from
         http://gpodder.org/podcastparser/

  From a source checkout, you can download local copies of all
  CLI dependencies for debugging (will be placed into "src/"):

      python3 tools/localdepends.py
```

Now the problem is not found python-podcastparser.

Many thanks

**Comment by elelay** [comment]
Good.
It may be easier to [run from git](https://gpodder.github.io/docs/run-from-git.html) instead of installing.
There is a script to download local dependencies, etc..
Please try it and let me know :-)

I'm leaving the ticket open as a reminder to update instructions with 
1. a STRONG emphasis on running from git instead of installing
2. a note with the way to find the install path + the correct command line for Debian and derivatives.

**Comment by ViniciusBRodrigues** [comment]
Ok, thanks. So, I just run from git following the steps and:

```
python3 tools/create-desktop-icon.py
Traceback (most recent call last):
  File "tools/create-desktop-icon.py", line 25, in <module>
    with open(DESTINATION, 'w') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/root/Desktop/gpodder-git.desktop'
```

:(

**Comment by ViniciusBRodrigues** [comment]
I'm running and using it, but it's not in my system.

**Comment by ViniciusBRodrigues** [comment]
And from git version, I'm having this issue:

![apagar](https://user-images.githubusercontent.com/12240167/47119002-afdbf280-d23f-11e8-99d1-90fb6b028767.png)

**Comment by elelay** [comment]
Thanks for trying it,

`python3 tools/create-desktop-icon.py` should not be run as root but as your normal user.

From what I read on the internet, maybe installing "python-gi-cairo" will solve the "could not find foreign type  Context" error.

**Comment by thp** [comment]
Note that it looks like "python3" there points to Python 3.6, whereas the installation path is for Python 3.5, suggesting that either multiple Python 3.x versions are installed or something is wrong with the installation.

Since Debian 9 doesn't yet ship with gPodder 3.10.x, maybe install the dependencies manually following the list at: https://packages.debian.org/sid/gpodder

In fact, it might work trying to install this deb from sid, even on Debian 9:
http://ftp.us.debian.org/debian/pool/main/g/gpodder/gpodder_3.10.3-2_all.deb

**Comment by ViniciusBRodrigues** [comment]
> Thanks for trying it,
> 
> `python3 tools/create-desktop-icon.py` should not be run as root but as your normal user.
> 
> From what I read on the internet, maybe installing "python-gi-cairo" will solve the "could not find foreign type Context" error.

Hi, i'm trying as normal user. The python-gi-cairo is already installed.
