### ISSUE TITLE
gpodder crashed with TypeError: position_func() takes 1 argument but 4 were given

### ISSUE THREAD

**Issue by kcwms** [gpodder/gpodder#559]
Oct 21 14:46:26 kevin-probook org.mate.panel.applet.BriskMenuFactory[1469]: 1540147586.550775 [gpodder.sync] WARNING: Could not find gpod
 Oct 21 14:48:48 kevin-probook org.mate.panel.applet.BriskMenuFactory[1469]: 1540147728.702141 [gpodder.opml] ERROR: Cannot import OPML from URL: super horror bros
 Oct 21 14:48:48 kevin-probook org.mate.panel.applet.BriskMenuFactory[1469]: Traceback (most recent call last):
 Oct 21 14:48:48 kevin-probook org.mate.panel.applet.BriskMenuFactory[1469]:   File "/usr/lib/python3/dist-packages/gpodder/opml.py", line 75, in __init__
 Oct 21 14:48:48 kevin-probook org.mate.panel.applet.BriskMenuFactory[1469]:     doc = xml.dom.minidom.parseString(util.urlopen(url).read())
 Oct 21 14:48:48 kevin-probook org.mate.panel.applet.BriskMenuFactory[1469]:   File "/usr/lib/python3/dist-packages/gpodder/util.py", line 1202, in urlopen
 Oct 21 14:48:48 kevin-probook org.mate.panel.applet.BriskMenuFactory[1469]:     request = urllib.request.Request(url, data=data, headers=headers)
 Oct 21 14:48:48 kevin-probook org.mate.panel.applet.BriskMenuFactory[1469]:   File "/usr/lib/python3.6/urllib/request.py", line 329, in __init__
 Oct 21 14:48:48 kevin-probook org.mate.panel.applet.BriskMenuFactory[1469]:     self.full_url = url
 Oct 21 14:48:48 kevin-probook org.mate.panel.applet.BriskMenuFactory[1469]:   File "/usr/lib/python3.6/urllib/request.py", line 355, in full_url
 Oct 21 14:48:48 kevin-probook org.mate.panel.applet.BriskMenuFactory[1469]:     self._parse()
 Oct 21 14:48:48 kevin-probook org.mate.panel.applet.BriskMenuFactory[1469]:   File "/usr/lib/python3.6/urllib/request.py", line 384, in _parse
 Oct 21 14:48:48 kevin-probook org.mate.panel.applet.BriskMenuFactory[1469]:     raise ValueError("unknown url type: %r" % self.full_url)
 Oct 21 14:48:48 kevin-probook org.mate.panel.applet.BriskMenuFactory[1469]: ValueError: unknown url type: 'super horror bros'
 Oct 21 14:50:42 kevin-probook org.mate.panel.applet.BriskMenuFactory[1469]: 1540147842.297707 [gpodder.log] ERROR: Uncaught exception: TypeError: position_func() takes 1 positional argument but 4 were given
 Oct 21 14:51:00 kevin-probook org.mate.panel.applet.BriskMenuFactory[1469]: TypeError: position_func() takes 1 positional argument but 4 were given
 Oct 21 14:51:00 kevin-probook org.mate.panel.applet.BriskMenuFactory[1469]: 1540147860.125843 [gpodder.download] WARNING: Content-disposition header contains non-ASCII characters - ignoring
Package: gpodder 3.10.1-1

**Comment by elelay** [comment]
Thanks for the report.
Did it actually crash or did it spit an error in the terminal and continued?
I think I've understood the reason why there is the position_func() error: it's used in Gtk.Menu.popup() calls, but the arguments the popup function will pass to position_func changed between [pygtk](https://developer.gnome.org/pygtk/stable/class-gtkmenu.html#method-gtkmenu--popup) and [gtk3](http://lazka.github.io/pgi-docs/Gtk-3.0/classes/Menu.html#Gtk.Menu.popup).

In what dialog were you at the moment of the crash?

**Comment by elelay** [comment]
This is fixed in gPodder master.
I could reproduce the bug in the episode selector dialog (after refreshing a podcast), by selecting an episode and pressing the *menu* key of my keyboard.
Thanks,
