### ISSUE TITLE
gpodder doesn't parse anchor.fm rss media enclosure properly

### ISSUE THREAD

**Issue by GreatBigTable** [gpodder/gpodder#560]
When you subscribe to an rss feed generated by an anchor.fm podcast, it will show the episodes and updates the subscription properly, but it can't seem to properly process the media enclosure in the rss. If you copy the enclosure URL and put it in a browser, it will resolve and download the file, but gpodder gets a 404 not found error when it tries to process them.

Here is the anchor.fm rss feed for a podcast named Plundergrounds https://anchor.fm/s/6e8a2b4/podcast/rss

This is an example of an enclosure that has problems:
`<enclosure url="https://anchor.fm/s/6e8a2b4/podcast/play/1594770/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2018-9-24%2F010-L-F-Hacks--Movies----Magic-7f11451727c01.m4a" length="17536109" type="audio/x-m4a"/>`

This is for gpodder 3.10.1 on Ubuntu 18.04.

**Comment by elelay** [comment]
It works fine for me with gPodder master on ArchLinux.
Not sure what could cause the 404: do you see the actual url it tries to download?

**Comment by GreatBigTable** [comment]
When I try to download episode "010 L&F Hacks, Movies, & Magic Items", on
the Progress tab of gpodder, I see the following error message:

Failed: Http Error 404: Not Found - Plundergrounds.

If I look at the Episode Details in the Podcasts tab of gpodder, I see the
following:

010 L&F Hacks, Movies, & Magic Items
from Plundergrounds

• Kirby's Kids -> http://anchor.fm/kirbyskids • Spikepit ->
http://anchor.fm/spikepit • JB Publishing ->
http://anchor.fm/jbpublishing • War & Craft ->
https://drive.google.com/file/d/1TyRfAes8Fh0Y4LDXiouCuxTVYyOZSQEj/view
• Sorcerers & Sellswords ->
http://jellysawgames.blogspot.com/p/sorcerers-sellswords.html • Blood
& Chrome -> https://nathanknaackdotcom.files.wordpress.com/2015/09/blood-chrome2.pdf
• Deputies & Desperados ->
https://www.drivethrurpg.com/product/182507/Deputies--Desperados • One
& Thousands -> https://exposit.github.io/katarpgs/superlite/onethousands/
• Pack of Strays ->
https://drive.google.com/file/d/0B1LY0MsvGmaCM1BqTXgxV3kxNWs/view •
Rockerboys & Vendingmachines ->
http://www.encodeddesigns.com/rocker-boys-and-vending-machines/ •
Whiskers & Claws ->
https://drive.google.com/file/d/0B-Kkij9dGdBCUmcwUUpLM1NOQUk/view • No
Save for You! -> http://anchor.fm/nosaveforyou • Harryhausen Skeleton
Fight -> https://mewe.com/group/5bc219c5a5f4e515644fe78f

When I try to download them through the gpo command line shell, I get
the following error:

1540492612.492431 [gpodder.download] ERROR: HTTP 404 while downloading
"010 L&F Hacks, Movies, & Magic Items": Not Found
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/download.py", line 766, in run
    self.tempname, reporthook=self.status_updated)
  File "/usr/lib/python3/dist-packages/gpodder/download.py", line 275,
in retrieve_resume
    fp = self.open(url, data)
  File "/usr/lib/python3.6/urllib/request.py", line 1757, in open
    return getattr(self, name)(url)
  File "/usr/lib/python3.6/urllib/request.py", line 1967, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/usr/lib/python3.6/urllib/request.py", line 1932, in _open_generic_http
    response.status, response.reason, response.msg, data)
  File "/usr/lib/python3.6/urllib/request.py", line 1948, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python3.6/urllib/request.py", line 2136, in http_error_302
    headers, data)
  File "/usr/lib/python3/dist-packages/gpodder/download.py", line 238,
in redirect_internal
    return self.open(newurl)
  File "/usr/lib/python3.6/urllib/request.py", line 1757, in open
    return getattr(self, name)(url)
  File "/usr/lib/python3.6/urllib/request.py", line 1967, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/usr/lib/python3.6/urllib/request.py", line 1932, in _open_generic_http
    response.status, response.reason, response.msg, data)
  File "/usr/lib/python3.6/urllib/request.py", line 1952, in http_error
    return self.http_error_default(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python3/dist-packages/gpodder/download.py", line 219,
in http_error_default
    raise gPodderDownloadHTTPError(url, errcode, errmsg)
gpodder.download.gPodderDownloadHTTPError: ('//anchor.fm/404', 404, 'Not Found')
Downloading 010 L&F Hacks, Movies, & Magic Items                         [DONE]


Is there a way to get a more detailed transaction log for gpodder that
I could run?

Thank you,

Jim

-- 
Jim Jones

**Comment by elelay** [comment]
I think this is the same bug as #399, fixed in gPodder 3.10.2.
Would you like to run gPodder [from git](https://gpodder.github.io/docs/run-from-git.html)?
