### ISSUE TITLE
Tooltips flicker/blink when mouseover on podcast thumbnail or in new episodes to download window

### ISSUE THREAD

**Issue by isaacg123** [gpodder/gpodder#562]
When you hover over the thumbnail/album icon for a podcast in gPodder 3.10.5 (Windows 10) the tooltip (black transparent bubble with white text) flickers on and off rapidly (several times a second) making it basically unreadable. Same when the new episodes download window comes up and you hover an item to read the description. On occasion it will stay solid but I can't figure out any method to why/when it does. Doesn't seem to matter the size of the tooltip text. Moving the window to the bottom of the screen does seem to help, I might get a few tooltips that don't blink, but still not most. Same thing happens on my unscaled 100% monitor and my 4k monitor that's scaled to 300%.

**Comment by elelay** [comment]
confirmed on Linux

**Comment by elelay** [comment]
Thanks for reporting!

**Comment by elelay** [comment]
This is a bug in [gtk 3.24](https://gitlab.gnome.org/GNOME/gtk/issues/1371).
Add
```
gtk-cursor-theme-size = 16
```
to etc/gtk-3.0/settings.ini in gpodder installation directory to fix it.

Linux users should put the fix in `~/.config/gtk-3.0/settings.ini`

**Comment by isaacg123** [comment]
Confirmed, fixed it for me. Thanks!

**Comment by elelay** [comment]
Just released gPodder 3.10.6 with gtk3.24.1 on Windows + workaround for macOS
