### ISSUE TITLE
When saving to local folder will overwrite files

### ISSUE THREAD

**Issue by ndias** [gpodder/gpodder#563]
When saving a episode to Local folder, gpodder doesn't check if a file already exists, and overwrite that file, this happens in the last version 3.10.5

**Comment by elelay** [comment]
Yes, and you expect a confirmation dialog if file already exists?

**Comment by ndias** [comment]
Yes, I expect a dialog box if file already exists :)

**Comment by elelay** [comment]
It would be easy to add a confirmation dialog (`self.show_confirmation`) in [`do_save_episode()`](https://github.com/gpodder/gpodder/blob/master/src/gpodder/gtkui/main.py#L1773).
