### ISSUE TITLE
minimize on startup doesn't work

### ISSUE THREAD

**Issue by Rejlan** [gpodder/gpodder#566]
Hi, 

Gpodder's previous versions worked like a charm on my computer, but with the latest one there is an annoying problem of Gpodder failing to minimize on the startup. I've enabled this extension in Preferences of course. 
Another problem that I'm experiencing is the progress bar not showing the completed downloads. The episodes are added to the download list, and they are actually downloaded normally, only I can't say when or whether some of them failed to download. 

Is there anything that I can do to fix these two bugs?

Thank you!

**Comment by elelay** [comment]
@Rejlan regarding minimize on startup, I'll have to check.

Regarding keeping successful downloads in the progress tab, you can check the `ui.gtk.download_list.remove` option in **Preferences** > **Edit Config**.

**Comment by elelay** [comment]
By default, only failed download will stay in the progress tab. Maybe knowing this you don't need to set the option...

**Comment by Rejlan** [comment]
Thank you for the help elelay :) "Minimize on start" not working is not a big deal maybe, but still a useful option for me, I hope you manage to fix it. What seems to happen when I open Gpodder that it for a short second minimizes the application and then brings it up again and stays maximized.  
Speaking of maximized, if that's possible, I'd also like to have Gpodder remember the size of the window, instead of always opening in full screen. 
Again, thank you for the help elelay, looking forward to new Gpodder updates. One of "must have" applications on my computer.

**Comment by elelay** [comment]
@Rejlan, you'll need to modify `share/extensions/minimize_on_start.py` as in b47ad8b636 for minimize on startup to work.

**Comment by Rejlan** [comment]
Thank you very much for fixing this problem elelay, it works fine now!
