### ISSUE TITLE
Feature request: Simple updates of RSS feed

### ISSUE THREAD

**Issue by geejaytee** [gpodder/gpodder#570]
Please can you add a simple way to update the RSS feed for a podcast without needing to unsubscribe (on the old feed - risking the deletion of downloaded episodes) and then subscribe on the new feed (potentially having to redownload older episodes not listened to)

**Comment by elelay** [comment]
What kind of update do you have in mind? If episode guids change, then gPodder doesn't have any trivial way to match episodes from the old subscription with the new subscription. It could be possible to match by title, but it requires code to do so: not so simple, indeed.

**Comment by elelay** [comment]
See #214 where there is no discussion of keeping downloaded episodes...

**Comment by geejaytee** [comment]
Close this then, it's covered in #214 for my use case.
