### ISSUE TITLE
Error when subscribing to an authenticated podcast

### ISSUE THREAD

**Issue by DinizBortolotto** [gpodder/gpodder#571]
Hi!
I'm trying to subscribe in an authenticated podcast and getting a authentication failure.
I'm pretty sure that _Username_ and _Password_ are correct because it works at my smartphone.
How could I track that better to clarify where is the error and help you?
Below is the related log using "`gpodder --verbose`" and some screen capture (cropped) related.

> 1543611715.506399 [gpodder.my] INFO: Reloading settings.
1543611715.506875 [gpodder.util] DEBUG: run_in_background: <bound method UserAppsReader.read of <gpodder.gtkui.desktopfile.UserAppsReader object at 0x7ff22b984eb8>> (False)
1543611715.733832 [gpodder.util] DEBUG: run_in_background: <bound method gPodder.find_partial_downloads of <gpodder.gtkui.main.gPodder at /gui at 0x7ff232053be0>> (False)
1543611722.169824 [gpodder.youtube] DEBUG: Analyzing URL: http 30min.com.br /feed/premium  
1543611722.169982 [gpodder.youtube] DEBUG: Not a valid Youtube URL: http://30min.com.br/feed/premium
1543611722.170146 [gpodder.util] DEBUG: run_in_background: <function gPodder.add_podcast_list.<locals>.thread_proc at 0x7ff22b086400> (False)
1543611722.170713 [gpodder.model] INFO: Updating download_folder of http://30min.com.br/feed/premium to http___30min.com.br_feed_premium
1543611726.227253 [gpodder.model] DEBUG: Fetch failed. Removing buggy feed.
1543611726.227524 [gpodder.dbsqlite] DEBUG: delete_podcast: 384 (http://30min.com.br/feed/premium)
1543611739.090269 [gpodder.my] WARNING: Flush requested, but sync disabled.
1543611739.155498 [gpodder.youtube] DEBUG: Analyzing URL: http 30min.com.br /feed/premium  
1543611739.155645 [gpodder.youtube] DEBUG: Not a valid Youtube URL: http://30min.com.br/feed/premium
1543611739.155794 [gpodder.util] DEBUG: run_in_background: <function gPodder.add_podcast_list.<locals>.thread_proc at 0x7ff22b086400> (False)
1543611739.156122 [gpodder.model] INFO: Updating download_folder of http://30min.com.br/feed/premium to http___30min.com.br_feed_premium
1543611742.030258 [gpodder.model] DEBUG: Fetch failed. Removing buggy feed.
1543611742.259908 [gpodder.dbsqlite] DEBUG: delete_podcast: 384 (http://30min.com.br/feed/premium)
1543611750.753443 [gpodder.my] WARNING: Flush requested, but sync disabled.
1543611754.849167 [gpodder.dbsqlite] DEBUG: Commit.
1543611757.173409 [gpodder.my] INFO: Worker thread may not execute (disabled).

![gpodder001](https://user-images.githubusercontent.com/4468840/49315061-8ddabe80-f4d3-11e8-95e4-e16d70b29d07.png)
![gpodder002](https://user-images.githubusercontent.com/4468840/49315062-8ddabe80-f4d3-11e8-8730-2ac82d83600d.png)
![gpodder003](https://user-images.githubusercontent.com/4468840/49315063-8ddabe80-f4d3-11e8-9781-335025770147.png)
![gpodder004](https://user-images.githubusercontent.com/4468840/49315064-8ddabe80-f4d3-11e8-8f08-c859f46f6172.png)

**Comment by elelay** [comment]
Thanks for reporting.
Yes, it's a bug in gPodder: it doesn't handle the case when there is a redirect to a different domain, then the authentication request.
You should be able to subscribe using http://assinante.30min.com.br/feed/premium/

**Comment by DinizBortolotto** [comment]
> Thanks for reporting.
> Yes, it's a bug in gPodder: it doesn't handle the case when there is a redirect to a different domain, then the authentication request.
> You should be able to subscribe using http://assinante.30min.com.br/feed/premium/

Hi  @elelay!
Just confirming that the bypass that you suggested worked fine. 
Thanks!

**Comment by elelay** [comment]
I'm curious: don't you have any trouble downloading episodes from your feed? Because gPodder 3.10.5 is unable to download episodes if they request the username/password.
Maybe only your feed is protected?

**Comment by elelay** [comment]
It's fixed in ad86c35.
