### ISSUE TITLE
Option to turn off pager in gpo

### ISSUE THREAD

**Issue by kadagv** [gpodder/gpodder#572]
A command line option to turn off pager in `gpo` would be handy.

**Comment by elelay** [comment]
Are you using it interactively?
`./bin/gpo episodes | cat` seems to do the trick

**Comment by kadagv** [comment]
I use another (perl) script to issue many commands. I want to make it download only some episodes based on episode title regexp.  "Fully interactive mode" with no need to create (pseudo) terminals would be better.  "interactive mode for scripts/programs" would be the best,

**Comment by elelay** [comment]
Sorry, I don't understand: the pager is still active from a perl script?

Anyway, to disable the pager, change [line 133 of bin/gpo](https://github.com/gpodder/gpodder/blob/master/bin/gpo#L133) to

    have_ansi = False
