### ISSUE TITLE
Locale issue on Linux prevents database save

### ISSUE THREAD

**Issue by mbbs1024** [gpodder/gpodder#576]
I just installed gpodder on KDE-Neon, and got my podcast subscriptions from gpodder.net
So far OK, my episodes start downloading.
Then I stop Gpodder and shut down the laptop.
The next time I start the laptop, I also start gpodder in order to continue downloading the episodes, but it starts up empty, no podcast subscriptions, and nearly all menu items greyed out.
Those that are not greyed out do not work.
I find lots of identical errors in the log file (see below)

2018-12-24 16:16:43,984 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 1301, in on_treeview_query_tooltip
    if not getattr(treeview, TreeViewHelper.CAN_TOOLTIP) or x > 50 or (column is not None and column != treeview.get_columns()[0]):
AttributeError: 'TreeView' object has no attribute '_gpodder_can_tooltip'

I re-installed it without wiping the gpodder directory --> it starts empty again.
Re-installing after completely removing it --> runs only once again.

**Comment by elelay** [comment]
Thanks for reporting!
Could it be the same thing as #471 ? Then it is when not explicitly quitting gPodder before kde shutdown.
Sorry, I didn't take time to investigate. Help is appreciated :-)

**Comment by mbbs1024** [comment]
To test, I completely removed Gpodder from my system (also deleted the gpodder directory) and re-installed it.
After installation I get my subscriptions from gpodder.net, and let Gpodder download a number of episodes. 
Then I stop Gpodder by clicking on the window close button (top right window X button)
When I start it again via K-menu, it starts empty, as I described above.
So I dont restart the laptop, I just stop and start Gpodder in a normal way.

Attached todays logfile of my test run.
[2018-12-27.log](https://github.com/gpodder/gpodder/files/2713423/2018-12-27.log)


There are duplicate directories in Downloads, but that is because different podcast url's use the same directory names, but this has been like that for a few years now, without causing problems.
marc@marc-samsung:**~/gPodder/Downloads$ ls**
 Click                                    'Hackaday (2)'        'Science in Action'
'Comments for BT Pod Show'                'Hackaday (3)'        'Science in Action (2)'
'De Universiteit van Vlaanderen Podcast'  'LINUX Unplugged'     'The Naked Scientists Podcast'
 Embedded                                 'Raspberry Pi'        'The Naked Scientists Podcast (2)'
'Embedded (2)'                            'Raspberry Pi Spy'    'This Week in Google (MP3)'
'Going Linux'                             'Science Friday'
 Hackaday                                 'Science Friday (2)'

**This is my gpodder.net podcast list**

  | Unknown Podcast from feeds2.feedburner.com32 Episodes |  
  | Unknown Podcast from www.embedded.fm143 Episodes |  
  | Unknown Podcast from hackaday.com32 Episodes |  
  | Raspberry Pi Spy |  
  | Science Friday407 Episodes |  
  | IoT Podcast – Internet of Things131 Episodes |  
  | LINUX Unplugged522 Episodes |  
  | Hackaday409 Episodes |  
  | The Naked Scientists Podcast3104 Episodes |  
  | De Universiteit van Vlaanderen Podcast94 Episodes |  
  | Embedded139 Episodes |  
  | Science in Action102 Episodes |  
  | This Week in Google (MP3)501 Episodes |  
  | Click508 Episodes |  
  | The Naked Scientists Podcast1363 Episodes |  
  | Science Friday2183 Episodes |  
  | Science in Action506 Episodes |  
  | Going Linux364 Episodes |  
  | Raspberry Pi7 Episodes |  
  | Raspberry Pi Today Podcast27 Episodes |  
  | TuxRadar Linux Podcast (ogg)121 Episodes |  
  | mintCast281 Episodes |  
  | A Little Bit of Python17 Episodes |  
  | tech5232 Episodes |  
  | Hacker Medley9 Episodes |

**Comment by elelay** [comment]
OK, so this is something different than #471.
Thanks for the details.
```
2018-12-27 21:55:38,571 [gpodder.util] WARNING: Cannot set locale (unsupported locale setting)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/util.py", line 97, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.6/locale.py", line 598, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```
Locales are not correctly set on your system, so python can't handle accented characters, causing exceptions (ascii decode errors follow).

Please try:
```
# export LC_ALL=C
# gpodder -v
```
in a shell : does it still show the *unsupported locale setting* and *'ascii' codec can't encode character*? If not, does it now persist subscriptions when you restart gPodder?

**Comment by mbbs1024** [comment]
This is the result

marc@marc-samsung:~$ **export LC_ALL=C**
marc@marc-samsung:~$ **gpodder -v**
1546271392.831812 [gpodder.log] DEBUG: ==== gPodder starts up (ui=gtk) ===
1546271393.432960 [gpodder.sync] WARNING: Could not find gpod
1546271393.525784 [eyed3] DEBUG: eyeD3 version 0.8.4
1546271393.558285 [gpodder.gtkui.shownotes] INFO: No WebKit2 gobject bindings, so no HTML shownotes

(gpodder:13223): Gtk-WARNING **: 16:49:54.195: Theme parsing error: gtk.css:127:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(gpodder:13223): Gtk-WARNING **: 16:49:54.195: Theme parsing error: gtk.css:128:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(gpodder:13223): Gtk-WARNING **: 16:49:54.196: Theme parsing error: gtk.css:132:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
1546271394.293543 [gpodder.extensions] DEBUG: Found extension "audio_converter" in /usr/share/gpodder/extensions/audio_converter.py
1546271394.298253 [gpodder.extensions] DEBUG: Found extension "concatenate_videos" in /usr/share/gpodder/extensions/concatenate_videos.py
1546271394.299455 [gpodder.extensions] DEBUG: Found extension "enqueue_in_mediaplayer" in /usr/share/gpodder/extensions/enqueue_in_mediaplayer.py
1546271394.300579 [gpodder.extensions] DEBUG: Found extension "episode_website_context_menu" in /usr/share/gpodder/extensions/episode_website_context_menu.py
1546271394.301543 [gpodder.extensions] DEBUG: Found extension "gtk_statusicon" in /usr/share/gpodder/extensions/gtk_statusicon.py
1546271394.302587 [gpodder.extensions] DEBUG: Found extension "minimize_on_start" in /usr/share/gpodder/extensions/minimize_on_start.py
1546271394.303238 [gpodder.extensions] DEBUG: Found extension "mpris-listener" in /usr/share/gpodder/extensions/mpris-listener.py
1546271394.304012 [gpodder.extensions] DEBUG: Found extension "normalize_audio" in /usr/share/gpodder/extensions/normalize_audio.py
1546271394.304560 [gpodder.extensions] DEBUG: Found extension "notification" in /usr/share/gpodder/extensions/notification.py
1546271394.308820 [gpodder.extensions] INFO: Module loaded: /usr/share/gpodder/extensions/notification.py
1546271394.312355 [gpodder.extensions] DEBUG: Found extension "notification-win32" in /usr/share/gpodder/extensions/notification-win32.py
1546271394.314521 [gpodder.extensions] DEBUG: Found extension "rename_download" in /usr/share/gpodder/extensions/rename_download.py
1546271394.315674 [gpodder.extensions] DEBUG: Found extension "rm_ogg_cover" in /usr/share/gpodder/extensions/rm_ogg_cover.py
1546271394.316966 [gpodder.extensions] DEBUG: Found extension "rockbox_convert2mp4" in /usr/share/gpodder/extensions/rockbox_convert2mp4.py
1546271394.318135 [gpodder.extensions] DEBUG: Found extension "rockbox_coverart" in /usr/share/gpodder/extensions/rockbox_coverart.py
1546271394.318917 [gpodder.extensions] DEBUG: Found extension "sonos" in /usr/share/gpodder/extensions/sonos.py
1546271394.319661 [gpodder.extensions] DEBUG: Found extension "tagging" in /usr/share/gpodder/extensions/tagging.py
1546271394.320806 [gpodder.extensions] DEBUG: Found extension "taskbar_progress" in /usr/share/gpodder/extensions/taskbar_progress.py
1546271394.322165 [gpodder.extensions] DEBUG: Found extension "ted_subtitles" in /usr/share/gpodder/extensions/ted_subtitles.py
1546271394.323797 [gpodder.extensions] DEBUG: Found extension "ubuntu_appindicator" in /usr/share/gpodder/extensions/ubuntu_appindicator.py
1546271394.325082 [gpodder.extensions] DEBUG: Found extension "ubuntu_unity" in /usr/share/gpodder/extensions/ubuntu_unity.py
1546271394.326151 [gpodder.extensions] DEBUG: Found extension "update_feeds_on_startup" in /usr/share/gpodder/extensions/update_feeds_on_startup.py
1546271394.327244 [gpodder.extensions] DEBUG: Found extension "video_converter" in /usr/share/gpodder/extensions/video_converter.py
1546271394.588097 [gpodder.dbsqlite] INFO: Loading podcasts
1546271394.599832 [gpodder.dbsqlite] DEBUG: Database opened.
1546271394.600665 [gpodder.dbsqlite] INFO: Loading episodes for podcast 1
1546271394.609770 [gpodder.dbsqlite] INFO: Loading episodes for podcast 2
1546271394.616258 [gpodder.dbsqlite] INFO: Loading episodes for podcast 3
1546271394.629586 [gpodder.dbsqlite] INFO: Loading episodes for podcast 4
1546271394.629989 [gpodder.dbsqlite] INFO: Loading episodes for podcast 5
1546271394.631305 [gpodder.dbsqlite] INFO: Loading episodes for podcast 6
1546271394.638474 [gpodder.dbsqlite] INFO: Loading episodes for podcast 7
1546271394.656401 [gpodder.dbsqlite] INFO: Loading episodes for podcast 8
1546271394.657770 [gpodder.dbsqlite] INFO: Loading episodes for podcast 9
1546271394.665617 [gpodder.dbsqlite] INFO: Loading episodes for podcast 10
1546271394.666458 [gpodder.dbsqlite] INFO: Loading episodes for podcast 11
1546271394.676117 [gpodder.dbsqlite] INFO: Loading episodes for podcast 12
1546271394.677339 [gpodder.dbsqlite] INFO: Loading episodes for podcast 13
1546271394.682876 [gpodder.dbsqlite] INFO: Loading episodes for podcast 14
1546271394.683669 [gpodder.dbsqlite] INFO: Loading episodes for podcast 15
1546271394.684836 [gpodder.dbsqlite] INFO: Loading episodes for podcast 16
1546271394.686440 [gpodder.dbsqlite] INFO: Loading episodes for podcast 17
1546271394.703657 [gpodder.dbsqlite] INFO: Loading episodes for podcast 18
1546271394.705030 [gpodder.dbsqlite] INFO: Loading episodes for podcast 19
1546271394.705353 [gpodder.dbsqlite] INFO: Loading episodes for podcast 20
1546271394.755172 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 3679, in do_activate
    self.window = gPodder(self, self.bus_name, core.Core(UIConfig, model_class=Model), self.options)
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 119, in __init__
    BuilderWidget.__init__(self, None, _builder_expose={'app': app})
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/interface/common.py", line 39, in __init__
    GtkBuilderWidget.__init__(self, gpodder.ui_folders, gpodder.textdomain, parent, **kwargs)
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/base.py", line 72, in __init__
    self.new()
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 194, in new
    self.channels = self.model.get_podcasts()
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 1238, in get_podcasts
    podcast.check_download_folder()
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 755, in check_download_folder
    glob.glob(os.path.join(self.save_dir, '*')) \
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 1193, in get_save_dir
    if not util.make_directory(save_dir):
  File "/usr/lib/python3/dist-packages/gpodder/util.py", line 168, in make_directory
    if os.path.isdir( path):
  File "/usr/lib/python3.6/genericpath.py", line 42, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 41: ordinal not in range(128)

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 3679, in do_activate
    self.window = gPodder(self, self.bus_name, core.Core(UIConfig, model_class=Model), self.options)
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 119, in __init__
    BuilderWidget.__init__(self, None, _builder_expose={'app': app})
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/interface/common.py", line 39, in __init__
    GtkBuilderWidget.__init__(self, gpodder.ui_folders, gpodder.textdomain, parent, **kwargs)
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/base.py", line 72, in __init__
    self.new()
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 194, in new
    self.channels = self.model.get_podcasts()
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 1238, in get_podcasts
    podcast.check_download_folder()
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 755, in check_download_folder
    glob.glob(os.path.join(self.save_dir, '*')) \
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 1193, in get_save_dir
    if not util.make_directory(save_dir):
  File "/usr/lib/python3/dist-packages/gpodder/util.py", line 168, in make_directory
    if os.path.isdir( path):
  File "/usr/lib/python3.6/genericpath.py", line 42, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 41: ordinal not in range(128)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_gpodder.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 3679, in do_activate
    self.window = gPodder(self, self.bus_name, core.Core(UIConfig, model_class=Model), self.options)
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 119, in __init__
    BuilderWidget.__init__(self, None, _builder_expose={'app': app})
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/interface/common.py", line 39, in __init__
    GtkBuilderWidget.__init__(self, gpodder.ui_folders, gpodder.textdomain, parent, **kwargs)
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/base.py", line 72, in __init__
    self.new()
  File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 194, in new
    self.channels = self.model.get_podcasts()
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 1238, in get_podcasts
    podcast.check_download_folder()
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 755, in check_download_folder
    glob.glob(os.path.join(self.save_dir, '*')) \
  File "/usr/lib/python3/dist-packages/gpodder/model.py", line 1193, in get_save_dir
    if not util.make_directory(save_dir):
  File "/usr/lib/python3/dist-packages/gpodder/util.py", line 168, in make_directory
    if os.path.isdir( path):
  File "/usr/lib/python3.6/genericpath.py", line 42, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 41: ordinal not in range(128)

**Comment by elelay** [comment]
OK, thanks.
One more thing: what is your locale?
What is the output of 
```bash
> locale
```
for me it's
```
> locale
LANG=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
```
I'm curious why gPodder can't set the locale...

**Comment by elelay** [comment]
OK. Thanks for the info. locale doesn't seem very happy.

I'm not familiar enough with Belgian locales to know what you want precisely. But you seem to want everything set to nl_BE.UTF-8, right?

Have you tried to fix it? Maybe uncomment the line
```
# nl_BE.UTF-8 UTF-8
```
(and maybe `en_GB.UTF-8 UTF-8` to have an English locale) if you have such line commented in `/etc/locale.gen` then running `locale-gen`.
Then try
```
 LANG=nl_BE.UTF-8 LC_CTYPE=nl_BE.UTF-8 LC_MESSAGES=nl_BE.UTF-8 locale
```
to see if it's more happy?
Maybe then reboot, re-run `locale` to see if it's more happy?
If not, maybe reset everything to nl in the Kde regional settings. Because environment variables seem to be mixed up.
Lots of maybe's ;-)

**Comment by mbbs1024** [comment]
I did your commands one by one to see which one worked.
**NOK** Uncomment nl_BE.UTF-8 UTF-8, comment out  de_BE.UTF-8 UTF-8 and run sudo locale.gen
**NOK**  LANG=nl_BE.UTF-8 LC_CTYPE=nl_BE.UTF-8 LC_MESSAGES=nl_BE.UTF-8 locale
**NOK** reboot, re-run locale to see if it's more happy
**OK** reset everything to nl in the Kde regional settings

**KDE** Language & region settings were set to EN and all other detailed settings were set to nl
--> I kept language to en and set **region settings to nl   + reboot**
after that, the locale command no longer produced the 3 error msgs, 
and gpodder seems to work normally, except for the GUI which is unresponsive during heavy
downloading, but it has been like that as long as I can remember 
(I set it to 20 concurrent downloads).

**Thanks a lot for your help !!!**

**Comment by elelay** [comment]
Great! I'm glad you sorted it out.
For the record, what is the output of `locale`, now?
Thanks,

**Comment by elelay** [comment]
@mbbs1024 please can you provide the output of the `locale` command in a terminal?
Thanks,

**Comment by elelay** [comment]
Cool, thanks!
Sorry for insisting. I think it might help someone in the future.
