### ISSUE TITLE
Add AppStream metadata

### ISSUE THREAD

**Issue by City-busz** [gpodder/gpodder#577]
[AppStream](https://www.freedesktop.org/wiki/Distributions/AppStream/) is a cross-distribution effort for enhancing the way we interact with the software repositories provided by (Linux) distributions by standardizing software component metadata.

The Flathub project has a metainfo file for gPodder:
https://github.com/flathub/org.gpodder.gpodder/blob/master/appdata.xml

Please include this file in the upstream project, and install it into '/usr/share/metainfo' folder during the build process, so other distributions could use it.

**Comment by elelay** [comment]
Hi City-busz,
I don't know anything about Appstream. From your description and freedesktop's page, it seems to be a way to build app stores indeed.
What does it bring that I install appdata.xml?
Thanks,

**Comment by City-busz** [comment]
It requires to install an XML file into the `/usr/share/metainfo/` directory that meets with the [AppStream specification](https://www.freedesktop.org/software/appstream/docs/). It can be validated by `appstreamcli validate` tool. It contains all the metadata (description, license, homepage, screenshots) that required for a software center. The translation of description field can be handled e.g. by [Intltool or Itstool](https://www.freedesktop.org/software/appstream/docs/sect-Quickstart-Translation.html).

**Comment by elelay** [comment]
OK. What I don't understand is what value it adds: the software center has already installed the package when files in *usr/share/metainfo/* are available. Or is it meant to signal to a third party software center that the distro's package manager already installed this package. I couldn't find the explanation in [the documentation](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps).

The appstream file is committed, with adjustments:
 - change the name of the desktop file: gpodder.desktop instead of org.gpodder.gpodder.desktop;
 - remove content rating attributes : they are all none;
 - add the 3.10.5 release.

Is it OK?

**Comment by City-busz** [comment]
There is an [appstream-generator](https://github.com/ximion/appstream-generator) tool for distibution maintainers, which scans all packages in a distribution, and creates a database to be used by software centers ([GNOME Software](https://wiki.gnome.org/Apps/Software), [KDE Discover](https://userbase.kde.org/Discover)). You can see the current status report for specific distributions here:
- [Debian issues](https://appstream.debian.org/sid/main/metainfo/gpodder.html)
- [Debian metadata](https://appstream.debian.org/sid/main/issues/gpodder.html)
- [Arch Linux issues](https://pkgbuild.com/~arojas/appstream/arch/community/issues/gpodder.html)
- [Arch Linux metadata](https://pkgbuild.com/~arojas/appstream/arch/community/metainfo/gpodder.html)

The committed appstream file looks good. Just one notice: `appstreamcli validate org.gpodder.gpodder.appdata.xml` gives the following warning:
```
W - org.gpodder.gpodder.appdata.xml:org.gpodder.gpodder:18
    Found empty 'content_rating' tag.
```
So the line `<content_rating type="oars-1.0"/>` should be removed if it's not filled.

**Comment by elelay** [comment]
Thanks for the detailed explanation! 

From https://github.com/hughsie/oars/issues/18#issuecomment-432431678
> the validator has been adjusted meanwhile, so appstreamcli will now consider empty content_rating tags to be valid. Update to AppStream >= 0.12.3 to get the change

Strangely appstreamcli 0.12.4 on Arch still shows the warning.
