### ISSUE TITLE
Toogle: In Episoden list option for open folder

### ISSUE THREAD

**Issue by TZocker** [gpodder/gpodder#579]
Toogle: In Episoden list option for open folder like in the Abo list.

On this position.
![toogle](https://user-images.githubusercontent.com/20260822/50541963-6ac62c00-0bb1-11e9-8407-e8157bfa3805.png)

**Comment by elelay** [comment]
why not. PR welcome :-)

**Comment by Lexora** [comment]
Like an open the download folder where the episode is currently saved option? @auouymous what do u think - would this be too redundant since it is already available in the podcasts menu (when right clicking a podcast --> Open download folder)  or is this worth implementing?
