### ISSUE TITLE
Bug: Lost Translation ID

### ISSUE THREAD

**Issue by TZocker** [gpodder/gpodder#580]
![lost](https://user-images.githubusercontent.com/20260822/50541970-95b08000-0bb1-11e9-8f10-2130f1f06154.png)

**Comment by TZocker** [comment]
%(count)d new episode added to download list.

Don't work.

**Comment by elelay** [comment]
*Export remaining %(count)d episodes...* was marked as fuzzy (the python source code moved a bit or something), so translation was not used.

**Comment by TZocker** [comment]
With 3.9.6 from Portableapps also the python extension moduls are lost.

By the way:

https://github.com/gpodder/gpodder/issues/581

greetz
