### ISSUE TITLE
gPodder 3.10.6 macOS Text too large

### ISSUE THREAD

**Issue by geowy** [gpodder/gpodder#584]
gPodder 3.10.6 has text that is way too big.

Version 3.10.5 looked fine.

Please let me know if you need any more info.

![screen shot 2019-01-02 at 3 07 12 pm](https://user-images.githubusercontent.com/5038349/50582814-321f9e80-0ea0-11e9-8fd4-2b3a00bd7559.png)

![screen shot 2019-01-02 at 3 03 34 pm](https://user-images.githubusercontent.com/5038349/50582798-06041d80-0ea0-11e9-8c52-47016a9d9fe8.png)

![screen shot 2019-01-02 at 3 09 08 pm](https://user-images.githubusercontent.com/5038349/50582831-61361000-0ea0-11e9-9282-47b99c75ec13.png)

**Comment by elelay** [comment]
Thanks for reporting!
I had hoped it was only on my non-retina screen. No solution at the moment.

**Comment by geowy** [comment]
Thanks @elelay 

Let me know if you need someone to test on a retina display

**Comment by elelay** [comment]
This was a bug in gtk 3.24.1, fixed in 3/24.2.
Please try gPodder 3.10.7, which contains the fixed version.
