### ISSUE TITLE
List of episodes on Network

### ISSUE THREAD

**Issue by slackland** [gpodder/gpodder#585]
Hi, I need a little bit help. I use gPodder on several devices. My podcast downloads saved all on my network hard drive. But when I get the feeds, I must know which episodes I have already downloaded from my Desktop, my Notebook or my mobile phone. The list about new Episodes is saved in „Database“ in folder of gPodder. I tried many things. I saved with softlinks on my Network device. I saved the „Database“ on my network and get softlink to gPodder on my other devices and so on.
Is there a possibility to do this?

**Comment by elelay** [comment]
Isn't setting gPodder's home instead of only the download directory working?

See [this documentation](https://gpodder.github.io/docs/user-manual.html#gpodder-home-folder-and-download-location) for ways of setting `GPODDER_HOME`...
