### ISSUE TITLE
gPodder 3.10.5 forgets downloaded podcasts in Windows 7

### ISSUE THREAD

**Issue by lowtekk** [gpodder/gpodder#587]
I recently had to downgrade from gPodder 3.10.5 back to 3.10.4 after the update made it forget downloaded podcasts were in their appropriate folders.  Interestingly, 3.10.4 doesn't have this issue.   When the issue appeared, it would download episodes that had not previously been downloaded, but sometimes refused to download "missing" ones for several days.

**Comment by elelay** [comment]
Thanks for reporting!

Can you try running gPodder in debug mode, to gather more info about the issue ?
See [this link](https://gpodder.github.io/docs/windows.html#debugging-gpodder-on-windows).

What are the podcasts?

Have you enabled the 'Rename after Download' extension?

What do you mean by *gPodder refused to download*?
