### ISSUE TITLE
Last folder used in "Sent to" -> "local folder" reset to Home folder, if cancel button is selected

### ISSUE THREAD

**Issue by ndias** [gpodder/gpodder#588]
If I use the "Sent to" -> "Local folder" to save a podcast, next time I use the same functionality I have the same folder that I used last time to save.

But if instead of saving the podcast I press the Cancel Button in the second time, the "Last Folder" used, is reset to home folder, so next time I use the "Sent To" -> "Local folder" the podcast will be saved in the home folder instead of the last successful podcast saved folder.

**Comment by elelay** [comment]
Thanks for reporting. It should be improved. Help welcome :-)
Code for handling this is around [there](https://github.com/gpodder/gpodder/blob/master/src/gpodder/gtkui/main.py#L1830).
