### ISSUE TITLE
Some user's settings get lost during gPodder update -> Request: Optional separate user config file (like userChrome.css in Mozilla products)

### ISSUE THREAD

**Issue by Marrib** [gpodder/gpodder#590]
**Problem**
Whenever gPodder gets updated to a newer version, it overwrites some custom settings and all the user made custom configuration is lost.

**Description**
I have made some custom configurations/settings to gPodder, in the settings dialog inside the program as well as directly inside some .PY files (e.g. turned off noticifactions, increased font size in podcast list). All these customizations get lost and are being reset to factory settings during a gPodder update because some of those config files get overwritten.

**Suggessted solution / new feature**
Code gPodder in such a way that it looks for a custom configuration file from where it loads user's custom settings. This way settings won't be lost every time a new version of gPodder is installed. Mozilla does this for example with a .CSS file file called "useChrome.css".

**Benefits**
Easy backup/restoring of custom settings and customizations
Custom configuration of users don't get lost on updates.
Users could switch between various configurations easily

**Comment by elelay** [comment]
Hi,
I'm surprised that your config gets overwritten. What's your platform?

As for modifications with source code, it's inevitable. At a time I maintained a fork of gPodder to read my RSS feeds with my changes in a branch in git so I could easily merge upstream changes. Maybe you should consider that?

**Comment by Marrib** [comment]
The only changes that get overwritten are the ones I do inside some .py-files. Especially to turn off notifications these changes are needed and get factory reset with every update. No changes inside the regular config dialog in gPodder are effected; only the ones that need to be unlocked in the py files to appear in the settings dialog.
I also do some others changed inside the py files: increase thumbnail and font sizes in the podcast list and in the episode list. All these things get also reset.

Is there a way to architect gPodder in such a way that non-critical settings (e.g. font size, thumbnail size, background colors) get a separate config file set apart from critical core system files? Every time gPodder would start up, it would look for such a config file and then use settings from there. Again, like what Mozilla does with the userchrome.css files.

**Comment by Marrib** [comment]
Works perfectly, thanks!

**Comment by elelay** [comment]
In upper commits I've made sure the podcast icon size is computed from the text size in tree widgets

**Comment by elelay** [comment]
Is it what you want?

**Comment by Marrib** [comment]
Yeah absolutely, settings that stay intact.

**Comment by Marrib** [comment]
Thanks!

**Comment by elelay** [comment]
Great!
Please, can you tell me what your gtk.css looks like + a screenshot?

**Comment by elelay** [comment]
@Marrib please can you share your gtk.css + a screenshot of gPodder (with a few sample podcasts in a fresh profile if you prefer: `GPODDER_HOME=/tmp/gpodder gpodder`, to know how users are tweaking gPodder's look?
Also, are there other changes that you would like to make permanent apart from cover and text size?
Thanks,

**Comment by elelay** [comment]
Released in gPodder 3.10.7

**Comment by Marrib** [comment]
Sorry for my late reply, I have totally missed to follow this conversation. I don't tweak the gPodder appearance settings anymore apart from the usual preferences available in the GUI, because nowadays I don't feel like taking the time to do this. I was more enthusiastic back in the days.

What I tweaked back then was the thumbnail size of the podcast pictures and the background colour of the podcast list to be a light grey.
