### ISSUE TITLE
Bon temps rouler

### ISSUE THREAD

**Issue by demonligth** [gpodder/gpodder#608]
Bonjour,

Pour information, depuis 2 mois, message d'erreur lors de la mise à jour des episodes : "Erreur pendant la mise à jour http://www.tsfjazz.com/flux/bontemps_podcasts.xml : 'str' object has no attribute 'get'

**Comment by elelay** [comment]
Interesting. gPodder chokes on the 308 permanent redirect code but works fine with the 302 redirect code. I'll look into it further.
Thanks for reporting!

**Comment by elelay** [comment]
Actually it's in [Python itself](https://github.com/python/cpython/blob/3.7/Lib/urllib/request.py#L670).
I don't know why they don't handle the http 308 error code...

**Comment by elelay** [comment]
Looking more into TSF Jazz website, I can't find any RSS or Atom link!
It's a new website.

**Comment by elelay** [comment]
Good news : podcasts are back
Bad news : not easily discoverable on the website and with empty guid, so they are not compatible with gPodder.
The link to Bon temps rouler, anyway, if you want to download episodes manually : https://api.tsfjazz.com/api/feeds/podcasts/bon-temps-rouler.xml

**Comment by elelay** [comment]
gPodder uses requests/urllib3 now so 308 redirects work.
