### ISSUE TITLE
New downloads lost

### ISSUE THREAD

**Issue by pecohen** [gpodder/gpodder#610]
Twice I seem to have had a problem that I suspect has to do with the marking of new files.  Apparently, once files are found they are no longer new - even if no action on those files was requested.   This is a problem when there is a delay following the search for new files to download; possibly there is an unwarranted time-out.  This is troublesome when an interruption in work while waiting for the search for new downloads to happen.  In my experience it once was someone ringing my door-bell and in another it was my wife coming into my office to ask me to help her with something unrelated to what I was doing at the computer.  The delays were no more than a few minutes but that was apparently enough.

In any event, when I got back, all I had to do was to move the mouse pointer and the list of files to be downloaded disappeared from the screen.  A new search reports there are no new files to download - after all, they had been found already.

**Comment by elelay** [comment]
What is your platform?
What is the Preference entry for Updating > When new episodes are found ?
There is nothing marking new files old when *Show Episode List* is selected.
In fact, I often dismiss the new file list to select new episodes later from the main window.
Does this work for you?

**Comment by pecohen** [comment]
I use Windows 10, 64 bits.  

If I understand your suggestion it is that I should somehow keep track of which episodes I have downloaded and which I may have deleted, etc.   I'd prefer that computer software do this kind of thing for me.  That does work much of the time but it has failed on at least two occasions recently.

As it happens, I subscribe to about twenty different podcasts.  Most of them publish one episode a week but a few are daily programs and some publish only infrequently, once a month or less.  I pretty much want to download them all and I do try to listen to as many as I can find time for, sometimes skipping episodes after a few minutes of listening if the topic does not interest me or seems presented poorly.  Manually keeping track of which episodes I've downloaded really would not work well for me and I'd have to find some other software that would manage this task for me.  Juice did a good job of this but seems not to be supported any longer.

**Comment by elelay** [comment]
Hi,
yes, it's the point of gPodder to do the bookkeeping, this is not what I suggest.

I wanted to know which settings you have in the Preferences in the *Updating* tab, in the *When new episodes are found* drop-down list.

Also, for troubleshooting purpose only, I wanted to know if when you dismiss the *new episodes* dialog you still see the new episodes as new in the main window.

Finally, can you try running gPodder in debug mode, to gather more info about the issue ?
See [this link](https://gpodder.github.io/docs/windows.html#debugging-gpodder-on-windows).

**Comment by pecohen** [comment]
Eric, 



What is your platform? Windows 10 

What is the Preference entry for Updating > When new episodes are found ? 
After your first email I reviewed the settings and I did change it but before I made the change it was whatever the default might be. I think it was "add to download list". The problem is that the download list seems to time out and disappear if left alone for too long. 

There is nothing marking new files old when Show Episode List is selected. 
In fact, I often dismiss the new file list to select new episodes later from the main window. 

How can you tell which episodes are new from the episode list? It seems that all episodes are shown and selecting just the new ones is a troublesome chore that should not be required. 

Does this work for you? 

I'll give it a try using the "download immediately" option. Maybe that will solve the problem.

**Comment by elelay** [comment]
Thanks for your answer.

The default settings for *Updating > When new episodes are found* is *Show Episode List*. This is supposed never to mark new episodes old.

> How can you tell which episodes are new from the episode list? It seems that all episodes are shown and selecting just the new ones is a troublesome chore that should not be required.

New episodes are in bold in the main window.

Have you managed to [run gPodder in debug mode](https://gpodder.github.io/docs/windows.html#debugging-gpodder-on-windows)?

PS. I'm not sending you emails: it's comments on your issue on github: https://github.com/gpodder/gpodder/issues/610
