### ISSUE TITLE
3.10.7 GNU/Linux Slackware64 14.2 performance hit

### ISSUE THREAD

**Issue by joshroybal** [gpodder/gpodder#612]
After upgrading to gpodder 3.10.7 on several Slackware64 14.2 systems there is a significant performance decline compared to 3.10.6

Comparing the output of gpodder --verbose the new version stalls at this point while 3.10.6 does not.

 [gpodder.util] DEBUG: run_in_background: <bound method UserAppsReader.read of <gpodder.gtkui.desktopfile.UserAppsReader object at 0x7f9ad4db8358>> (False)

3.10.7 also is noticeably slower when checking for new podcasts.

For now I have reverted to 3.10.6 On multiple Slackware64 14.2 Linux systems there is a significant performance decline compared to 3.10.6

For now I have reverted to 3.10.6

**Comment by elelay** [comment]
Strange: [UserAppsReader](https://github.com/gpodder/gpodder/blob/master/src/gpodder/gtkui/desktopfile.py#L166) parses `*.desktop` in `/usr/share/applications/`, `/usr/local/share/applications/`,`/usr/share/applications/kde/`. The code has not changed between 3.10.5 and 3.10.7.
