### ISSUE TITLE
RSS feed not properly parsed

### ISSUE THREAD

**Issue by limburgher** [gpodder/gpodder#614]
http://www.flashforcast.com/nynf.xml, in gpodder, does not show new episodes, though they are visible in the XML.

**Comment by elelay** [comment]
A `<guid/>` element is missing in the feed items, making them all identical to gPodder.
See https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.flashforcast.com%2Fnynf.xml
and https://www.w3schools.com/xml/rss_tag_guid.asp .
Thanks,

**Comment by limburgher** [comment]
That might be a problem. Thanks! :)
