### ISSUE TITLE
YouTube + API key still 15 episode limit 

### ISSUE THREAD

**Issue by talindley** [gpodder/gpodder#616]
I have the YouTube API key installed, but I can still only get the latest 15 episodes. Am I doing something wrong or is this a YouTube limitation even with the API?

**Comment by elelay** [comment]
YouTube api usage has been removed from gPodder starting with 3.10.2.
It means there is a limitation on the 15 last episodes indeed.

**Comment by talindley** [comment]
I'm running 3.10.7. Why is there still a place to put the key? Preferences > Video > YouTube API key (v3):

**Comment by elelay** [comment]
It's an oversight. It will be removed
