### ISSUE TITLE
gPodder makes gnome-software confused

### ISSUE THREAD

**Issue by hughsie** [gpodder/gpodder#620]
In Fedora, the application ID is `gpodder.desktop` but on flatpak it is `org.gpodder.gpodder` -- looking upstream it seems the application has changed ID fairly recently. To "merge" the old and new IDs together in front-ends like gnome-software and KDE discover, and to use reviews reported against the old ID with the new ID you need to add an line in the existing `provides` section in the metainfo.xml file:

    <provides>
      <id>gpodder.desktop</id>
    </provides>

See https://blogs.gnome.org/hughsie/2017/07/05/using-a-reverse-style-application-ids-in-your-application/ for more details.

**Comment by hughsie** [comment]
Thanks! Much appreciated.

**Comment by elelay** [comment]
Thanks for reporting :-)
