### ISSUE TITLE
UnicodeEncodeErrors during make install

### ISSUE THREAD

**Issue by WinnersGoHome** [gpodder/gpodder#621]
I've been working on building gpodder in an ubuntu container `docker run -it ubuntu:latest /bin/bash` for a service account.  The build steps have been as follows:

    # As root
    apt update
    apt install build-essential git help2man intltool python3 python3-dbus python3-distutils python3-eyed3 python3-html5lib python3-mygpoclient python3-podcastparser
    adduser gpo
    su - gpo

    # As gpo
    git clone https://github.com/gpodder/gpodder.git gpodder-src && cd gpodder-src
    git checkout tags/3.10.8
    PREFIX=~/.local LINGUAS=en GPODDER_INSTALL_UIS="cli" make install

I'm getting the following error after trying to run gpo:

    gpo@81db04b48e32:~$ gpo
    Could not find gpod
    ERROR:gpodder.log:Uncaught exception: Traceback (most recent call last):
      File "/home/gpo/.local/bin/gpo", line 1163, in <module>
        main()
      File "/home/gpo/.local/bin/gpo", line 1157, in main
        cli._shell()
      File "/home/gpo/.local/bin/gpo", line 1010, in _shell
        """ % gpodder.__dict__).splitlines()))
    UnicodeEncodeError: 'ascii' codec can't encode character '\xa9' in position 51: ordinal not in range(128)

    Traceback (most recent call last):
      File "/home/gpo/.local/bin/gpo", line 1163, in <module>
        main()
      File "/home/gpo/.local/bin/gpo", line 1157, in main
        cli._shell()
      File "/home/gpo/.local/bin/gpo", line 1010, in _shell
        """ % gpodder.__dict__).splitlines()))
    UnicodeEncodeError: 'ascii' codec can't encode character '\xa9' in position 51: ordinal not in range(128)

I don't think the missing gpod module is causing the UnicodeEncodeErrors.  

I also get these errors when using the https://gpodder.github.io/docs/run-from-git.html method.

**Comment by WinnersGoHome** [comment]
For anyone else with this issue there is an environment variable to set the default python encoding.

`export PYTHONIOENCODING=utf8`

**Comment by elelay** [comment]
Exactly: setting the locale is required for gPodder to function properly.
