### ISSUE TITLE
create-desktop-icon.py fails when the name of the Desktop dir is localized

### ISSUE THREAD

**Issue by hkockerbeck** [gpodder/gpodder#627]
In `tools/create-desktop-icon.py`, the name of the Desktop directory is hardcoded (line 19). But on systems with a non-English locale, the name may be different. On my system with a German locale, for example, the dir's called "Schreibtisch" (the German word for "desktop"). So the line would need to be something like `DESTINATION = os.path.expanduser('~/Schreibtisch/gpodder-git.desktop')`.

It's possible to [obtain the path from bash](https://stackoverflow.com/questions/4358115/how-to-obtain-the-path-of-desktop-in-gnome) with something like `echo $(xdg-user-dir DESKTOP)`. I also found [some hints about getting it in Python](https://askubuntu.com/questions/457047/how-can-i-get-the-xdg-default-user-directories-from-python/457584#457584), but I didn't look into how current that info is.

I'm running Gnome Shell 3.28.3 on Ubuntu 18.04 LTS, but I'd assume the problem appears on most systems running Gnome Shell, maybe other desktop environments as well.

**Comment by elelay** [comment]
Thanks for reporting!
It's fixed in master now, using your suggestion to get the user's desktop directly from GLib.
