### ISSUE TITLE
Error: Cannot download video: HTTP is not supported

### ISSUE THREAD

**Issue by TinoJ** [gpodder/gpodder#628]
Hello,
since about 4 days gpodder portable stopped downloading from Youtube with "Error: Cannot download video: HTTP is not supported", but all URLs are actually HTTPS.
It looks like it is only youtube channels. Audio channels from soundcloud, radios stations are working.
The current gPodder portable app version is 3.10.7 (2019-02-01).
Last changes to the Win7 system:
15.05.2019: 2019-05 security rollup KB4499164
15.05.2019: 2019-05 Security and Quality rollup for .NET KB4499406
and the windows tool agains viruses May 2019: KB890830

Any advice, what I coud check?
Best, Tino

**Comment by Jennifer202** [comment]
I am having the same problem. Just like Tino it is ONLY youtube not working. At first I was thinking it may be some kind of downgrade attack and "not downloading youtube" was a side effect but I have no ideal how or what it would be. 

My skinny:
I am using Ubuntu. I have been working on the problem for over 24 hours now. I even went so far as to do a wipe of my main computer and reload the OS. I downloaded the windows version of gPodder and tried that one, on one of the few Windows computers I have. I tried using data stream from my phone and over my home internet, same thing. I get the same exact error. I can still download the videos if I go to the website and use a down-loader add-on. I used my VPN to try servers from all over the world. Thinking Google maybe blocking VPNs I turned it off and tried without any VPN. (this and my phone data would also use a different DNS) I even re-did one feed without the HTTPS at all, just the www.* same thing.

Thanks in advance for any help you can give,
Jennifer

**Comment by elelay** [comment]
Hi,
thanks for reporting and sorry @Jennifer202 you had to do all these things to try to fix it.
Please take a look at #625 for a quick fix.
