### ISSUE TITLE
403 Forbidden on one YouTube downloading

### ISSUE THREAD

**Issue by ryanerwin** [gpodder/gpodder#633]
I've patched the `HTTPS` issue in gPodder, but for the last month I'm still getting an error when trying to download a certain podcast.

`gpodder.download.gPodderDownloadHTTPError: ('//r3---sn-8pxuuxa-nboss.googlevideo.com/videoplayback?expire=1559764220&ei=nMj3XOrJEMHgogOk9Zm4Bg&ip=115.79.198.131&id=o-AOSNvNNM_CiNg6dkFgDegA5kMx0OrjhDz06Qjm2tSwxN&itag=18&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-8pxuuxa-nboss%2Csn-oguelney&ms=au%2Conr&mv=m&pcm2cms=yes&pl=21&initcwndbps=593750&mime=video%2Fmp4&gir=yes&clen=32816793&ratebypass=yes&dur=582.472&lmt=1556132071796383&mt=1559740035&fvip=3&beids=9466587&c=WEB&txp=4531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgQhU969MvA3V8D9Rv_gHg77aYs_QEyTpZlQFpz8MbudECIEj4_A9NWtFR-vNRrg6qWbnXEoAkz784pGXtguokHgEP', 403, 'Forbidden')
`

Other episodes from the same stream work... I have this issue occasionally...

Is there a way via the UI or the `gpo` CLI to clear a specific episode that hasn't downloaded properly so that you don't get a message about it every day? For the ones that don't work, I would rather just download them manually or skip all together.

The stack trace when downloading via `gpo` is:

`
Paul Joseph Watson
1559742626.427033 [gpodder.download] ERROR: HTTP 403 while downloading "Latest Atrocities in Modern Architecture": Forbidden
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gpodder/download.py", line 767, in run
    self.tempname, reporthook=self.status_updated)
  File "/usr/lib/python3.7/site-packages/gpodder/download.py", line 285, in retrieve_resume
    fp = self.open(url, data)
  File "/usr/lib/python3.7/urllib/request.py", line 1756, in open
    return getattr(self, name)(url)
  File "/usr/lib/python3.7/urllib/request.py", line 1965, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/usr/lib/python3.7/urllib/request.py", line 1930, in _open_generic_http
    response.status, response.reason, response.msg, data)
  File "/usr/lib/python3.7/site-packages/gpodder/download.py", line 216, in http_error
    return super().http_error(url, fp, errcode, errmsg, headers, data=data)
  File "/usr/lib/python3.7/urllib/request.py", line 1950, in http_error
    return self.http_error_default(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python3.7/site-packages/gpodder/download.py", line 229, in http_error_default
    raise gPodderDownloadHTTPError(url, errcode, errmsg)
gpodder.download.gPodderDownloadHTTPError: ('//r3---sn-8pxuuxa-nboss.googlevideo.com/videoplayback?expire=1559764220&ei=nMj3XOrJEMHgogOk9Zm4Bg&ip=115.79.198.131&id=o-AOSNvNNM_CiNg6dkFgDegA5kMx0OrjhDz06Qjm2tSwxN&itag=18&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-8pxuuxa-nboss%2Csn-oguelney&ms=au%2Conr&mv=m&pcm2cms=yes&pl=21&initcwndbps=593750&mime=video%2Fmp4&gir=yes&clen=32816793&ratebypass=yes&dur=582.472&lmt=1556132071796383&mt=1559740035&fvip=3&beids=9466587&c=WEB&txp=4531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgQhU969MvA3V8D9Rv_gHg77aYs_QEyTpZlQFpz8MbudECIEj4_A9NWtFR-vNRrg6qWbnXEoAkz784pGXtguokHgEP', 403, 'Forbidden')
Downloading Latest Atrocities in Modern Architecture                     [DONE]
`

**Comment by ryanerwin** [comment]
I found one workaround...

Using `sqlitebrowser` to open `~/gPodder/Database`, find the record for the episode that's causing problems when downloading and delete it. Of course, make sure that gPodder is NOT RUNNING while making a database modification like this.

**Comment by elelay** [comment]
Thanks for the report!
You should have been able to right-click the episode and uncheck "new"...
