### ISSUE TITLE
Vimeo download fail

### ISSUE THREAD

**Issue by ndias** [gpodder/gpodder#635]
I have this feed from Vimeo "https://vimeo.com/faroldeideiaslda/videos/rss" but every download fails with "Failed: HTTP Error 403: Forbidden" but if go to an episode this for example https://vimeo.com/342035317 I can download the video, there are even an button to download.

**Comment by elelay** [comment]
Yes, confirmed.
Strangely, Vimeo's CDN wants the star and slash escaped:
```
https://gcs-vimeo.akamaized.net/exp=1560692357~acl=%2A%2F1366545416.mp4%2A~hmac=66b3843dad7ced666ee9c15b350a99dc3167a223fb1ab1118f9ebd2fe494df29/vimeo-prod-skyfire-std-us/01/3407/13/342035615/1366545416.mp4
```
vs
```
https://gcs-vimeo.akamaized.net/exp=1560692357~acl=*/1366545416.mp4*~hmac=66b3843dad7ced666ee9c15b350a99dc3167a223fb1ab1118f9ebd2fe494df29/vimeo-prod-skyfire-std-us/01/3407/13/342035615/1366545416.mp4
```

**Comment by elelay** [comment]
The code un-escaping the url dates back to April 2018. By chance, could you tell me if vimeo download was working some recent time ago, or it could have be broken for a year?

**Comment by ndias** [comment]
Yes, was working recent, but I was using version 3.9.x one or two months ago, so I Can't say for sure that this was working in version 3.10.x recent

**Comment by elelay** [comment]
Thanks,
you can apply the patch 03819e4 directly in your gPodder installation.
Otherwise, wait for next release, but it will be in a few weeks.
