### ISSUE TITLE
Failed: HTTP Error 403: Forbidden message for all YouTube downloads

### ISSUE THREAD

**Issue by jrdeutsch** [gpodder/gpodder#636]
Every single one of my YouTube downloads has been failing ever since June 24, 2019.

Running .9 on Windows.

Help?

**Comment by elelay** [comment]
Thanks for reporting!
Can you try running gPodder in debug mode, to gather more info about the issue ?
See [this link](https://gpodder.github.io/docs/windows.html#debugging-gpodder-on-windows).

**Comment by jrdeutsch** [comment]
It seems to have started working again (?), but thanks for the note!

**Comment by elelay** [comment]
OK, let us know if it happens again.
