### ISSUE TITLE
hr2 podcasts don't update (invalid guid attribute)

### ISSUE THREAD

**Issue by altheeagle** [gpodder/gpodder#640]
I have problems with the Podcasts from http://podcast.hr2.de/derTag/podcast.xml
When I add the Podcast via "Add Podcast via URL" for the first time it showed me all the episodes and I downloaded them. But after that it wouldn't be updated. I have al few other Podcast URLs which are working fine, except that one. I already deleted my Database-File and recreated it, but it doesn't change a thing.

**Comment by elelay** [comment]
Unfortunately, some hr2 podcasts are invalid. See https://github.com/gpodder/gpodder/issues/309#issuecomment-418163663 for details.

All podcasts listed on https://www.hr2.de/rss/index.html are correct in the first section, but all the others (****/podcast.xml) have the same problem. Please try to contact them to correct the issue.

**Comment by elelay** [comment]
Great news: hr2 will fix those podcasts in "a few weeks". They were aware of the problem with other podcatcher. They kindly sent me a preview url with the new format and it works with gPodder.

**Comment by altheeagle** [comment]
Thank you for your help :)
> 
> Great news: hr2 will fix those podcasts in "a few weeks". They were aware of the problem with other podcatcher. They kindly sent me a preview url with the new format and it works with gPodder.

**Comment by elelay** [comment]
:tada: It's fixed!
