### ISSUE TITLE
Other gPodder projects unmaintained

### ISSUE THREAD

**Issue by Keeper-of-the-Keys** [gpodder/gpodder#641]
Hi,
I tried reaching out by mail and over IRC but without luck (the IRC channel has no maintainers there).
Can you provide some TLC to gpodder-sailfish gpodder-ui-qml and gpodder-core?
Just appointing someone who is willing to go over pull requests would be great!
There are currently 3 PRs open for gpodder-sailfish and 1 for gpodder-ui-qml though maintaining a fork elsewhere is for sure possible to me it seems ideal if upstream remains upstream.
Thanks!

**Comment by elelay** [comment]
Hi,
good that you kept trying to reach out to us ! I should be on IRC more often, but I have no time for this atm. The gPodder [mailing list](https://www.freelists.org/list/gpodder) is also active...

Regarding the qml gpodder stack, I'll gladly accept help. I've never looked into it (no jolla phone owner). I think Thomas created gPodder 4 to disentangle from gtk, but I kept maintaining the gtk gPodder 3 branch instead. Let's try to work on open PRs together?

Regarding sailfish, I don't know how to make new releases. Do you copy you local build on your phone?

**Comment by Keeper-of-the-Keys** [comment]
ATM it's worse then that, I edit the files on my phone until I figure out how to get it working and then implement them on the git branch I have on my computer.
So far I have not attempted to build an RPM because I don't know if they would accept it since I'm not the original author, at the end of this week there is an IRC dev meeting for SailfishOS and I hope to participate and see if there is any procedure to switch orphaned OSS software to new authors.

I'll gladly help where I can when I have time.

**Comment by elelay** [comment]
OK. There are instructions [here](https://github.com/gpodder/gpodder-sailfish/issues/46) for a build setup and also in the [README](https://github.com/gpodder/gpodder-sailfish/blob/master/README.md). Are they still relevant?

Would you like to be part of the gpodder sailfish team? You'll then be able to manage issues, push to the repo, merge PRs, etc. In the begining, I'd prefer that we still review one another's PRs before merging.

Regarding releases, we can ask Thomas for transfer if need be. The problem with jolla harbour or [openrepos](https://openrepos.net/content/thp/gpodder) is that it's linked to a user name, not a team. If you have time, it would be great if you could ask the sailfishOS devs about that.

**Comment by Keeper-of-the-Keys** [comment]
I will try the instructions tomorrow I hope and update them as needed.

As far as becoming a member of the team I am interested since this is a program I use daily in improving it where I can. That being said the amount of time I have available varies pretty wildly so if you need someone who can commit to steady attention that may be an issue.

I hope to join the SailfishOS collaboration meeting of this Thu and bring this issue up.

**Comment by elelay** [comment]
Great, I'm not asking for more.
We have a new sailfish stack maintainer :tada:

**Comment by Keeper-of-the-Keys** [comment]
@elelay What is the correct way to get a hold of the rest of the team to double check my decisions if needed?

**Comment by elelay** [comment]
I'm elelay on IRC. PM me with your email address so that we can exchange privately.
For code change, submit PRs. We can discuss on them.
For issues, mention me if you want an opinion ;-)
Thanks,
