### ISSUE TITLE
convert audio files, transcode audio files to mp3/ogg, failes with an error when trying to tick the box in the extention window

### ISSUE THREAD

**Issue by mhussaincov** [gpodder/gpodder#645]
stepps to reproduce:
1.
launch gpodder on linux
2.
go to the extentions window via the prefferances dialog box
3, locate the extension named transcode audio files to mp3/ogg and try to tick the box to launch it.
what should happen, the box should be ticked ready for use,
what happens, an error does descend:

extention can't be activated, name true is not defigned.
please note, running the very latest gpodder from the arch linux reposatories if you wish me to use gpodder from git via the aur, let me know:
Majid Hussain

**Comment by elelay** [comment]
Thanks for reporting!
Please run `gpodder -v` from a terminal to get more debug output: there should be a stacktrace when you activate the extension.

**Comment by mhussaincov** [comment]
hi there,
just upgraded to your git version of gpodder,
the issue I reported has vanished, so will close this issue, sorry for being a pain in the ***
next time I promise i'll install from git in future 
Majid
