### ISSUE TITLE
Podcast titles not recognised since about 9/7/19

### ISSUE THREAD

**Issue by HSmp** [gpodder/gpodder#651]
Files are downloading from the BBC into gPodder and being listed correctly (eg: 15/08/2019) under 'Episode'.

However, in the gPodder 'Downloads' folder, they now appear as unknown (eg: bUnknown-f09b2fd0-51bd-44a9-8f74-864b190103c7_p07jwmcy_cUnknown_1565086263140.mp3).

This means that when I download to my phone, episodes aren't recognised, or even found.

I'm assuming this is probably down to some 'improvement' the BBC has made to it's inadequate web presence. A fix would be greatly appreciated.

I'm running Xubuntu 18.04 and gPodder 3.10.01

Thanks.

**Comment by elelay** [comment]
You can use the "Rename episodes after download" extension: it will rename episodes to TITLE.mp3 (only newly downloaded ones). Also use the "Edit Config" and type "rename" if you want to add a date or the podcast title.

**Comment by HSmp** [comment]
Thank you elelay, that helped.

I'd looked in preferences for a way of renaming files, but hadn't thought of looking in extensions.

Odd though - there hadn't been a problem until very recently..
