### ISSUE TITLE
Paged Feeds

### ISSUE THREAD

**Issue by rosemaryginfizz** [gpodder/gpodder#660]
Would it be possible to enable gpodder to handle [paged feeds](https://podlove.org/2013/06/22/paged-feeds-for-podcasts/)?

I subscribe to several podcasts that have been running for years and have published quite a number of episodes. I like to keep some favorite ones, preferably inside gpodder, to listen to them again. Recently I had to reinstall the app. For some of the podcasts it meant that I was no longer able to download the full archive of episodes but only the most recent, e.g. 50. [Raumzeit](https://raumzeit-podcast.de/) would be an example. The rss feed is paged and should contain all episodes starting with the first, but gpodder doesn't seem to be able to fully read it. 

Thank you for all your effort with this program. After all these years it's still my favorite podcatcher and I'm glad to see it kept alive.

**Comment by elelay** [comment]
Thanks for your kind words!

Yes, it's already implemented (#231) and will be available in next release.
You might want to run the unreleased version [from git](https://gpodder.github.io/docs/run-from-git.html).
A new released will be out in a few weeks anyway.
