### ISSUE TITLE
error "invalid token" in RSS feeds when check for new episodes

### ISSUE THREAD

**Issue by bollullera** [gpodder/gpodder#661]
Hi!

1. Check for new episodes or add podcast via URL.
2. Error "invalid token" in RSS subcriptions.
3. I can't sync.

![Captura de pantalla de 2019-09-03 18-30-49](https://user-images.githubusercontent.com/54855271/64191634-2fcf7300-ce79-11e9-9b69-0df00ca70682.png)

**Comment by JuanjoSalvador** [comment]
Can you describe the steps to reproduce?

**Comment by bollullera** [comment]
When I add a new podcast via RSS feed or check for new episodes I receive an error message that says "invalid token" and then I cannot synchronize or download those episodes. It is not something that happens with all feeds, only with some but, for example, with apps like AntennaPod I have no problem. That's why I think it's not a problem with those feeds, but with gPodder in Linux. I'm not sure.

**Comment by elelay** [comment]
The RSS feed is indeed invalid: it contains an attribute `"Government & Organizations"`, with the & not escaped. It should be `"Government &amp; Organizations"`.

gPodder will not add an invalid feed.
If you can, please report the issue to the podcast author: they can fix it very easily...

**Comment by elelay** [comment]
feed url for easy copy/paste:  https://www.ivoox.com/podcast-voz-inaki_fg_f116525_filtro_1.xml

**Comment by JuanjoSalvador** [comment]
Can we parse on the application the XML to make it safe?

**Comment by elelay** [comment]
We try to stick to simple parsing and inform podcast authors so they fix their feeds to be at least valid XML.
It seems the problematic episode is gone...

**Comment by elelay** [comment]
@JuanjoSalvador thanks for the help :+1: yours were valid questions :-)
