### ISSUE TITLE
New cannot download video error

### ISSUE THREAD

**Issue by tazewhatnow** [gpodder/gpodder#665]
Youtube videos can't download. The same issue happens with youtube download video plugins for browsers, suggesting there's a change in how Youtube handles video url. Gpodder version used is 3.10.9 portable. Similar to the earlier problem that was fixed with this release and the .py file edits before.

**Comment by tazewhatnow** [comment]
Issue also happens for older episodes when adding a new feed. So it's not just new episodes that fail to download.

**Comment by mads5408** [comment]
I have the same issue

**Comment by elelay** [comment]
Thanks for reporting! Indeed, google changed sthing in Youtube breaking our code, as well as many projects' I guess.
#666 reports the same problem
