### ISSUE TITLE
Stopped downloading YouTube

### ISSUE THREAD

**Issue by mads5408** [gpodder/gpodder#666]
After i had updated (apt update and upgrade) my system, gpodder has stopped downloading YouTube. I tried to start gpodder in the terminal, witch removed the list of things i had updated in the terminal history. 

It no longer shows any error messages in the "Progress" tab. The terminal shows this error:

gpodder.youtube.YouTubeError: Cannot download video: 
1568217407.906139 [gpodder.download] ERROR: Download failed: Cannot download video: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/download.py", line 745, in run
    url = youtube.get_real_download_url(self.__episode.url, fmt_ids)
  File "/usr/lib/python3/dist-packages/gpodder/youtube.py", line 157, in get_real_download_url
    fmt_id_url_map = sorted(find_urls(page), reverse=True)
  File "/usr/lib/python3/dist-packages/gpodder/youtube.py", line 155, in find_urls
    raise YouTubeError('Cannot download video: %s' % error_message)

I have tried to purge and reinstall both gpodder and python3.

Attached is terminal output file
[GpodderError.txt](https://github.com/gpodder/gpodder/files/3601693/GpodderError.txt)

**Comment by pieska** [comment]
There's no "url_encoded_fmt_stream_map=" in the downloaded page, youtube-dl has the same issue:

ERROR: This video is unavailable.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 795, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 2099, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video is unavailable.

**Comment by elelay** [comment]
Thanks for reporting and the link to youtube-dl's fix :-)

**Comment by pieska** [comment]
hmm, wouldn't it be beneficial if gpodder would just use youtube-dl for downloading stuff? just an idea to prevent duplicate work...

**Comment by tazewhatnow** [comment]
It seems to be fixed. gPodder now downloads Youtube again and I didn't change anything. Maybe Youtube rolled back the change they made because they ran into issues. Could be temporary.

**Comment by mads5408** [comment]
Can confirm

**Comment by elelay** [comment]
As a lucky coincidence, next gPodder release (originally due this week-end, but I'll take the time to fix the youtube code if possible) will have a new youtube-dl extension, to manage subscriptions and/or download episodes using youtube-dl.
You can try out the [Windows preview](https://ci.appveyor.com/project/elelay/gpodder/builds/27346230/artifacts) or [Run gPodder from git on Linux](https://gpodder.github.io/docs/run-from-git.html) to try it out.
Documentation is here : https://gpodder.github.io/docs/extensions/youtubedl.html

**Comment by pieska** [comment]
the youtibe-dl extension is great, much appreciated. i tried it out and filed an issue ;-)
#673

**Comment by elelay** [comment]
Google seem to have rolled back the change.
