### ISSUE TITLE
Won't work in Mac OS Catalina

### ISSUE THREAD

**Issue by MarvMarsh** [gpodder/gpodder#669]
I'm presently using the beta version of OS Catalina.  When I opened gPodder, I found an empty shell of the programme.  All drop-down menus were greyed-out and the menus under gpodder didn't work.  No previously uplodaded data was gone.

Do I have to wait for an upgraded version of the programme for it to work in the new operating system?

**Comment by elelay** [comment]
Thanks for reporting!
I don't have access to a mac with Catalina installed.
Please can you confirm that gPodder 3.10.9 doesn't work on Catalina?
It would be a major setback.
If so, can you try again and collect any error on the terminal (https://gpodder.github.io/docs/macos.html#debugging-gpodder-on-macos)?

**Comment by MarvMarsh** [comment]
Thank you for the reply.  I'm presently using the most recent except one version of gPodder and things seem mostly OK.  It has crashed a couple of times; it would freeze, but a restart would took care of the problem.
I'm feeling more confident about gPodder and I'll probably upgrade shortly and, when I do, I'll advise you if there are any problems.

I appreciate your follow-up on my message and I want to say that I'm continuing to use the app.
    On Sunday, September 15, 2019, 1:11:49 a.m. GMT+9, Eric Le Lay <notifications@github.com> wrote:  
 
 
Thanks for reporting!
I don't have access to a mac with Catalina installed.
Please can you confirm that gPodder 3.10.9 doesn't work on Catalina?
It would be a major setback.
If so, can you try again and collect any error on the terminal (https://gpodder.github.io/docs/macos.html#debugging-gpodder-on-macos)?

**Comment by elelay** [comment]
OK, thanks

**Comment by elelay** [comment]
I've just tried gPodder 3.10.12 on macOS catalina and it works fine.
