### ISSUE TITLE
File sizes are not formatted according to user’s locale

### ISSUE THREAD

**Issue by huftis** [gpodder/gpodder#671]
The file sizes shown in episode list (and other places) are not formatted according to the user’s locale, i.e., they use a dot as the decimal separator instead of the locale-specific decimal separator.

For example, they are formatted like this:

`17.3 MiB`

For most European locales (e.g. ‘nn_NO.utf8’), the decimal separator should be a comma:

`17,3 MiB`

**Comment by elelay** [comment]
That's right. Please feel free to improve that :-)

**Comment by elelay** [comment]
I guess it should use `locale.str()` to format the number according to current locale

**Comment by huftis** [comment]
Surprisingly, `locale.str()` does **not** (yet) support *locale-aware* fixed-point number formatting (see https://bugs.python.org/issue35638). But I think I’ve found a solution, using `locale.format_string()`. I’ll submit a pull request after some more testing.
