### ISSUE TITLE
downloading files with youtube-dl extension fails if format_ids is X+Y

### ISSUE THREAD

**Issue by pieska** [gpodder/gpodder#673]
the youtube-dl extension is great but it does not work as expected.

youtube-dl allows format ids like "137+140". it diwnloads the video and audiofile and merges them zu the final containter file.

the youtube-dl extension downloads the correct files and merges them but then something with renaming goes wrong:

0 13. Sep 20:03 'CONTROL 🤯 018_ Die Macht von Copy & Paste.mp4'
427423784  6. Sep 19:13 'CONTROL 🤯 018_ Die Macht von Copy & Paste.mp4.partial.mp4'

The actual file is named abc.mp4.partial.mp4 but the download is registered in the database as abc.mp4 and the GUI cannot play the file.

here the log:

1568399671.635185 [gpodder.gtkui.main] DEBUG: Downloading episode: CONTROL 🤯 018: Die Macht von Copy & Paste
1568399671.654872 [gpodder.my] DEBUG: Storing 1 episode download actions
1568399671.656782 [gpodder.download] INFO: 1 tasks to do, can start at most 4 threads
1568399671.657282 [gpodder.download] INFO: Starting new worker thread.
1568399671.657678 [gpodder.util] DEBUG: run_in_background: <bound method DownloadQueueWorker.run of MainThread> (False)
1568399671.658602 [gpodder.download] INFO: Starting new thread: Thread-5
1568399671.660730 [gpodder.download] INFO: Thread-5 is processing: CONTROL 🤯 018: Die Macht von Copy & Paste
1568399671.663447 [gpodder.registry] INFO: custom_downloader resolved by custom_downloader from youtube-dl: None -> <youtube-dl.YoutubeCustomDownload object at 0x7fe4989c4610>
1568399671.664354 [gpodder.download] INFO: Downloading https://www.youtube.com/watch?v=YveUjRPx5o8 with <youtube-dl.YoutubeCustomDownload object at 0x7fe4989c4610>
[youtube] YveUjRPx5o8: Downloading webpage
[youtube] YveUjRPx5o8: Downloading video info webpage
[download] Destination: /home/pharaoh/gPodder/Downloads/Gronkh/CONTROL 🤯 018_ Die Macht von Copy & Paste.mp4.partial.f137
[download]   0.0% of 383.17MiB at 157.63KiB/s ETA 41:491568399673.283420 
[gpodder.download] DEBUG: Updating file size of /home/pharaoh/gPodder/Downloads/Gronkh/CONTROL 🤯 018_ Die Macht von Copy & Paste.mp4 to 401782503.0
[download] 100% of 383.17MiB in 01:13
[download] Destination: /home/pharaoh/gPodder/Downloads/Gronkh/CONTROL 🤯 018_ Die Macht von Copy & Paste.mp4.partial.f140
[download]   0.0% of 23.78MiB at 75.01KiB/s ETA 05:251568399747.195647 [gpodder.download] DEBUG: Updating file size of /home/pharaoh/gPodder/Downloads/Gronkh/CONTROL 🤯 018_ Die Macht von Copy & Paste.mp4 to 24932845.0
[download] 100% of 23.78MiB in 00:05

////// here ffmpeg adds mp4 to the filename
[ffmpeg] Merging formats into "/home/pharaoh/gPodder/Downloads/Gronkh/CONTROL 🤯 018_ Die Macht von Copy & Paste.mp4.partial.mp4"
////

Deleting original file /home/pharaoh/gPodder/Downloads/Gronkh/CONTROL 🤯 018_ Die Macht von Copy & Paste.mp4.partial.f137 (pass -k to keep)
Deleting original file /home/pharaoh/gPodder/Downloads/Gronkh/CONTROL 🤯 018_ Die Macht von Copy & Paste.mp4.partial.f140 (pass -k to keep)

/// this is the tempname in gpoder but ffmpeg added mp4 to the file name on disk
/home/pharaoh/gPodder/Downloads/Gronkh/CONTROL 🤯 018_ Die Macht von Copy & Paste.mp4.partial
/// this is the final name
/home/pharaoh/gPodder/Downloads/Gronkh/CONTROL 🤯 018_ Die Macht von Copy & Paste.mp4

due to the mismatch in filenames shutil.move does not rename the tempfile to the final name.

I "fixed" it this way:
```
--- download.py.org	2019-09-12 19:34:02.000000000 +0200
+++ download.py	2019-09-13 20:49:13.448505562 +0200
@@ -884,6 +884,7 @@ class DownloadTask(object):
             self.tempname = os.path.join(os.path.dirname(self.filename),
                     os.path.basename(self.tempname))
             shutil.move(self.tempname, self.filename)
+            shutil.move(self.tempname+'.mp4', self.filename)
 
             # Model- and database-related updates after a download has finished
             self.__episode.on_downloaded(self.filename)
```

**Comment by elelay** [comment]
Thanks for reporting! I hadn't tested this case.
Also made download progress is more accurate, since it adds downloaded video size when downloading audio.
