### ISSUE TITLE
Patch to enable some hotkeys, help needed

### ISSUE THREAD

**Issue by Vrihub** [gpodder/gpodder#677]
Once upon a time (gpodder still used gtk 2) I wrote myself a patch to add hotkeys (accelerators) for some frequently used buttons and menu options.

Back then, it was just a matter of adding "_" characters to the relevant strings in the `(Image)MenuItem` and `make_menu_item` calls.

I tried to port that old patch to the current gpodder version, but it seems that with gtk 3 things are a bit more complicated, so I'd like some help.

Initially I tried to replicate adding the "_" to the new code but it doesn't work (the underscores were literally displayed in the strings), then I noticed that already existing hotkeys use the `.new_with_mnemonic` method, so I tried adding it, but I got mixed results (see the attached patch for reference).

Things that work OK:
- In the popup context menu when right-clicking on a podcast feed:

  "Update podcast", "Open download folder", "Mark episodes as old", "Archive", "Delete podcast", "Podcast settings"  defined in `gtkui/main.py`

Things that almost work, buggy:

- In the popup context menu when right-clicking on an episode:
   
  "Play", "Preview", "Stream", "Download", "Delete", "Episode details" defined in `gtkui/main.py`

  These work, but when I update a feed, strange things happen:
  - I get an empty "episode selector" window (I can just close it), though new episodes actually appear in the episodes panel of the main window
  - If I click on the bottom-left icon to stop the feed update, gpodder gets stuck on "Cancelling" and I can't update any other feed.
  - I get errors in the log:
  
    2019-09-13 11:43:35,099 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 2713, in update_feed_cache_finish_callback
      self.new_episodes_show(episodes, notification=True)
    File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 3086, in new_episodes_show
      show_notification=False)
    File "/usr/lib/python3/dist-packages/gpodder/gtkui/interface/common.py", line 36, in __init__
      GtkBuilderWidget.__init__(self, gpodder.ui_folders, gpodder.textdomain, parent, **kwargs)
    File "/usr/lib/python3/dist-packages/gpodder/gtkui/base.py", line 71, in __init__
      self.new()
    File "/usr/lib/python3/dist-packages/gpodder/gtkui/desktop/episodeselector.py", line 139, in new
      self.btnOK.set_label.new_with_mnemonic(_('_Download'))
    AttributeError: 'gi.FunctionInfo' object has no attribute 'new_with_mnemonic'

Things that don't work:

- In the "episode selector" window: the "Download", "Select all", "Select none" buttons,
  defined in `gtkui/desktop/episodeselector.py`

- While I'm dowloading episodes, if I right-click on an episode in the "Progress" window: in the context menu, the "Download", "Cancel", "Pause", etc items.

  Plus, I get errors in the log:

    2019-09-13 12:12:56,025 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 700, in on_treeview_downloads_button_released
        return self.treeview_downloads_show_context_menu(treeview, event)
      File "/usr/lib/python3/dist-packages/gpodder/gtkui/main.py", line 1651, in treeview_downloads_show_context_menu
        menu.append(make_menu_item.new_with_mnemonic(_('_Download'), 'document-save',
    AttributeError: 'function' object has no attribute 'new_with_mnemonic'

- I'd also like to add hotkeys to the "Mark as old" button in the "episode selector"
  window, i.e. `remove_action=_('Mark as old')` in `gtkui/main.py`, any help?

BTW, it seems that a recent -feature- bug in gtk prevents the accelerator keys from
actually be underlined in the ui, unless you press the Alt key (see
https://unix.stackexchange.com/questions/212470/enabling-alt-hotkeys-for-buttons-in-gnome)
While this works for accelerators on the main menu bar, I couldn't find a
similar way for the items in the popup/context menus, except for pressing some
key and hoping that it is amongst the defined accelerators for that menu.
Is there a way to make accelerator keys ALWAYS visible?

[hotkeys.patch.txt](https://github.com/gpodder/gpodder/files/3616959/hotkeys.patch.txt)

**Comment by elelay** [comment]
Hi,

why are you calling `new_with_mnemonic` on the `make_menu_item` function?
Have you tried calling `make_menu_item(_('_Download')`? It shows the underlined D when I press Alt and move the mouse to the popup. But pressing Alt-D doesn't trigger the action.

If it's a change in behaviour in new gtk versions I'm afraid there is nothing to do about it.

**Comment by Vrihub** [comment]
> Hi,
> why are you calling `new_with_mnemonic` on the `make_menu_item` function?

It was just a naive try, since it worked OK with other functions.

> Have you tried calling `make_menu_item(_('_Download')`?

Uhm actually I thought I had tried this, but I had the wrong impression that it doesn't work on any string; in fact it works OK for the contextual menu in the progress window (Download, Pause etc); and it also gets rid of the errors in the log, thanks!

Also I now noticed that "Mark as old", "Cancel" and "Download" in the episode selector window work, though they require pressing `Alt`.

So the only buttons that remain to be fixed are these two in the episode selector window: "Select all", "Select none", defined in `gtkui/desktop/episodeselector.py`.
Neither `Gtk.MenuItem(_('Select _all'))` nor  `Gtk.MenuItem.new_with_mnemonic(_('Select _all'))` seem to work.

And if I press any key in the episode selector window a text field pops up in the bottom right corner, just like the ones used in the main gpodder window to allow filtering podcasts or episodes. I guess this might prevent the hotkeys to work? (and what use is it anyways in the episode selector window? shouldn't we get rid of it?)

**Comment by elelay** [comment]
Good :-)

Those buttons are not created by espisodeselector.py but declared in `share/gpodder/ui/gtk/gpodderepisodeselector.py`. If you change the label here it will work.
What you changed in `gtkui/desktop/episodeselector.py` is the context-menu items when you right-click on the episode list in the popup.

Typing in the episode selector window only goes to the episode list and shows the search field if the episode list has focus. On my system it doesn't have focus by default. If it does on yours, press tab to move to a button and then the shortcut should work.

**Comment by Vrihub** [comment]
Ah, thank you very much, I didn't look into `/share`.
Actually the change in `gtkui/desktop/episodeselector.py` is required for the `Download` button in the episode selector window.

I'm attaching the final patch; if anyone is interested in merging it, or further developing it (any other useful hotkeys?), I can set up a fork and open a PR.

[hotkeys_final.patch.txt](https://github.com/gpodder/gpodder/files/3638655/hotkeys_final.patch.txt)

**Comment by elelay** [comment]
Great!
My only issue with it is that it will mess up translations.
Can you open a PR?
I won't merge it right now because I'd like to cut a release and already asked for translation updates, but it will be in next one.

**Comment by Vrihub** [comment]
> My only issue with it is that it will mess up translations.

It surely will! :)

> I won't merge it right now because I'd like to cut a release

No problem, I can open a PR, and we might use that to add accelerators for other frequently used keys, these were just the ones I use most.

**Comment by auouymous** [comment]
Thanks for posting this. It doesn't work for me because any Alt keys other than P, S, E, X and V (main menu bar) cause the filter input to open and the letter added to it. Did I miss something you did that corrects this?

But elelay's `share/gpodder/ui/gtk/` suggestion pointed me to `menu.ui` which allows Ctrl keys, and maybe Alt keys, to be added to menu items. Wouldn't it be better to add Ctrl keys for frequently used actions?
