### ISSUE TITLE
Rename already downloaded podcasts.

### ISSUE THREAD

**Issue by clort81** [gpodder/gpodder#678]
Having downloaded a few thousand poorly named podcast episodes, I would like to rename them to something sensible and sortable - e.g. beginning with a date.

I see the rename_podcast extension is available but I find no way to rename all podcast episodes for a particular podcast.

Is there an existing way to do this?  Ideally the user would just right click on the podcast name and select 'rename downloaded podcasts'.

**Comment by elelay** [comment]
Good idea!
It would be quite easy to implement: take a look at https://github.com/gpodder/gpodder/blob/master/share/gpodder/extensions/episode_website_context_menu.py for inspiration on how to add a context-menu item and call `self.on_episode_downloaded()` on each episode selected or each downloaded episode of the channel...
PR is welcome :-)

**Comment by joesmith222** [comment]
i use this free program, for example to move the date to the end of the filename:

https://www.bulkrenameutility.co.uk/Main_Intro.php

its very good

**Comment by jeettrivedi** [comment]
I am working on this issue. I will submit a pull request likely sometime next week.

**Comment by elelay** [comment]
@jeettrivedi cool! Looking forward to merging it :-)

**Comment by kwingart** [comment]
how is the progressing, is it done? i looking forward it。；）
thank you guys。

**Comment by kwingart** [comment]
i got that rename trick. thanks

**Comment by velcroskids3** [comment]
I agree with OP.     I too do not know how gpodder can prefix, suffix or completely replace existing podcast names with configurable release date [YYYY.MM.DD] and/or with number sequence and/or custom text or symbol.
I mention all these options as I find far too many podcasts so poorly named for collecting it's maddening.

**Comment by bonelifer** [comment]
> I am working on this issue. I will submit a pull request likely sometime next week.

Any progress?

**Comment by elelay** [comment]
@bonelifer it's up for grabs :-)

**Comment by batman004** [comment]
@elelay  I would like to take up this issue. Would appreciate a little more context and help in terms of which files should I look out for and in what way should new code be added.

Thanks

**Comment by auouymous** [comment]
@batman004 I would extend the rename-download extension to do this. From the context menu hook that elelay provided, you can simply wrap the code from on_episode_downloaded() in a loop over the episodes. I would move the code to a function and call it from both locations.

You can also add an item to the extras menu like #978 does. The following should provide a list of all episodes. See on_ui_object_available() in #978 to get `self.gpodder`.

```python
model = self.gpodder.episode_list_model
episodes = [row[model.C_EPISODE] for row in model]
```

**Comment by batman004** [comment]
Hey @auouymous, I'm thinking along these lines (refer code screenshot), let me know if this is not correct. I'm not sure what you mean by "call it from both locations"

Added this function to the `rename_download.py` file

<img width="763" alt="Screenshot 2022-11-14 at 11 31 09 PM" src="https://user-images.githubusercontent.com/58564635/201732939-69e69681-776f-4712-bd58-e797e837287d.png">


Also I've been trying to run Gpodder locally but getting errors related to Dbus 
```
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoMemory: Not enough memory
```

**Comment by auouymous** [comment]
The `self.open_dialog` should be `self.rename_all_downloaded_episodes`. It should also open a progress dialog since updating thousands of downloads can take a while. Something like this inside rename_all_downloaded_episodes should do it.

```python
count = len(episodes)
progress_indicator = ProgressIndicator(
    _('Renaming all downloaded episodes'),
    '', True, self.gpodder.get_dialog_parent())
progress_indicator.on_message('0 / %d' % count)

n = 0
for episode in episodes:
    self.on_episode_downloaded(episode)

    n += 1
    progress_indicator.on_message('%d / %d' % (n, count))
    progress_indicator.on_progress(n / count)
    if time.time() >= progress_indicator.next_update:
        progress_indicator.update_gui()
        self.gpodder.force_ui_update()
        if not progress_indicator.cancellable:
            break

progress_indicator.on_finished()
```

I didn't think about just calling on_episode_downloaded, which does what I suggested to prevent duplicating the code in that function.

I just updated https://gpodder.github.io/docs/run-from-git.html, do the new instructions fix your issue?

**Comment by batman004** [comment]
Thanks for the help @auouymous. I think this should work. Also, any reason for not using f-strings?


```python
  def on_rename_all_episodes_menu(self):
      return [(_("Renaming all downloaded episodes"), self.rename_all_downloaded_episodes)]


  def rename_all_downloaded_episodes(self):
      model = self.gpodder.episode_list_model
      episodes = [row[model.C_EPISODE] for row in model]

      number_of_episodes = len(episodes)
      progress_indicator = ProgressIndicator(
          _('Renaming all downloaded episodes'),
          '', True, self.gpodder.get_dialog_parent())
      progress_indicator.on_message('0 / %d' % number_of_episodes)

      renamed_count = 0
      for episode in episodes:
          self.on_episode_downloaded(episode)

          renamed_count += 1
          progress_indicator.on_message('%d / %d' % (renamed_count, number_of_episodes))
          progress_indicator.on_progress(renamed_count / number_of_episodes)
          if time.time() >= progress_indicator.next_update:
              progress_indicator.update_gui()
              self.gpodder.force_ui_update()
              if not progress_indicator.cancellable:
                  break

      progress_indicator.on_finished()
        
```

As for running it locally, I'm still facing issues with Dbus. How can I run with the fake-dbus module ?

**Comment by auouymous** [comment]
> Also, any reason for not using f-strings?

Because gpodder still supports python 3.5.


> As for running it locally, I'm still facing issues with Dbus. How can I run with the fake-dbus module ?

Try running `export PYTHONPATH=${PATH_TO_GPODDER_GIT}/tools/fake-dbus-module/` before starting gpodder.
