### ISSUE TITLE
Lower minimum episodes to download from 100 to 1

### ISSUE THREAD

**Issue by kwoot** [gpodder/gpodder#679]
At the moment my disc is burning after installing gpodder. I could import an opml file and now it turns out it is downloading 100 episodes from every podcast because that is the minimum I can set it to. This is waaaaay to much.

**Comment by mhussaincov** [comment]
hi,
interesting,
when you inport rss feeds via your .opml is a prompt not displayed
asking if you want to download the selected epesodes?
you could deselect all of them and go to every individual podcast then
select the epesodes you wish to download could you not?
curious?

On 26/09/2019, Jeroen Baten <notifications@github.com> wrote:
> At the moment my disc is burning after installing gpodder. I could import an
> opml file and now it turns out it is downloading 100 episodes from every
> podcast because that is the minimum I can set it to. This is waaaaay to
> much.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/gpodder/gpodder/issues/679


-- 
kind regards,
Majid Hussain

**Comment by kwoot** [comment]
I don't know. When I select gpodder -> preferences -> update: I can enter a number between 100 and 1000 in the widget "maximum number of episodes per podcast". Since I have some 30 podcasts to listen to, this means after installation it goes to download some 3000 episodes. A lot of that is really old material by now so I will never listen to that. I would suggest to have a minimum of 1 to start playing with gpodder and in real life I would probably use a value of 5 or so.

**Comment by elelay** [comment]
Hi, @mhussaincov is correct:
on a fresh install, 
 1. Import from OPML File presents you with a dialog to select podcasts
 2. then they are imported (no download yet)
 3. then a dialog is presented, letting you choose which episode you want to download.

At this point you can select a few, all, none, dismiss the dialog. It tells you how many will be downloaded and how big (bytes) this is.

The behaviour you describe is as if you had selected **Download Immediately** in the *Update* tab of the preferences dialog.

**Comment by joesmith222** [comment]
i think the dialog popup that shows up with what episodes are available will automatically start downloading if you hit the space key.   it has happened several times to me

**Comment by elelay** [comment]
I fixed the space-key effect, but kept the Enter shortcut, because I think it's a nice fast workflow when all presented episodes are acceptable to press Enter to start downloading (as press Escape to dismiss the dialog). Also it's not an irreversible change: one can select all downloads and cancel.

**Comment by elelay** [comment]
gPodder 3.10.15 has the focus change
