### ISSUE TITLE
should deleting an episode cancel it in the progress tab?

### ISSUE THREAD

**Issue by auouymous** [gpodder/gpodder#682]
Some youtube videos fail to download for various reasons, and often can't ever be downloaded with gpodder or youtube-dl. I delete the episode from gpodder after watching it on youtube, but the failed entry remains in the progress tab and must be cancelled. Should deleting the episode also remove the progress entry? Or is there valid reason to keep it there?

**Comment by auouymous** [comment]
I don't know if this is the best way to handle it, but it properly removes the entry from the progress tab when the episode is deleted.

```
diff --git a/src/gpodder/gtkui/main.py b/src/gpodder/gtkui/main.py
index 2427d1d2..b58c6fab 100644
--- a/src/gpodder/gtkui/main.py
+++ b/src/gpodder/gtkui/main.py
@@ -2739,6 +2739,8 @@ class gPodder(BuilderWidget, dbus.service.Object):
         if confirm and not self.show_confirmation(message, title):
             return False
 
+        self.on_item_cancel_download_activate(force=True)
+
         progress = ProgressIndicator(_('Deleting episodes'),
                 _('Please wait while episodes are deleted'),
                 parent=self.get_dialog_parent())
@@ -2973,7 +2975,7 @@ class gPodder(BuilderWidget, dbus.service.Object):
         # Executes after tasks have been registered
         util.idle_add(queue_tasks, new_tasks, queued_existing_task)
 
-    def cancel_task_list(self, tasks):
+    def cancel_task_list(self, tasks, force=False):
         if not tasks:
             return
 
@@ -2984,6 +2986,8 @@ class gPodder(BuilderWidget, dbus.service.Object):
                 task.status = task.CANCELLED
                 # Call run, so the partial file gets deleted
                 task.run()
+            elif force:
+                task.status = task.CANCELLED
 
         self.update_episode_list_icons([task.url for task in tasks])
         self.play_or_download()
@@ -3438,7 +3442,7 @@ class gPodder(BuilderWidget, dbus.service.Object):
         # Update the tab title and downloads list
         self.update_downloads_list()
 
-    def on_item_cancel_download_activate(self, *params):
+    def on_item_cancel_download_activate(self, *params, force=False):
         if self.wNotebook.get_current_page() == 0:
             selection = self.treeAvailable.get_selection()
             (model, paths) = selection.get_selected_rows()
@@ -3451,7 +3455,7 @@ class gPodder(BuilderWidget, dbus.service.Object):
             (model, paths) = selection.get_selected_rows()
             selected_tasks = [model.get_value(model.get_iter(path),
                     self.download_status_model.C_TASK) for path in paths]
-        self.cancel_task_list(selected_tasks)
+        self.cancel_task_list(selected_tasks, force=force)
 
     def on_btnCancelAll_clicked(self, widget, *args):
         self.cancel_task_list(self.download_tasks_seen)
```

**Comment by lb-d** [comment]
Do you get "Failed: Missing content from server" ?   I have seen that lately.

**Comment by auouymous** [comment]
Yes, it has been getting worse over the last year. I switched to the webm format yesterday hoping it will fix the missing content problem. But there are other reasons the download could fail: video removed, age-gated, contains copyrighted music, or a livestream in the distant future.

**Comment by lb-d** [comment]
Same here. Formats doesn't matter, I have tried different youtube-dl versions including the latest installed with pip. And are running a gpodder instance I pulled from git. But nothing changes anything. It's strange because it only affects some channels. Don't know what is going on.

**Comment by auouymous** [comment]
The problem is most likely with youtube and there really isn't much gpodder or youtube-dl can do about. The issue on youtube-dl suggested webm would work since the website uses it, but it too is failing in gpodder. We shouldn't talk about that problem here since this issue is for something else.

**Comment by elelay** [comment]
@auouymous seems good. Please provide a patch or PR.

**Comment by auouymous** [comment]
The patch works fine if the user deletes the episode. But the episode isn't removed from progress tab when it gets removed during an update by remove_unreachable_episodes(). I had the gPodder class add itself to gpodder.ui.gPodder and was able to find the download task in gpodder.ui.gPodder.download_tasks_seen and call gpodder.ui.gPodder.cancel_task_list(). Problem is that self.update_downloads_list() in cancel_task_list() causes gpodder to segfault, maybe because it is in a thread outside gtk's main loop?

Do you have any ideas how to handle this? Or should I just push a PR for user deletions and ignore feed updates for now?
