### ISSUE TITLE
Discoverable way to search feeds

### ISSUE THREAD

**Issue by shmabler** [gpodder/gpodder#685]
I'd like to be able to search the feeds I have subscribed to.

**Comment by elelay** [comment]
Focus the podcast list (mouse click) and start typing to search

**Comment by shmabler** [comment]
Oh, I didn't realize I could search like that. I can actually search the episodes pane like that too, which is the one I wanted to search. Thank you for explaining.

I wonder if that is the most user friendly way to search. This was not obvious to me. You also have to click, not just mouse-over. I am used to using control+f or seeing a permanent search/filter box and was using control+f with the RSS news reader Liferea which can also handle audio attachments, but is not specifically intended for podcasts and functions differently.

I also wonder if any other search features would be beneficial, like ability to search episode title separately from episode details.

Either way, I'm very glad there is search functionality.

**Comment by elelay** [comment]
- Discover podcasts should be moved to Ctrl-Shift-F or maybe Ctrl-D.
- either Ctrl-F should show the search field in Podcasts or Episodes (or add Ctrl-Shift-F for the other one).

**Comment by Nord-Licht** [comment]
This is one of the best hidden features I have ever not seen. I was also about to write a bug report about it, please make it more visible.

**Comment by huftis** [comment]
After *years* of using gPodder, I too accidently discovered this extremely useful feature (that I had actually been missing). I think it would be much more discoverable if an incremental search field was shown by *default* (or two search fields – one for the podcast list and one for the episode list).

**Comment by auouymous** [comment]
I run gpodder in a small window and having them always there would waste a lot of space. Perhaps a checkbox in the View menu to force them always on, and it could default to checked.

**Comment by elelay** [comment]
Trying to figure out how to permanently show search bars:
![double-search](https://user-images.githubusercontent.com/222469/78471297-80b98980-7730-11ea-908b-393d3fa1a87b.png)
Ain't that ugly? The one above podcasts is acceptable, but isn't it better to add Podcasts > Search (Ctrl-Shift-F) and Episodes > Search (Ctrl-F) menu items?

**Comment by huftis** [comment]
@elelay No, I actually think that looks quite good (and if there’s an option to hide the search bars, everyone should be happy).

Another option would be to put it in the toolbar (to the right), if that’s technically possible. That’s the way it’s implemented in the KDE/Plasma System Settings window (with the icon view layout). Then you would just have one search field, and the select pane would decide if it’s the podcasts or the episodes that are searched. But I prefer your mockup.

**Comment by elelay** [comment]
@huftis I'm still unsure it would be convenient, but I've added an option to always show search entries. They will stay at the bottom as they are now.

**Comment by elelay** [comment]
![always_search](https://user-images.githubusercontent.com/222469/78503284-fc81f900-7765-11ea-8449-af2ce4e4fc60.png)
