### ISSUE TITLE
gPodder shows empty panels in Podcasts and Progress tabs

### ISSUE THREAD

**Issue by DaveOJ1** [gpodder/gpodder#687]
I set up my installation a few months ago; I had 10 different podcasts added. Today, I noticed a podcast had downloaded very quickly, but didn't think anything of it and closed it.

When I opened gPodder soon after, I noticed the Podcasts and Progress tabs were completely empty. The Podcasts, Subscriptions, Episodes and Extras drop down menus are completely grayed out. None of the gPodder drop-down menu is not grayed out, but clicking any of the options there doesn't do anything.

I did a reinstall of gPodder as well, but that didn't change anything.

Here is what it looks like:
![gPodder screenshot](https://user-images.githubusercontent.com/56209414/66262507-f1daad00-e79e-11e9-864c-aac6136eb1ba.jpg)

**Comment by elelay** [comment]
Hi,
it looks like an exception is triggered when creating the UI.
Can you try running gPodder in debug mode, to gather more info about the issue ?
See [this link](https://gpodder.github.io/docs/windows.html#debugging-gpodder-on-windows).
Thanks,

**Comment by DaveOJ1** [comment]
Here's what it says when I run it in the command window:

C:\WINDOWS\System32>"C:\Program Files\gPodder\bin\gpodder-cmd.exe" -v
Calling SetDllDirectoryW(C:\Program Files\gPodder\bin)
Successfully SetDllDirectoryW
D: windows build; registry home = None
D: windows build; documents home = C:\Users\David\Documents\gPodder
1571181227.296889 [gpodder.log] DEBUG: ==== gPodder starts up (ui=gtk) ===
1571181227.484389 [gpodder.util] WARNING: html5lib not found, falling back to HTMLParser
1571181227.583998 [gpodder.registry] DEBUG: Registering download_url resolver: <function youtube_real_download_url at 0x02762c44>
1571181227.591808 [gpodder.registry] DEBUG: Registering download_url resolver: <function escapist_real_download_url at 0x02771344>
1571181227.605482 [gpodder.registry] DEBUG: Registering download_url resolver: <function vimeo_real_download_url at 0x0276202c>
1571181228.226573 [gpodder.sync] WARNING: Could not find gpod
1571181228.228525 [gpodder.sync] WARNING: Could not find eyed3.mp3
1571181228.496104 [gpodder.gtkui.shownotes] INFO: No WebKit2 gobject bindings, so no HTML shownotes

C:\WINDOWS\System32>

**Comment by elelay** [comment]
I hoped there would be an actual exception in the log. Unfortunately, there is none :-(
What is your windows version ?

**Comment by DaveOJ1** [comment]
I'm running the 32-bit version of Windows 10.

**Comment by elelay** [comment]
Closing due to no way to investigate
