### ISSUE TITLE
Please provide proxy support to GUI.

### ISSUE THREAD

**Issue by dhra** [gpodder/gpodder#689]
I know we can use a HTTP/HTTPS proxy server for downloading episodes and feeds. But is it possible to provide proxy support to GUI?

**Comment by elelay** [comment]
We try not to add too much contents in the GUI. Especially since this setting is not used by any gPodder code, but directly by [python library](https://docs.python.org/3.7/howto/urllib2.html#proxies).
Is there any reason not to set the http_proxy environment variable?

**Comment by dhra** [comment]
As you know this is a necessary feature in GUI, it makes gPodder more friendly, like Spotify proxy. I'll be happy if you add this feature to your future tasks.

**Comment by elelay** [comment]
Actually, I don't think that it's a necessary feature.
