### ISSUE TITLE
Mac OS X download folder environment variable help

### ISSUE THREAD

**Issue by KaaSerpent** [gpodder/gpodder#691]
I'm running Mac OS X Mojave 10.14.6. I read all the directions on how to direct gpodder to put the downloads in a different location. Then I spent quite a while re-learning unix enough to figure out how to make it permanent, or so I thought.

I THOUGHT I had it right, but when I start up gpodder, it still wants to put all the downloaded files in the default location, and there is not enough disk space.

Here is what I did.

I created a file called <code>.bash_profile</code> in my <code>~/kaa</code> folder.
Into that file, I added the following line:

<code>export GPODDER_DOWNLOAD_DIR=/Volumes/externdrivename/gpodderDownloads</code>

I then tested its permanence by starting several terminal apps and doing a printenv, and it was there in each of them.

I then rebooted my laptop and started gpodder. I had it subscribe to a single podcast. It put the files in the DEFAULT location, not in the one specified above.

The environment variable is still there:

<blockquote><code>MacPro:~ Kaa$ echo $GPODDER_DOWNLOAD_DIR
/Volumes/externdrivename/gpodderDownloads</code></blockquote>
 
What have I done wrong? I have about 100G of free space on my local drive, and I cannot have gpodder start downloading files because it will fill that up in no time. 

Please help.

**Comment by rwoodpecker** [comment]
Put the exports in the gPodder launcher file:
/Applications/gPodder.app/Contents/MacOS/_launcher

Save and relaunch and it should work.

**Comment by KaaSerpent** [comment]
Thank you!

Is there a plan to add the ability to set the download directory inside the app itself? That seems like a huge oversight.
