### ISSUE TITLE
gpodder maxemum number of epesodes per podcast could they be increesed from 1000 to a custom number?

### ISSUE THREAD

**Issue by mhussaincov** [gpodder/gpodder#692]
hi there,
would it be possible to have custom values for this?
you are able to set how many epesodes you would like?
past 1000?
i've got a podcast that has 3000 epesodes and I want to archive the audio content i hope this is possible?
thanks!
Majid Hussain

**Comment by elelay** [comment]
Hi,
you can edit Settings.json in the GPODDER_HOME to increase limit.episodes to any value you want.

**Comment by auouymous** [comment]
The limit.episodes value in "Preferences...Edit Config" is the same thing and easier to edit from within gpodder. But wouldn't it be even easier to adjust the min/max limits so this could be changed directly from the UI? This patch allows any value from 1 to a million. It also makes the value in limit.episodes show up in the UI, instead of displaying some other incorrect min/max limit for it.

```
diff --git a/share/gpodder/ui/gtk/gpodderpreferences.ui b/share/gpodder/ui/gtk/gpodderpreferences.ui
index 997dc636..cce5092d 100755
--- a/share/gpodder/ui/gtk/gpodderpreferences.ui
+++ b/share/gpodder/ui/gtk/gpodderpreferences.ui
@@ -2,8 +2,8 @@
 <!--*- mode: xml -*-->
 <interface>
   <object class="GtkAdjustment" id="adjustment_episode_limit">
-    <property name="upper">1000</property>
-    <property name="lower">100</property>
+    <property name="upper">1000000</property>
+    <property name="lower">1</property>
     <property name="page_increment">10</property>
     <property name="step_increment">10</property>
     <property name="page_size">0</property>
```

**Comment by elelay** [comment]
@auouymous good point about edit config.
There is an upper reasonable limit at 1000 episodes in the UI to prevent users from shooting themselves in the foot.

> It also makes the value in limit.episodes show up in the UI, instead of displaying some other incorrect min/max limit for it.

What do you mean by this ?

**Comment by auouymous** [comment]
The GtkAdjustment widget outside of edit config clamps the value between 100 and 1000. So any value set with edit config only displays properly when inside edit config.

**Comment by auouymous** [comment]
I was partially wrong, it displays correct values over upper bounds, it only clamps values below lower bounds.

**Comment by elelay** [comment]
So it works as expected, then.
