### ISSUE TITLE
macOS Catalina gpodder cannot access external folders and files

### ISSUE THREAD

**Issue by rwoodpecker** [gpodder/gpodder#698]
**Steps to reproduce:**

1. Change gpodder settings or data directory to point to an external drive e.g. /Volumes/NAS
2. Launch gpodder
3. gpodder will exit

**Result:**
```
Sandbox: python3(8382) System Policy: deny(1) file-read-data /Volumes/NAS/Podcasts/.gpodder/Logs
Violation:       System Policy: deny(1) file-read-data /Volumes/home/Podcasts/.gpodder/Logs 
Process:         python3 [8382]
Path:            /Applications/gPodder.app/Contents/MacOS/python3
Load Address:    0x101959000
Identifier:      python3
Version:         ??? (???)
Code Type:       x86_64 (Native)
Parent Process:  bash [8368]
Responsible:     /bin/sh [/Applications/gPodder.app/Contents/MacOS/_launcher]
User ID:         501
```

In short: there have been new security changes in Catalina whereby the user must approve the application's access to access folders. Usually a prompt will appear for the user to approve. There is no prompt with gpodder to do this and launching the application silently fails. **See https://github.com/duplicati/duplicati/issues/3957 for some more context/workaround on the issue.**

My workaround was to create an automator script to run shell script `/Applications/gPodder.app/Contents/MacOS/gpodder` - gpodder launches fine and can again access my settings and data folder on an external drive.

**Comment by elelay** [comment]
Thanks for the heads up!
Did you also change system preferences (Security and privacy > Privacy) to give the gPodder application full disk access (as in the screenshot in https://forum.duplicati.com/t/running-on-macos-catalina-beta/7347)? Or maybe there was a prompt and you accepted?

**Comment by rwoodpecker** [comment]
Giving gpodder full disk access had no effect and I've currently just removed it entirely from the access list. The first time I used my launcher it had a prompt which requested access to network volumes which I granted.

**Comment by elelay** [comment]
Hi @rwoodpecker,
I might have a workaround in a newer build.
Can you try to run https://72-2688640-gh.circle-artifacts.com/0/Users/distiller/project/_build/gPodder-base-4.1.0-9-gee6e874.zip ? It is a native launcher now, so you should be able to allow it external disk access.

**Comment by rwoodpecker** [comment]
Hi @elelay. That build is indeed working. Only issue I have is that there is no longer the _launcher file where I had exports to set gpodder's configuration & download location. I've also got these exports to my .bashrc but they don't seem to get picked up by GUI applications in OSX! urgh! So at the moment the only way I can open gpodder with the correct download/config location is to open it through terminal using the open command.

Is it possible to get these config options set with the new launcher?

**Comment by elelay** [comment]
Is creating a symbolic link acceptable? The advantage is that you have nothing to do on gPodder upgrades.
From a terminal:
`ln -s /Volumes/PATH/TO/WHERE/YOU/WANT "~/Library/Application Support/gPodder"

Or you can edit [gPodder.app/Contents/Resources/launcher.py line 111](https://github.com/gpodder/gpodder-osx-bundle/blob/native-launcher/misc/bundle/launcher.py#L111) to add `os.environ['GPODDER_HOME'] = '/Volumes/PATH/TO/WHERE/YOU/WANT' to set the environment variable before the call to `gpodder_home()`.

What is run now is:
 1. gPodder.app/Contents/MacOS/gpodder (native launcher)
 2. gPodder.app/Contents/Resources/launcher.py (python script to replace the shell script `_launcher`)
 3. gPodder.app/Contents/Resources/bin/gpodder (or another cmd like gpo)

**Comment by rwoodpecker** [comment]
Both of those tricks work. However, I also need to be able to specify a seperate download location. For neatness sake I put the config files under .gpodder in a Podcasts folder and the Podcasts are only visible. Is there a way I can also set the download folder?

Thanks

**Comment by elelay** [comment]
gPodder 3.10.12 has been released
