### ISSUE TITLE
Some downloads say "WARNING: Unknown external file"

### ISSUE THREAD

**Issue by citroboy** [gpodder/gpodder#705]
gPodder 3.10.11
Debian Testing

Some podcasts are successfully downloaded but the filenames don't make it into the database. When gPodder starts up the log says eg.:

[gpodder.model] WARNING: Unknown external file: /home/citroboy/gPodder/Downloads/Weekly Economics Podcast/Ep. 140 - Hostile Environment.mp3

The URL for that is http://feeds.podtrac.com/19WzVTx1_HfX

However, it looks normal in the GUI but when I try to play it (in audacious) it gets streamed instead of playing the file. This rather defeats the purpose of downloading.

I had a similar problem before which I fixed by removing the %U which had mysteriously appeared in the audacious command string. That is still gone but the problem has returned.

**Comment by auouymous** [comment]
I downloaded the episode and it played the local file after a restart. After downloading, does the episode play fine before you restart gpodder? Have you tried running gpodder with -v and looking for issues on the console? Does it commit when shutting down?

http://borg.qzx.com/files/gpodder-debug-extension.zip

That extension adds a debug option to the menu when you right click an episode (it outputs to console). The 'download_filename' value should match the file you have on disk, excluding the path.

**Comment by citroboy** [comment]
Pretty sure this was how it was before restart. I don't restart very often, though I did have to reboot the night before I downloaded. So I may have been running a new version of gPodder for the first time.

When I run with -v the only warnings are like the log I showed above. I downloaded 15 podcasts and they all acted like this. It does Commit when shutting down.

I said the GUI seemed normal, but I didn't notice that the new episode counter doesn't show in the left pane.

Debug output:
<gpodder.gtkui.model.GEpisode object at 0x7fb35462fe50>
id:  9518
url:  https://chtbl.com/track/G7D97/https://dts.podtrac.com/redirect.mp3/feeds.soundcloud.com/stream/711577573-weeklyeconomicspodcast-hostile-environment-how-immigrants-became-scapegoats.mp3
title:  Hostile Environment: how immigrants became scapegoats
file_size:  86490698
mime_type:  audio/mpeg
guid:  tag:soundcloud,2010:tracks/711577573
link:  https://soundcloud.com/weeklyeconomicspodcast/hostile-environment-how-immigrants-became-scapegoats
published:  1573552364
download_filename:  None
state:  0

I already established that download_filename was null by opening the db in a db browser.

$ ls -l ~/gPodder/Downloads/Weekly\ Economics\ Podcast
total 84920
-rw-r--r--  1 citroboy citroboy 86494042 Nov 15 16:09 'Ep. 140 - Hostile Environment.mp3'
-rw-rw-r--  1 citroboy citroboy   450177 Oct 23  2015  folder.jpg

**Comment by citroboy** [comment]
Debian Testing is in the process of expunging all traces of python2. I wonder if that might be germane.

**Comment by citroboy** [comment]
Hmm. Just tried downloading another podcast and it worked. Maybe it just needed restarting to sync up with some updates. I tend to update packages much more often than I restart things. I guess I'll enter the missing filenames into the db manually and look out for this in future.

**Comment by citroboy** [comment]
I did my weekly download on Friday, about 15 podcasts, and everything worked fine so I'll close this.
