### ISSUE TITLE
More and more youtube videos failing to download.

### ISSUE THREAD

**Issue by fhelwjhewqouywy** [gpodder/gpodder#710]
I'm using 3.10.11 on windows if that makes any difference.  And this has always been an occasional issue, with maybe one vid a week saying "Failed: Error: Cannot download video"  But, lately it's almost half the videos I try to get.  No connection between channels either, with some vids downloading fine and other just not at all.
Is YouTube screwing with their API again?  Is this because of the whole COPPA crap going on?  Or is it just a random problem on my end?

P.S.  Why the hell doesn't this program have a proper forum?  At least get a subreddit or something.

**Comment by fhelwjhewqouywy** [comment]
Thanks for ignoring my issue, that really helped.

**Comment by auouymous** [comment]
Being nice is a good way to not get your issue closed. I am working on a fix in https://github.com/gpodder/gpodder/issues/711.

**Comment by fhelwjhewqouywy** [comment]
This is the internet, that was me being nice.
