### ISSUE TITLE
Some channel tooltips have excessive blank space below description

### ISSUE THREAD

**Issue by auouymous** [gpodder/gpodder#715]
I don't know what causes it, but some channels (with short or long descriptions) can have tooltips as tall as my screen with most of the tooltip containing blank space below the description. The attach method for Table widget has been deprecated since 3.4 and Grid should be used instead. Is there a reason Table (or Grid) should be used instead of a Box?

http://borg.qzx.com/files/gpodder-715-use-box-instead-of-table-to-fix-size-of-channel-tooltips.patch

That patch replaces the Table with a Box and fixes the issue.

**Comment by elelay** [comment]
Merged, thanks!
This is old code, ported from pygtk. I've also replaced table with grid elsewhere in the code, but a vertical box is fine here.
