### ISSUE TITLE
quieter youtube-dl

### ISSUE THREAD

**Issue by elelay** [gpodder/gpodder#717]
It has been reported that youtube-dl console output is too verbose.

There should be a way to put it in quieter mode and only enable debug output when `gpodder -v`

**Comment by auouymous** [comment]
Pass "-q" to youtube-dl to eliminate all normal output. When `gpodder -v` is used, pass "-v" to youtube-dl instead of "-q", so youtube-dl would also be in verbose mode when gpodder is.

**Comment by auouymous** [comment]
I don't know how to detect verbose mode, but adding either of these in gPodderYoutubeDL __init__() will enable quiet or verbose mode in youtube-dl.

```
self._ydl_opts['quiet'] = True
self._ydl_opts['verbose'] = True
```

**Comment by elelay** [comment]
done, thanks
