### ISSUE TITLE
warning: internationalized messages should not contain the '\r' escape sequence

### ISSUE THREAD

**Issue by auouymous** [gpodder/gpodder#720]
Seven of the po files spam that message about 24 times when compiling gpodder. Removing the \r was approved in #713 and should be removed from the others as well.

**Comment by auouymous** [comment]
nl.po still contains a \r that appears to have been removed by the above commit but is somehow still in the source even though no future commits added it back.

**Comment by elelay** [comment]
removed it again :-)
