### ISSUE TITLE
Failed: Error: Cannot download video: - xxxxx

### ISSUE THREAD

**Issue by Ploddles** [gpodder/gpodder#721]
Where xxxx above is the name of the Youtube channel.

For the last few weeks gpodder has been unable to download the majority of its videos. There doesn't seem to be any pattern to the failure. One day it will happily download from one channel on Youtube but the next few days it fails on the same channel.

The failure rate seems to be about 90% but I can manually go to the Youtube channel and download the videos using the ClipGrab app.

The only recent updates to my system that I can think of are the Creative Cloud apps. I'm running Catalina 10.15.2 and gpodder is the only app not behaving.

I've tried all the usual rebooting, deleting and reinstalling the app etc but it is still failing at about the same rate.

Any help would be greatly appreciated. Thanks.

**Comment by auouymous** [comment]
Install youtube-dl and enable the youtube-dl extension in gpodder, or use the patch in #711.

**Comment by elelay** [comment]
Since you use the macOS app, no need to install anything more.
Go to gPodder's  Preferences > Extensions and enable youtube-dl. You should be able to download any yt video now.
https://gpodder.github.io/docs/extensions/youtubedl.html
