### ISSUE TITLE
Get duration for youtube episodes

### ISSUE THREAD

**Issue by auouymous** [gpodder/gpodder#723]
http://borg.qzx.com/files/gpodder-723-get-duration-for-youtube-episodes.patch

This patch requires #722 

It works when downloading with gpodder or the youtube-dl extension. The duration will appear at the start of a download with gpodder, or at the end of a download with youtube-dl extension. This is because it isn't sent in the RSS feed and must be queried during download for each format (and can actually be different for each format). The duration is sent as milliseconds and mplayer truncates (always rounds down), so I made gpodder do the same. But youtube-dl rounds the value (up or down) and returns it as seconds, so any episodes downloaded with youtube-dl might show as one second longer than what is shown in mplayer. I don't know if other video players round or truncate, but the gpodder code could round to match youtube-dl.

**Comment by elelay** [comment]
Great!
Can you change the attr YoutubeCustomDownload.episode to YoutubeCustomDownload._episode?

**Comment by auouymous** [comment]
Oops, done.

**Comment by elelay** [comment]
Thanks! Also make the code a bit more concise wouldn't hurt:

    duration = f['approxDurationMs'] if 'approxDurationMs' in f else None
    yield int(f['itag']), [f['url'], duration]

to (two occurences)

    yield int(f['itag']), [f['url'], f.get('approxDurationMs')]

and

    url = fmt_id_url_map[id][0]
    duration = fmt_id_url_map[id][1]

to

    url, duration = fmt_id_url_map[id]

**Comment by auouymous** [comment]
Done, thanks for those tips.

**Comment by elelay** [comment]
thanks
