### ISSUE TITLE
Editing what the "Stream" button does

### ISSUE THREAD

**Issue by predator8bit** [gpodder/gpodder#733]
Is it possible to make the Stream button do the same thing as the episode_website_context_menu.py extension, but instead of opening the url with a browser it'd do it with the media player? 

For example it'd run: "mpv site.url" and mpv would use youtube-dl to start playing the video/audio.

**Comment by elelay** [comment]
Hi,
no it's not possible at the moment. Next version of gPodder (due soon) will include a 'Download with youtube-dl' context-menu.
However you can try to modify your local install of gPodder to do what your want on Stream button clicks...

**Comment by predator8bit** [comment]
I was looking around in the files, but I couldn't make sense of them. I mostly only use bash scripts and nothing more when it comes to 'coding'.

**Comment by elelay** [comment]
You can replace `registry.download_url.resolve(config, self.url, self)` with `self.link` in this line: https://github.com/gpodder/gpodder/blob/master/src/gpodder/model.py#L504 and it will do what you want: launch the media player with the episode's website.

If you want to do this only with youtube episodes, you can check if url contains youtube:
```python
    def get_playback_url(self, config=None, allow_partial=False):
        """Local (or remote) playback/streaming filename/URL

        Returns either the local filename or a streaming URL that
        can be used to playback this episode.

        Also returns the filename of a partially downloaded file
        in case partial (preview) playback is desired.
        """
        url = self.local_filename(create=False)

        if (allow_partial and url is not None and
                os.path.exists(url + '.partial')):
            return url + '.partial'

        if url is None or not os.path.exists(url):
            if 'youtube' in self.link:
                url = self.link
            else:
                # FIXME: may custom downloaders provide the real url ?
                url = registry.download_url.resolve(config, self.url, self)
        return url
```

**Comment by predator8bit** [comment]
Thanks
