### ISSUE TITLE
Showing Offline-Channels/Pages

### ISSUE THREAD

**Issue by a3nima** [gpodder/gpodder#736]
With a certain amount of channels/pages in your subscriptions-list after a long period of time you might want to clean your list of those not existing anymore or have changed their URLs. When you check all channels for updates gpodder gives out a task-icon info about the channels that failed to update. This info does not show the channel-name and (afaik) does not go into some sort of log, it also disappears when you "mouse-over" it.
It would be handy to have the offline pages somehow marked in your list (on the sidebar inside gpodder gui) or a log with channel-name info about the offline/online status or at least to see the name of the ones that are offline somewhere. 
Right now keeping your subscriptions tidy means checking one after another if they're still working.
Maybe in some way this can be optimised. Something in this manner would be a good and user friendly feature in my opinion :) thanks!

**Comment by elelay** [comment]
Yes, something like what you describe would be great!
