### ISSUE TITLE
gpo crashes if error with UTF-8 filenames

### ISSUE THREAD

**Issue by JimH44** [gpodder/gpodder#740]
Hello,
The CLI version of gpodder, gpo, works nicely until it needs to report an error about a filename that contains UTF-8 characters. Here's the message:
```
1580502549.389791 [gpodder.model] WARNING: Unknown external file: /data/LT/Groups/Videos_non-English/Videos.FR/Introduction à l_outil liste de mots.srt
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 884, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 130: ordinal not in range(128)
Logged from file model.py, line 902
```
This is a warning about files in the destination folder that are not in the online source's RSS database. (The files in question are caption files with .srt extension.)
Warnings about filenames just with ascii characters don't cause the decode error.
The attached file shows the wider context.
[gpo-errors.txt](https://github.com/gpodder/gpodder/files/4141473/gpo-errors.txt)
I would also like to have a way of telling gpo not to complain about extra files in the destination folder, but that's a different question.

**Comment by auouymous** [comment]
Does it work if you use python 3.5 or greater? Less than 3.5 might not be supported.

**Comment by JimH44** [comment]
Thanks, @auouymous , for that suggestion. My python had been 2.7.
I got the latest python3 for my Lubuntu 18.04, and adjusted the symbolic links to point to 3.5, and then ran gpo again. This time I got an exception in the exception reporting mechanism:
```jim@langtran:~$ which python
/usr/bin/python
jim@langtran:~$ python --version
Python 3.5.2
jim@langtran:~$ ll /usr/bin/pyth*
lrwxrwxrwx 1 root root       7 Feb  9 12:37 /usr/bin/python -> python3*
lrwxrwxrwx 1 root root       9 Nov 23  2017 /usr/bin/python2 -> python2.7*
-rwxr-xr-x 1 root root 3640344 Oct  8 10:35 /usr/bin/python2.7*
lrwxrwxrwx 1 root root       9 Apr 10  2017 /usr/bin/python3 -> python3.5*
-rwxr-xr-x 2 root root 4772104 Oct  8 07:41 /usr/bin/python3.5*
-rwxr-xr-x 2 root root 4772104 Oct  8 07:41 /usr/bin/python3.5m*
lrwxrwxrwx 1 root root      10 Apr 10  2017 /usr/bin/python3m -> python3.5m*
jim@langtran:~$ gpo update
  File "/usr/bin/gpo", line 159
    except Exception, e:
                    ^
SyntaxError: invalid syntax
jim@langtran:~$
```
I have read that python3 is not backwards compatible, but I don't know the differences between them well enough to understand this syntax error.
Thanks again for your help,
Jim

**Comment by auouymous** [comment]
What version of gpodder do you have? That `except Exception, e:` doesn't exist in 3.10.13 and the two `except Exception as e:`'s that do exist aren't near line 159.

**Comment by JimH44** [comment]
Thanks again @auouymous , and sorry I didn't get back sooner.
How would I find out the version of /usr/bin/gpo? It doesn't respond to 
gpo --version

**Comment by auouymous** [comment]
It displays the version when you start it, a little problematic if it won't start.

I don't normally use gpo but I just ran it and got the same exception, with a different cause that prevented startup. What is the output of `locale |grep LANG`? Using `LANG=en_US.utf8 gpo` allowed it to startup for me.

**Comment by JimH44** [comment]
Thanks again.
My LANG variable was already set as yours above, and also exported.
I changed my /usr/bin/python link to point to python3 and downloaded the latest gpodder, which has a requirement for python3.
I also had to get various other dependencies and modify the program as described in another issue to get the local libraries included.
Then I got an error with gpodder not being able to find podcastparser.
I downloaded that and installed it, then the error moved on to mygpoclient.
I downloaded that, but it doesn't have any install.py file, so I don't know where to copy its files to.
Seems this latest release is a bit fragile :-(
Regards,
Jim

**Comment by elelay** [comment]
Hi,
have you followed instructions at https://gpodder.github.io/docs/run-from-git.html ?

    git clone https://github.com/gpodder/gpodder.git
    cd gpodder
    python3 tools/localdepends.py         # To install dependencies
    bin/gpodder                           # To directly launch from command line

It should have downloaded podcastparser and mygpoclient...

**Comment by JimH44** [comment]
Yes, I had followed the steps in "run from github", and I just ran localdepends.py again.
gpodder still doesn't run. It coesn't notice inside main() that sys has already been included in the global statements above:
```
jim@langtran:~/gpodder$ bin/gpodder
Traceback (most recent call last):
  File "bin/gpodder", line 159, in <module>
    main()
  File "bin/gpodder", line 53, in main
    gpodder_script = sys.argv[0]
UnboundLocalError: local variable 'sys' referenced before assignment
jim@langtran:~/gpodder$ ll /usr/bin/pyth*
lrwxrwxrwx 1 root root       7 Feb 13 22:51 /usr/bin/python -> python3*
lrwxrwxrwx 1 root root       9 Nov 23  2017 /usr/bin/python2 -> python2.7*
-rwxr-xr-x 1 root root 3640344 Oct  8 10:35 /usr/bin/python2.7*
lrwxrwxrwx 1 root root       9 Apr 10  2017 /usr/bin/python3 -> python3.5*
-rwxr-xr-x 2 root root 4772104 Oct  8 07:41 /usr/bin/python3.5*
-rwxr-xr-x 2 root root 4772104 Oct  8 07:41 /usr/bin/python3.5m*
lrwxrwxrwx 1 root root      10 Apr 10  2017 /usr/bin/python3m -> python3.5m*
```
Perhaps this should move to a new issue, because it is now about the latest version of gpodder, which requires python3.
I'll start one.
Thanks again for your help,
Jim

**Comment by elelay** [comment]
Closing this issue as it relates to the old python2 gpodder
