### ISSUE TITLE
ivoox feeds "broken"

### ISSUE THREAD

**Issue by jEsuSdA** [gpodder/gpodder#745]
Hi!
Recently, ivoox has changed a bit its way of working with some podcast. They made "ivoox originals".

The thing is that some podcast does not bring the full audio via ivoox feed.
The links to a ivoox podcast are not actually broken, but you can not obtain the full audio.

For example: you have an ivoox podcast subscription configured in gpodder. And suddently when you clic on an episode to play it, the player only reproduces the first minutes of the episode.

You have to go to the ivoox webpage to reproduce the entire episode.

It is any way to solve this issue.

Sendin you an exaple:

- RSS Feed: http://www.ivoox.com/podcast-economia-directa_fg_f130951_filtro_1.xml
- Episode: https://www.ivoox.com/ganadores-perdedores-del-salario-minimo-economia-audios-mp3_rf_46885995_1.html

You can see the episode last 1:39:09, but if you add the feed to your gpodder you only can listen to 12:19 minutes.

Thanks a lot!

**Comment by jEsuSdA** [comment]
Here, the complete mp3 link to the full episode. It was obtained via ivoox "download" link:

https://podcastcdn-23.ivoox.com/audio/5/9/9/5/ganadoresperdedoresdelsalariominimo-colectivoburbuja-ivoox46885995.mp3?secure=iC1Z5-6fHuSwv3gu30NXug==,1580843281

**Comment by auouymous** [comment]
The enclosure says the downloaded file should be 47593073 bytes, it is only 4868991. There is clearly an issue on their end and you should contact them about it.

**Comment by elelay** [comment]
Closing as an error in the feed.
