### ISSUE TITLE
gpodder menus are unresponsive

### ISSUE THREAD

**Issue by Richie87G** [gpodder/gpodder#746]
I was using 3.10.x and upon upgrade to 3.10.12 the rename_download extension stopped working.
I uninstalled gpodder and reinstalled 3.10.13 but now 
The only menu that shows options is the 1st one, "gpodder" see attached, the other options are all grey.
Even on the 1st menu that does show options clicking on any of them fails to do anything,  Even QUIT doesn't work. I have to close with the X at  the top right corner.

![gpodder](https://user-images.githubusercontent.com/47278921/74066265-d0940280-49c4-11ea-850f-e28aa04c873d.jpg)

**Comment by auouymous** [comment]
Start gpodder from a terminal to see if it is throwing an exception, or look in gPodder/Logs/.

You can also try renaming the gPodder directory and starting gpodder. If it works, your database is corrupt and will need to be fixed or restored from a backup.

**Comment by Richie87G** [comment]
Not sure what "Start gpodder from a terminal" means, but I can say:
Renaming the folder to gPodder2 and running the EXE I see the same failing result.
The logs do show errors, I thought I wiped out all old versions of gPodder before installing 3.10.13 but I missed the old downloads folder and databases. 
Wiped them out and now have a working gpodder again.
Thanks!
