### ISSUE TITLE
Plugin/setting for hiding right click menu entries

### ISSUE THREAD

**Issue by predator8bit** [gpodder/gpodder#747]
Is it possible to create a plugin that hides entries from the right-click menu? Specifically I'd like to hide the Stream, Download and Delete buttons/entries as I don't use them.

**Comment by elelay** [comment]
Hi,
you'll want to patch this method: https://github.com/gpodder/gpodder/blob/master/src/gpodder/gtkui/main.py#L1876

**Comment by predator8bit** [comment]
Thanks!
