### ISSUE TITLE
Frequent crashes

### ISSUE THREAD

**Issue by lcabrini** [gpodder/gpodder#748]
Of late, gPodder has been segfaulting frequently. I'm on Fedora 31, fully updated. Normally I use the gPodder from the official repositories, but I have also tried with the Flatpak version, with the same results.

It appears to happen randomly. Sometimes it happens within the first few minutes, sometimes gPodder can run for an hour before crashing. The crash can happen while I'm looking for new episodes, when downloading episodes, or simply by clicking on a podcast or on an episode.

I take it that a segfault indicates the error happens at a lower level (GLib, Gtk, or their python bindings). Is there anything I can do to figure out more? Should I report this to Fedora rather than here?

Apart from gPodder, I also use another application that uses Python and Gtk: Zim. However, this application does not crash.

It seems to happen more frequently as the number of Podcasts and/or episodes increases. (I tried removing ~/.gPodder and starting over), but I guess that could simply indicate that with more podcasts to process, the offending code is 

I'm a bit desperate to find a solution, because I use gPodder pretty much all the time. I have tried alternatives (Gnome Podcast, Vocal, CPod, etc), but only gPodder works the way I want a podcatcher to work. (Vocal would be #2, but it crashes way more than gPodder).

For reference, here is crash output. I don't think the messages before the segfault are related, but I could be wrong.

```
ConnectionResetError: [Errno 104] Connessione interrotta dal corrispondente
1581429866.889278 [gpodder.download] ERROR: Connessione interrotta dal corrispondente while downloading "02月10日 午前９時のNHKニュース": None
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gpodder/download.py", line 813, in run
    self.tempname, reporthook=self.status_updated)
  File "/usr/lib/python3.7/site-packages/gpodder/download.py", line 344, in retrieve_resume
    block = fp.read(min(size - read, bs))
  File "/usr/lib64/python3.7/tempfile.py", line 481, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/lib64/python3.7/http/client.py", line 457, in read
    n = self.readinto(b)
  File "/usr/lib64/python3.7/http/client.py", line 501, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib64/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connessione interrotta dal corrispondente
zsh: segmentation fault (core dumped)  gpodder
```

**Comment by elelay** [comment]
Sorry to hear that gPodder crashes a lot for you.
Could you try to produce a stacktrace from the core dump?
Maybe running `gdb --args python ./bin/gpodder` where you will get a stacktrace upon the crash?

**Comment by elelay** [comment]
What's the gPodder version in Fedora, by the way?

**Comment by lcabrini** [comment]
> Sorry to hear that gPodder crashes a lot for you.
> Could you try to produce a stacktrace from the core dump?
> Maybe running `gdb --args python ./bin/gpodder` where you will get a stacktrace upon the crash?

Sure, will do that.



> What's the gPodder version in Fedora, by the way?

3.10.13. Came in today. It has already crashed twice.

**Comment by lcabrini** [comment]
I haven't had any more crashes since my last comment, so I haven't been able to get a stack trace. That day there was a glib update. I suspect the issue may have been there. 

If it happens again, I think I should really report it to the Fedora team. As I said originally, I don't think this really is an issue with gPodder itself. But thanks a lot for wanting to help out! 

Sorry for being a little confused, but I reported this and it seems resolved. Am I supposed to close this issue myself, or?

**Comment by elelay** [comment]
Thanks for the update. I'm clossing the issue now.
