### ISSUE TITLE
Bug: gpodder can't support custom installation path

### ISSUE THREAD

**Issue by xmha97** [gpodder/gpodder#749]
Hello
I installed gpodder on `%LocalAppData%\gPodder`
But shortcut created for `%ProgramFiles(x86)%\gPodder`
![image](https://user-images.githubusercontent.com/23485114/74377752-6bac2400-4d99-11ea-9e0a-20d10949e341.png)
Please fix this bug.

**Comment by elelay** [comment]
Thanks for reporting! Also uninstall.exe is always created in the default location.

**Comment by elelay** [comment]
Next release will work correctly.
In the meantime, you can try latest build: https://ci.appveyor.com/project/elelay/gpodder/builds/30835893/artifacts
