### ISSUE TITLE
3.10.13 blocking errors, after run-from-git

### ISSUE THREAD

**Issue by JimH44** [gpodder/gpodder#755]
Hello,
Although previous versions of gpodder and gpo have been working pretty well, I have not been able to get 3.10.13 to run.
I upgraded my python from 2 to 3, as required by 2.10.13.
Then I did the steps in the run-from-git page.
I also ran the install script, and that copied gpodder etc to /usr/bin.
Whether I run gpodder from there or from ~/gpodder/bin, I still get some error that stops it running.
(By the way, I'm running on Lubuntu 16.04).
Here are the current errors:
```
jim@langtran:~/gpodder$ bin/gpodder
Traceback (most recent call last):
  File "bin/gpodder", line 159, in <module>
    main()
  File "bin/gpodder", line 53, in main
    gpodder_script = sys.argv[0]
UnboundLocalError: local variable 'sys' referenced before assignment
```
It seems python3 did not notice that sys had been included in the global section (line 35), because it then complained about sys being used within main().
Here is a listing of my python files:
```
jim@langtran:~/gpodder$ ll /usr/bin/pyth*
lrwxrwxrwx 1 root root       7 Feb 13 22:51 /usr/bin/python -> python3*
lrwxrwxrwx 1 root root       9 Nov 23  2017 /usr/bin/python2 -> python2.7*
-rwxr-xr-x 1 root root 3640344 Oct  8 10:35 /usr/bin/python2.7*
lrwxrwxrwx 1 root root       9 Apr 10  2017 /usr/bin/python3 -> python3.5*
-rwxr-xr-x 2 root root 4772104 Oct  8 07:41 /usr/bin/python3.5*
-rwxr-xr-x 2 root root 4772104 Oct  8 07:41 /usr/bin/python3.5m*
lrwxrwxrwx 1 root root      10 Apr 10  2017 /usr/bin/python3m -> python3.5m*
```
Also, when I try to run gpo from a script that was working well before, with the source of gpo set to
```
~jim/gpodder/bin/gpo
```
I get these errors:
```
html5lib not found, falling back to HTMLParser
Could not find gpod
Could not find eyed3.mp3
```
Do we need more items in tools/localdepends.py ?
Thanks for thinking about this,
Jim

**Comment by elelay** [comment]
This is really surprising, since I run `bin/gpodder` every day.
Are you sure there is no local change (`git status`)?

**Comment by auouymous** [comment]
Are you sure python is installed correctly?
```
#!/usr/bin/env python3
import sys
print('I am %s' % sys.argv[0])
```

Put that in a file, chmod it to 700, and then run it. Does it produce the same sys error?

The warnings about not finding gpod and eyed3 are harmless unless you need them (#756).

**Comment by elelay** [comment]
Closing as no response from OP.
