### ISSUE TITLE
Podcast download missing tags

### ISSUE THREAD

**Issue by rko31415** [gpodder/gpodder#760]
I used the same URL in iTunes and gPodder. For each episode, iTunes (yuch) fetched the podcast description %podcastdesc% and subtitle %subtitle% tags ... gPodder didn't.

You can try it yourself at: https://libwww.freelibrary.org/podcast/rss.cfm

I tried with Mutagen and not.

**Comment by elelay** [comment]
Thanks for reporting.
I've tried with gPodder master on Linux and here are the tags in the original last episode:
[orig.txt](https://github.com/gpodder/gpodder/files/4277863/orig.txt)
And now after dl and tagging by gPodder:
[new.txt](https://github.com/gpodder/gpodder/files/4277862/new.txt)
as given by mutagen-inspect
TIT2 has been replaced with the episode's description, TIT3 added with full description, a COMM has been added, also with the full description, TDRC=2020-02-28 12:44 has been added.

**Comment by elelay** [comment]
So it seems to work. Please reopen if you have more info.
