### ISSUE TITLE
Possible database corruption

### ISSUE THREAD

**Issue by Ahuka5656** [gpodder/gpodder#762]
This started with the indicator for unlistened podcasts not updating when new episodes were downloaded. Then it started redownloading old ones that I had marked as "Not New". I am guessing the database is corrupted, but how should I fix it?

Thank you

**Comment by auouymous** [comment]
You can try restoring the database from a backup and restarting gpodder. Or delete the database, import from a backup OPML file and restart gpodder. If no backups, try exporting to OPML, delete the database, and then import that OPML after restarting gpodder.

**Comment by Ahuka5656** [comment]
Thank you, I think that worked.
