### ISSUE TITLE
gpodder not downloading podcasts from RSS feed

### ISSUE THREAD

**Issue by geejaytee** [gpodder/gpodder#766]
I'm trying to subscribe to this feed:
https://anchor.fm/s/c9e17e8/podcast/rss
where all the enclosures are of the form:
https://anchor.fm/s/c9e17e8/podcast/play/10875005/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fproduction%2F2020-2-6%2F54984817-44100-2-cc40e55adf84b.mp3,
gpodder can see the episodes when adding the field and get the metadata, but does not download the file, returning a 404.

The unmangled URL https://d3ctxlq1ktw2nl.cloudfront.net/production/2020-2-6/54984817-44100-2-cc40e55adf84b.mp3 does lead to an audio file, however.

**Comment by auouymous** [comment]
That enclosure URL is a redirect to the real URL and both gpodder 3.10.13 and firefox handle it. I was able to download and play all episodes in that feed. Are you using 3.10.13? If so, could you provide a debug log?

**Comment by geejaytee** [comment]
No problem, I've been running Ubuntu 18.04 and an old version of gpodder. I've found a backport of the latest version for that version of Ubuntu and it's all running fine
