### ISSUE TITLE
Reporting download bug "Failed: I/O Error:..."

### ISSUE THREAD

**Issue by hallamjeff** [gpodder/gpodder#775]
I am reporting an issue which has come up downloading some otherwise very reliable feeds. The failed downloads all started occurring on the same day and are indicated within gPodder as per the screenshot. I've attached the headers from wireshark as per the wiki, for two of the failed download re-attempts. Note that my other 15+ feeds updated and downloaded without issue.

[gpodder_error_headers_2.txt](https://github.com/gpodder/gpodder/files/4467006/gpodder_error_headers_2.txt)
[gpodder_error_headers_1.txt](https://github.com/gpodder/gpodder/files/4467007/gpodder_error_headers_1.txt)
![gPodder_error_screenshot](https://user-images.githubusercontent.com/17209731/79078696-76732e80-7ce0-11ea-894e-6ae271f402fd.png)

**Comment by auouymous** [comment]
The problem is most likely with the feed and not gpodder, but please provide the feed URL, as we can't test anything without it.

**Comment by hallamjeff** [comment]
Doh! of course. Here you are (in the same order as the screenshot):

[The Way I Heard It](http://thewayiheardit.rsvmedia.com/rss/)
[Risky Business](http://risky.biz/feeds/risky-business)
[Fine Woodworking Live](http://shoptalklive.podcast.static.taunton.com/rss)

and the last error was from the same _The Way I Heard It_ podcast.

**Comment by auouymous** [comment]
All three feeds work fine for me. Your system most likely has temporary routing issues to those hosts.

**Comment by hallamjeff** [comment]
I'll look into it. Odd that it's only three out of ~20 podcasts though. Cheers.

**Comment by hallamjeff** [comment]
Closing the loop on this issue in case others encounter the same problem. As @auouymous suspected, the issue was with the use of DNSBL on my network, specifically using the "Blocklist.site Ads" list which had the CDN for several podcasts feeds designated as a source of ads.
