### ISSUE TITLE
how to delete the downloaded file, but not the episode listing?

### ISSUE THREAD

**Issue by deadformat** [gpodder/gpodder#777]
After listening to an episode, when I select "delete" it deletes both the audio file and the episode listing in gpodder.  

My preferred behavior is that the file is deleted but not the listing--I'd like to just mark it as played. 

In fact, I can't even delete the episode directly from the downloads folder, because the music/downloaded icon remains in gpodder as if the downloaded file is still there. 

I think this is new behavior, as I used to be able to delete the file without removing the episode.  

Am I missing or forgetting something?

Thanks.

**Comment by auouymous** [comment]
Select "all episodes" from view menu to see deleted episodes.

**Comment by deadformat** [comment]
That's what I had forgotten, thank you.
