### ISSUE TITLE
Gpodder gives error message "some podcasts couldn't be added to your list"

### ISSUE THREAD

**Issue by dharmabum59** [gpodder/gpodder#779]
Hi.  When trying to download a podcast on a Linux Mint 19.3 laptop, Gpodder app displays the following error message: " Some podcasts couldn't be added to your list: http://feeds.feedburner.com/MakeshiftStories: slice indices must be integers or None or have an_index_method." 
     I don't understand what that cryptic message means, so i can't solve this problem. 
Thanks for your help with this!

**Comment by elelay** [comment]
Hi,
the podcasts is added without issue for me. What version of gPodder do you have?

Please can you post the logs? Run `gpodder -v` from the command line and add makeshiftstories again. There should be a stacktrace on the console...

**Comment by dharmabum59** [comment]
Hello.  My Gpodder version is 3.10.1, and here's the information that was displayed after i entered the command "gpodder -v": scott@scott-HP-2000-Notebook-PC:~$ sudo gpodder -v

1587342287.807002 [gpodder.log] DEBUG: ==== gPodder starts up (ui=gtk) ===
1587342289.136526 [gpodder.util] WARNING: html5lib not found, falling back to HTMLParser
1587342289.602845 [gpodder.sync] WARNING: Could not find gpod
1587342289.603273 [gpodder.sync] WARNING: Could not find eyed3.mp3
1587342292.120886 [gpodder.extensions] DEBUG: Found extension "audio_converter" in /usr/share/gpodder/extensions/audio_converter.py
1587342292.153086 [gpodder.extensions] DEBUG: Found extension "concatenate_videos" in /usr/share/gpodder/extensions/concatenate_videos.py
1587342292.154231 [gpodder.extensions] DEBUG: Found extension "enqueue_in_mediaplayer" in /usr/share/gpodder/extensions/enqueue_in_mediaplayer.py
1587342292.206689 [gpodder.extensions] DEBUG: Found extension "episode_website_context_menu" in /usr/share/gpodder/extensions/episode_website_context_menu.py
1587342292.208054 [gpodder.extensions] DEBUG: Found extension "gtk_statusicon" in /usr/share/gpodder/extensions/gtk_statusicon.py
1587342292.251405 [gpodder.extensions] DEBUG: Found extension "minimize_on_start" in /usr/share/gpodder/extensions/minimize_on_start.py
1587342292.252685 [gpodder.extensions] DEBUG: Found extension "mpris-listener" in /usr/share/gpodder/extensions/mpris-listener.py
1587342292.307173 [gpodder.extensions] DEBUG: Found extension "normalize_audio" in /usr/share/gpodder/extensions/normalize_audio.py
1587342292.308675 [gpodder.extensions] DEBUG: Found extension "notification" in /usr/share/gpodder/extensions/notification.py
1587342292.475324 [gpodder.extensions] INFO: Module loaded: /usr/share/gpodder/extensions/notification.py
1587342292.503741 [gpodder.extensions] DEBUG: Found extension "notification-win32" in /usr/share/gpodder/extensions/notification-win32.py
1587342292.540865 [gpodder.extensions] DEBUG: Found extension "rename_download" in /usr/share/gpodder/extensions/rename_download.py
1587342292.542028 [gpodder.extensions] DEBUG: Found extension "rm_ogg_cover" in /usr/share/gpodder/extensions/rm_ogg_cover.py
1587342292.542854 [gpodder.extensions] DEBUG: Found extension "rockbox_convert2mp4" in /usr/share/gpodder/extensions/rockbox_convert2mp4.py
1587342292.574605 [gpodder.extensions] DEBUG: Found extension "rockbox_coverart" in /usr/share/gpodder/extensions/rockbox_coverart.py
1587342292.575824 [gpodder.extensions] DEBUG: Found extension "sonos" in /usr/share/gpodder/extensions/sonos.py
1587342292.576587 [gpodder.extensions] DEBUG: Found extension "tagging" in /usr/share/gpodder/extensions/tagging.py
1587342292.619123 [gpodder.extensions] DEBUG: Found extension "taskbar_progress" in /usr/share/gpodder/extensions/taskbar_progress.py
1587342292.620567 [gpodder.extensions] DEBUG: Found extension "ted_subtitles" in /usr/share/gpodder/extensions/ted_subtitles.py
1587342292.663776 [gpodder.extensions] DEBUG: Found extension "ubuntu_appindicator" in /usr/share/gpodder/extensions/ubuntu_appindicator.py
1587342292.665194 [gpodder.extensions] DEBUG: Found extension "ubuntu_unity" in /usr/share/gpodder/extensions/ubuntu_unity.py
1587342292.665958 [gpodder.extensions] DEBUG: Found extension "update_feeds_on_startup" in /usr/share/gpodder/extensions/update_feeds_on_startup.py
1587342292.708337 [gpodder.extensions] DEBUG: Found extension "video_converter" in /usr/share/gpodder/extensions/video_converter.py
1587342296.934115 [gpodder.dbsqlite] INFO: Loading podcasts
1587342297.015841 [gpodder.dbsqlite] DEBUG: Database opened.
1587342297.016390 [gpodder.dbsqlite] INFO: Loading episodes for podcast 1
1587342297.050426 [gpodder.dbsqlite] INFO: Loading episodes for podcast 2
1587342297.067631 [gpodder.dbsqlite] INFO: Loading episodes for podcast 3
1587342297.088285 [gpodder.dbsqlite] INFO: Loading episodes for podcast 11
1587342297.091727 [gpodder.dbsqlite] INFO: Loading episodes for podcast 14
1587342297.130784 [gpodder.my] INFO: Reloading settings.
1587342297.131713 [gpodder.util] DEBUG: run_in_background: <bound method UserAppsReader.read of <gpodder.gtkui.desktopfile.UserAppsReader object at 0x7f3ae0096908>> (False)
1587342297.305699 [gpodder.util] DEBUG: run_in_background: <bound method gPodder.find_partial_downloads of <gpodder.gtkui.main.gPodder at /gui at 0x7f3ae895cc18>> (False)
1587342297.306634 [gpodder.gtkui.main] DEBUG: Setting up auto update timer with interval 720.
...Note: now, after using the commmand gpodder -v, I'm able to add "MakeShift Stories".
Thank you very much!
...dharmabum59...

**Comment by elelay** [comment]
Cool!
Note that running `gpodder -v` doesn't increase the chance of success. I think there was a network issue that got resolved.
