### ISSUE TITLE
Feature Request: only create individual podcast download folder when new podcast actually received

### ISSUE THREAD

**Issue by pgchase43228** [gpodder/gpodder#780]
Feature Request: only create individual podcast download folder when new podcast actually received

Didn't find anything like this in search.
I still use Winamp(!) because it's a good podcast downloader, mostly, although some URL's won't work with it. I'm using gPodder because, unlike Winamp, gPodder is being actively maintained. One nice thing about Winamp is I can delete all the individual podcast download folders when I'm done, and going forward Winamp will only create those folders that actually have new podcasts which makes it easier when I go to the main download folder. I can see at a glance what's new since I last cleared everything out. With gPodder, every individual podcast download folder is recreated when the program starts every time whether there's anything new or not, partly because it's including the podcast album art. (Sub-request: need a way to turn that off.) This creates a lot of clutter if we have a lot of podcasts subscriptions. I can, however, for now, observe the Date Modified for each gPodder download folder, and that gives a clue if there's anything new, besides, obviously just looking at the gPodder interface...

**Comment by elelay** [comment]
This is pretty much inherent to how gPodder operates, allowing to
 - store podcast art
 - recover episodes downloaded externally by scanning the podcast's folder

Maybe you could use the Sync function, even if it results in a copy?

You could also try to modify gPodder to not create folders and not manager podcast art. Maybe it's not that hard if you're willing to break some functionalities you don't use?
