### ISSUE TITLE
MKV Videos Aren't Downloaded

### ISSUE THREAD

**Issue by ChrisMTheMan** [gpodder/gpodder#785]
GPodder never downloads MKV videos.

**Comment by elelay** [comment]
Example feed please

**Comment by ChrisMTheMan** [comment]
https://www.youtube.com/user/FreeDocumentary
https://www.youtube.com/channel/UCctuj_C9POmIHS4CkojVD1g
https://www.youtube.com/channel/UCBo9TLJiZ5HI5CXFsCxOhmA
https://www.youtube.com/channel/UCaJ_xrKTkBWMNbc8G-2SIwA

In all 4 of these cases, higher quality MKV files are bypassed in favor of lower quality MP4 videos.  I have a few more examples if you need them.  Thank you for taking a look.

**Comment by auouymous** [comment]
Gpodder can't combine audio and video formats (adaptive formats) and 22 (720p) is the highest quality format youtube offers. They used to offer more and may still offer them on some old videos.

https://github.com/gpodder/gpodder/blob/master/src/gpodder/youtube.py#L42

That lists a few adaptive formats (the adaptive format for 22 is '136+140') that can be used by the youtube-dl extension when the primary formats aren't available. Running `youtube-dl -F <url>` from the command line will display a list of all formats, and the adaptive formats say "audio only" or "video only". Not all videos will have all formats, they only offer up to the quality provided by the creator. The formats for one of the videos you gave has the following formats.

```
249          webm       audio only tiny   57k , opus @ 50k (48000Hz), 8.80MiB
250          webm       audio only tiny   74k , opus @ 70k (48000Hz), 11.59MiB
140          m4a        audio only tiny  131k , m4a_dash container, mp4a.40.2@128k (44100Hz), 22.44MiB
251          webm       audio only tiny  145k , opus @160k (48000Hz), 22.79MiB
278          webm       256x144    144p   98k , webm container, vp9, 25fps, video only, 13.06MiB
160          mp4        256x144    144p  118k , avc1.4d400c, 25fps, video only, 7.68MiB
242          webm       426x240    240p  205k , vp9, 25fps, video only, 18.48MiB
133          mp4        426x240    240p  252k , avc1.4d4015, 25fps, video only, 16.01MiB
243          webm       640x360    360p  415k , vp9, 25fps, video only, 38.16MiB
134          mp4        640x360    360p  632k , avc1.4d401e, 25fps, video only, 31.02MiB
244          webm       854x480    480p  762k , vp9, 25fps, video only, 66.63MiB
135          mp4        854x480    480p 1061k , avc1.4d401e, 25fps, video only, 53.28MiB
136          mp4        1280x720   720p 1502k , avc1.4d401f, 25fps, video only, 92.95MiB
247          webm       1280x720   720p 1533k , vp9, 25fps, video only, 127.57MiB
248          webm       1920x1080  1080p 2653k , vp9, 25fps, video only, 247.50MiB
137          mp4        1920x1080  1080p 4932k , avc1.640028, 25fps, video only, 319.89MiB
18           mp4        640x360    360p  500k , avc1.42001E, mp4a.40.2@ 96k (44100Hz), 86.76MiB
22           mp4        1280x720   720p  665k , avc1.64001F, mp4a.40.2@192k (44100Hz) (best)
```

The `youtube.preferred_fmt_ids` config option allows you to specify your own. It overrides the default format list, so you need to specify all formats you want, in the order you want them. Feel free to send a PR or post here with any adaptive formats for the higher quality components. 

But as for MKV, youtube-dl only produces MP4 and WEBM containers.

**Comment by ChrisMTheMan** [comment]
Thank you for your reply.  I'm not sure I understood all of that because I'm not very video savvy.  Other tools such as 4kVideoDownloader or VideoDownloadHelper show MKV as an available format for these videos.  How are they doing that if it isn't available natively on YouTube?  Are they combining the audio and video only formats itself?

Specifically, this video comes up in both tools I mentioned with an MKV download choice that is higher resolution than the available MP4.  https://www.youtube.com/watch?v=KOKH3-PplV4

**Comment by ChrisMTheMan** [comment]
Another good example is this link:  https://www.youtube.com/watch?v=cSRpNw_BY48

GPodder downloads a 640x310 MP4 when a much higher resolution is available.  Using youtube-dl -F {url} shows a 1920x932 MP4 is available.  Why is GPodder skipping the higher resolution file?

**Comment by ChrisMTheMan** [comment]
auouymous - I think I'm beginning to understand what you were saying about the audio and video only formats.  For the last link I posted, what would I put in youtube.preferred_fmt_ids?

**Comment by auouymous** [comment]
That last link only contains a single format usable by gpodder, format 18 (640x310).

Use 248+251 for webm and 137+140 for mp4 to get 1080p videos. But you need to enable the youtube-dl extension and either let it download all youtube videos or manually select "download with youtube-dl" from the episode menu. Also add some fallback formats for videos that lack 1080p, so something like "137+140, 248+251, 22,136+140,18,134+140,43".

I don't know if it will work with the youtube-dl extension, but youtube-dl itself supports "bestvideo+bestaudio". That single format would give you the best for any given video and not need fallback formats. Of course, it will also give you an 8k video if available, so manually selecting formats is better unless you actually want 8k.

**Comment by ChrisMTheMan** [comment]
As a follow up, I experimented with the numeric string that auouymous provided and it seemed to work.  I added more, higher resolutions and that seemed to work too.  Finally, "bestvideo+bestaudio" also appears to be working so it looks like the youtube-dl extension support it.

Thank you all for taking a look at this.
