### ISSUE TITLE
Filtering not working

### ISSUE THREAD

**Issue by tordenflesk** [gpodder/gpodder#789]
https://i.imgur.com/A6Tpk3v.png
As you can see, the Destillert episode still gets downloaded.

I download using a scheduled task in Windows:
gpo.exe update
gpo.exe download

**Comment by auouymous** [comment]
What is the url for that feed?

**Comment by tordenflesk** [comment]
https://api.p4.no/podcast/rss/pid/330

**Comment by auouymous** [comment]
Is there any whitespace before or after the word?

If you mark a deleted destillert episode as new and then click the "filter now" button, does it unmark the episode?

**Comment by tordenflesk** [comment]
No whitespace, 'Filter Episodes Now' does not remove the 'New' check-mark on old episodes.

**Comment by auouymous** [comment]
Do you have any other working filters? Does it work if you check regular expression?

**Comment by tordenflesk** [comment]
No other filters, checking 'regular expression' makes no change.

**Comment by auouymous** [comment]
Do the logs indicate any issues related to filtering?

**Comment by tordenflesk** [comment]
Only errors are:
2020-04-26 16:46:38,334 [gpodder.sync] WARNING: Could not find gpod
2020-04-26 16:46:38,334 [gpodder.sync] WARNING: Could not find eyed3.mp3

**Comment by auouymous** [comment]
I don't have windows to test if this is a problem with the windows build. Another problem, even if filtering worked for you, is that the filter extension is gtk-only, meaning it probably won't load in gpo.

@elelay What needs to be done to make it work in gpo as well? Would simply adding 'cli' make filters added via gtk work in gpo?

**Comment by elelay** [comment]
yes, that should do the trick.

**Comment by auouymous** [comment]
It doesn't fix the issue with filter extension not working on windows (or just your windows install), but #795 allows the filter extension to load and filter channels updated with gpo.

**Comment by tordenflesk** [comment]
Yes, I think it works with gpo now. when i launch full gpodder the "new" check-box is unchecked for the latest "destillert" and gpo doesn't download it.

**Comment by auouymous** [comment]
Are you still running a release version of gpodder? And the filter extension is working fine in the GUI? Updating in gpo won't load the filter extension unless you install a pre-release that contains the 795 patch.

https://ci.appveyor.com/project/elelay/gpodder/build/artifacts

**Comment by tordenflesk** [comment]
I just replaced filter.py in the release version.

**Comment by elelay** [comment]
The filter extension works in gpo as of 3.10.16
