### ISSUE TITLE
Request - Can there be a dark mode? 

### ISSUE THREAD

**Issue by MrPointyFinger** [gpodder/gpodder#792]
Request - Can there be a dark mode? 

That's all I'm asking for. I have bad eyesight and constant white screens do my head in. 

Would you mind putting that in please? 

Thank you. 

MrPointyFinger

**Comment by auouymous** [comment]
Why can't you use a dark gtk3 theme? I have frequent headaches and use a dark gtk theme. Gpodder uses the same theme as any other gtk3 app.

**Comment by ruharen** [comment]
> 
> 
> Why can't you use a dark gtk3 theme? I have frequent headaches and use a dark gtk theme. Gpodder uses the same theme as any other gtk3 app.

Is this possible on Windows?

**Comment by auouymous** [comment]
Yes, see https://stackoverflow.com/a/39041558.

**Comment by ruharen** [comment]
Thanks!
I looked myself and found this example from another project that was also useful: https://github.com/shoes/shoes3/wiki/Changing-Gtk-theme-on-Windows

**Comment by ruharen** [comment]
Example on my laptop:
![imagen](https://user-images.githubusercontent.com/2373634/80949152-bf0b9c80-8df3-11ea-8234-7000711dc835.png)
Theme: https://www.gnome-look.org/p/1316887/

I only wish I could change the icons a little too, but this is pretty good :)

**Comment by auouymous** [comment]
You can also change the icon theme gtk uses.

**Comment by elelay** [comment]
I've update the documentation on https://gpodder.github.io/docs/windows.html

**Comment by ruharen** [comment]
After upgrading to new version of gpodder on Windows I lost the theme I previously set...
I guess this was because the installerperformed an uninstallation before the actual installation.
I don't know if this can be avoided somehow or if I need to set the theme differently.

I switched to use `gtk-application-prefer-dark-theme = true` and will see if that works when a newer version appears.

**Comment by elelay** [comment]
Cool

**Comment by omgwtfbbqpls** [comment]
What an utterly crude solution. 
I added `gtk-application-prefer-dark-theme = true` and `gtk-theme-name = whatever_theme` to settings.ini, made a `*username*.theme` folder in `C:\Users`, extracted and moved the "whatever_theme" folder to `C:\Users\*username*.theme`, and it still doesn't work.
Why isn't there an easier way?

**Comment by xthursdayx** [comment]
Is it possible to do this while running gPodder from source on Linux?

**Comment by auouymous** [comment]
@xthursdayx You can change `/etc/gtk-3.0/settings.ini` or `~/.config/gtk-3.0/settings.ini`.

```
[Settings]
gtk-application-prefer-dark-theme = true
gtk-theme-name = Adwaita
```

It is also possible to set the theme when running gpodder.

```
GTK_THEME=Adwaita gpodder

GTK_THEME=Adwaita-dark gpodder
```

If Windows and Mac users can set an environment variable in the icon, it might be easier than adding the settings.ini changes after every release. And GTK_THEME should also work with the flatpak build if it doesn't pick up the settings.ini.

**Comment by xthursdayx** [comment]
Thanks a lot! Adding the settings to '~/.config/gtk-3.0/settings.ini' did the trick.
