### ISSUE TITLE
gpo error Could not find gpod

### ISSUE THREAD

**Issue by JimH44** [gpodder/gpodder#799]
The Linux command line tool "gpo" produces the error "Could not find gpod", like this:
```
Storing data in /data/LT/gpo (GPODDER_HOME is set)
Storing downloads in /data/LT/Groups/Videos_non-English (GPODDER_DOWNLOAD_DIR is set)
Could not find gpod
```
I'm running Lubuntu 18.04, and the gpodder version that installed gpo is 3.10.15, which I got with "Install from git".

I have searched for code that might be producing this error, but haven't been able to find it.

Can you help, please.

**Comment by auouymous** [comment]
It is an optional feature and gpodder works fine without it, unless you need the feature it provides. That and eyed3 really need better messages to indicate they are optional features. They should also only write those warnings to the log, and not the console.

**Comment by JimH44** [comment]
Thanks, auouymous.

Can you please point me to the documentation that describes what gpod and eyed3 do, and will you change the error messages and send them only to the log as you suggested?

**Comment by auouymous** [comment]
The eyed3.mp3 module is only used during syncing if mplayer is not installed. I have a PR almost ready to fix the warnings for mplayer/eyed3.mp3 track length detection.

I don't yet know what the gpod module does, but it has something to do with syncing as well. None of this matters if you don't sync to an ipod or mp3 device.

**Comment by auouymous** [comment]
The gpod module is for syncing with an iPod device.

**Comment by JimH44** [comment]
Very helpful, @auouymous , thankyou.
