### ISSUE TITLE
Request option to avoid "WARNING: Unknown external file"

### ISSUE THREAD

**Issue by JimH44** [gpodder/gpodder#800]
I support a software distribution system for people with poor internet connections working in language development. When they are in town they update from our repository, then use the results off-line back in the village.

We need to keep subtitle files in the same folders as video files that I get from Vimeo with the command-line version of gpodder, "gpo".

This all works, but gpo complains about the subtitle files in the destination folder, because they are not listed in the RSS file from vimeo.com.

Could we please have a command line argument for gpo to ask it not to complain about extra files in the folder listed in GPODDER_DOWNLOAD_DIR. I would suggest -i for "ignore unknown external files"

Thanks for considering this feature request.

**Comment by auouymous** [comment]
That PR would indirectly solve your problem by eliminating all warnings.

**Comment by JimH44** [comment]
Thanks, @auouymous , I look forward to that option becoming available.

**Comment by JimH44** [comment]
Thanks, it works nicely.
