### ISSUE TITLE
gpo update fails on windows 10

### ISSUE THREAD

**Issue by markifi** [gpodder/gpodder#801]
any idea why this doesn't work?

here:
https://pastebin.com/raw/bRZbDawd

I just switched to windows 10 for the first time, it was working fine in 8.1
when I gpo update from the command line, it fails. when I do gpo update from powershell, it works.
not sure about the error messages

**Comment by elelay** [comment]
As seen in the first log line each time:
 - from powershell it sets the dll directory to gpodder's bin directory
 - from cmd it sets the dll directory to current directory

Maybe you have another version of python or openssl dlls in your path, breaking gPodder's python code.

From cmd, cd to `C:\Program Files (x86)\gPodder\bin` before calling gpo update and it should work.

**Comment by markifi** [comment]
Thank you for pointing that out, it works now. I'm an idiot!

**Comment by elelay** [comment]
Don't worry :-)
