### ISSUE TITLE
Adding podcast files that don't appear in the subscription list

### ISSUE THREAD

**Issue by Nrgreen3** [gpodder/gpodder#809]
Sorry if this is in the wrong place. I'm looking to add old podcast files to a subscription stream that have release dates previous to what auto-populates when you subscribe. 

For example, This American Life only goes back 7 episodes, but I have 15 previously un-listened to episodes I want to add into the feed. How do I do this please?

Thanks,

**Comment by Nrgreen3** [comment]
To be clear, I have the actual files, just am not sure how to get them into the software.

**Comment by auouymous** [comment]
That isn't possible. It is a highly requested feature and something I want, but haven't had time to write yet.

**Comment by Nrgreen3** [comment]
Too bad, but I understand. Thanks for the info.
