### ISSUE TITLE
iOS 13.4.1 on iPod Touch Gen 7

### ISSUE THREAD

**Issue by Nrgreen3** [gpodder/gpodder#810]
I'm trying to be able to use the above device on gPodder for podcasts (using Windows). I've read about jailbreaking on Hexxa or using the newest Checkra1n, but was unsure about the effectiveness of this.

Would this work then following the provided instructions afterwards?
https://gpodder.github.io/docs/ipod-touch.html 

Many thanks for the help.

**Comment by Nrgreen3** [comment]
I was also playing with some software called iExplorer in an attempt to mount the iPod for use with gPodder, but didn't have immediate success. Curious if anyone knows about its potential for this. https://macroplant.com/iexplorer

**Comment by elelay** [comment]
good question: never having owned an ipod I can-t help you there...
