### ISSUE TITLE
Speed of older vs newer version(s)?

### ISSUE THREAD

**Issue by a3nima** [gpodder/gpodder#811]
I've noticed that version 3.10.15 needs far more time to refresh all channels on my subcriptions list (mostly youtube) than version 3.10.7. I would like to use the new features that have been added and wondered if there might be a fix or an option that can be used to have the same speed (or faster ;) ) like in the older version?

**Comment by auouymous** [comment]
Are you using youtube-dl to manage channels? Try unchecking the `manage_channel` option in edit config. It lets you access more episodes, but also requires more time to check them. Using youtube-dl to manage channels is only needed right after subscribing to a new channel (and you want all episodes), if you infrequently update or a channel releases more than 20 episodes a day.

The `manage_downloads` option will use youtube-dl to download each episode, and is only needed if you want DRM content or formats other than 720p MP4 and 360p MP4. I have both options unchecked and use the `download with youtube-dl` menu option when gpodder is unable to download an episode.

**Comment by a3nima** [comment]
I haven't activated anything. It's the process to check all channels for new episodes that was slower with the newer version.

**Comment by auouymous** [comment]
Did you verify the youtube-dl extension is not enabled?

If it isn't, please post a debug log that contains a full update of all channels.

**Comment by a3nima** [comment]
yt-dl extension is not enabled and the log does not show anything special only the errors about channels that are not online anymore.

**Comment by auouymous** [comment]
A debug log would show a timestamp when each channel was updated. There are several update steps per channel, but they average 1-2 seconds for me (without youtube-dl). You can compare the before and after debug logs to see which step is taking longer. It is also possible the before and after times are similar but one or more channels are just taking longer than others to update.
