### ISSUE TITLE
Ctrl-q does not quit

### ISSUE THREAD

**Issue by wdenton** [gpodder/gpodder#815]
The latest revision (cbb5104185f1c9d7a3e54fdb95088cbe3584d472) stopped Ctrl-q from quitting (at least for me, on Ubuntu 18.04).  I checked out the previous version, and there Ctrl-q quits.  Back to master, it doesn't.  

I don't have any idea where the problem might be, but let me say gPodder is great!

**Comment by auouymous** [comment]
The CSD app menu lacks all keyboard accelerators: ctrl-p for preferences and ctrl-q for quit. You can launch gpodder with `GTK_CSD=0 gpodder` to get the old interface until this is fixed.

**Comment by elelay** [comment]
is it fixable?

**Comment by auouymous** [comment]
It looks like the CSD app menu uses the same app menu as the non-CSD interface. I'd imagine CSD app menus support accelerators, but maybe something wasn't initialized properly causing it to not add them. @thp Do you know?

You could always comment out `self.want_headerbar` and set it to false if not fixed before next release.

**Comment by thp** [comment]
Probably we need to get an accel group from somewhere and then add it with:
[Gtk.Window.add_accel_group()](https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Window.html#Gtk.Window.add_accel_group)

**Comment by elelay** [comment]
This is fixed in master (by re-parsing the xml menu definition)...

**Comment by auouymous** [comment]
The accelerators now work for me with CSD and without it, so the commit didn't break anything. Do you have other CSD apps and do they display accelerators in the CSD app menu? The lack of visible accelerators reduces their discoverability.

**Comment by elelay** [comment]
gPodder 3.10.16 is out.

**Comment by elelay** [comment]
> The lack of visible accelerators reduces their discoverability.
It's a limitation of gtk3 but should be fixed in [gtk4](https://gitlab.gnome.org/GNOME/gtk/-/issues/903)
