### ISSUE TITLE
Size of the episode detail panel

### ISSUE THREAD

**Issue by lmjst** [gpodder/gpodder#819]
Hi,
I'm on Linux and the size of the episode detail panel is too large. Text is not wrapped. Also the police is courier and very small so not easily legible.
I couldn't  find a way to correct this.
Thanks

**Comment by elelay** [comment]
Thanks for reporting!

Can you add a screenshot, please?

**Comment by lmjst** [comment]
I close this as this is not a gpodder issue : the format of the description of the episode depends on the provider : sometimes html, sometimes txt, sometimes crap...
Thanks for your response!
