### ISSUE TITLE
Shortcut key conflict with version 3.10.16

### ISSUE THREAD

**Issue by oldpink** [gpodder/gpodder#830]
I found that there is a conflict with the shortcut key combination for "Discover new podcasts" (under the "Subscriptions" menu bar section) and "Episode descriptions" (under the "View" menu bar section), both of which are bound to Ctrl+D.
I'm certain that "Episode descriptions" was the one originally activated with Ctrl+D, at least with 3.10.5 and (without me going to the trouble of looking back at the others) several revisions back.
I modified the source code, changing "Discover new podcasts" to use Ctrl+I to get around this conflict, but I still wanted to let you know about it because I'm certain that this was a mistake, albeit a very minor one.
Again, thank you so much for maintaining what I still consider the best podcast client with the most understandable interface out there.
Here is the patch that I made up, verified as working after rebuilding with it:
[gpodder_ctrl+i.patch.txt](https://github.com/gpodder/gpodder/files/4839854/gpodder_ctrl%2Bi.patch.txt)

**Comment by auouymous** [comment]
You are correct, https://github.com/gpodder/gpodder/commit/ff8582d6dd7ec1e23f3df4c7759209202655b22e#diff-19e4d0e05f05f0125173b1ed7501951dR71 changed it from ctrl-f to ctrl-d. I don't see a reason why `Discover new podcasts` needs a shortcut, would someone use that feature a lot? (This was my first time clicking that menu option)

**Comment by elelay** [comment]
Yeah, no need for a discover new podcasts shortcut.
Thanks!
