### ISSUE TITLE
youtube-dl download with dollar symbol in the title results in 0-byte files

### ISSUE THREAD

**Issue by romlok** [gpodder/gpodder#837]
A recent post on [Jim Sterling's YouTube feed](https://www.youtube.com/feeds/videos.xml?channel_id=UCWCw2Sd7RlYJ2yuNVHDWNOA) included a dollar character in the video name. The file created by gPodder is named:
`NBA 2K21 Is $69.99 On Next-Gen Consoles While 2K Spews Vague Nonsense About _Value_.mp4`

However, when the youtube-dl extension is used to manage the download, the "partial" file is named differently:
`NBA 2K21 Is $$69.99 On Next-Gen Consoles While 2K Spews Vague Nonsense About _Value_.mp4.partial.webm`

Note that the dollar symbol has doubled up. It seems this makes gPodder not able to locate the file to move over to the final file location once the download is complete.

The next time gPodder starts, I get the message:
> [gpodder.common] WARNING: Partial file without episode: /home/mel/gPodder/Downloads/Jim Sterling/NBA 2K21 Is $$69.99 On Next-Gen Consoles While 2K Spews Vague Nonsense About _Value_.mp4.partial

at which point the file is deleted, leaving only the zero-byte placeholder file.

--

Workaround:
Preventing youtube-dl from managing downloads (`extensions.youtube-dl.manage_downloads: false`) avoids this issue.

FWIW, the youtube-dl command line executable names the file correctly, with only a single dollar sign.

--

System:
Debian Testing
gPodder 3.10.16 (from Debian repos)
youtube-dl 2020.06.16.1-1 (from Debian repos)

**Comment by auouymous** [comment]
It creates two partial files while downloading, and correctly writes to the file with $$.

```
96065200 'NBA 2K21 Is $$69.99 ... _Value_.bin.partial'
       0 'NBA 2K21 Is $69.99 ... _Value_.bin.partial'
```

After downloading, it removes partial from the file without the $$, leaving the downloaded file on disk, even after deleting the episode.

```
145181113 'NBA 2K21 Is $$69.99 ... _Value_.bin.partial'
        0 'NBA 2K21 Is $69.99 ... _Value_.mp4'

```

The problem is this code that replaces % and $. The youtube-dl man page doesn't say anything about $ for the output template, but %(NAME) is used.

```
    def fetch_video(self, url, tempname, reporthook):
        opts = {
            # outtmpl: use given tempname by DownloadTask
            # (escape % and $ because outtmpl used as a string template by youtube-dl)
            'outtmpl': tempname.replace('%', '%%').replace('$', '$$'),
```
