### ISSUE TITLE
Channels without episodes are hidden from channel list

### ISSUE THREAD

**Issue by auouymous** [gpodder/gpodder#849]
Feeds with items and no enclosures don't produce any episodes, and gpodder hides channels that lack episodes, only making them visible after a non-empty channel search. Adding a news/blog feed has no user feedback at all. There is no channel in the list (with show-all-episodes), no message that the channel lacks episodes and no indication it was even added. It also clutters the database unless the user knows that a channel search can be used to find and delete it.

At a minimum, all channels should be displayed in list when show-all-episodes is enabled. Even if the following option is implemented, because a feed could have issues and should still remain visible in the list.

Gpodder could also create entries for episodes without enclosures. A feed might publish a news item that lacks an enclosure, or gpodder could just be used to subscribe to news and blog feeds. The stream/download menu item would be grayed out and maybe a special no-media icon displayed next to the episode. The user would need to show description to read it, or gpodder could automatically open description and close it when another episode is selected.

**Comment by elelay** [comment]
Isn't it because View > **hide channels without episodes** is active?

**Comment by elelay** [comment]
Regarding gPodder as an RSS reader, it [can be done](https://github.com/elelay/gPodderAsRSSReader/commit/183c59f784a502891003dd4415418eef35e74cc8).

**Comment by auouymous** [comment]
You are correct, that option was active. I guess the only valid solution is limited support for episodes without enclosures. I'll open a PR if I find time to work on it.
