### ISSUE TITLE
I/O Error

### ISSUE THREAD

**Issue by KeithSilva** [gpodder/gpodder#854]
Hi:

I've been using gPodder successfully for several years. Thank you for your work. In addition, I've been using this particular podcast source successfully for several months:

https://feeds.buzzsprout.com/1004629.rss

Recently, I've been receiving this error message and the podcast is failing to download:

Failed: I/O Error: [Errno socket error] [Errno -3] Temporary Failure in name resolution: None - Garden Basics with Farmer Fred

Is this a problem with me, the client, or the podcast server? I'm using Lubuntu 18.04.5 LTS and gPodder 3.10.1 from the standard Ubuntu repository. Sorry to bother you with this.

Thanks, Keith Silva

**Comment by auouymous** [comment]
That is a problem with your DNS or buzzsprout.com's nameservers.

**Comment by KeithSilva** [comment]
Thank you for the reply. I'll research this problem with your help in mind.

Take care, Keith Silva
