### ISSUE TITLE
Lots of "[Errno 11001] getaddrinfo failed" notifications

### ISSUE THREAD

**Issue by Thra11** [gpodder/gpodder#856]
gPodder running on Windows. When updating feeds, it sometimes shows a lot of notifications:
> #### Error while updating feed
> Error while updating Some Podcast at https://example.com/podcast.rss: \&lt;urlopen error [Errno 11001] getaddrinfo failed\&gt;
> gPodder

Looks very similar to #825, although the Errno is slightly different.
The suggestion that it is a transient network failure seems reasonable. Sometimes it's just one or two podcasts, sometimes it's every single one. When it's every single one, you get, for example, 20 very similar notifications appearing sequentially (you have to dismiss each one before the next one is shown) which is rather inconvenient.
There might not be a lot gPodder can do to fix the transient failures themselves. However, you could consider two improvements:
1. Retry a few times (with a short delay between tries), before giving up and reporting the failure. Most of these failures seem to be very short-lived, so trying again will probably fix most of them.
2. When updating multiple podcasts, collect the errors and show a single notification when all updates have finished if any have failed.

There also appear to be a minor issue with the encoding of the text: The `<` and `>` have been html escaped, but the notification isn't rendering the escape codes.

**Comment by auouymous** [comment]
What version of gpodder are you using? When I disable DNS, gpodder 3.10.16 displays an error icon over the channel icon with an error message below channel name. There are no dialogs and the <> brackets are correctly shown.

**Comment by Thra11** [comment]
Currently 3.10.13. Will update to the latest version and see if the issue persists.

**Comment by auouymous** [comment]
Error reporting was fixed with #741 and released in 3.10.14.

**Comment by Thra11** [comment]
Awesome! Thanks

**Comment by Thra11** [comment]
It just happened again while running 3.10.16. 17 notifications in a row, one after another.

**Comment by auouymous** [comment]
Can you post a section of the log from one of the failed channels?

**Comment by auouymous** [comment]
And by notification, do you mean a dialog window in gpodder or a notification from your operating system?

**Comment by Thra11** [comment]
A notification from the operating system

**Comment by auouymous** [comment]
Okay, I don't have a notification system and therefore can't see them. I'll post a PR to condense the notifications to one.

**Comment by Thra11** [comment]
Would the logs still be useful? Happy to provide them, but not sure where to find them.

**Comment by auouymous** [comment]
No, I don't need the logs.
