### ISSUE TITLE
Flatpack install issue

### ISSUE THREAD

**Issue by xmundt** [gpodder/gpodder#858]
The flatpack install file for Linux has an error.  It refers to "Flatpack.org" as a source.   This is no longer accurate.  The correct address is "Flatpack.com".
File Name: org.gpodder.gpodder.flatpackref 
Original:
[Flatpak Ref]
Name=org.gpodder.gpodder
Branch=stable
Title=org.gpodder.gpodder from flathub
IsRuntime=false
Url=https://dl.flathub.org/repo/
SuggestRemoteName=flathub
-------------------------------------------------
corrected version:
[Flatpak Ref]
Name=org.gpodder.gpodder
Branch=stable
Title=org.gpodder.gpodder from flathub
IsRuntime=false
Url=https://dl.flathub.com/repo/
SuggestRemoteName=flathub

**Comment by elelay** [comment]
Hi,
thanks for the heads up! Are you sure about this? Because flatpak.org seems alive and up to date.

**Comment by elelay** [comment]
dl.flathub.com doesn't exist in DNS
