### ISSUE TITLE
Thank you very much for the program!

### ISSUE THREAD

**Issue by mrkaban** [gpodder/gpodder#863]
Thank you very much for the program distributed under a free open license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%BD%D0%B5%D1%82/%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B8/gpodder-%D0%BC%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80-%D0%BF%D0%BE%D0%B4%D0%BA%D0%B0%D1%81%D1%82%D0%BE%D0%B2.html).

Please do not drop the project, this is a very interesting program!

**Comment by elelay** [comment]
Thanks for the praise: I'm glad you like it!
We would welcome a Russian translation maintainer.

If you want, you can you fork the gpodder project, edit the po/ru.po file and submit a pull request?
I use poedit on Linux to edit translation files: it has a nice user interface and a way to let you review warnings, etc.. But a basic text editor is enough to write translations. Don't hesitate to ask: we will help you if you have problems along the way :-)

Even a one-shot translation update would help. If it becomes regular, please subscribe to #518 to be notified of pending releases, so you can update the few changed strings at best time.

**Comment by mrkaban** [comment]
Done, thanks!

https://github.com/gpodder/gpodder/pull/865
