### ISSUE TITLE
Feature Request: add redownload dropdown menu option

### ISSUE THREAD

**Issue by Dakforever** [gpodder/gpodder#864]

**Comment by auouymous** [comment]
Would this be for episodes that are already downloaded? If so, the youtube-dl extension should also have a `Redownload with Youtube-DL` option.

@elelay Can extensions add to the `Episodes` menu? There is no `Download with Youtube-DL` option there.

**Comment by auouymous** [comment]
There are times, like today, when a youtube video is downloaded before it has finished processing all formats and only the tinest format is available. An `Undownload` option could be used to delete the file and mark it as new. Another attempt could be made later or the next day during a normal update. This one option would eliminate the need to have two `Redownload` and `Redownload with Youtube-DL` options. Thoughts?

**Comment by elelay** [comment]
Yes, we need to discuss more before adding a *Redownload* function.
@Dakforever what is your actual use case?

If needing to re-download I would delete the episode, switch views to include deleted and download it again...

**Comment by Dakforever** [comment]
Hm....
@elelay I'm sorry for not being clear, I have had a busy week and only posted the request without filling in basic information.
My use case was to re-download files that have not been fully downloaded or not converted due to some error in order to see the error and fix or report it, As you have described there is a way to do this already, however it was not apparent to me when I posted, however I believe there is still room for this option to automate the re-download process, as some of us have used this program for quite a while and may delete episodes frequently and changing views to show all episodes would introduce clutter.

**Comment by auouymous** [comment]
Do you both agree an `Undownload` option would be more useful than a `Redownload` option, which also needs a `Redownload with Youtube-DL` option? Undownloading automates the show deleted episodes, delete, mark as new, and hide deleted episodes steps. It takes an extra step to choose which type of download you want, but doesn't require multiple options and allows the download to be delayed if needed.

**Comment by Dakforever** [comment]
@auouymous  Yeah that makes sense.

**Comment by bityob** [comment]
Hey,

My use case for the `redownload` option, is to fix corrupted downloads. 

I have multiple cases and I would like to select a bunch of them and send them to `redownload` again, without the need to delete them first and then download them again.

Maybe also we can add an extra feature to checksum the downloaded episode with the episode file link.

**Comment by auouymous** [comment]
This was removed due to UI issues it caused but will return as soon as we figure out how to solve them. Redownloading is limited to a single case while undownloading is more generalized and works for all cases. Maybe the file on site is corrupt but will be repaired tomorrow, undownloading would cause it to be redownloaded on the next update. Or take youtube where new videos are posted lowest resolution first, and updating shortly after an episode is released will download the lowest resolution because that is all that currently exists.

RSS feeds don't provide checksums to compare the downloaded files with, which is how checksums work.
