### ISSUE TITLE
gpodder should have an adaptive GTK / libhandy GUI

### ISSUE THREAD

**Issue by tpikonen** [gpodder/gpodder#878]
It would be nice to use gpodder with a smaller screen, like the one in pinephone, librem 5 etc. This could be accomplished by making  the GTK GUI to use adaptive widgets from libhandy. The current GTK user interface starts to show its age also in desktop use IMO.

I'm thinking of taking a stab at implementing this, but has anyone else (maintainers?) thought about this already?

**Comment by elelay** [comment]
Hi,
I'd be happy to see gPodder on librem5 for sure, but this is not something I will work on for now.

**Comment by tpikonen** [comment]
There's now a work-in-progress prototype of adaptive GTK UI [here](https://github.com/tpikonen/gpodder/tree/hdy).

At the moment only the main gPodder window is converted, but the result is already somewhat usable on a touchscreen device.
The horizontal and vertical panes are replaced by HdyLeaflet and HdyDeck containers and the Podcasts / Progress notebook and the main menu and toolbar are gone. The Treeviews have their column headers replaced by sort buttons in the header bar and the context menu in the channels list is replaced by a more finger friendly version. Some of the main window functionality (like search) is still missing. 

Ironically, swiping from one view to another in the container stack works well with a laptop touchpad with 2-finger swipes (this needs libhandy-1.0.1), but on touchscreen the Treeviews and Gtk swipes do not interact well, so one has to use the arrow buttons in header bar to go back and forth. GTK4 will both remove Treeviews and allow arbitrary widgets in a performant list widget (GtkListView), so the channel and episode lists will have to be rewritten anyway for a GTK4 port. This will probably also fix the swipe problem. The GTK4 port of libhandy is not yet ready, so all this will have to wait.

The new UI code is BTW completely independent from the old one, just set 'gpodder.ui.hdy = False' in bin/gpodder (at line 117) to go back to the classic GTK UI.

I'm going to work on this when time allows, and if the problems above are solved, turn this into an actual pull request.

**Comment by ollieparanoid** [comment]
Awesome that you have started this @tpikonen!

I was evaluating podcast players that could work on Linux phones and ended up with gpodder as well (also Vocal, but unfortunately upstream seems dead): https://gitlab.com/postmarketOS/pmaports/-/issues/872

Lately I also played with using libhandy in gpodder, but it looks like you have gotten much further, what you wrote sounds great already! :smile:

**Comment by tpikonen** [comment]
Thanks @ollieparanoid! I just pushed the latest rebased version of libhandy patches (here: https://github.com/tpikonen/gpodder/tree/hdy).

**Comment by Johennes** [comment]
@tpikonen, great work!

I tried your branch on my laptop and I'm hitting this error on launch:

```
1608400082.806072 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/home/jm/Code/pmos/gpodder/src/gpodder/gtkui/app.py", line 196, in do_activate
    self.window = gPodder(self, self.bus_name, core.Core(UIConfig, model_class=Model), self.options)
  File "/home/jm/Code/pmos/gpodder/src/gpodder/gtkui/hdy_main.py", line 107, in __init__
    BuilderWidget.__init__(self, None, _builder_expose={'app': app})
  File "/home/jm/Code/pmos/gpodder/src/gpodder/gtkui/interface/common.py", line 36, in __init__
    GtkBuilderWidget.__init__(self, gpodder.ui_folders, gpodder.textdomain, parent, **kwargs)
  File "/home/jm/Code/pmos/gpodder/src/gpodder/gtkui/base.py", line 71, in __init__
    self.new()
  File "/home/jm/Code/pmos/gpodder/src/gpodder/gtkui/hdy_main.py", line 242, in new
    self.btnUpdateFeeds.show()
AttributeError: 'gPodder' object has no attribute 'btnUpdateFeeds'
```

Once I comment out these two lines, everything works fine though.

```
        if not self.application.want_headerbar:
            self.btnUpdateFeeds.show()
```

**Comment by tpikonen** [comment]
@Johennes Thanks, you were probably testing on something else than Gnome, which meant that want_headerbar was false, and this happened. You were likely also missing the headerbar, which really is needed with the adaptive GUI.

The latest patch on my branch fixes this, want_headerbar is now always true when running the adaptive version.

**Comment by Johennes** [comment]
Ah, yes, that's right. I'm using XFCE on my laptop.

Thanks for fixing this so quickly! :slightly_smiling_face:

**Comment by Johennes** [comment]
@tpikonen do you have any thoughts yet on how to make the dialogs adaptive? I'm just starting to learn libhandy but it seems that `HdyDialog` was removed in 1.0 without a replacement. I've been looking at the add-podcast dialog in specific and the only way I found so far to keep it within the screen bounds is to reduce the `default_width` property.

**Comment by tpikonen** [comment]
@Johennes I think the only way to fix dialogs is to rewrite them to use HdyWindow with manually added the OK/cancel buttons etc. I just did this to the episode selector to fix some usability problems (not mobile related, but using libhandy anyway).

I'm using mobian for testing on a small (pinephone) screen, which apparently patches GTK so that the Add podcast dialog is forced to fit the screen. It is also stretched to fill the whole screen, making it look rather funny. Fixing that would be a good project to start learning libhandy.

**Comment by Johennes** [comment]
Thanks for the pointers @tpikonen. I think the stretching of the text entry is actually just due to the expansion property on its parent box being enabled. I submitted #930 to correct that.

I converted the add-podcast dialog to use `HdyWindow` [here](https://github.com/Johennes/gpodder/tree/feature/addpodcast). When I tested this on an actual device with pmOS I did see the same effect you describe though. The dialog essentially looks the same before and after switching to `HdyWindow`. Interestingly they looked different in Qemu but I believe Phosh might just not work correctly in Qemu in general.

@elelay what would be your preferred way of integrating an adaptive UI based on libhandy into gpodder? I think the swiping issue mentioned above is not a total deal breaker. The real blocker is just an adaptive layout that is _usable_ on a mobile screen. Would you prefer this to be implemented in a second standalone UI next to the existing UI? Or would you rather see this replace the existing UI?

**Comment by auouymous** [comment]
Forcing desktop users to install libhandy and use a fat finger UI would be an issue.

**Comment by Johennes** [comment]
I personally find the desktop UI on @tpikonen's `hdy` branch a little more visually appealing than the current UI but that's totally subjective and I get your point as well.

So if you want to retain the traditional desktop UI, my next question is if you'd accept a second UI path based on libhandy in the gpodder code base? That'll likely mean double maintenance since I suppose most changes will have to be tested in both UIs going forward.

**Comment by auouymous** [comment]
There is nothing appealing about requiring want_headerbar, see #791. Is it not possible for it to adapt the gtk UI without needing a separate code base, and without forcing a touch UI on desktop users? It is difficult to test features and extensions across UIs and would lead to inconsistencies when a new feature is only implemented for one of them, or not implemented at all because the developer can't port it to the other UI.

I am open to making some changes to the UI that might make it easier to add touch, such as getting rid of the GtkNotebook which adds a lot of wasted space for two tabs. `Progress` could be an item or button in the left pane and its contents open in the right pane.

**Comment by Johennes** [comment]
> It is difficult to test features and extensions across UIs and would lead to inconsistencies when a new feature is only implemented for one of them, or not implemented at all because the developer can't port it to the other UI.

Yeah, I totally understand that concern.

> I am open to making some changes to the UI that might make it easier to add touch, such as getting rid of the GtkNotebook which adds a lot of wasted space for two tabs. Progress could be an item or button in the left pane and its contents open in the right pane.

The biggest problem for me right now is the size of the window(s). You can't really fit the current main window onto a portrait mobile screen, for instance.

![panes](https://user-images.githubusercontent.com/1137962/103104558-509c7880-4628-11eb-8f58-c2d9d764171f.png)

You can fit it in landscape orientation but that doesn't leave a lot of room for content (and when the keyboard is shown basically just one line of text).

Doing away with the tab bar would improve the situation a little bit. We'll also have to think about other parts though like, for instance, the episode details in the bottom right of the right pane. There's not enough vertical space to show both the top and bottom part of the right pane in landscape orientation on a mobile screen.

I am not totally sure if selectively tweaking these things will end up in a UI that's usable and intuitive on both desktop and mobile. However, I also understand your reservations about header bars and CSD so maybe that's the best we can achieve at this point.

**Comment by tpikonen** [comment]
> I am open to making some changes to the UI that might make it easier to add touch, such as getting rid of the GtkNotebook which adds a lot of wasted space for two tabs. `Progress` could be an item or button in the left pane and its contents open in the right pane.

Personally I don't see much need at all for the Progress tab, but a 'Downloads' item above or below 'All episodes' leading to the download list currently under the Progress tab sounds like a good idea to me.

The point of @Johennes about not fitting two lists side by side on a mobile screen is valid, so something like libhandy (or at least HdyLeaflet) is in any case needed to make gpodder on a phone workable.

**Comment by auouymous** [comment]
I rarely use the progress tab but it is needed. I have also wanted to remove the notebook for a while now. The channel list wouldn't gain more vertical space, but the episode list would, and it would remove the wasted border space around the notebook. I have too many other changes/fixes to work on a notebook removal PR right now, but I can help test it if one of you did. 

@Johennes that screenshot is slightly smaller than my gpodder window on desktop. I have been using a patch for a year now that adds `Duration+` and `Size+` episode columns. It vertically integrates size and duration into a single column and whould be a good feature to have both on a small window. I'll try to get a PR up soon.

What about a multi-pane setting that changes to a single pane UI when disabled, using magic to move right and left through the three panes? Desktop and tablet users can then keep the current multi-pane UI, and if possible, detection could be used to initialize the setting to single-pane for known phone platforms.

Forcing want_headerbar should not happen though. I had a maemo device (4" tablet) that could have benefited from a single-pane UI, and I would not have wanted that headerbar. The change should not target what looks good only on a single device. Instead, add known platforms to the headerbar detection list, and honor the GTK_CSD setting for those who want it off on those platforms.

**Comment by Johennes** [comment]
> What about a multi-pane setting that changes to a single pane UI when disabled, using magic to move right and left through the three panes? Desktop and tablet users can then keep the current multi-pane UI, and if possible, detection could be used to initialize the setting to single-pane for known phone platforms.
>
> Forcing want_headerbar should not happen though. I had a maemo device (4" tablet) that could have benefited from a single-pane UI, and I would not have wanted that headerbar. The change should not target what looks good only on a single device. Instead, add known platforms to the headerbar detection list, and honor the GTK_CSD setting for those who want it off on those platforms.

I'm totally d'accord with not ruining the experience on one platform in favor of another. :ok_hand: 

I'm still relatively new to libhandy myself but I think we should be able to use its adaptive controls without enforcing the headerbar / CSD. The `HdyLeaflet` control that @tpikonen mentioned basically provides the adaptive switch between one and two panes that you describe.

> I rarely use the progress tab but it is needed. I have also wanted to remove the notebook for a while now. The channel list wouldn't gain more vertical space, but the episode list would, and it would remove the wasted border space around the notebook. I have too many other changes/fixes to work on a notebook removal PR right now, but I can help test it if one of you did.

Getting rid of the notebook and finding a new home for the downloads tab sounds like a good first step to me. Are you adamant that it should go into the channel list? If this is rarely used, maybe we could also put it into e.g. a dialog that is opened from the menu bar (which _might_ require less work)?

**Comment by auouymous** [comment]
It was just an idea, opening in a dialog would provide more horizontal space versus opening in the right pane. Of course that is only an issue for desktop users with narrow windows, mobile users would have sliding panes so the progress content would be full width.

The biggest issue is that the progress tab displays the number of active downloads and failed downloads. That information needs to be displayed somewhere on the UI. It should also be quick and easy to open the progress dialog to see which download is taking forever or the reason it has failed. Having an entry in channel pane would provide a button and that info.

**Comment by Johennes** [comment]
I started hacking around to move the progress tab into the channel list on [this branch](https://github.com/Johennes/gpodder/tree/feature/byebyetabs) but it'll still need quite a bit of work.

Essentially it'll look something like this:

![downloads](https://user-images.githubusercontent.com/1137962/103158166-38109780-47bb-11eb-9bb2-d44aae9a03c7.png)

What complicates things is that the "All podcasts" item in the channel list is already a tiny bit of a hack (as evidenced by the `# Dirty hack to check for "All episodes" (see gpodder.gtkui.model)` comments :sweat_smile:). Adding a "Downloads" item makes the hack a little bigger though maybe not significantly worse than it already is.

**Comment by tpikonen** [comment]
Looks good to me @Johennes! A small nitpick: I mostly use 'All episodes' view sorted by release date, so having it as the first (and default) view would be a lot better than the Downloads, which I almost never view.

**Comment by Johennes** [comment]
Ah, good point yeah. No reason for "Downloads" to take the first / default spot in the list. :+1:

**Comment by auouymous** [comment]
It should probably be called `Progress` because `Downloads` sounds like a filter to see all downloaded episodes, similar to `View...Downloaded episodes`.

**Comment by Johennes** [comment]
Good point as well. I swapped it into the second slot and renamed the title. Still have some commented out parts and the UI hierarchy that I need to fix.

**Comment by Johennes** [comment]
Ok, I think I might have something that works. I opened #938. Any testing and / or review highly appreciated - especially since this is my first real contribution to gpodder. :sweat_smile:

**Comment by elelay** [comment]
tried the hdy branch on desktop and it looks really usable on a phone :+1:

**Comment by thp** [comment]
Not sure if it's helpful and the content below is mostly 10 years old at this point, but gPodder was ported to mobile UIs multiple times in the past (once to Maemo 4, then to Maemo 5 -- both Gtk-based and then to Qt/QML twice -- once MeeGo Harmattan and then Sailfish OS), here are some screenshots (some of the older ones have broken links, since the Flickr album from back in the day was deleted):

http://thpmaemo.blogspot.com/search/label/screenshots

There were also a bunch of screenshots on the web page (sit tight while the images load; tap on the version name to expand the section and the screenshots):

http://web.archive.org/web/20110519105812/http://gpodder.org/screenshots.html

The initial version had it "solved" by moving the tab to the toolbar on the bottom right (yes, that's Gtk 2 running on a mobile device in 2008):

![](http://web.archive.org/web/20101217141851if_/http://gpodder.org/releases/0.16.0.maemo/gpodder-0.16.0-maemo-downloads.png)

Whereas the version for Maemo 5 added a "start screen":

![](http://web.archive.org/web/20110101055511if_/http://gpodder.org/releases/2.1.fremantle/Screenshot-20091212-191405.png)

Eventually the main screen was changed so that the start screen was the list of podcasts (and "drilling down" into an episode list when tapping on a podcast):

![](http://web.archive.org/web/20110519110543if_/http://gpodder.org/releases/2.2.fremantle/Screenshot-20100205-151602.png)

The "Progress" tab (previously "Downloads" list) was moved to the top menu (on Maemo 5, tapping the titlebar could bring up that menu):

![](http://web.archive.org/web/20110519110653if_/http://gpodder.org/releases/2.2.fremantle/Screenshot-20100205-151645.png)

If you go to 02:40 you see some of the UI interactively (and also younger versions of @tigert and me designing an improved Maemo 5 UI for gPodder): https://www.youtube.com/watch?v=yjkobuF7T8U

Just some things that sprung to mind while reading through the PRs :) The Git history also reflects the Maemo 4, Maemo 5 and MeeGo (Qt/QML) ports, as they were kept in the same repo (the Sailfish and Qt5 QML ports are in the "gpodder-core" repo + separate repos for UIs).

Not sure what Librem5 runs, but maybe the QML UI (on top of gpodder-core) is more suitable for this?

**Comment by tpikonen** [comment]
Thanks for the comments @thp. I've actually used gPodder on all the platforms you mentioned and still use the Sailfish port. Thanks for all your work though the years!

What is different with the latest generation of mobile UI toolkits on Linux is the promise of convergence, i.e. running the same binary on both small phone screens and large desktop monitors. This can even happen on a same device, the pinephone for example can output to a 4K monitor and windows can be dragged freely between the two screens. The current state of the GTK3+libhandy platform is far from perfect, but it's usable as it is, and there is enough momentum so that it's going to improve.

My adaptive gPodder version is now close to feature-complete, missing mostly just the prefences window. I'm not completely happy with the UI, so some changes will be needed still. There seems to be some interest in the pinephone / phosh and postmarketOS communities, so I'll probably end up making a separate github project for it when things stabilize.

As for the Downloads/Progress widget, the adaptive version currently has it in a separate non-modal dialog which is launched from menu items in both channels and episodes views. This way it's two clicks away from both screens, but does not have a separate button taking up space.

**Comment by elelay** [comment]
> My adaptive gPodder version is now close to feature-complete, missing mostly just the prefences window. I'm not completely happy with the UI, so some changes will be needed still. There seems to be some interest in the pinephone / phosh and postmarketOS communities, so I'll probably end up making a separate github project for it when things stabilize.

If you're committed to maintaining it (I appreciated your PRs) there is definitely room for maintaining it. Either within gpodder org or as a gPoddder branch.

> As for the Downloads/Progress widget, the adaptive version currently has it in a separate non-modal dialog which is launched from menu items in both channels and episodes views. This way it's two clicks away from both screens, but does not have a separate button taking up space.

A transfer dialog is not so weird after getting used to it. What I don't like is that there is no sign that downloads are in progress from the podcast screen. There is the progress icon in episode list, and menu items to show transfers, but is it enough?
Could there be a button shown in the header bar when downloads are in progress? The icon could have an active download counter or show a progress bar as a custom icon-widget but here with a single down-pointing-arrow... The button could be hidden when no active download.
![hdy](https://user-images.githubusercontent.com/222469/105024951-f76c0d00-5a4c-11eb-8a13-cb764b69ede5.png)

**Comment by tpikonen** [comment]
@elelay, you're right about the lack of feedback when starting downloads. The button should be visible in both views, channels and episodes, but the episodes header bar does not have space any more on mobile screens.

So, I implemented an overlay with a button on the lower right corner of the main app window, which shows the transfers dialog and is only visible when there are downloads or syncs in progress (not tested with syncs). The text on the button is the same as in the 'Progress' tab. I think this works rather well, it's a visible indicator that downloads are in progress, allows easy launching of the dialog and does not much interfere with the rest of the UI (except maybe the update progress bar).

**Comment by tpikonen** [comment]
I'm starting to be pretty happy with the state of the adaptive interface, so this issue is ready be closed soon. There's now a branch at https://github.com/tpikonen/gpodder/tree/adaptive where hdy_main.py is gone and the adaptive changes are in main.py. This hopefully makes it easier to merge in changes from the master branch. It will also not be rebased, unlike the former hdy branch.

The libhandy development version (1.1.x) has a new widget called HdyFlap, which I found to be useful in converting the preferences and podcast directory dialogs to fit into small screens. These are available in the '1.1-adaptive' branch here https://github.com/tpikonen/gpodder/tree/1.1-adaptive and will be merged in to 'adaptive' when a release of libhandy with the Flap widget is made.

gpodder-adaptive is now also included in PostmarketOS, so it would be nice to get a place for bug reports, PRs etc. A separate project or branches under gpodder/gpodder? What do you think @elelay?

**Comment by elelay** [comment]
Hi @tpikonen,

good to see it taking shape! Not having the development version of libhandy, I've tried the adaptive branch.
I'm not familiar with conventions in gtk mobile apps, but it's a bit strange to me that in the "Select New Episodes"  dialog a click to the checkbox shows the episode details. Is it intentional or an oversight?

You are welcome to an adaptive branch in gpodder/gpodder, as long as we agree that you're committed to maintain it ;-)
Issues would go to gpodder/gpodder, with an *adaptive* label.
Is this what you prefer?

**Comment by tpikonen** [comment]
Ah, yes, this part of the episode selector broke when adding the keyboard shortcuts. This is now fixed.

If the bug reports for this project are fine in gpodder/gpodder, then a branch there is fine with me.

**Comment by elelay** [comment]
OK, so you're now invited to the *gpodder contributors* group. Once you join it, you'll have write access to gpodder/gpodder.

:partying_face:  **Welcome aboard** :partying_face: 

Let's set some rules:
 - you may push your **adaptive** branch and create as many other branches as you need (1.1-adaptive, etc.)
 - you may create tags, as long as they are not ambiguous with gPodder desktop
 - you are responsible for issues labelled with *adaptive UI*
 - you are very welcome to help us on other issues, submit enhancements, etc.
 - you may not yet push to the **master** branch of any repo directly but should use pull requests
 - you may add documentation for the adaptive UI on gpodder.github.io

If unsure, just ask: we'll figure out the best way to work together.

**Comment by tpikonen** [comment]
Thanks @elelay! I've pushed the adaptive and 1.1-adaptive branches to gpodder/gpodder.

Closing this issue.

**Comment by Johennes** [comment]
Great work @tpikonen and awesome that this is now in the official gpodder repo! :slightly_smiling_face: 

We're updating the pmOS package to the latest version hosted here in https://gitlab.com/postmarketOS/pmaports/-/merge_requests/1975.

**Comment by craftyguy** [comment]
Will the adaptive branch live on forever as essentially a fork of gpodder, or will it be merged into the master branch at some point? (and if so, what open issues need to be resolved before that happens?)

**Comment by auouymous** [comment]
It would be nice if it could be merged into master as it is currently 67 commits behind.

I still believe removing the GtkNotebook should happen in the desktop client, and that might reduce some of the 52 commits in adaptive branch. There might also be other minor changes in there that could be merged. After that, it depends on how feasible it would be to integrate the remaining changes into master, enabled with detection or an environment variable to force it on when not detected (testing or using on desktop).

**Comment by craftyguy** [comment]
> enabled with detection or an environment variable to force it on when not detected (testing or using on desktop).

Hmm, I thought the whole point of using libhandy was that the UI is adaptive, meaning it does the detection/resizing automatically. Or did you mean detecting something else?

**Comment by auouymous** [comment]
But is libhandy available and stable on all distros, including mac and windows? And does the adaptive branch have the same appearance when run on a desktop with libhandy, or does the UI become chunky for touch?

**Comment by craftyguy** [comment]
The UI on a desktop is no different than any other Gtk3 app.

I see your point about windows/mac though, I have no idea if libhandy is available there.

**Comment by Johennes** [comment]
Mac has it: https://formulae.brew.sh/formula/libhandy

**Comment by tpikonen** [comment]
I'm planning on merging the latest gpodder release(s) to the adaptive branch soonish, but it will probably still take a week or so.

As for the other platforms, currently the adaptive UI is based mostly on headerbar buttons and I don't know how these would look on Windows or Mac. The buttons could be moved to a separate button bar if needed though.

The Win and Mac installers already bundle Python and GTK, so I suppose adding libhandy would be possible as well.

**Comment by auouymous** [comment]
> As for the other platforms, currently the adaptive UI is based mostly on headerbar buttons and I don't know how these would look on Windows or Mac. The buttons could be moved to a separate button bar if needed though.

I don't know what "buttons" you have in the headerbar but I don't want headerbar/CSD or a new button bar.

**Comment by tpikonen** [comment]
The adaptive branch is now merged with 3.10.19 release. It also has the new preferences and podcast directory dialogs using the HdyFlap widget in libhandy 1.2, which should be available in the bleeding edge versions of most distros.

Help with testing would be appreciated. I'll tag the branch head to mark a stable version in a few days, if no bugs are found.

**Comment by ollieparanoid** [comment]
@tpikonen: I just checked out the branch and will test drive it a bit. The new adaptive podcast directory and settings dialogs are great!

One thing I've noticed is, that tapping `"All episodes" in podcast list` in settings makes the interface hang for a bit (I guess until it has reloaded all podcasts), from user perspective it would be nice to see a loading bar or something to know that it did not crash. But this new settings dialog is a big improvement over not having an adaptive one for phones, so this detail shouldn't stop you from making the release IMHO.

I'll let you know if I find any bugs, but so far everything looks good!

Thank you very much for updating the branch! :tada:

**Comment by black-puppydog** [comment]
I also have been using this branch over the week. It is really great work @tpikonen thank you so much!
I still think that on mobile devices, the lack of integrated player hurts. I don't know how other people use their podcatchers on android/ios, but I seek extensively, to skip ads, and even more to skip 10s *back* to re-listen to stuff. 

Of course that is all out of scope for this branch. Again: thank you!

**Comment by tpikonen** [comment]
@ollieparanoid Yeah, the (lack of) performance with 'All episodes' is annoying, but fixing that would be tricky. I added the correct sidebar / flap icon in the latest commit, this was bothering me as well.

@black-puppydog Thanks for your comments. I'm not planning on adding an integrated player, but a better (than Lollypop) podcast oriented audio player with skip buttons would be nice to have. Maybe someone should resurrect [panucci](https://github.com/gpodder/panucci) :)

**Comment by tpikonen** [comment]
@elelay I would like to tag the current head of 'adaptive' with something like 'adaptive/3.10.19', but I have no idea what that would start in terms CI, releases etc. Would it be safe to add the tag?

**Comment by auouymous** [comment]
Appveyor only runs for master branch and branches starting with `win`. Circleci is currently running on the adaptive branch but should be disabled since gpodder-osx-bundle doesn't have libhandy. As for Travis, it stopped working mid-March, probably because they stopped supporting open-source projects.

Releases would not be affected and I agree that it should be tagged with gpodder's version number.

**Comment by ollieparanoid** [comment]
@black-puppydog: regarding seek buttons, I'm using phosh with [this patch](https://source.puri.sm/Librem5/phosh/-/merge_requests/664) FWIW

**Comment by elelay** [comment]
@tpikonen as @auouymous implied, you're welcome to tag an adaptive/3.10.19 :+1:

**Comment by tpikonen** [comment]
Ok, there's now 'adaptive/3.10.19+1' tag in the repo. +1 because there's some commits post 3.10.19 release, and I will probably make more tags before 3.10.20 is ready anyway.
