### ISSUE TITLE
gPodder 3.10.11+ wont start in Win 7 x 64

### ISSUE THREAD

**Issue by joesmith222** [gpodder/gpodder#885]
I've stayed at v3.10.10 (Portable Apps version) for quite a while now and had been trying to start newer versions as they came out but none worked.  I've today even tried the installer version and same thing happens, double click EXE file to run and the spinning wheel starts for a second next to the cursor as though the program is going to open but it never does.  I check processes to see whats running and no gPodder there.

I have disabled Windows Updates on my computer for several years now so i'm guessing this might be the problem?  

Win 7 x 64 - is there a dependency on an update that i need to install?

thx

**Comment by elelay** [comment]
Hi,
no idea.

Can you try running gPodder in debug mode, to gather more info about the issue ?
See [this link](https://gpodder.github.io/docs/windows.html#debugging-gpodder-on-windows).

**Comment by joesmith222** [comment]
ok, i got this result - 

================================

> C:\Program Files (x86)\gPodder\bin>"C:\Program Files (x86)\gPodder\bin\gpodder-c
> md.exe" -v
> 
> 
> Calling SetDllDirectoryW(C:\Program Files (x86)\gPodder\bin)
> Successfully SetDllDirectoryW
> Failed to get current screen language with 'GetUserDefaultUILanguage'
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder_launc
> h\gpodder.py", line 81, in main
>     import gpodder  # isort:skip
>   File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\__ini
> t__.py", line 127, in <module>
>     install(textdomain, locale_dir)
>   File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\utilw
> in32locale.py", line 354, in install
>     from ctypes import cdll
>   File "lib\python3.8\ctypes\__init__.py", line 457, in <module>
>   File "lib\python3.8\ctypes\__init__.py", line 373, in __init__
> OSError: [WinError 87] The parameter is incorrect
> 
> 
> C:\Program Files (x86)\gPodder\bin>

======================

also, i may have installed and uninstalled a version of Python maybe 4-6 months ago, doesnt seem to be anything left of it afaict

**Comment by auouymous** [comment]
Do you have KB2533623? If not, can you try installing it?

**Comment by joesmith222** [comment]
> Do you have KB2533623? If not, can you try installing it?

that got it, thanks man

i had only 3 updates installed according to the Control Panel
