### ISSUE TITLE
"Delete Podcast" should have option to not remove the episodes 

### ISSUE THREAD

**Issue by arbizm** [gpodder/gpodder#890]
The user should be given the option to delete the feed & podcast, just the feed, or cancel.

If you've got a feed that is no longer making content but still has episodes, you probably want to delete the feed. (since it takes longer to check every time you start up).

Yes, you can make a copy of the episodes or maybe there is some other non-obvious way to preserve them, but these three choices make sense.  Other apps I've used have given an option to do this and this seems to be the most logical approach from a user perspective.

**Comment by elelay** [comment]
You can pause the feed subscription (Right-click on the cover > Podcast Settings > Disable feed updates).
This is what I do for old feeds.

**Comment by arbizm** [comment]
I did mention a non-obvious way but again, this is not something that is intuitive and deleting a feed but keeping the .mp3's is a common action.  Ideally, the user should not have search for a solution to an expected action.

**Comment by elelay** [comment]
I have to disagree on this. gPodder can't leave behind the downloads/your_podcast folder. Have you tried to simply move the files using your file browser or command-line if you don't want to keep them in gPodder?

**Comment by arbizm** [comment]
I am very aware of doing that and that's what I do.  the gpodder folder is where all my podcasts get stored and I fetch them out of there as I listen to them.  But there is no reason whatsoever that you can't keep it there if that's what the user desires.

I've been using pod software for a long time and the others allowed the user to manage things.  You're not leaving anything in the folder unless the user specifically asks for it.
