### ISSUE TITLE
How set proxy?

### ISSUE THREAD

**Issue by hamedsbt** [gpodder/gpodder#891]
Can I set proxy server & port ?
most podcast's hosts blocked in my country, so I have to use proxy to access them.

**Comment by elelay** [comment]
Hi,
see https://gpodder.github.io/docs/user-manual.html#using-a-http-proxy-server for how to set the correct environment variable.

**Comment by hamedsbt** [comment]
I hope it will be in gui.
anyway; thank you for your reply.
