### ISSUE TITLE
Problem to download a US podcast from Germany

### ISSUE THREAD

**Issue by Gabriele1969** [gpodder/gpodder#904]
Trying to download from https://www.gatesnotes.com/Podcast
Get error :2:6 Unsupported feed type: html (see attached screenshot).
![Podcast Problem](https://user-images.githubusercontent.com/74783310/99818702-d3747400-2b4e-11eb-92b3-8f647dbf20e8.png)
Download from German site https://www.ndr.de/nachrichten/info/podcast4684.html
works fine.
Where is my mistake?
Thanks for help!

**Comment by auouymous** [comment]
You need to give gpodder an RSS feed, not an html page. My guess is that gpodder is able to extract an rss link tag from the html. The german site has such a link tag `<link rel="alternate" type="application/rss+xml" title="Das Coronavirus-Update von NDR Info" href="https://www.ndr.de/nachrichten/info/podcast4684.xml" />`, the US site does not. Some sites don't use standard conventions to advertise their feeds, while other sites completely lack feeds.

**Comment by Gabriele1969** [comment]
Thank you for the background information!

I suspected something like that, but I’m not knowledgeable enough to extract that information. 

So, obviously this site calls it a podcast, although it is just a “streaming point”. They just have the “apple podcast” symbol, don’t have the rss symbol.

 

Von: auouymous <notifications@github.com> 
Gesendet: Freitag, 20. November 2020 22:53
An: gpodder/gpodder <gpodder@noreply.github.com>
Cc: Gabriele1969 <gabriele.sowada@gmx.net>; Author <author@noreply.github.com>
Betreff: Re: [gpodder/gpodder] Problem to download a US podcast from Germany (#904)

 

You need to give gpodder an RSS feed, not an html page. My guess is that gpodder is able to extract an rss link tag from the html. The german site has such a link tag <link rel="alternate" type="application/rss+xml" title="Das Coronavirus-Update von NDR Info" href="https://www.ndr.de/nachrichten/info/podcast4684.xml" />, the US site does not. Some sites don't use standard conventions to advertise their feeds, while other sites completely lack feeds.

**Comment by elelay** [comment]
Hi,
as you pointed out some editors call podcasts things without atom or rss feeds.
Se can't access them from  gPodder.

**Comment by elelay** [comment]
Wait a minute: maybe this is it: https://feeds.feedburner.com/BillGatesAndRashidaJonesAskBigQuestions
(found on podcastindex.org)

**Comment by Gabriele1969** [comment]
YES, this was it!!! 😊 Thanks a lot!

 

Von: Eric Le Lay <notifications@github.com> 
Gesendet: Samstag, 21. November 2020 15:32
An: gpodder/gpodder <gpodder@noreply.github.com>
Cc: Gabriele1969 <gabriele.sowada@gmx.net>; Author <author@noreply.github.com>
Betreff: Re: [gpodder/gpodder] Problem to download a US podcast from Germany (#904)

 

Wait a minute: maybe this is it: https://feeds.feedburner.com/BillGatesAndRashidaJonesAskBigQuestions
(found on podcastindex.org)
