### ISSUE TITLE
When connecting with HTTPS_PROXY=http://127.0.0.1:8118, all downloads fail

### ISSUE THREAD

**Issue by shunf4** [gpodder/gpodder#905]
When gPodder runs in environment where HTTPS_PROXY is some HTTP proxy server, all downloads (from a HTTPS link) fail (the situation differs with different proxy servers; some respond with 400 Bad Request, and some misinterpret the request).

This may have something to do with the deprecated `FancyURLopener`, which directly sends `b'GET https://host-of-url.com/path HTTP/1.1\r\n ...'` to the HTTP proxy server instead of using the CONNECT method.

**Comment by auouymous** [comment]
`FancyURLopener` was removed by #843 which will be merged shortly after the next release. Are you able to test that PR with a proxy?

**Comment by shunf4** [comment]
@auouymous Yes, I can confirm it resolves the issue.
