### ISSUE TITLE
Windows Installer Build Script: GIT_REV and GIT_HASH may be wrong when master branch is selected

### ISSUE THREAD

**Issue by shunf4** [gpodder/gpodder#906]
https://github.com/gpodder/gpodder/blob/4e4bf49e78019fb8cb4ea9483fc41f23c643327c/tools/win_installer/_base.sh#L138-L150

currently checked out branch (`git rev-parse --short HEAD`) is possibly different from that in `${REPO_CLONE}` (which is master), so it's possible that `$GIT_REV` and `$GIT_HASH` are wrong during installer build.

**Comment by elelay** [comment]
Seems like it, thanks.
PR welcome
