### ISSUE TITLE
Bad gateway error (error 502)

### ISSUE THREAD

**Issue by privacymentor** [gpodder/gpodder#909]
I have recently upgraded my phone's software manually and then installed antenna pod app which my client for podcasts, when I tried to synchronize it with gpodder.net it is giving me `error 502` Even tried to get access from the web from different browsers and devices but same error, which is eventually I found out is server side error, so any words on it!

**Comment by HeikoAdams** [comment]
Same here since wednesday

**Comment by tom3220** [comment]
This is an issue with gpodder.net being down. I believe they only have limited server capacity.

Not an issue with the gpodder code.

**Comment by RKDTOO** [comment]
> This is an issue with gpodder.net being down. I believe they only have limited server capacity.
> 
> Not an issue with the gpodder code.

So how does that help? Who do we reach out to about the website gpodder.net? There is no information about what's going on anywhere.

**Comment by tom3220** [comment]
> > This is an issue with gpodder.net being down. I believe they only have limited server capacity.
> > Not an issue with the gpodder code.
> 
> So how does that help? Who do we reach out to about the website gpodder.net? There is no information about what's going on anywhere.

There's not a lot you can do. You can watch here for possible updates https://github.com/gpodder/mygpo/issues/527

**Comment by privacymentor** [comment]
Server is up again,though painfully slow.
