### ISSUE TITLE
Crash Log

### ISSUE THREAD

**Issue by WHBecker001** [gpodder/gpodder#916]
Gpodder gpodder-3.10.16-portable crashed while downloading a podcast.  Program would restart but it couldn't find the config file.  In case it's useful, the log is attached.  Great program, BTW.  First time I've had any issues.

Windows 10 x64
Version 2004 
Build 19041.630

[2020-11-28.log](https://github.com/gpodder/gpodder/files/5625900/2020-11-28.log)

**Comment by auouymous** [comment]
Could you upgrade to https://ci.appveyor.com/project/elelay/gpodder/build/artifacts and see if it fixes the issue?

```
OSError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1108)
```

**Comment by WHBecker001** [comment]
Will do.  A couple of additional bits of information:
  - I think that gpodder crashed with an unhandled exception error message
(or maybe not) but Windows did not blue screen.
  - I had desktop shortcuts for gpodder and the gpodder downloads folder
and they were assigned the shortcut icon gpodder.ico.  They both changed to
generic windows icons after the crash.  Weird.
  - Double-clicking the changed gpodder shortcut opened gpodder but with no
podcasts, - i.e. it couldn't find the config folder.
  - I upgraded to gpodder-3.10.17-portable, moved the existing config file,
and all is well.
  - I will install and use the newer build, but I have used gpodder for
over a year with no issues so this is a pretty limited test.  I'll let you
know how it goes.
Thanks for responding and I hope my feedback is of some use.

**Comment by WHBecker001** [comment]
Upgraded to the above version and all seems well.  I will post back if I encounter any issues.

**Comment by elelay** [comment]
Cool

**Comment by WHBecker001** [comment]
As note above, I updated to the "experimental" version https://ci.appveyor.com/project/elelay/gpodder/build/artifacts on 12/7/2020.  Been running it ever since and no issues.  Great program.
