### ISSUE TITLE
The same episodes keep downloading, even after deleation

### ISSUE THREAD

**Issue by ideasman42** [gpodder/gpodder#918]
I keep being prompted to download the same episode of a podcast, even if I let it download. delete it... I'm *sometimes* prompted to download it again.

Unfortunately this doesn't happen so reliably enough that I can give exact steps to redo, since immediately deleting an episode and updating does *not* prompt to re-download it.

However this happens for me ... many times a week, and has been happening for the last... 4 months to take a rough guess.

For example this feed just prompted me to download episode 12 for the 3rd or 4th time.

- https://latenightlinux.com/feed/extra

Although this happens with other podcasts too.

Tested latest master, using gpodder version: e78f54b0cb836de43b67e940adf12c5426192a31

----

Is this a known issue? Or should I try re-create my gPodder configuration?

**Comment by auouymous** [comment]
This is a known issue that was fixed in 3.10.17. Are you using the latest youtube-dl?

**Comment by ideasman42** [comment]
I think so, using `youtube-dl` `2020.12.07`.

Although I don't even use the `youtube-dl` extension, so I've disabled all extensions and I'll see if this keeps happening.

**Comment by auouymous** [comment]
The problem is the `manage_channels` setting. You can keep the youtube-dl extension loaded and `manage_downloads` for special formats or use the `Download with Youtube-DL` menu option for DRM content. I don't understand why it is still an issue if you have lastest gpodder and youtube-dl, unless it broken again.

**Comment by ideasman42** [comment]
I exported all my feeds and re-imported them into a clean configuration, since then I have not been experiencing the problem.

So it seems there was an issue with my configuration (which is very old).

Closing this report.

**Comment by auouymous** [comment]
Sorry about this, I completely misread your post, which had nothing to do with youtube or the issue I said was known. It was probably a corrupt database file.

**Comment by ideasman42** [comment]
Ah, that explains the confusion, after a re-import I still don't have any problems.

Even so, odd that the data-base managed to get corrupt. I'd rather it fail entirely in this case since I have backups.

**Comment by auouymous** [comment]
An exception is thrown (I think it is written to logs), and one day I or someone else will display it in the UI.
