### ISSUE TITLE
Download failing with « Failed: Error: __enter__ - [podcast name] »status

### ISSUE THREAD

**Issue by etnadji** [gpodder/gpodder#923]
On a running from git repository version of gPodder, on GNU/Linux.
Can’t tell at which commit the downloads didn’t failed, maybe an update from 5be5f584.

The feeds handled with youtube-dl extension download fine but any others (no RSS feeds issues) don’t. 
Disabling the extension & restarting gPodder don’t solve the problem, so it may not be at fault.

It is gPodder’s `download.py` file which raise an exception : 

```code=pythonTraceback (most recent call last):
  File "/home/etienne/apps/gpodder/src/gpodder/download.py", line 790, in run
    headers, real_url = downloader.retrieve_resume(self.tempname, self.status_updated)
  File "/home/etienne/apps/gpodder/src/gpodder/download.py", line 340, in retrieve_resume
    headers, real_url = downloader.retrieve_resume(url,
  File "/home/etienne/apps/gpodder/src/gpodder/download.py", line 268, in retrieve_resume
    with session.get(url,
AttributeError: __enter__
```

Some feeds failing : 

- http://radiofrance-podcast.net/podcast09/rss_20856.xml
- https://feed.ausha.co/qbPLtZwxnmDb
- https://www.geekzone.fr/feed/les-demons-du-midi/

(sorry for broken english)

**Comment by auouymous** [comment]
All three podcasts work for me, with master. Do you have requests 2.24.0 or greater installed?

If so, can you try checking out 3.10.17 (4e4bf49e) and see if it works?

```
git checkout 4e4bf49e
```

The download code was changed immediately after the 3.10.17 release. It is the cause if 3.10.17 works, but aa58c70a fails.

```
git checkout aa58c70a
```

**Comment by etnadji** [comment]
Before updating requests, it works with 4e4bf49e, and it don’t with aa58c70a.

requests was 2.14.2, updating it make the downloads works with aa58c70a, and latest commit.

So I think this issue should be closed.
