### ISSUE TITLE
"Error while updating feed" after upgrade to Ubuntu 20.04.1 LTS

### ISSUE THREAD

**Issue by dglevy2** [gpodder/gpodder#928]
Running gpodder 3.10.15; after upgrading to Ubuntu 20.04.1 LTS, immediately started to get this:  After notification "New episodes available.  Downloading [n] episodes", where 'n' is the number of episodes: 
1) "Error while updating feed" ""Could not parse feed: <unknown>:1:127: Unsupported feed type: html".  
AND/OR
2) "Error:<urlopen error [Errno -3] Temporary failure in name resolution>"
This happens frequently across the board, all subscriptions, at random.

**Comment by auouymous** [comment]
Are all feeds from the same site? The first error means the site sent a website, probably an error page because the feed URL is no longer valid or the site is having issues. The second error is a probably with your DNS. Do the feed URLs work if you open them in a browser?

**Comment by dglevy2** [comment]
Thanks for your reply.  I think I found the problem.  When you said 'probably with your DNS', a light went on in my head.  It looks like it's just a coincidence that I started having trouble after the upgrade to Ubuntu 20.04.1.  The problem appears to be in the DNS settings.  I switched them OpenDNS (208.67.222.222) and that seems to have solved it.  But please leave the issue open for a day or two while I leave gPodder running, to see if I get any more error messages.  And thanks again for your quick reply!

**Comment by dglevy2** [comment]
No problems since the DNS change yesterday.  Thanks again, auouymous, for taking the time to write!
