### ISSUE TITLE
Youtube-dl file merging failing on MacOS

### ISSUE THREAD

**Issue by daneoshiga** [gpodder/gpodder#948]
Hi guys, long time no see xD,

Testing 3.10.17 I'm facing a strange behavior on the youtube-dl extension.

When it downloads multiple formats (as when prefered_fmts is set to bestvideo+bestaudio), it fails to merge the audio and video files.

With `LOG_LEVEL=DEBUG` environment var enabled, I got:

```
youtube_dl.utils.DownloadError: ERROR:   Reason: Incompatible library version: ffmpeg requires version 24.0.0 or later, but libfreetype.6.dylib provides version 6.0.0
```

when the download finishes.

tried:

` cp /usr/local/Cellar/freetype/2.10.4/lib/libfreetype.6.dylib /Applications/gPodder.app/Contents/Resources/lib`

got:

```
youtube_dl.utils.DownloadError: ERROR:   Reason: Incompatible library version: libgnutls.30.dylib requires version 11.0.0 or later, but libintl.8.dylib provides version 10.0.0
```

tried:

`cp /usr/local/Cellar/gettext/0.21/lib/libintl.8.dylib /Applications/gPodder.app/Contents/Resources/lib`

got:

`youtube_dl.utils.DownloadError: ERROR:   Reason: Incompatible library version: libass.9.dylib requires version 5.0.0 or later, but libfribidi.0.dylib provides version 0.0.0`

Then I gave up and came here.

**Comment by elelay** [comment]
Thanks for reporting!
The gPodder.app bundle for macOS comes with its own version of many libraries. They may conflict with homebrew's ffmpeg libraries.
When running ffmpeg as a subprocess, it inherits the library path and ffmpeg won't find the correct versions.

Maybe creating a wrapper script that sets the DYLD_LIBRARY_PATH will help you:

```bash
#!/bin/bash
export DYLD_LIBRARY_PATH=/usr/local/lib:$DYLD_LIBRARY_PATH
/usr/local/bin/ffmpeg "$@"
```

**Comment by daneoshiga** [comment]
It didn't work exactly the way you put it, but you gave me an idea that worked xD

I've looked up and found a[ static-linked version of ffmpeg](https://github.com/eugeneware/ffmpeg-static), that I put on that `ffmpeg_location` and that seems to have solved this! thanks!

**Comment by elelay** [comment]
ok, cool! Even easier...

**Comment by daneoshiga** [comment]
I've tried your solution and that gave me more crypt errors, but your explanation helped me think on trying that, thanks again :)
