### ISSUE TITLE
Lost podcast subscriptions and episodes, greyed out menu

### ISSUE THREAD

**Issue by ghost** [gpodder/gpodder#950]
I'm using gpodder-3.10.17-portable on Win7. Since a few days, the UI comes up blank, with all the menu items greyed out, the items unresponsive, and no supscriptions or epidoses show up. Updating (from .16 to .17) or running in compatibility mode changes nothing. Grateful for any help.

**Comment by auouymous** [comment]
Have you looked at the logs in the gpodder directory? There are probably sqlite errors which indicate your database is corrupt and you need to delete the `Database` file and restore from backup.

**Comment by stagars** [comment]
That was it. How do I restore the database from backup?

**Comment by auouymous** [comment]
Close gpodder, copy the `Database` file from backup into the gpodder directory and start gpodder. Then check logs to see if other gpodder files are causing errors.
