### ISSUE TITLE
Import to gpodder from Pocketcasts not working

### ISSUE THREAD

**Issue by naphtap** [gpodder/gpodder#955]
Pocketcasts exports my podcast lists as an xml file. When I try to import my podcast list into gpodder with this file, no podcasts pop up on the podcast select screen. 

Would I need to convert my xml file into an opml file before I can import the podcast lists into gpodder?

Thanks!

**Comment by auouymous** [comment]
Yes, but OPML is just an XML file, and it looks like gpodder only cares about the `outline` tags in it. Does the file look anything like the following?

```
<?xml version="1.0" encoding="utf-8"?>
<opml version="2.0">
    <head>
        ...
    </head>
    <body>
        <outline type="rss" title="..." text="..." xmlUrl="..."/>
        ...
    </body>
</opml>
```

It could look like the following and gpodder would probably accept it.

```
<?xml version="1.0" encoding="utf-8"?>
<outline type="rss" title="..." text="..." xmlUrl="..."/>
<outline type="rss" title="..." text="..." xmlUrl="..."/>
...
```

**Comment by naphtap** [comment]
The file looks exactly like that, but when I upload the file to gPodder, no podcasts show up. I have uploaded the zipped opml file, and the accompanying image of what happens when I import the opml file to gPodder.

[podcasts_opml.zip](https://github.com/gpodder/gpodder/files/5824732/podcasts_opml.zip)

![image](https://user-images.githubusercontent.com/13200850/104817323-934c0d80-57ee-11eb-9434-2b9dae944889.png)

**Comment by auouymous** [comment]
```
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 32, column 51
```

Delete lines 32, 62, 289 and 499. You will need to remember their URLs and manually subscribe to those 4 podcasts.

**Comment by auouymous** [comment]
The OPML file contains \0 bytes in utf8 sequences, something either corrupted the utf8 or pocketcasts has a bug. I don't think gpodder can do anything to fix this.

**Comment by naphtap** [comment]
I deleted the lines you recommended, and that worked! It seems that 4 of the podcasts had strange characters added to them... 
Thanks for your help!

**Comment by elelay** [comment]
great!
