### ISSUE TITLE
"Open website" menu link is always enabled for each podcast episode, even if there's no website

### ISSUE THREAD

**Issue by Robson** [gpodder/gpodder#958]
I'm using gPodder 3.10.17 (2020-11-23) on Windows 10, 64-bit. The installed version.

This specifically refers to the extension under **Interface** called **"Open website" episode and podcast context menu**. This file looks relevant: https://github.com/gpodder/gpodder/blob/master/share/gpodder/extensions/episode_website_context_menu.py

Each podcast episode has a right-click menu, which has an "Open website" item when that extension is active. This item is always enabled, even if there's no website associated with the episode.

_If there is an associated website_, it performs as expected: it opens the website. Example podcasts with episode links:
- https://feeds.megaphone.fm/darknetdiaries
- https://feeds.simplecast.com/JT6pbPkg

_If there is not an associated website_, Windows Explorer opens and shows C:\Program Files (x86)\gPodder. For me that's the folder with "contents.txt", "uninstall.exe" and a few folders. Example podcasts with no episode links:
- http://feeds.gimletmedia.com/heavyweightpodcast
- https://feeds.megaphone.fm/TPG9562451353

My suggestion would be to disable the "Open website" menu item, if there's no website associated with the episode.

**Comment by elelay** [comment]
Good point! I don't think the menu item could be disabled (the extension returns a label + a function to call) but it should not be available or the label could be changed?

**Comment by Robson** [comment]
Of those two options, my view would be:

Making the menu item unavailable would solve the issue.

Changing the text doesn't feel like the right approach, because other applications don't work in this way. If this is the only option, I think the code should also have a check to see if there is a website to open, before attempting to open it. That way it could be handled gracefully by showing an informative error message instead of opening Windows Explorer.

**Comment by Robson** [comment]
I see that @auouymous has implemented new functionality to resolve this - that's perfect! Thank you.
