### ISSUE TITLE
500 - Internal server error. The service is currently overloaded. Please try again later or contact us.

### ISSUE THREAD

**Issue by LittleBovey** [gpodder/gpodder#964]
How do I clear this alarm that I have had for 9months when trying to access Gpodder?

**Comment by elelay** [comment]
This is for gpodder.net from a web browser, right?

**Comment by LittleBovey** [comment]
Yes I have surfed around and the wisdom is there is nothing the end user
can do to resolve what looks to be a program issue

**Comment by elelay** [comment]
Thank for reporting, but it's a known problem with gpodder.net hosting/scaling.
See https://github.com/gpodder/mygpo/issues/527 for instance.
