### ISSUE TITLE
Cannot subscibe Logbuch Netzpolitik

### ISSUE THREAD

**Issue by mase76** [gpodder/gpodder#967]
Hallo!
I cannot add the feed of Logbuch Netzpolitik (https://logbuch-netzpolitik.de/feed/m4a).
This is the error message I get:
Could not parse feed: <unknown> 671:3: not well-formed (invalid token)

Regards
Thomas

**Comment by auouymous** [comment]
You need to contact the feed owner and ask them to fix it. The first page of the feed validates with some minor issues. But it contains `<atom:link rel="next" href="https://logbuch-netzpolitik.de/feed/m4a?paged=2"/>` which does not validate https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Flogbuch-netzpolitik.de%2Ffeed%2Fm4a%3Fpaged%3D2.
