### ISSUE TITLE
adaptive: crash when running without WebKit2

### ISSUE THREAD

**Issue by paper42** [gpodder/gpodder#972]
gpodder adaptive master (d7bcf105adeddb96e8f16900f4880290080a3c04) crashes when running without WebKit2.
```
[gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/usr/bin/gpodder", line 168, in <module>
    main()
  File "/usr/bin/gpodder", line 157, in main
    from gpodder.gtkui import app
  File "/usr/lib/python3.8/site-packages/gpodder/gtkui/app.py", line 36, in <module>
    from .main import gPodder
  File "/usr/lib/python3.8/site-packages/gpodder/gtkui/main.py", line 42, in <module>
    from . import shownotes
  File "/usr/lib/python3.8/site-packages/gpodder/gtkui/shownotes.py", line 262, in <module>
    class gPodderShownotesHTML(gPodderShownotes):
  File "/usr/lib/python3.8/site-packages/gpodder/gtkui/shownotes.py", line 264, in gPodderShownotesHTML
    ctx = WebKit2.WebContext.get_default()
NameError: name 'WebKit2' is not defined
```

This happens because WebKit2 is called outside methods of a class which means it will be called even if the class was not used and WebKit2 was not imported.
```python
has_webkit2 = False
try:
    gi.require_version('WebKit2', '4.0')
    from gi.repository import WebKit2
    has_webkit2 = True
except (ImportError, ValueError):
    logger.info('No WebKit2 gobject bindings, so no HTML shownotes')

...

class gPodderShownotesHTML(gPodderShownotes):
    ctx = WebKit2.WebContext.get_default()
    ctx.set_process_model(WebKit2.ProcessModel.MULTIPLE_SECONDARY_PROCESSES)
    ctx.set_cache_model(WebKit2.CacheModel.DOCUMENT_VIEWER)
    ctx.set_sandbox_enabled(True)
    ctx.set_spell_checking_enabled(False)

    def init(...):
```

This bug was introduced by commit 90c65a3708c642585780a1c60719a0fa25970e07 which adds only the variable ctx which is not used anywhere. Why was this commit neccessary? Reverting the commit fixes this bug. @tpikonen

**Comment by tpikonen** [comment]
Thanks for the report. The commit is/was a failed attempt at fixing a crash when two gPodderShownotesHTML objects are used. It was 'fixed' by the next commit which uses only one instance.

I'll revert the commit in the adaptive branch. The 1.1-adaptive gets this when I'll get around merging the changes from master and rebasing it on top of 'adaptive' again.
