### ISSUE TITLE
Assigning sections breaks sorting when disabled

### ISSUE THREAD

**Issue by auouymous** [gpodder/gpodder#986]
Turn on sections and assign some podcasts to them. Then turn off sections and notice how podcasts are arranged in the same order as when section were on. Turning off sections only turns off the labels.

Is this intended behavior? I imagine anyone not using sections would want the podcasts sorted.

**Comment by auouymous** [comment]
It appears podcasts sorted correctly until #971, so this needs to be fixed.

**Comment by elelay** [comment]
Good point. It's fixed now
