### ISSUE TITLE
Downloaded Episodes view also shows new not-downloaded episodes

### ISSUE THREAD

**Issue by fbarda** [gpodder/gpodder#987]
Title says it all.
Downloaded episodes view shows new episodes that are not downloaded yet, which is weird.

**Comment by fbarda** [comment]
Here is where it is counted as "downloaded": https://github.com/gpodder/gpodder/blob/64e8cde817384fe794273ec013f7a386561a8fc2/src/gpodder/gtkui/model.py#L938

**Comment by tpikonen** [comment]
There is a config setting called ui.gtk.episode_list.always_show_new, which is by default True. If you turn this off (go to Preferences, 'Edit config' and search for 'new'), the new episodes should not be displayed with the downloads any more.

The defaulting to True for this option is confusing, so I think this bug should remain open.

**Comment by elelay** [comment]
This is to prevent new episodes from disappearing before they can be selected for download.
The default is the way it's intended to work, the advanced setting is for people disagreeing.
This is not likely to change, since it would break the experience of existing users.

**Comment by fbarda** [comment]
> The default is the way it's intended to work, the advanced setting is for people disagreeing.
> This is not likely to change, since it would break the experience of existing users.

Oh alright then. Closing the issue.

**Comment by elelay** [comment]
Hum, I responded a bit too fast: it's not even an advanced setting anymore. In gPodder master there is a checkbox in the View menu, driving this setting.
