### ISSUE TITLE
Lock doesn't prevent deletion of single episodes

### ISSUE THREAD

**Issue by auouymous** [gpodder/gpodder#989]
Locking episodes prevents accidental deletion, for downloaded or undownloaded episodes. It works fine when multiple episodes are selected, but the code below clearly bypasses the lock when only one episode is deleted. The lock even remains on the episode after deleting it. I don't see a reason to bypass the lock, because if someone really wants to delete the episode, they can take the time to unlock it first.

Is there a reason for the current useless behavior? I propose the skip_locked parameter be removed entirely.

```
    def on_btnDownloadedDelete_clicked(self, widget, *args):
        episodes = self.get_selected_episodes()
        if len(episodes) == 1:
            self.delete_episode_list(episodes, skip_locked=False)
        else:
            self.delete_episode_list(episodes)
```

**Comment by elelay** [comment]
I don't know why it is so. OK for not bypassing when a single episode is selected.
